- openshift-3.11/group.yml
AFAICT it should be ok to use the version variables here instead of the hard-coded version.  The hard-coded version was introduced in a previous commit (9a31c6b655fb97a915a53368370240b4f001650e) to prevent building from master.
> openshift-3.11: use version vars for cluster-monitoring-operator

- openshift-4.0/group.yml
- openshift-4.0/images/ose-metering-helm.yml
There is now a rhel specific Dockerfile for helm: https://github.com/operator-framework/helm/blob/release-4.0/Dockerfile.rhel
> Update ose-metering-helm Dockerfile source

- openshift-3.11/group.yml
- openshift-4.0/group.yml
Change branches from 'openshift-master' to 'release-X.Y' with fallback
of 'master' to match other openshift projects.
Grafana stays on 'openshift-master' for now until its master branch is updated.
> update monitoring projects branches

- openshift-3.11/group.yml
- openshift-4.0/group.yml
The 'openshift-master' branch is now deprecated.
> update openshift/grafana repo to build from 'master'

- openshift-4.0/images/ose-metering-reporting-operator.yml
There is now a rhel specific Dockerfile for ose-metering-reporting-operator: https://github.com/operator-framework/operator-metering/blob/master/Dockerfile.reporting-operator.rhel
> Update reporting operator Dockerfile source

- modifications/README
- modifications/update-console-sources
- openshift-3.11/images/openshift-enterprise-console.yml
- openshift-4.0/images/openshift-enterprise-console.yml
Since this introduces a script I'll take the unusual step of making a PR and requesting review...
This relies on https://github.com/openshift/enterprise-images/pull/470 and causes the console build to invoke the new script at rebase time so that NPM sources are updated and uploaded automatically (if changed), removing the manual blocker for upstream changes to sources.
> invoke script to update console sources at rebase

- openshift-4.0/group.yml
- openshift-4.0/images/ose-etcd.yml
* updated config to cover multi-stage build process
* added labels.
* updated etcd upstream and target
Dockerfile.rhel is located: https://github.com/openshift/etcd/tree/origin-4.0-etcd-v3.3.10
> openshift-4.0: etcd

- openshift-4.0/images/prometheus-config-reloader.yml
- openshift-4.0/images/prometheus-operator.yml
openshift/prometheus-operator has recently switched to use multistage builds for OKD because it had a dependency on Go 1.10 (see https://github.com/openshift/prometheus-operator/pull/14). This is the corresponding change to ensure that the OCP builds keep running. It is based on the actual [cluster-monitoring-operator.yml](https://github.com/openshift/ocp-build-data/blob/7ddfe5bac449d02e9ea15a0c092f4b6fd17678c5/openshift-4.0/images/cluster-monitoring-operator.yml).
cc @s-urbaniak @pgier
> Multistage build for prometheus-operator images

- images/openshift-enterprise-haproxy-router-base.yml
- images/openshift-enterprise-haproxy-router.yml
The haproxy-router was moved to stop using `oc` to contain its router
content, and a new router-base image was created to be the common base
for any future template based router. The binary used by haproxy-router
lives in router-base and was missing from the previous version of
haproxy-router, which fixes an OCP only error:
no such executable: /usr/bin/openshift-router
> Add router-base to the 4.0 build, base haproxy-router off it

- group.yml
Adding ppc64le repos for 4.0 ppc64le support. 
A few containers (18ish) don't build, so for now we should leave -ppc64le commented out. 
I'll open a separate PR to uncomment when everything is ready to go.
> Add ppc64le repos for 4.0

- images/openshift-jenkins-2.yml
Add `ose-` prefix to master jenkins image. Allows image to be incorporated in release payload.
> Include master jenkins image in release payload

- images/openshift-enterprise-base.yml
- images/openshift-enterprise-egress-dns-proxy.yml
- images/openshift-enterprise-egress-router.yml
- images/openshift-enterprise-keepalived-ipfailover.yml
- images/openshift-enterprise-pod.yml
- images/ose-egress-http-proxy.yml
The base image should be rebuilt less often, and the others benefit
from faster build times being out of the main repo.
Before merging:
> Move some images out of ose into their own repo

- images/openshift-enterprise-cli.yml
- images/openshift-enterprise-deployer.yml
- images/openshift-enterprise-hyperkube.yml
- images/openshift-enterprise-hypershift.yml
- images/openshift-enterprise-node.yml
- images/openshift-enterprise-recycler.yml
- images/openshift-enterprise-tests.yml
- images/openshift-enterprise.yml
- images/template-service-broker.yml
These are the new locations for these files that removes dependencies
on RPMs and moves to multi-stage builds. After this merges we can start dropping RPMs from being built
in origin and OCP for everything except `kubelet` and `oc`.
> Use the new unified `Dockerfile.rhel` images for origin

- images/cri-o.yml
Unless/until we can get https://github.com/kubernetes-sigs/cri-o/pull/1966/files
to merge, we'll need this modification to keep the build from failing.
> cri-o: "temporary" replace needed

- images/baremetal-machine-controller.yml
- images/csi-provisioner.yml
These are the names we would have if we matched upstream CI config.
There are other upstream names OCP just doesn't have at all yet AFAICS.
> true up image names with OKD

- images/openshift-enterprise-cli-artifacts.yml
- images/ose-installer-artifacts.yml
They descend from cli/installer and contain the versions for other
operating systems.
Same as https://github.com/openshift/release/pull/3321 and https://github.com/openshift/release/pull/3322
> Add new artifacts images

- images/ose-cluster-kube-scheduler-operator.yml
Start using golang 1.11
/cc @soltysh @sjenning 
https://github.com/openshift/cluster-kube-scheduler-operator/pull/102
> Switch to go 1.11

- images/ose-cli-artifacts.yml
No need to build  the cli-artifacts container on other architectures.
> mark cli-artifacts as x86_64 only

- images/golang-github-prometheus-alertmanager.yml
- images/golang-github-prometheus-node_exporter.yml
- images/golang-github-prometheus-prometheus.yml
- images/image-inspector.yml
- images/logging-eventrouter.yml
- images/openshift-enterprise-autoheal.yml
- images/openshift-enterprise-base.yml
- images/openshift-enterprise-cli.yml
- images/openshift-enterprise-deployer.yml
- images/openshift-enterprise-egress-dns-proxy.yml
- images/openshift-enterprise-egress-router.yml
- images/openshift-enterprise-haproxy-router.yml
- images/openshift-enterprise-hyperkube.yml
- images/openshift-enterprise-hypershift.yml
- images/openshift-enterprise-keepalived-ipfailover.yml
- images/openshift-enterprise-mariadb.yml
- images/openshift-enterprise-mediawiki.apb.yml
- images/openshift-enterprise-mediawiki.container.yml
- images/openshift-enterprise-mysql.yml
- images/openshift-enterprise-node.yml
- images/openshift-enterprise-pod.yml
- images/openshift-enterprise-postgresql.yml
- images/openshift-enterprise-recycler.yml
- images/openshift-enterprise-tests.yml
- images/openshift-local-storage.yml
- images/ose-egress-http-proxy.yml
- images/ose-haproxy-router-base.yml
- images/snapshot-controller.yml
- images/snapshot-provisioner.yml
Here's all the missing owner files in 4.1, I'm tracking down one by one with group lead, still wip
> adding missing owner images for 4.1

- images/etcd3-docker.yml
since buildvm-maint failed due to `oc mirror failed: missing or empty Content-Type headererror: an error occurred during planning`
> update etcd3-docker.yml to change mode: disabled

- images/ose-cluster-openshift-controller-manager-operator.yml
- images/ose-cluster-samples-operator.yml
* ose-cluster-samples operator email change
* ose-cluster-openshift-controller-manager-operator now owned by DevEx
> [4.1] Update DevEx owners

- images/ose-must-gather.yml
Changed base image from openshift-enterprise-base to [openshift-enterprise-cli](https://github.com/openshift/ocp-build-data/blob/openshift-4.1/images/openshift-enterprise-cli.yml).
> Bug 1703240: Update base image for ocp build of must-gather.

- images/jenkins-slave-base-rhel7.yml
@adammhaile @sosiouxme PTAL
only added the 1 repo in the 3.9 version based on https://github.com/openshift/ocp-build-data/blob/openshift-3.9/images/openshift-jenkins-2.yml
@waveywaves @sthaha fyi
> enable repos so slave-base can install dumb-init

- group.yml
With openshift/release#3641 being merged openshift/kuryr-kubernetes has
the CI configuration, which was the reason behind putting it on this
list. This commit removes it from it.
> Remove Kuryr images from non_release list

- images/ose-cluster-dns-operator.yml
- images/ose-cluster-ingress-operator.yml
- images/ose-haproxy-router-base.yml
Add container_yaml stanzas for the Network Edge team's images.
Note that building the base-router image involves building the Go-based openshift-router binary, but building the haproxy-router image only layers RPMs and some configuration on top of the base-router image without itself building any Go code.  Thus this PR only adds a stanza to the base-router config, not to the haproxy-router config.
Building the egress-http-proxy image also does not involve building any Go code.
* `images/ose-cluster-dns-operator.yml`:
* `images/ose-cluster-ingress-operator.yml`:
* `images/ose-haproxy-router-base.yml`: Add `container_yaml` stanza.
---
@openshift/sig-network-edge
~I'm not sure what to do about the egress router images; https://github.com/openshift/origin/commit/7aedc3cb19c39e22b382eff96380bef …
> Add golang module paths for Network Edge components

- images/ose-cluster-update-keys.yml
This image controls the content that verifies an OCP update payload
is signed.
Still verifying everything, do not merge yet.
> Add cluster-update-keys to OCP

- group.yml
With openshift/release#3853 merged, openshift/leader-elector is now
built by prow. This should be enough to remove it from non_release list.
> Remove leader-elector from non_release list

- group.yml
- images/openshift-enterprise-ansible-operator.yml
- images/openshift-enterprise-apb-base.yml
The upstream repos are using 2.7 from the ansible-runner base, so we should update the OSE images to ansible 2.7 also.
/hold
Needs review from the teams owning ansible-operator and apb images.
> Update apb-base and ansible-operator to use ansible 2.7 RPM repositories

- group.yml
Metering is shipping as a redhat-operator in 4.2 so we need these to be in the marketplace publishing pipeline.
> Remove metering components from non-release list for 4.2

- images/hadoop.yml
- images/hive.yml
- images/ose-metering-ansible-operator.yml
- images/ose-metering-helm.yml
- images/ose-metering-reporting-operator.yml
- images/presto.yml
OLM manifests are in https://github.com/operator-framework/operator-metering/tree/master/manifests/deploy/openshift/olm/bundle so I think this is correct.
> Update metering components configs for marketplace publishing in 4.2

- images/sriov-network-operator.yml
As requested in [ART-672](https://jira.coreos.com/browse/ART-672) I'm adding [sriov-network-operator](https://github.com/openshift/sriov-network-operator) to **openshift-4.2**.
(with `config: wip` until a successful execution of our Jenkins "custom" job)
> [ART-672] Add sriov-network-operator.yml

- images/ose-cluster-update-keys.yml
We added the image to 4.1, but it was not part of the branch to
4.2.
> Add cluster-update-keys for 4.2 (was not part of branch)

- group.yml
Fixes
```
2019-06-24 12:50:43,038 INFO Cloning config data from https://gitlab.cee.redhat.com/openshift-art/ocp-build-data.git
2019-06-24 12:50:46,260 INFO Using branch from group.yml: rhaos-4.2-rhel-7
No value defined for default advisory: The key advisories.image is not defined for group openshift-4.2 in group.yml
```
> Correct the default advisory key names for 4.2

- images/sriov-network-config-daemon.yml
failing due to missing mstflint pkg which appears to be in extras.
nothing is installing from optional so just removing that.
> sriov-network-config-daemon: use extras repo not optional

- group.yml
Those are needed for kuryr-kubernetes to have python3-openvswitch, but
were also present for RHEL 7, so I think it isn't controversial to have
them for 8 as well.
> Add RHEL 8 fast-datapath repos

- Jenkinsfile
> Always pull latest CI image (openshift-4.3)

- Jenkinsfile
> Always pull latest CI image (openshift-4.2)

- Jenkinsfile
> Always pull latest CI image (openshift-4.1)

- Jenkinsfile
> Always pull latest CI image (openshift-3.11)

- Jenkinsfile
> Always pull latest CI image (openshift-3.10)

- Jenkinsfile
> Always pull latest CI image (openshift-3.9)

- group.yml
Manually doing this because our Jenkins doesn't have the permission to write this repo: https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fadvisories/15/console
> Update advisory numbers for 3.9.102

- images/linuxptp-daemon.yml
This is to maintain consistent image names between
Origin and OCP. Origin image is added via:
https://github.com/openshift/release/pull/5631
> Rename linuxptp-daemon image name to ptp

- erratatool.yml
In favor of https://jira.coreos.com/browse/ART-1011, configure boilerplate text in ocp-build-data for different kinds of advisories.
> 4.2: Provide per advisory kind boilerplate text

- erratatool.yml
In favor of https://jira.coreos.com/browse/ART-1011, configure boilerplate text in ocp-build-data for different kinds of advisories.
> 4.1: Provide per advisory kind boilerplate text

- erratatool.yml
In favor of https://jira.coreos.com/browse/ART-1011, configure boilerplate text in ocp-build-data for different kinds of advisories.
> 4.3: Provide per advisory kind boilerplate text

- erratatool.yml
In favor of https://jira.coreos.com/browse/ART-1011, configure boilerplate text in ocp-build-data for different kinds of advisories.
> 3.11: Provide per advisory kind boilerplate text

- group.yml
- images/ose-ovn-kubernetes.yml
This will allow us to select OVS 2.12 for its RAFT HA feature.
@squeed @pecameron @danwinship
> ovn-kubernetes: add FDP Next repo and allow it for ovn-kubernetes

- group.yml
Per QE's request, I created extras and metadata advisories so 4.3
so that QE can test operators earlier.
> 4.3 extras and metadata advisories

- images/kuryr-cni.yml
- images/kuryr-controller.yml
- rpms/openshift-kuryr.yml
We want Kuryr to use newer dependencies so we're switching it to use
RHEL8 and OSP16. This commit does so.
> Switch Kuryr images to RHEL8 and OSP16

- images/ose-containernetworking-plugins.yml
Has been failing Dockerfile reconcilation due to a miscount of image parents.
Source Dockerfile @ https://github.com/openshift/containernetworking-plugins/blob/master/Dockerfile
> ose-containernetworking-plugins: Adds rhel-8-golang as an image stream

- images/kuryr-cni.yml
- images/kuryr-controller.yml
Kuryr is being ported to Power LE in RHOS 16.
CC: @sosiouxme
> 4.3: Enable kuryr on ppc64le

- images/multus-cni.yml
Including the `rhel-8-golang` stream.
> [Openshift-4.4] Multus CNI should be built from two streams

- group.yml
Fast Datapath is now shipping s390x as of this week.
> Use CDN for s390x fast-datapath

- group.yml
- images/ironic-inspector.yml
- images/ironic-ipa-downloader.yml
- images/ironic-rhcos-downloader.yml
- images/ironic-static-ip-manager.yml
- images/ironic.yml
- images/kuryr-cni.yml
- images/kuryr-controller.yml
- images/openshift-enterprise-keepalived-ipfailover.yml
This is a backport of the changes made in the 4.3 branch to enable s390x.  The actual "master switch" enablement is left commented out in line with the current status of ppc64le.  When the opportunity arises, it should be enabled and a full sync (with unsigned builds for now) executed.
> 4.2: Prepare s390x enablement

- group.yml
This reverts commit 78a540d788fa4ac68d87f73a55c1136dc53615bf.
To rebuild 4.2.10 signed compose.
> Revert "Update advisories on group.yml"

- images/kuryr-cni.yml
- images/kuryr-controller.yml
All the Kuryr dependencies are now tagged into OCP repos, so we can
remove OpenStack deps from Kuryr builds.
> Remove OpenStack repos from Kuryr builds

- images/ironic.yml
This should hopefully fix the issue:
FAILURE: Error reconciling Dockerfile for openshift/ose-ironic in OCP v4.3
> Add builder for ironic image

- images/ose-metering-helm.yml
https://github.com/operator-framework/helm/pull/10 fixed the build itself.
We will want this cherry-picked to at least 4.3 once the build fix is cherry-picked there.
> Enable ose-metering-helm on all arches

- images/ironic-rhcos-downloader.yml
Revert renaming ironic-rhcos iamge in 4.2 release.
This was supposed to happen from 4.3 and forward.
> Revert: Rename ironic-rhcos to ironic-machine-os in 4.2

- group.yml
- images/ose-ovn-kubernetes.yml
ovs2.12 is now GA and available in the usual fastdatapath repos.
This reverts PR 202 that gets ovs2.12 from the beta repos
SDN-736 [ovn] revert hardcoded OVS/OVN version hacks
https://issues.redhat.com/browse/SDN-736
Signed-off-by: Phil Cameron <pcameron@redhat.com>
> Revert ovs from beta

- images/ose-kube-storage-version-migrator.yml
> [ART-1422] Disable kube-storage-version-migrator

- images/ironic-hardware-inventory-recorder-image.yml
- images/ironic-inspector.yml
- images/ironic-rhcos-downloader.yml
- images/ironic-static-ip-manager.yml
- images/ironic.yml
Removing osp 16 repo dependency from ironic images.
Excluding ipa-downloader until [0] is merged.
[0] https://github.com/openshift/release/pull/6528
> Ironic images should not use osp repos

- images/cluster-storage-operator.yml
- images/csi-attacher.yml
- images/csi-livenessprobe.yml
- images/csi-provisioner.yml
- images/efs-provisioner.yml
- images/local-storage-diskmaker.yml
- images/local-storage-operator.yml
- images/local-storage-static-provisioner.yml
- images/openshift-enterprise-recycler.yml
All storage images should be owned by aos-storage-staff mailing list.
For example:
* `mawong@redhat.com` has left the company. 
* `aos-storage-devel` is not really used.
I will cherry-pick into all 4.x when this gets merged.
> 4.4: Sanitize storage image owners

- images/golang-github-openshift-oauth-proxy.yml
https://github.com/openshift/oauth-proxy/pull/135 moved Dockerfile
from images subdirectory to project root.
> Change oauth-proxy Dockerfile path

- images/ironic-ipa-downloader.yml
We have all the packages tagged, we can remove the reference from
the ipa-downloader image.
> The ironic-ipa-downloader image should not use osp repos

- group.yml
Turn on `odcs_enabled` and `odcs_aggressive` feature gate so that future 3.11 image build will use ODCS composes.
Requires https://github.com/openshift/doozer/pull/158 to be landed.
> Enable ODCS for image build

- images/ose-multus-route-override-cni.yml
- images/ose-multus-whereabouts-ipam-cni.yml
It was discovered that these image names didn't meet conventions. I renamed the files to match the image names, and updated the image names.
Related to #287
> Renames route-override-cni and whereabouts-cni to follow naming conventions

- images/openshift-enterprise-template-service-broker-operator.yml
- images/template-service-broker.yml
The Service Catalog removal job did not make it in for feature freeze because of some late bugs found with the Job and CVO. So we need to re-enable the Template Service Broker and its Operator for OpenShift 4.4. The Ansible Service Broker and its Operator will not be re-enabled and should remain disabled.
> Bug 1798086: Re-enable the TSB and its operator

- images/openshift-enterprise-template-service-broker-operator.yml
- images/template-service-broker.yml
Current Doozer version treats images in the dependent list as enabled images.
Need to disable it to make doozer happy until the disabled image is ready to build.
> Remove template-service-broker-operator from dependent list

- group.yml
ovn2.12 was not added to ppc64le/s390x product listings when originally
shipped for x86_64.  Fixing that might take some time, but these puddles
contain the same packages.
> Bug 1802325: Use Fast Datapath puddles on IBM arches

- group.yml
Changed to use:
http://download-node-02.eng.bos.redhat.com/rhel-7/nightly/FDN/latest-FDP-7-RHEL-7/compose/Server/s390x/os/
for x86_64, s390x, ppcle64 architectures.
This is the location used by the FDN builds.
Signed-off-by: Phil Cameron <pcameron@redhat.com>
> Bug 1802716: Use FDP-next repos

- rpms/openshift.yml
Working to satisfy https://issues.redhat.com/browse/ART-1550 . Moving away from custom tito logic with 4.4 as the first test bed.
> Eliminate tito use for 4.4

- images/cluster-network-operator.yml
- images/kube-proxy.yml
- images/ose-ovn-kubernetes.yml
- images/ose-sdn.yml
The sdn image is currently owned by `aos-sdn-staff`, which AFAICT is not a real list. (It exists but appears to have no members.) The real team list is `aos-networking-staff`.
cluster-networking-operator is owned by `atomic-networking`, which does exist, but goes to lots of irrelevant people in addition to the relevant ones.
kube-proxy and ovn-kubernetes are currently owned by individuals, and it would make more sense to have them owned by the list as well. I'll cc those individuals here (@pecameron @dcbw @squeed) to give them a chance to object, except that they won't because one of them is on PTO and one is on paternity leave, which is exactly the reason we shouldn't have individuals as owners...
This should be cherry-picked as far back as it can go
> Fix up owners of networking images

- images/cluster-logging-operator.yml
- images/cluster-nfd-operator.yml
- images/clusterresourceoverride-operator.yml
- images/local-storage-operator.yml
- images/ptp-operator.yml
Disable operators which do not have 4.5 references in their package
files so that our builds don't crash. Revert each as they are fixed
upstream.
ART JIRA: https://issues.redhat.com/browse/ART-1559
Individual Request PRs:
* https://github.com/openshift/ptp-operator/issues/38
* https://github.com/openshift/local-storage-operator/issues/94
* https://github.com/openshift/cluster-resource-override-admission-operator/issues/25
* https://github.com/openshift/cluster-nfd-operator/issues/71
* https://github.com/openshift/cluster-logging-operator/issues/387
> ART-1559 [4.5] - Get OLM operator owners to update their CSV channels

- images/cluster-network-operator.yml
- images/kube-proxy.yml
- images/ose-ovn-kubernetes.yml
- images/ose-sdn.yml
Backport of #323 to openshift-4.2. Only change is that previously ose-sdn was owned by @mfojtik here, which is just because he's the one who originally split sdn out of origin, but it doesn't make sense for him to be the owner now.
> Fix up owners of networking images [4.2]

- images/cluster-network-operator.yml
- images/kube-proxy.yml
- images/openshift-enterprise-node.yml
- images/ose-ovn-kubernetes.yml
Backport of #323 to openshift-4.1. This was before sdn was split out of origin, and the image is still defined in a file called "`images/openshift-enterprise-node.yml`" here for historical reasons, but it is actually just the SDN image, as seen by the `dockerfile: images/sdn/Dockerfile.rhel`, with the "node" image being `images/openshift-enterprise/hyperkube.yml`
> Fix up owners of networking images [4.1]

- group.yml
- images/openshift-enterprise-ansible-operator.yml
- Update Dockerfile location
- Update to ansible-2.9 RPMs which are required for proper collection support
Depends on https://github.com/openshift/ocp-release-operator-sdk/pull/46
> Update ansible-operator base image

- images/openshift-enterprise-cluster-capacity.yml
Cluster-capacity is now owned by workloads team
> Change owners of cluster-capacity image

- images/openshift-enterprise-cluster-capacity.yml
Cluster-capacity is now owned by workloads team
4.5: https://github.com/openshift/ocp-build-data/pull/359
> bug 1810977: Change owners of cluster-capacity image

- group.yml
Changed to use:
http://download-node-02.eng.bos.redhat.com/rhel-7/nightly/FDN/latest-FDP-7-RHEL-7/compose/Server/s390x/os/
for x86_64, s390x, ppcle64 architectures.
This is the location used by the FDN builds.
Signed-off-by: Phil Cameron <pcameron@redhat.com>
> Use FDP-next repos

- images/ose-ovn-kubernetes.yml
ose-ovn-kubernetes is failed with Error in plugin compare_components: Failed component comparison for components: openvswitch2.12, openvswitch2.12-devel. OSBS build id: ose-ovn-kubernetes-rhaos-44-rhel-7-4cf91-218 : https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27163307.
I didn’t met this issue before. It looks like related to openvswitch2.12 and openvswitch2.12-devel for ppc64le. Let's temporarily disable ppc64le on it.
> Disable ppc64le build for ose-ovn-kubernetes

- images/local-storage-operator.yml
Fixed via https://github.com/openshift/local-storage-operator/pull/95
> 4.5 Enable local-storage operator. 

- images/logging-elasticsearch5.yml
- images/logging-kibana5.yml
Per request of @jcantrill we are disabling these components for 4.5 for the indefinite future.
Slack conversation record: https://coreos.slack.com/archives/CB95J6R4N/p1584109467133300
> Disable logging components for 4.5

- images/ose-baremetal-installer.yml
This is needed for packages like jq that are tagged for ocp only.
> Add rhel-server-ose repo to baremetal-installer

- group.yml
ovn2.12 has since shipped on P&Z.
> [openshift-4.5] use only pulp repos for fast-datapath

- group.yml
- images/ose-ovn-kubernetes.yml
ovn2.12 has since shipped on P&Z.
> [openshift-4.4] Re-enable ovn-kubernetes on all group arches

- erratatool.yml
Pruning unused rhel-8 for 3.11 to prevent the [following error](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fsweep/8127/console) from happening:
```
elliott -g openshift-3.11 find-builds -k rpm --use-default-advisory rpm
[Pipeline] sh
+ set +x
2020-03-30 13:24:49,282 INFO Cloning config data from https://github.com/openshift/ocp-build-data.git
2020-03-30 13:24:50,086 INFO Using branch from group.yml: rhaos-3.11-rhel-7
Default advisory detected: 53185
Generating list of rpms: Hold on a moment, fetching Brew builds
Gathering additional information: Brew buildinfo is required to continue
[******************]
Traceback (most recent call last):
File "/home/jenkins/.local/lib/python3.6/site-packages/koji/__init__.py", line 2683, in _callMethod
return …
```
> Remove rhel-8 brew tags from 3.11

- streams.yml
`logging-fluentd` had this issue:
```
Error: Package: glibc-2.17-292.el7.i686 (rhel-server-rpms-x86_64)
Requires: glibc-common = 2.17-292.el7
Installed: glibc-common-2.17-307.el7.1.x86_64 (@anaconda/7.8)
```
Current `:latest` of `rhscl-ruby-25-rhel7` includes a pre-release glibc,
which causes this. This patch is intended to be temporary.
> Pin rhscl-ruby-2.5 to previous version

- group.yml
FDN builds are for internal development only, and must not be used in
potentially shipping products.  FDP nightly composes reflect what has or
will soon be shipped.
CC: @dcbw
> Use FDP nightlies, not FDN.

- images/ose-ovn-kubernetes.yml
Fixes: https://github.com/openshift/ocp-build-data/pull/412
@wking @knobunc
> ovn-kubernetes: enable fast-datapath-beta repos for OVS/OVN 2.13

- images/atomic-openshift-descheduler.yml
- images/ose-cluster-kube-scheduler-operator.yml
The workloads team are the current owners of the scheduler and descheduler, going forward
> Update scheduler/descheduler owners to include aos-workloads

- group.yml
With the move to registry-proxy, there should be no need to pull images
insecurely.
> Pull images with SSL

- group.yml
- images/openshift-enterprise-ansible-operator.yml
Per QE and https://github.com/openshift/openshift-ansible/commit/02c6b7bedacde486669fbeae2ab1cd0bd1c06162, 4.4 openshift-ansible uses ansible 2.9.
I cherry-picked 1cf1054cf8f5a3d3c1021fbb97189c993a21d980 from 4.5 but not sure if bumping the ansible version for ose-ansible-opeator is required or we only need to have entry in group.yml for QE's TPS testing.
> Bump to ansible-2.9

- images/ose-ovn-kubernetes.yml
What's in FDP itself is good enough for ovnkube and is part of
the FDP 20.C.1 release (and thus errata-ed).
@danwinship @sosiouxme
> ovn-kubernetes: disable FDP beta/next repo for release

- images/image-inspector.yml
Ship `image-inspector` with our next 3.11 release. **if** that's what we agree on this thread: https://coreos.slack.com/archives/CB95J6R4N/p1588169544270000
> Re-enable image-inspector

- images/atomic-openshift-descheduler.yml
This adds aos-workloads to the list of descheduler owners
Is there anything we need to do to ensure this is copied forward for future versions? I added it in 4.5 as well, aos-workloads should be on the list for each release going forward.
> Add aos-workloads to descheduler owners

- group.yml
This image is related to a feature of kuryr-kubernetes that is not
enabled at all on 4.5, so we should be able to skip releasing it.
> Add ose-leader-elector to non_release

- images/cluster-logging-operator.yml
- images/elasticsearch-operator.yml
- images/elasticsearch-proxy.yml
- images/logging-curator5.yml
- images/logging-elasticsearch6.yml
- images/logging-eventrouter.yml
- images/logging-fluentd.yml
- images/logging-kibana6.yml
the email group aos-logging is too large and contains members other than the logging team itself
cc @jcantrill
> Updating logging image owners to be team-logging@redhat.com

- modifications/update-console-sources
@tbielawa i think we aren't ready yet to enable operators since they don't rebase properly without the release-specific subdirs... so, probably hold on this for now but... ready when the branch is.
> logging: fix dependencies and enable builds

- group.yml
- images/ose-ovn-kubernetes.yml
If we need development RPMs in 4.6 we'll just tag the right ones in.
@jupierce
> [openshift-4.6] remove fast-datapath-beta repos now that SCR is active

- group.yml
The conclusion from [this conversation](http://post-office.corp.redhat.com/archives/aos-team-art/2020-March/msg00041.html) is that the additional push of images to reg-aws is not consumed for 4.y releases. Removing, to save some waiting time.
> Remove reg-aws from push list

- images/prom-label-proxy.yml
To build prom-label-proxy we need the `prometheus-promu` package which is available from rhel-server-ose-rpms if I'm not mistaken.
For example, this is the list of repositories for Prometheus:
https://github.com/openshift/ocp-build-data/blob/9e8c4b4e8c300b72356cbe6f04f7315c70877ab3/images/golang-github-prometheus-prometheus.yml#L12-L15
> images: add rhel-server-ose-rpms for prom-label-proxy

- images/logging-curator5.yml
- images/logging-fluentd.yml
- streams.yml
This PR addresses upcoming changes in base images used to build the logging stack.
**Depends on:** openshift/origin-aggregated-logging#1892
> [logging] Migrate using ubi7 base images

- group.yml
Per https://coreos.slack.com/archives/CJARLA942/p1593765423362300,
remove the operator from non_release on behalf of QE's request.
> Make ose-clusterresourceoverride-rhel7-operator GA

- group.yml
- images/openshift-golang-builder.Dockerfile
Until now, the rhel8 golang-builder was only used for a handful of images.  This should help facilitate switching the rest.
A successful scratch build was made internally.
> Install devel packages found in rhel7 builder + add aarch64

- images/openshift-golang-builder.Dockerfile
However, the MANPATH, X_SCLS, LD_LIBRARY_PATH, PATH, and PKG_CONFIG_PATH
variables need not be set, as RHEL8 golang is a module rather than an SCL.
> rhel-8-golang-1.14: Make functionally equivalent to RHEL7 golang-builder

- images/cluster-node-tuning-operator.yml
Adding one more stage to `cluster-node-tuning-operator`'s Dockerfile, to reflect its current upstream counterpart: https://github.com/jmencak/cluster-node-tuning-operator/blob/9fff20cec49b986add48f92059113520cc3d467a/Dockerfile
> Add build stage on cluster-node-tuning-operator

- group.yml
- images/cluster-logging-operator.yml
- images/ose-machine-api-operator.yml
The ose content sets for rhel-8 do not match the naming scheme for
rhel-7. This results in a content_sets.yml that differs from the
configured repositories.
To test:
```sh
curl -sSL -XPOST --header "Accept-Encoding: gzip, deflate" --header "Accept: */*" --header "Content-Type: application/json" --header "Authorization: Basic ABC" -d '
{
"criteria": {
"fields": [
"id",
"notes"
],
"filters": {
"$in": [
]
},
"$in": [
"rhocp-4.6-for-rhel-8-x86_64-rpms",
"rhocp-4.6-for-rhel-8-ppc64le-rpms",
"rhocp-4.6-for-rhel-8-s390x-rpms"
]
}
}
}
}
' "https://pulp.dist.prod.ext.phx2.redhat.com/pulp/api/v2/repositories/search/" | jq -r '.[] | .id + " " + .notes.content_set'
rhocp-4_DOT_6-for-rhel-8-ppc64le-rpms …
```
> Correct rhel-8-server-ose content_set

- group.yml
The ose content sets for rhel-8 do not match the naming scheme for
rhel-7. This results in a content_sets.yml that differs from the
configured repositories.
To test:
```sh
curl -sSL -XPOST --header "Accept-Encoding: gzip, deflate" --header "Accept: */*" --header "Content-Type: application/json" --header "Authorization: Basic ABC" -d '
{
"criteria": {
"fields": [
"id",
"notes"
],
"filters": {
"$in": [
]
},
"$in": [
"rhocp-4.6-for-rhel-8-x86_64-rpms",
"rhocp-4.6-for-rhel-8-ppc64le-rpms",
"rhocp-4.6-for-rhel-8-s390x-rpms"
]
}
}
}
}
' "https://pulp.dist.prod.ext.phx2.redhat.com/pulp/api/v2/repositories/search/" | jq -r '.[] | .id + " " + .notes.content_set'
rhocp-4_DOT_6-for-rhel-8-ppc64le-rpms …
```
> 4.5: Correct rhel-8-server-ose content_set

- group.yml
The ose content sets for rhel-8 do not match the naming scheme for
rhel-7. This results in a content_sets.yml that differs from the
configured repositories.
To test:
```sh
curl -sSL -XPOST --header "Accept-Encoding: gzip, deflate" --header "Accept: */*" --header "Content-Type: application/json" --header "Authorization: Basic ABC" -d '
{
"criteria": {
"fields": [
"id",
"notes"
],
"filters": {
"$in": [
]
},
"$in": [
"rhocp-4.6-for-rhel-8-x86_64-rpms",
"rhocp-4.6-for-rhel-8-ppc64le-rpms",
"rhocp-4.6-for-rhel-8-s390x-rpms"
]
}
}
}
}
' "https://pulp.dist.prod.ext.phx2.redhat.com/pulp/api/v2/repositories/search/" | jq -r '.[] | .id + " " + .notes.content_set'
rhocp-4_DOT_6-for-rhel-8-ppc64le-rpms …
```
> 4.4 Correct rhel-8-server-ose content_set

- group.yml
The ose content sets for rhel-8 do not match the naming scheme for
rhel-7. This results in a content_sets.yml that differs from the
configured repositories.
To test:
```sh
curl -sSL -XPOST --header "Accept-Encoding: gzip, deflate" --header "Accept: */*" --header "Content-Type: application/json" --header "Authorization: Basic ABC" -d '
{
"criteria": {
"fields": [
"id",
"notes"
],
"filters": {
"$in": [
]
},
"$in": [
"rhocp-4.6-for-rhel-8-x86_64-rpms",
"rhocp-4.6-for-rhel-8-ppc64le-rpms",
"rhocp-4.6-for-rhel-8-s390x-rpms"
]
}
}
}
}
' "https://pulp.dist.prod.ext.phx2.redhat.com/pulp/api/v2/repositories/search/" | jq -r '.[] | .id + " " + .notes.content_set'
rhocp-4_DOT_6-for-rhel-8-ppc64le-rpms …
```
> 4.3 Correct rhel-8-server-ose content_set

- images/openshift-enterprise-hyperkube.yml
- rpms/openshift.yml
As of 4.6 the hyperkube builds are moving from openshift/origin to openshift/kubernetes to simplify the maintenance of our fork of kubernetes.
My intent with this PR is to determine the necessary ART configuration in preparation for an orchestrated transition. I'm marking as WIP until both the configuration and transition plan have been finalized.
> Switch to build hyperkube image and rpm to openshift/kubernetes

- group.yml
Removing the following repositories as they are not consumed by `rpms/*` or `images/*`:
```
rhel-7-server-ansible-2.4-rpms
rhel-7-server-ansible-2.5-rpms
rhel-7-server-ansible-2.6-rpms
rhel-fast-datapath-htb-rpms
```
> 3.11: Remove unused repositories

- images/openshift-golang-builder.Dockerfile
These are needed for building ose-hyperkube, but just happened to be
pulled into the rhel7 golang-builder as dependencies of other packages.
> Install diffutils and rsync

- images/golang-github-prometheus-node_exporter.yml
The builder installs packages from rhel-server-ose-rpms, but that package will not be in the resulting image.
> Add rhel-server-ose-rpms back to ose-prometheus-node-exporter image

- images/golang-github-prometheus-alertmanager.yml
- images/golang-github-prometheus-prometheus.yml
- images/prom-label-proxy.yml
- images/thanos.yml
node_exporter has been fixed already in https://github.com/openshift/ocp-build-data/pull/580 and https://github.com/openshift/ocp-build-data/pull/579.
/cc @vfreex @openshift/openshift-team-monitoring
> images: add ose-rpms to fix broken build with missing promu package

- images/cluster-logging-operator.yml
This PR addresses a latest build breaking change in cluster logging operator introduced by openshift/cluster-logging-operator#628. In detail the referenced PR adds a new `FROM` directive to include the `oc` utility in its build.
/cc @sosiouxme @thiagoalessio
> [cluster-logging-operator] Add missing member to oc cli image

- images/ose-containernetworking-plugins.yml
This adds another layer reference, to resolve a dockerfile that has failed to reconcile.
Dockerfile in question changed in this PR @ https://github.com/openshift/containernetworking-plugins/pull/30
> The reference CNI plugins should have an additional layer for windows binaries

- group.yml
Conten sets were ignored. These are the correct names:
```
curl -sSL -XPOST --header "Accept-Encoding: gzip, deflate" --header "Accept: */*" --header "Content-Type: application/json" --header "Authorization: Basic abc" -d '
{
"criteria": {
"fields": [
"id",
"notes"
],
"filters": {
"$in": [
]
},
"$in": [
"fast-datapath-for-rhel-8-x86_64-rpms",
"fast-datapath-for-rhel-8-ppc64le-rpms",
"fast-datapath-for-rhel-8-s390x-rpms"
]
}
}
}
}
' "https://pulp.dist.prod.ext.phx2.redhat.com/pulp/api/v2/repositories/search/" | jq
```
> Correct rhel-8 fast datapath content sets

- group.yml
We ended up including those images in 4.2, but they were never supported
due to PM decisions. This commit removes them from there.
> Add kuryr-kubernetes to 4.2 non_release images

- images/hive.yml
Starting to tackle some of the CVP content_set failures that have been popping up.
When inspecting the [sanity test log for the optional CVP tests](http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-product-test/hive-container-v4.6.0-202008061759.p0/d3fc2eda-b726-42a7-bd45-b9b6854bb29d/sanity-tests-optional-results.json), I saw the following error message:
```
{
"name": "content_set_check",
"ok": false,
"status": "FAIL",
"description": "Content sets defined in Dist-git have to match with rpm content which is installed in the image",
"message": "Content sets in content_sets.yml have to be correct",
"reference_url": "https://mojo.redhat.com/docs/DOC-1023066#jive_content_id_Content_set_information",
"logs": [
"Checking CS of build: hive-container-v4.6.0-202008061759.p0.amd64",
"Some …
```
> Remove the redundant rhel-7-server-optional-rpms content set from the Hive image.

- images/ose-etcd.yml
- streams.yml
etcd has unique approval to track its own etcd version. Other repos need arch approval to diverge from what kube apiserver uses for a given release.
ref: https://coreos.slack.com/archives/CB95J6R4N/p1598453188186800?thread_ts=1598449075.172000&cid=CB95J6R4N
> Allow etcd to specify its own golang version

- group.yml
- images/openshift-golang-builder.Dockerfile
Since we already have 1.14 for most of 4.6 and now 1.12 for etcd, probably best if we just do 1.13 now too and avoid any future emergencies.
> Make rhel-8-golang-1.13 fully functional

- group.yml
Without this, the build fails with the following error message:
```
No available modular metadata for modular package
'golang-src-1.12.12-4.module+el8.1.0+4559+87297aa9.noarch', it cannot be
installed on the system
```
Please build after merging.
> Define module_hotfixes to avoid modularity errors

- images/baremetal-runtimecfg.yml
This change is in support of bugzilla 1872080. It modifies the
configuration file for the baremetal-runtimecfg component by adjusting their
dockerfile to match the newly created "Dockerfile.openshift" file.
This change also depends on another pull request and should not be
merged until they are:
https://github.com/openshift/baremetal-runtimecfg/pull/93
> Update dockerfile paths for baremetal-runtimecfg configurations

- images/atomic-openshift-cluster-autoscaler.yml
- images/baremetal-machine-controller.yml
- images/ose-aws-machine-controllers.yml
- images/ose-azure-machine-controllers.yml
- images/ose-cluster-autoscaler-operator.yml
- images/ose-cluster-machine-approver.yml
- images/ose-gcp-machine-controllers.yml
- images/ose-machine-api-operator.yml
- images/ose-openstack-machine-controllers.yml
- images/ose-ovirt-machine-controllers.yml
- images/vertical-pod-autoscaler.yml
This change is in support of bugzilla 1872080. It modifies the
configuration files for the machine-api components by adjusting their
dockerfile to match the newly created "Dockerfile.rhel" files.
This change also depends on several pull requests and should not be
merged until they are:
https://github.com/openshift/machine-api-operator/pull/692
https://github.com/openshift/cluster-api-provider-gcp/pull/118
https://github.com/openshift/cluster-api-provider-aws/pull/349
https://github.com/openshift/cluster-api-provider-ovirt/pull/67
https://github.com/openshift/cluster-api-provider-openstack/pull/115
https://github.com/openshift/kubernetes-autoscaler/pull/169
https://github.com/openshift/kubernetes-autoscaler/pull/168
https://github.com/openshift/cluster-api-provider-azure/pull/161 …
> Update dockerfile paths for machine-api image configurations

- group.yml
To match what we provide for RHCOS.
@jupierce
> ci-deps: add rhel7 fast-datapath repos

- images/operator-registry.yml
this will include the cross-compilers for mac and windows
> use rhel-8-golang as a base for operator-registry

- images/cluster-version-operator.yml
Because we don't care if it's 7 or 8.  Catches up with openshift/cluster-version-operator@32204c00ba (openshift/cluster-version-operator#444).
Not sure if this needs to land in openshift-4.6-rhel-8 too or not.
> images/cluster-version-operator: Use Dockerfile.rhel

- images/cluster-version-operator.yml
So we get emails when Brew builds fail and on other image-maintenance tasks.
I'm not sure if @crawford wants to remain an owner alongside the team or be replaced by the team.  Until he weighs in, keeping him as a co-owner is the most conservative approach.
> images/cluster-version-operator: Add the over-the-air updates team as owners

- images/cluster-version-operator.yml
The over-the-air updates team is the more responsive owner.
> images: remove crawford from CVO ownership

- streams.yml
The hadoop upstream build process requires epel repositories. These are not available in the -base image. Change over to -release image. None of this will affect downstream builds.
> Use release image instead of base for hadoop

- images/openshift-enterprise-ansible-operator.yml
- images/ose-metering-ansible-operator.yml
This didn't work for s390x, so the necessary packages have been
cross-tagged instead.
> Remove openstack repos from ansible-operator

- images/openshift-golang-builder.Dockerfile
A couple shared libraries are built and required by the osxcross
toolchain. These need to be installed and ldconfig'ed for the dependent
binaries to work.
> Install osxcross built libraries

- images/openshift-enterprise-cli.yml
- images/ose-cli-artifacts.yml
oc is currently dynamically linked, which is needed for gssapi support.
Dynamically linked RHEL 8 binaries will not run on RHEL 7 because of
dependencies on GLIBC_2.28 symbols.
https://github.com/openshift/oc/pull/568 needs to be merged in tandem.
> Build cli and cli-artifacts with RHEL 7

- images/operator-registry.yml
- streams.yml
Reverts openshift/ocp-build-data#664
PR opening tooling failed. Backing out.
> Revert "Transition from golang 1.14 to 1.15"

- images/ose-jenkins-agent-nodejs-12.yml
@yselkowitz please confirm that renaming `jenkins-agent-nodejs-12-rhel7.yml => ose-jenkins-agent-nodejs.yml` in https://github.com/openshift/ocp-build-data/commit/86e266142baa51ded25911ad79ec773f952e3b68 was not intended. I thought we were just plain deprecating that, not re-using it for nodejs 12. However there is still a jenkins-agent-nodejs in the upstream payload, so I wasn't sure if you were trying to preserve that somehow.
-------- Commit msg:
This was incorrectly renamed from jenkins-agent-nodejs-12-rhel7 to
ose-jenkins-agent-nodejs, dropping the version.
Meanwhile ose-jenkins-agent-nodejs and component/comet repo is
deprecated (referred to unsupportable nodejs 8).
Moved to name ose-jenkins-agent-nodejs-12 as clearly intended per …
> [ART-2065] ose-jenkins-agent-nodejs-12: should have nodejs version in name

- bugzilla.yml
Bugzilla does not accept unspecified as a version anymore. Making `version` explicit.
> Add bugzilla version

- streams.yml
The stream name is the same but using a different upstream definition will drive PRs so that this all goes through CI testing first.
> make rhel7 builders use golang 1.15

- images/vertical-pod-autoscaler.yml
According to https://docs.google.com/document/d/1V_DGuVqbo6CUro0RC86THQWZPrQMwvtDr0YQ0A75QbQ I should add the component to my image metadata if I can't add it to the root `OWNERS` file. Since VPA lives in the https://github.com/openshift/kubernetes-autoscaler/ repo along with cluster autoscaler, we can't put the component in the root `OWNERS` since the two images are part of different compoents.
> Add bugzilla component to VPA image metadata

- images/ose-jenkins-agent-base.yml
cluster-samples-operator needs this to overwrite the jenkins-agent-base
imagestream like it already does for the agents themselves:
https://github.com/openshift/cluster-samples-operator/pull/331
/cherry-pick openshift-4.6
> Add jenkins-agent-base to payload

- images/operator-registry.yml
An issue in Go 1.15 causes darwin cross-compilation to fail when debug info is enabled (see https://github.com/golang/go/issues/40974#issuecomment-701429581).
Switching back to 1.14 until this can be resolved.
> fix(operator-registry): switch to go 1.14

- images/ose-cluster-kube-scheduler-operator.yml
Node (formerly Pod) team doesn't not own this.
FYI @sttts @rphillips
> images: change scheduler-operator owner to aos-master mailing list

- bugzilla.yml
The bugzilla component `CNF Platform Validation` is managed by its own errata flow. Instruct ARTs tooling to ignore bugs with this component. As requested here: https://coreos.slack.com/archives/CJARLA942/p1605001593172200
> Ignore bz component CNF Platform Validation

- images/ptp-operator-must-gather.yml
Image builds have been failing with the following error:
```
--> COPY --from=builder /go/src/github.com/openshift/ptp-operator/must-gather/collection-scripts/* /usr/bin/
API error (404): lstat /var/lib/docker/overlay2/.../go/src/github.com/openshift/ptp-operator/must-gather/collection-scripts/: no such file or directory
```
This sets the working directory as expected.
Test run initiated here: https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fcustom/1718/console
> openshift-4.7: Fix build of ptp-operator-must-gather

- group.yml
When an upstream developer attempts to build their (current) ART aligned upstream Dockerfiles on their laptops, they will fail. That is because the base ART equivalent images have repos which only resolve on the CI cluster (i.e. they are hosted on the cluster and only accessible by internal workloads). This obviously interferes with some development workflows where developers want to build locally and test.
This PR, in conjunction with https://github.com/openshift/doozer/pull/327 should improve this by adding repos that will resolve to internal Red Hat repositories if the user is within the firewall. If the user is outside the firewall, the repos will fail and be ignored because of skip_if_unavailable.
> Rpm ci alignment

- group.yml
- images/openshift-golang-builder.yml
RHEL 7.9 initscripts, which is a dependency of s390utils, added a
dependency on bc.  While s390utils and its dependencies is removed from
the base image kickstart, bc wasn't added to the list of removals.  The
result is a signed bc ending up in the base image only on s390x.  When
bc is then installed in golang-builder from the brew buildroot which is
unsigned, a mismatch results and the build fails.
Adding a RHEL pulp repo, which is signed, and making it first
alphabetically should give it priority in yum mitigating the mismatch.
> [golang-1.13] Add RHEL 7 pulp repo to get signed content

- images/atomic-openshift-descheduler.yml
Got this error when building stage operator metadata for 4.4.31:
`Command returned non-zero exit status: Error running [/mnt/workspace/jenkins/working/aos-cd-builds/build%2Fappregistry] skopeo inspect docker://registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-descheduler:v4.4.0-202011132159.p0. See debug log.` (https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fappregistry/7753/console)
I didn't check the error in details, but it seems to me the operator `ose-cluster-kube-descheduler-operator` has a reference to an old version of operand `atomic-openshift-descheduler`.
To make sure the operator is always rebuilt once its operand is rebuilt, add the operator as a dependent.
> Add ose-cluster-kube-descheduler-operator as a dependent of descheduler

- images/cluster-nfd-operator.yml
- images/clusterresourceoverride-operator.yml
- images/vertical-pod-autoscaler-operator.yml
Manifests have all been updated for 4.7:
https://github.com/openshift/cluster-nfd-operator/commit/5d809ee4cd461c628b45be90588e2659a04f4ed3
https://github.com/openshift/cluster-resource-override-admission-operator/commit/b13fb5ce67cbe4ad271027a140e186636fcb4ba4
https://github.com/openshift/vertical-pod-autoscaler-operator/commit/d64a5ca5ff684e65813e9e0edc8f3f7311d63580
> [openshift-4.7] Enable remaining OLM operators

- group.yml
- rpms/openshift-ansible.yml
- rpms/openshift-clients.yml
- rpms/openshift.yml
> Support multi-target rpm build and golang buildroot check - 4.6

- group.yml
- rpms/machine-config-daemon.yml
- rpms/openshift-clients.yml
- rpms/openshift-kuryr.yml
- rpms/openshift.yml
> Support multi-target rpm build and golang buildroot check - 4.5

- group.yml
- rpms/machine-config-daemon.yml
- rpms/openshift-clients.yml
- rpms/openshift-kuryr.yml
- rpms/openshift.yml
> Support multi-target rpm build and golang buildroot check - 4.4

- group.yml
- rpms/machine-config-daemon.yml
- rpms/openshift-clients.yml
- rpms/openshift-kuryr.yml
- rpms/openshift.yml
> Support multi-target rpm build and golang buildroot check - 4.3

- group.yml
- rpms/machine-config-daemon.yml
- rpms/openshift-clients.yml
- rpms/openshift.yml
> Support multi-target rpm build and golang buildroot check - 4.2

- group.yml
- rpms/openshift-ansible.yml
- rpms/openshift-clients.yml
- rpms/openshift.yml
Requires https://github.com/openshift/doozer/pull/320 and https://github.com/openshift/doozer/pull/324.
> 4.7: Support multi-target rpm build and golang buildroot check - 4.7

- images/ose-special-resource-operator.yml
This reverts commit be893ba920fe17b0602f0c47d6dedf7b21e83a4b.
The version currently installed is not setting ClusterOperator status, which is breaking nightly promotion.  Drop it until they have green CI showing their operator functioning as expected.
> Revert "[ART-2473] Un-wip images/ose-special-resource-operator.yml"

- images/csi-driver-manila-operator.yml
- images/csi-driver-manila.yml
- images/csi-driver-nfs.yml
Although running Manila on RHOS for IBM Power is not currently 
supported, OpenStack IPI causes the CSO to require the operator to be 
present, even if just to report that Manila is not enabled on OpenStack. 
Therefore, these need to be built on Power but will not be supported.
> Enable manila images on ppc64le

- images/ose-network-tools.yml
The aim is to rename `openshift/debug-network` to `openshift/network-tools` and to move the content of the repos.
Related `openshift/release` commit: https://github.com/openshift/release/pull/14261
> Rename debug-network image to network-tools

- group.yml
> ART-2589: Adapt to Pulp hostname change - 4.4

- group.yml
> ART-2589: Adapt to Pulp hostname change - 4.5

- group.yml
> ART-2589: Adapt to Pulp hostname change - 4.6

- images/operator-registry.yml
- streams.yml
The necessary build fix and CI Dockerfile update have already been 
merged in https://github.com/operator-framework/operator-registry/pull/541 .﻿
> Build operator-registry with golang-1.15

- images/ose-network-tools.yml
The present Dockerfile path is named as `Dockerfile.rhel7` whereas it is
using the rhel8 builder. This is really confusing and in future would end
up in more confusion with each version.
This patch changes art to use the default `Dockerfile` in the repo so that the
file name doesn't cause confusion with the image type or version.
This was also a part of the suggestion of the security review for the repo (to have the main file named as `Dockerfile`).
> SDN-1492: Network-tools: Change dockerfile path

- images/ose-network-tools.yml
In https://github.com/openshift/ocp-build-data/pull/808 the Dockerfile was changed, but the base image information for building
was not changed and now the ocp-build-data configuration is not in sync which causes
build failures. This patch updates the image stream information.
> SDN-1492: Fix ART builds for network-tools

- images/openshift-golang-builder.Dockerfile
Someone [ran into an issue](https://coreos.slack.com/archives/CB95J6R4N/p1611283490047400) where builds would succeed on amd64, but fail on s390x and ppc64le. The dockerfile had a dependency on patch. 
This PR moves some general purpose packages to all images, to minimize the risk of this type of surprise.
> Add patch and xz for all

- images/openshift-enterprise-builder.yml
4.5 openshift-enterprise-builder is constantly failing. By looking at the build http://download.eng.bos.redhat.com/brewroot/work/tasks/8842/34488842/x86_64.log, runc-1.0.0-71.rhaos4.5.git5101761.el7.x86_64 requires  container-selinux >= 2:2.2-2 which doesn’t exist in our buildroot.
By looking at errata https://errata.devel.redhat.com/package/show/container-selinux, container-selinux package is in the rhel7 extras repo. I think we can try enable the rhel-server-rpms repo in our ocp-build-data.
> ose-docker-builder: add rhel-server-extras-rpms repo

- images/egress-router-cni.yml
This is in the same category as the Multus images which are extracted on
to the node by the cluster-network-operator, and therefore must be built
twice for compatibility with both BYO RHEL and RHCOS.
This depends on https://github.com/openshift/egress-router-cni/pull/33
/cc @dougbtv
/hold
> Build egress-router-cni for both RHEL 7 and 8

- images/openshift-kubernetes-nmstate-handler.yml
- images/openshift-kubernetes-nmstate-operator.yml
- images/operator-registry.yml
- streams.yml
- kube-nmstate-handler: set operator as dependent
- kube-nmstate: internal names should match external
- Migrate to app.ci for upstream Dockerfiles
- Build operator-registry with golang 1.15
> Fix missing changes from 4.7 in 4.8

- images/local-storage-static-provisioner.yml
I think none of the images in the payload depend on this image. This
commit moves `local-storage-static-provisioner` to the place where
local-storage-operator and its descendants are.
@jsafrane does this sound right to you?
> 4.8: Remove local-storage-static-provisioner from payload

- images/logging-fluentd.yml
- streams.yml
Make RHEL8 the base image for logging-fluentd
> Bug 1930360: fluentd is unable to send logs to Elasticsearch because it can't authenticate to the es-proxy

- images/ose-jenkins-agent-maven.yml
This is part of an effort to use version agnostic naming in the https://github.com/openshift/jenkins repo.
And as we are moving to maven 3.6 this change is necessary.
> Bug 1935732: Update jenkins agent maven for 4.8

- images/clusterresourceoverride-operator.yml
- images/clusterresourceoverride.yml
- images/kube-rbac-proxy.yml
- images/linuxptp-daemon.yml
- images/ptp-operator.yml
- Re-enable clusterresourceoverride-operator after https://github.com/openshift/cluster-resource-override-admission-operator/pull/57
- Re-enable ptp-operator after https://github.com/openshift/ptp-operator/pull/100
Please verify that those are correct before merging this.
> Re-enable the remaining operators in 4.8

- images/driver-toolkit.yml
No longer needed, since https://github.com/openshift/driver-toolkit/pull/9
> [ART-2744] Remove obsolete modifications

- streams.yml
ref. https://issues.redhat.com/browse/ART-2732
> streams.yml: RHEL 8 builds use go 1.16 now

- images/operator-lifecycle-manager.yml
- images/operator-registry.yml
Update the existing OLM image configuration and update the Dockerfile name and the source upstream repository.
/hold
> images: Update the 4.8 OLM configuration(s) to use the downstream monorepo

- group.yml
Opening 4.6 merge window early since release is dropped this week.
See https://coreos.slack.com/archives/CJARLA942/p1617210467329200?thread_ts=1617195961.298300&cid=CJARLA942
> Enable automation

- erratatool.yml
Updates:
- Replace instances of `2020` with `2021`
- Remove `.` following any URLs so that the links render correctly in the published advisory
- Add placeholders for all three image type architectures
> Updates to 4.7 advisory text

- erratatool.yml
Updates:
- Replace instances of `2020` with `2021`
- Remove `.` following any URLs so that the links render correctly in the published advisory
- Add placeholders for all three image type architectures
> Updates to 4.6 advisory text

- erratatool.yml
Updates:
- Replace instances of `2020` with `2021`
- Remove `.` following any URLs so that the links render correctly in the published advisory
> Updates to 4.5 advisory text

- images/ose-vmware-vsphere-csi-driver-operator.yml
- images/ose-vmware-vsphere-csi-driver.yml
CC @openshift/storage
This is the second step described here: https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#removing-or-renaming-an-image-from-an-openshift-release-image
> Remove "vmware" prefix from CSI operator and driver

- images/vmware-vsphere-syncer.yml
Trying to fix this error: https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.8.0-0.nightly/release/4.8.0-0.nightly-2021-04-12-222417
> vsphere syncer: add missing "-driver-"

- images/openshift-enterprise-pod.yml
Update the openshift-enterprise-pod.yaml to
point to the Dockerfile under openshift/k8s/build/pause
so we build a pod image containing the pause.c binary
bringing down the pod image size from ~250MB to ~1MB.
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
> openshift-4.8: Update Dockerfile for pod yaml

- group.yml
- images/openshift-golang-builder.Dockerfile
- streams.yml
1.15 (and earlier) are locked to 8.2 because 4.6 is, but 1.16 is only for
4.8+ and therefore can use the latest.  Once we move to 8.4, this will
need to be updated again.
/cc @sosiouxme
> Build rhel-8-golang-1.16 with RHEL 8.3

- images/openshift-enterprise-cluster-capacity.yml
- do not inherit summary label
- remove `rhel-8-server-ose-rpms-embargoed` since no rpm is installed from it
- cluster-capacity repository moved under kubernetes-sigs organization
> cluster-capacity: fix CVP warnings

- images/jenkins-agent-nodejs-12-rhel7.yml
...and name it as the [long forgotten nodejs8 image](https://github.com/openshift/ocp-build-data/commit/8e45baece769bec15a427c083c7a7a401f599c07#diff-c93f6b07e45b2147145f673f148c3cd2b10f98e3e23ab70b00a0a39ade7dbad8L23)
This is to address failures like https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.5.0-0.nightly/release/4.5.0-0.nightly-2021-04-19-171118
Discussion in [thread](https://coreos.slack.com/archives/CB95J6R4N/p1618811457110800).
> 4.5 Add nodejs12 image to payload

- group.yml
- images/openshift-enterprise-pod.yml
Since https://github.com/openshift/kubernetes/pull/633 and
https://github.com/openshift/ocp-build-data/pull/873, builds for
`openshift-enterprise-pod` started to fail because `glibc-static` could
not get installed. This commit adds the rhel-8 repository for the
glibc-static rpm.
> [4.8] Fix enterprise-pod build

- group.yml
We're trying to use the FDP repo for aarch64 to enable RHCOS builds on
that arch.  The usual repo sync via the release-controller doesn't
seem to be doing the trick, so it was suggested using this method.
See: https://github.com/openshift/release/pull/17851
See: https://github.com/openshift/os/pull/541#issuecomment-823601083
> add fast-datapath repo for aarch64

- group.yml
- images/driver-toolkit.yml
- streams.yml
RHCOS 4.8 is currently building as such, this would do the same for OCP.
Whether this is a good idea at this point or not is a different question.
/hold
/cc @sosiouxme @jupierce
> Build 4.8 with RHEL 8.4 Beta

- group.yml
This too should be reverted after RHEL 8.4 GA.
The addition of the CRB repo to get glibc-static for pod snuck in while
the 8.4 Beta PR was pending.
> Use Beta repos for CRB as well

- images/openshift-enterprise-builder.yml
This makes the runc on the builder image in sync with the runc from rhcos.
> builder: Use runc from ose repo

- images/cluster-nfd-operator.yml
relates to: https://github.com/openshift/cluster-nfd-operator/pull/157
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
> Bug 1954881: update manifests location for NFD

- images/atomic-openshift-node-problem-detector.yml
- images/ose-ovn-kubernetes.yml
- rpms/atomic-openshift-node-problem-detector.yml
Change the github branch of node-problem-detector from master to
release-3.11. Direct reason is a current build failure where the 3.11
golang does not recognize the `-mod` flag.
> openshift-3.11: node-problem-detector branch

- images/openshift-enterprise-node.yml
- images/openshift-enterprise.yml
Somehow, some modifiers do not match anymore. Not really sure why, but
in the Dockerfile in distgit the chained commands are prepended with
`&&`, rather than appearing in the end.
This change replaces the command with the truthy, noop shell command
`:`, leaving the `&&` in place.
> Fix modifier matchers

- images/ose-ovn-kubernetes.yml
Commit 4d9d4c89510eff205027cc7966a42d305afeee5d changes the build branch from `master`
to `release-3.11`. The Dockerfile in `release-3.11` doesn't use the golang builder.
> Fix ose-ovn-kubernetes build

- modifications/update-console-sources
Brew-pulp was deprecated long ago. Changing to registry-proxy.engineering.
> Fix 3.11 ose-console build

- group.yml
This is to fix what was the result of running prepare-release again.
> Revert to previous advisories

- images/openshift-enterprise-tests.yml
Following https://github.com/openshift/origin/pull/26131, the builds
failed complaining about a missing python3-cinderclient package. This
commit adds the containing repository.
> Add openstack repo for tests

- group.yml
Allows 4.8 to begin using early assembly concepts.
Related:
- https://github.com/openshift/doozer/pull/408
- https://github.com/openshift/aos-cd-jobs/pull/2623
> Enable assemblies for 4.8

- images/driver-toolkit.yml
Until some point after OCP 4.8 GA, we have pinned RHCOS 4.7 to use
RHEL 8.3 content.
In order to not break `driver-toolkit`, let's pin the kernel versions
that are expected to be used during this time.
We don't anticipate any changes to which kernel is used unless there
is a CVE or urgent problem that affects OCP which needs to be
backported.
> Pin the kernel for RHCOS 4.7 using RHEL 8.3

- group.yml
- rpms/openshift-ansible.yml
- rpms/openshift-clients.yml
- rpms/openshift.yml
Some rpms use non-default Brew targets. Needs to define them explicitly.
Merge this before https://github.com/openshift/doozer/pull/410.
> 4.8: Define Brew targets for hotfix builds

- images/logging-kibana6.yml
This reverts commit 6e0d7ba88d4c0f7619828be88bee8fd355746a0b.
There's no symlink in `release-4.6` branch. We still need to build from Dockerfile.rhel8 except the developers request that.
> Revert "align with upstream change"

- group.yml
`http://download.lab.bos.redhat.com/rcm-guest/puddles/RHAOS/plashets/{MAJOR}.{MINOR}-el8/building-embargoed/ARCH/os`
==> `http://download.lab.bos.redhat.com/rcm-guest/puddles/RHAOS/plashets/{MAJOR}.{MINOR}-el8/{runtime_assembly}/building-embargoed/ARCH/os`
Requires https://github.com/openshift/doozer/pull/422
> ART-2945: Qualify repos in group.yml with assembly information

- images/ose-azure-machine-controllers.yml
- images/ose-machine-api-operator.yml
I asked about getting these fixed yesterday in slack https://coreos.slack.com/archives/CB95J6R4N/p1623754058362900 but had intended for the Azure image to be fixed up as this is the one that causes issues. We are adding more repos in the future which will need this prefix (anything forked as `cloud-proivder-...`), so assuming I'm following the correct process here I should be able to add these in the future independently?
> Update cloud team PR prefixes

- images/ose-azure-machine-controllers.yml
- images/ose-machine-api-operator.yml
> I asked about getting these fixed yesterday in slack https://coreos.slack.com/archives/CB95J6R4N/p1623754058362900 but had intended for the Azure image to be fixed up as this is the one that causes issues. We are adding more repos in the future which will need this prefix (anything forked as cloud-proivder-...), so assuming I'm following the correct process here I should be able to add these in the future independently?
This is the same as #950 but for 4.9
> OpenShift 4.9: Update cloud team PR prefixes

- images/ose-cluster-cloud-controller-manager-operator.yml
This reverts commit 61bd5aac9ef56e920b79c53ac47d49e09aad1696.
CCCMO has a couple of dependent images still in the process of being added to the payload, this means the image reference is breaking the nightly builds right now
> Make CCCMO WIP

- group.yml
Ceph 3 ended regular support earlier this year, updates are only going
to ELS now:
https://access.redhat.com/support/policy/updates/ceph-storage
> Switch Ceph to ELS repos

- group.yml
As per the document
https://access.redhat.com/support/policy/updates/openshift_noncurrent,
POWER for 3.X is EOL after June 2021. This commit removes the ppc64le
architecture from the build targets of 3.11.
> Stop building ppc64le for 3.11

- images/openshift-proxy-pull-test.yml
Add this image into the ocp-build-data(https://github.com/openshift/ocp-build-data)
repository. So product MCO(https://github.com/openshift/machine-config-operator) can
pull the image through a proxy that the customer configured to validate the proxy.
Ticket for the image build request: https://issues.redhat.com/browse/ART-2961
Signed-off-by: Qi Wang <qiwan@redhat.com>
> Add image ose-openshift-proxy-pull-test

- bugzilla.yml
Add comment to explain future artists why we filter out some OCP components in bugzilla.
context: https://coreos.slack.com/archives/CB95J6R4N/p1624983225109500
> Add comment explaining bugzilla filters

- images/local-storage-operator.yml
In LSO we changed location of manifests directory - https://github.com/openshift/local-storage-operator/tree/master/config/manifests
> Change location of manifests directory

- bugzilla.yml
This commit added the operator component to ignore https://github.com/openshift/ocp-build-data/commit/2007fa5365a136fa454350f0c393d22b31ea7007 to default list. Add component to security filter too.
> Ignore poison pill from security bugs too

- streams.yml
While this image is updated in base-rhel8, that results in bigger images 
than when starting with a current base.
It would be preferable to let this float (e.g. `registry.redhat.io/ubi8:8.4`) 
but it seems that was tried previously and there were issues?
> Update ubi8 base image

- images/driver-toolkit.yml
We are in an uncomfortable position of having to pin the kernel trying
to get builds out in time to address CVE-2021-33909, so pin the kernel
just to be safe.
> [openshift-4.8] driver-toolkit: pin kernel for 4.8

- images/driver-toolkit.yml
We are in an uncomfortable position of having to pin the kernel trying
to get builds out in time to address CVE-2021-33909, so pin the kernel
just to be safe.
> [openshift-4.6] driver-toolkit: pin kernel for 4.6

- images/driver-toolkit.yml
Even though `perl-*` versions are correctly offered in all arches, for some reason Brew/OSBS is picking a different version for s390x during build, and this inconsistency across arches prevents the build from succeeeding.
> Temporary workaround on driver-toolkit

- streams.yml
Because RHEL 8.3 was not EUS, the yum updates in base-rhel8 and
base-nodejs have essentially been updating these to 8.4 since its
release.
> [openshift-4.7] Update base images

- images/driver-toolkit.yml
A full rebuild of 4.6 should make this moot.
Reverts openshift/ocp-build-data#1007
> Revert "Temporary workaround on driver-toolkit"

- images/ose-aws-efs-csi-driver-operator.yml
We changed location of manifests - https://github.com/openshift/aws-efs-csi-driver-operator/commit/f7d484b6e5cdf191b58fd8261d1c5663b7c0ebbf
> Fix location of efs manifests

- erratatool.yml
@stevsmit confirmed with @sferich888 that we were ok to always put BZ entries in the Release Notes themselves, so this PR removes the related section. 
Some background on why we proposed this change:
The previous situation was that we would add BZ doc text to the advisory text if it fit, but if it exceeded the Errata character limit, it would go into the Rel Notes. By always including it in the Rel Notes, we make for a more consistent customer experience instead of having them find this in one of two locations for seemingly arbitrary reasons. 
It also ensures that doc text gets documentation peer review, and allows us to make updates after publication if needed (which we cannot do with Errata).
I think we are ok to go ahead with this, but I will bring it up at the next z-stream call so …
> Removes BZ section from 4.8 template

- bugzilla.yml
Test Infrastructure bugs are not user facing, and do not need to be swept into advisories.
...unless there is a good reason we're not doing so already. Up for discussion.
> [ART-3100] Do not sweep Test Infrastructure bugs

- group.yml
Observed this message from gen-payload:
```yaml
openshift-enterprise-builder:
- code: OUTDATED_RPMS_IN_STREAM_BUILD
msg: Found outdated RPM (runc-1.0.0-73.rc93.module+el8.4.0+11311+9da8acfb) installed
in openshift-enterprise-builder-container-v4.9.0-202107292001.p0.git.94e422c.assembly.stream
when runc-1.0.1-2.rhaos4.9.git4144b63.el8 was available
```
After digging, I found that `runc-1.0.1-2.rhaos4.9.git4144b63.el8` was in the plashet when `openshift-enterprise-builder-container-v4.9.0-202107292001.p0.git.94e422c.assembly.stream` was built. However, the RPM was not found because yum was finding `runc-1.0.0-73.rc93.module+el8.4.0+11311+9da8acfb` in the rhel-8 appstream repo.
Despite the rhaos4.9 RPM having a greater NVR, the fact that the appstream version was a module …
> Enable module_hotfixes for ose rhel-8 repos

- streams.yml
We will be bumping etcd to v3.5 in the next couple days bumping golang to allow  proper testing.
/hold for other deps
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>
> Bug 1990541: ETCD-203: Migrate etcd to 1.16 for OCP 4.9

- images/driver-toolkit.yml
per [conversation](https://coreos.slack.com/archives/CB95J6R4N/p1628614813142500?thread_ts=1628543497.130400&cid=CB95J6R4N) we will let 4.7 consume latest RHEL 8.4 content.
> driver-toolkit: revert RHEL 8.3 pins / repo

- Dockerfile
```
Error:
Problem: package nodejs-full-i18n-1:14.17.3-2.module+el8.4.0+11738+3bd42762.x86_64
requires nodejs(x86-64) = 1:14.17.3-2.module+el8.4.0+11738+3bd42762,
but none of the providers can be installed
```
from e.g.
http://download.eng.bos.redhat.com/brewroot/work/tasks/3742/38883742/x86_64.log.
Also disallow changing the version of nodejs-full-i18n.
> Fix nodejs base image build failure

- images/driver-toolkit.yml
PR #1032 fixed the kernel version, but we forgot to also update the RHEL version to 8.4(which RHCOS is now based on in 4.7).
Signed-off-by: David Gray <dagray@redhat.com>
> Update RHEL version in driver-toolkit

- releases.yml
Reverts openshift/ocp-build-data#1042
Not needed. It was caused by a different issue, see https://issues.redhat.com/browse/ART-3277
> Revert "Pin the missing cli image to 4.7.26"

- images/openshift-enterprise-hyperkube.yml
On aarch64, this image often fails to build with an error like:
```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
```
See e.g. http://download.eng.bos.redhat.com/brewroot/work/tasks/332/39520332/aarch64.log
Parallel to https://github.com/openshift/ocp-build-data/pull/1065
/cc @yselkowitz
> [4.9] Work around pthread creation error

- group.yml
Setting scanning freshness treshhold hours to 1. It seems unnecessary to
wait for 6 hours for a failed build, especially since we do not create
nightlies anymore if siblings are based off a different commit.
For context, we have had this set to 1 hour for 4.8, and I have not
noticed an issue with that.
```
⫸  yq -r '@text "\(.vars.MAJOR).\(.vars.MINOR) scan_freshness.treshhold_hours: \(.scan_freshness.threshold_hours)"' */group.yml
3.11 scan_freshness.treshhold_hours: null
4.5 scan_freshness.treshhold_hours: 6
4.6 scan_freshness.treshhold_hours: 6
4.7 scan_freshness.treshhold_hours: 6
4.8 scan_freshness.treshhold_hours: 1
4.9 scan_freshness.treshhold_hours: 6
4.10 scan_freshness.treshhold_hours: 6
```
> [openshift-4.10] Set treshhold_hours to 1

- releases.yml
Permits the following issues:
```yaml
cluster-node-tuning-operator:
- code: CONFLICTING_INHERITED_DEPENDENCY
msg: Expected image to contain assembly override dependencies NVR kernel-4.18.0-305.19.1.el8_4
but found kernel-4.18.0-305.12.1.el8_4 installed
permitted: false
ironic-rhcos-downloader:
- code: CONFLICTING_INHERITED_DEPENDENCY
msg: Expected image to contain assembly override dependencies NVR kernel-4.18.0-305.19.1.el8_4
but found kernel-4.18.0-305.12.1.el8_4 installed
permitted: false
openshift-enterprise-operator-sdk:
- code: CONFLICTING_INHERITED_DEPENDENCY
msg: Expected image to contain assembly override dependencies NVR kernel-4.18.0-305.19.1.el8_4
but found kernel-4.18.0-305.12.1.el8_4 installed
permitted: false
openshift-enterprise-tests:
- code: …
```
> 4.7.30: Permit CONFLICTING_INHERITED_DEPENDENCY

- releases.yml
Reverts openshift/ocp-build-data#1081
STANDARD assemblies like 4.7.30 do not allow "permits"
> Revert "4.7.30: Permit CONFLICTING_INHERITED_DEPENDENCY"

- images/ose-aws-cloud-controller-manager.yml
- images/ose-ibm-cloud-controller-manager.yml
- images/ose-ibmcloud-machine-controllers.yml
These repositories are forks from upstreams which have git history checks. We use this prefix to identify downstream commits. This should fix the dockerfile update PRs to include the correct git history.
> Update commit prefixes for cloud provider forks

- releases.yml
Dry run of the hotfix process to pull in BZ1998673; pulling in cherry-pick https://github.com/openshift-cherrypick-robot/machine-config-operator/tree/cherry-pick-2631-to-release-4.7
> Hotfix art3334

- images/ironic-agent.yml
cluster-baremetal-operator just added a reference to ironic-agent:
https://github.com/openshift/cluster-baremetal-operator/pull/202
Therefore it needs to be in the payload, and it not being so is now
causing the payload generation to fail.
> [ART-3341] Add ironic-agent to the payload

- erratatool.yml
4.9 is to be shipped on ARM like the other architectures, but not documented due to its status as Developer Preview on ARM.
> [4.9] erratatool: Add aarch64 to cdn_repos

- images/special-resource-operator.yml
Due to an error in rebasing folling a name change, image builds are
blocked. Temporarily disabling special-resource-operator.
> [openshift-4.9] Temporarily disable special-resource-operator

- group.yml
- streams.yml
Backport of #1126 to 4.7 (does not cherry-pick due to addition of CRB in 4.8).
> [openshift-4.7][ART-3423] Use RHEL 8.4 EUS content

- releases.yml
Currently, no nightlies are being produced because mismatched siblings
are detected. One cause is openshift-installer failing to build on for
ppc64le, which possibly is solved by upgrading golang to 1.17.
Permitting this class of inconsistencies for now.
> 4.10: Allow MISMATCHED_SIBLINGS

- streams.yml
https://issues.redhat.com/browse/ART-3409
brew build https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1787026
> ART-3409 Bump rhel8 golang to 1.17

- group.yml
- images/ironic-agent.yml
- images/ironic-hardware-inventory-recorder-image.yml
- images/ironic-ipa-downloader.yml
- images/ironic-rhcos-downloader.yml
- images/ironic-static-ip-manager.yml
- images/ironic.yml
- Use puddles for RHOS content on s390x and aarch64
- Enable Ironic images on aarch64, disable ppc64le
Except for ironic-ipa-downloader, which is being deprecated in 4.10.  Bare Metal IPI support never happened for Power, so it is disabled too.
> Enable Ironic containers on aarch64

- group.yml
This pulp repo and content set were exclusively for 16.0, which is out
of support.  16.1 and 16.2 are supported in parallel and therefore have
their own repos and content sets.  This also resolves mismatches with
the ARM puddle, which is also 16.2.
/assign @thiagoalessio
> Bump OpenStack to 16.2

- images/ose-metallb-operator.yml
- images/ose-metallb.yml
...as https://github.com/openshift/metallb-operator/pull/33 got merged.
edit: https://github.com/openshift/ocp-build-data/pull/1151 fix is in
> [openshift-4.9] Reenable metallb-operator

- releases.yml
As the rpms are pinned in the Dockerfile, it is expected that the
installed version is not the latest version.
> 4.10: Allow outdated rpms for ose-ovn-kubernetes

- images/ose-frr.yml
Resolves the following error during rebase of `ose-metallb-operator`:
```
ERROR [containers/ose-metallb-operator] Unable to find metallb-frr-rhel8 in image-references data for ose-metallb-operator
```
> Fix metallb operator bundle

- images/ironic-ipa-downloader.yml
The package is not used anymore since OCP 4.6
> Remove rhosp-director-images scan

- images/openshift-kubernetes-nmstate-handler.yml
Since we replaced microdnf with dnf in the handler image in
https://github.com/openshift/kubernetes-nmstate/pull/240, this
modification is not needed anymore.
**Additional information:**
This "invalid" replacement lead to an error in the last build:
> **FAILURE: Error reconciling Dockerfile for openshift/ose-kubernetes-nmstate-handler-rhel8 in OCP v4.10**
> 
> Why am I receiving this?
>
> You are receiving this message because you are listed as an owner for an
> OpenShift related image - or you recently made a modification to the definition
> of such an image in github. Upstream (github) OpenShift Dockerfiles are
> regularly pulled from their upstream source and used as an input to build our
> productized images - RHEL-based OpenShift Container Platform (OCP) images.
> 
> To serve as an …
> Remove microdnf replacement for kubernetes-nmstate handler

- images/cluster-node-tuning-operator.yml
This change adds rhel-8-fast-datapath-rpms to the node tuning operator.
See: https://github.com/openshift/cluster-node-tuning-operator/pull/304
Signed-off-by: Jiri Mencak <jmencak@users.noreply.github.com>
> cluster-node-tuning-operator: Add rhel-8-fast-datapath repo

- erratatool.yml
> Updates to advisory text 4.9

- erratatool.yml
> Updates to advisory text 4.8

- erratatool.yml
> Updates to advisory text 4.7

- erratatool.yml
> Updates to advisory text 4.6

- erratatool.yml
> Updates to advisory text 4.10

- erratatool.yml
> Updates to advisory texts 3.11

- releases.yml
Don't merge yet, to be merged when rhcos pipeline is disabled Dec 20
Change to be reverted on Jan 3
> Permit outdated rpms in rhcos for year end freeze

- releases.yml
It is preventing me from preparing the next release, since it complains about "duplicate key"
> Remove duplicate "art3594" release definition

- releases.yml
"elliott find-builds" is finding `ose-metering-ansible-operator-container-v4.6.0-202112160147.p0.gd74112d.assembly.stream`, which is not correctly tagged.
> Force correct build of ose-metering-ansible-operator on 4.6.53

- images/ose-machine-api-provider-openstack.yml
Rename the image for consistency with upstream.
See openshift/release#25351
> Rename MAPO image

- images/ironic-agent.yml
- images/ironic-hardware-inventory-recorder-image.yml
- images/ironic-rhcos-downloader.yml
- images/ironic-static-ip-manager.yml
- images/ironic.yml
The OSP repositories should not be needed to build ironic images anymore.
> Remove OSP repo dependencies from ironic images

- images/logging-elasticsearch5.yml
This updates the base image to base RHEL to allow building of Elasticsearch image using Elasticsearch built from PNC
> Bug 2036043: Update logging-elasticsearch5.yml 

- releases.yml
https://coreos.slack.com/archives/CJARLA942/p1642796895105200
bundle nvrs to go with this
- cluster-logging-operator-metadata-container-v4.6.0.202201181437.p0.g7f7eccc.assembly.stream-1
- elasticsearch-operator-metadata-container-v4.6.0.202201181437.p0.gd421c69.assembly.stream-1
> 4.6.54 to include #2036040 fix

- images/ironic-agent.yml
- images/ironic-hardware-inventory-recorder-image.yml
- images/ironic-rhcos-downloader.yml
- images/ironic-static-ip-manager.yml
- images/ironic.yml
Reverts openshift/ocp-build-data#1273
Quite some dependencies are missing as it is, see e.g. [this build](http://download.eng.bos.redhat.com/brewroot/work/tasks/8321/42658321/x86_64.log). Proposing to revert this change to get 4.11 nightlies rolling.
> Revert "Remove OSP repo dependencies from ironic images"

- group.yml
- images/ironic-agent.yml
- images/ironic-hardware-inventory-recorder-image.yml
- images/ironic-rhcos-downloader.yml
- images/ironic-static-ip-manager.yml
- images/ironic.yml
- images/ose-image-customization-controller.yml
- images/ose-machine-os-images.yml
This is for 4.10 ONLY and should NOT be carried forward to 4.11.﻿
> [ART-3709] Disable Ironic images on aarch64 in 4.10

- erratatool.yml
This PR fixes a broken link in the advisory templates.
https://issues.redhat.com/browse/OSDOCS-3224
@stevsmit PTAL
> OSDOCS-3224: [4.10] Fixed broken link in the advisory templates

- erratatool.yml
This PR fixes a broken link in the advisory templates.
https://issues.redhat.com/browse/OSDOCS-3224
@stevsmit PTAL
> OSDOCS-3224: [4.11] Fixed broken link in advisory templates

- group.yml
- images/openshift-golang-builder.yml
In cases where we want to follow the backport process, we'll need to update buildroots in the highest release first. So, move to the newest release that uses a golang version, in this case 4.9 for go 1.16.
> [rhel7] build from 4.9 buildroot instead

- group.yml
- images/openshift-golang-builder.yml
In cases where we want to follow the backport process, we'll need to update buildroots in the highest release first. So, move to the newest release that uses a golang version, in this case 4.9 for go 1.16.
> [rhel8] build from 4.9 buildroot instead

- group.yml
For all arches except ppc64le, as there is not yet a succesful build
there.
> Get m-o-c to 4.11

- releases.yml
newer nightlies ;D
[build/build-sync#22266](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/22266/console) against my fork succeeded.
> Update 4.9.23 assembly definition

- group.yml
FDP 22.A enabled aarch64 and included most current versions, except for openvswitch2.16, but we are using a cross-tagged (and version pinned) build of that anyway.
This is for 4.11; once we have confirmed that FDP-consuming images (listed below) build successfully (without component mismatches) then this should be backported to 4.10 (keeping freezes in mind) and 4.9.
cluster-node-tuning-operator
ose-ovn-kubernetes
ose-sdn
> Use pulp repo for FDP on aarch64

- images/grafana.yml
- images/kuryr-cni.yml
- images/kuryr-controller.yml
- images/logging-curator5.yml
Builds fail when those package manager magics are used. Disable for now.
> Cachito: Disable pip and yarn package manager magics

- group.yml
At this moment, 3 images are still failing to build with Cachito. I’ve temporarily disabled Cachito for those 3 images: https://github.com/openshift/ocp-build-data/pull/1353/files
> Thaw automation

- images/hypershift.yml
Reverts openshift/ocp-build-data#1360 - this can wait until 4.10.1
> Revert "[openshift-4.10] Hypershift should be included in release payloads"

- images/hypershift.yml
Reverts openshift/ocp-build-data#1362 - Merge after 4.10 GA to include in 4.10.1
> Revert "Revert "[openshift-4.10] Hypershift should be included in release payloads""

- images/openshift-base-rhel8.yml
- streams.yml
In addition to updating the base image, we discovered our consistency
checks were complaining about things present in the base image but
updated by our candidate repo; because not all images use our candidate
repo, they ended up with different contents that triggered the checks.
This also caused problems with cross-arch consistency checks in the OSBS
build.
So, the simplest solution is just to update base image contents with
candidate content where relevant.
> [ART-3854] base image -> ELS and update w/ OSE repo

- group.yml
This waits on [ppc64le rhcos build](https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.11-ppc64le/builds.json) being available.
> 4.11: Consume 4.11 rhcos

- images/special-resource-operator.yml
Picking this change to 4.11 and 4.10 
https://github.com/openshift/ocp-build-data/commit/911a2b2b8bb4d0dee59885a9e2083987c69ad96c
additional context: https://coreos.slack.com/archives/CB95J6R4N/p1646739090629709
> Correct sro name

- images/openshift-enterprise-ansible-operator.yml
- images/openshift-enterprise-helm-operator.yml
- images/openshift-enterprise-operator-sdk.yml
- images/openshift-kubernetes-nmstate-handler.yml
- images/openshift-kubernetes-nmstate-operator.yml
- images/ose-aws-efs-csi-driver-operator.yml
- images/ose-aws-efs-csi-driver.yml
from the 4.10 failed job https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/26789/
the following images failed to build
ose-aws-efs-csi-driver,
openshift-enterprise-helm-operator,
openshift-enterprise-operator-sdk,
openshift-enterprise-ansible-operator,
openshift-kubernetes-nmstate-operator,
openshift-kubernetes-nmstate-handler
> Disable cachito for failed images

- images/ose-aws-efs-csi-driver.yml
- images/ose-aws-efs-utils.yml
- aws-efs-utils
Cachito can be enabled but use empty package managers to provision sources only.
- aws-efs-csi-driver
The comment is not corrected. Updated.
> Update Cachito configuration for aws-efs-csi-driver, aws-efs-utils

- images/openshift-enterprise-ansible-operator.yml
- images/openshift-enterprise-helm-operator.yml
- images/openshift-enterprise-operator-sdk.yml
- images/openshift-kubernetes-nmstate-handler.yml
- images/openshift-kubernetes-nmstate-operator.yml
- images/ose-aws-efs-csi-driver-operator.yml
to prevent errors like:
```
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
in "<unicode string>", line 3, column 16:
container_yaml:
```
https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/26798/console
> 4.10: Remove tabs and spaces

- images/ose-aws-efs-csi-driver.yml
As https://bugzilla.redhat.com/show_bug.cgi?id=2063117 has been claimed
to be fixed.
> 4.10: Enable cachito for ose-aws-efs-csi-driver

- images/ose-installer-artifacts.yml
This build takes long, and fails often on arm64. Most of the time in the
build, it is downloading and gzipping isos. This commit proposes to
disable concurrency in the go build process to not have it fail on this.
> Set build concurrency installer-artifacts to 1

- images/ose-installer-artifacts.yml
Reverts openshift/ocp-build-data#1445
This PR also sets the concurrency of `go generate` to 1, which is causing timeouts. Reverting for now.
> Revert "Set build concurrency installer-artifacts to 1"

- images/ose-powervs-cloud-controller-manager.yml
PowerVS is limited to ppc64le, but x86_64 needs to be included for now in all images due to ART-3417.
This is a follow-up to #1451.
/cc @locriandev @joepvd
> Limit arches of ose-powervs-cloud-controller-manager

- streams.yml
... except etcd which is still stuck using 1.12
Requisite image PRs are complete:
- https://github.com/openshift/kubernetes/pull/1173
- https://github.com/openshift/oauth-apiserver/pull/74
- https://github.com/openshift/openshift-apiserver/pull/280
The images are the parts we care about here, but we'll follow up to update the buildroots as well for RPM builds.
> [ART-3664] build 4.8 with go 1.16.12 builders

- images/jenkins-agent-nodejs-10-rhel7.yml
Related conversation: https://coreos.slack.com/archives/CB95J6R4N/p1648475650505609
> Stop building deprecated image (jenkins-agent-nodejs-10-rhel7)

- images/ose-azure-cluster-api-controllers.yml
build failed for aarch64, succeeded in all other arches: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=44228086
ironically, my second build attempt (with limited arches) worked fine, building successfully for x86_64 _and_ aarch64: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=44229794
> [ART-3889] Add ose-azure-cluster-api-controllers

- streams.yml
TODO
- https://github.com/openshift/ocp-build-data/tree/golang-1.18/
- https://github.com/openshift/ocp-build-data/tree/rhel-8-golang-1.18/
- [RHEL 8](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=44278103)
- [RHEL 7](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=44278041)
- http://brew-task-repos.usersys.redhat.com/repos/scratch/dbenoit/golang/1.18+nofips.git.4aa1efed4853ea067d665a952eee77c52faac774/2.el8/
- http://brew-task-repos.usersys.redhat.com/repos/scratch/dbenoit/golang/1.18+nofips.git.4aa1efed4853ea067d665a952eee77c52faac774/2.el7_9/
> [ART-3892] provide go 1.18 for 4.11

- releases.yml
We were requested to pin 411.85.202203242008-0 until https://bugzilla.redhat.com/show_bug.cgi?id=2072050 is fixed.
> Pin rhcos for amd64 until BZ 2072050 is fixed

- group.yml
- streams.yml
As rhcos seems to switch to 8.6-beta repos, we should probably follow suit.
There does not seem to be a released ubi8.6 beta image available, not sure if we should stick to released 8.5 based ubi, or if we should consume an unreleased image in this phase of 4.11 development?
> Switch 4.11 to consume rhel-8.6 beta repos

- group.yml
- images/ose-baremetal-installer.yml
The product builds for ose-baremetal-installer on 4.11 [started to fail](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=44521601) since we changed the appstream repositories to rhel-8.6 beta content with `Error: Unable to find a match: libvirt-devel-6.0.0.`
libvirt is pinned to a GA version, and we need to keep that to interact with the libvirt most customers will be using until 8.6 is GA. So this enables GA repos to fit that need for now.
> ose-baremetal-installer: provide GA libvirt

- releases.yml
This unreverts the pin for amd64, as the 8.6 bump has catastrophically
broken Azure.
This reverts commit 5b87660ab179f9c5d66f609752a4aaa08d2a0d4a.
> Pin rhcos for amd64 until BZ2077052 is fixed

- Dockerfile
- ubi.repo
ubi based images have the ubi repositories available. EUS / ELS images do not have their repositories
configured, and these repositories are not publicly accessible without an enabled subscription.
Losing these repositories is a regression for at least ansible-operator.
This commit makes ubi8 repo available for all base images for the end user (they
are disabled during the osbs build, and get patched in again afterwards,
so it does not interfere with product builds).
> Make ubi8 repos available in base image

- rpms/openshift.yml
Reverts openshift/ocp-build-data#1531
Branch rhaos-4.11-rhel-8 does not exist yet in distgit. Reverting for now.
> Revert "openshift RPM: no longer supporting RHEL7 workers"

- images/ose-libvirt-machine-controllers.yml
ref https://coreos.slack.com/archives/CB95J6R4N/p1650895691230349?thread_ts=1650637363.040359&cid=CB95J6R4N
> ose-libvirt-machine-controllers: enable CI alignment labels

- rpms/openshift.yml
should be ready for this now that https://issues.redhat.com/browse/CLOUDBLD-9878 is complete.
> Revert "Revert "openshift RPM: no longer supporting RHEL7 workers""

- releases.yml
RHCOS builds using RHEL 8.6 content and NetworkManager 1.32.10-4.el8
(from RHEL 8.5) have been successfully produced and tested in Azure
(where https://bugzilla.redhat.com/show_bug.cgi?id=2077052 ->
https://bugzilla.redhat.com/show_bug.cgi?id=2077605) was observed.
Let's try using the 8.6 content yet again.
This reverts commit 516e23d7538dfa2ff8ddff60a012005ced101bf8.
> Revert "Pin rhcos for amd64 until BZ2077052 is fixed"

- releases.yml
Reverts openshift/ocp-build-data#1552
This is being reverted in preference of changing RHCOS 4.11 over to consume 8.5 bits.
> Revert "Bug 2081062: Revert "Revert "Pin rhcos for amd64 until BZ2077052 is fixed"""

- images/ose-ibm-cloud-controller-manager.yml
[This PR](https://github.com/openshift/cloud-provider-ibm/pull/35/files#diff-1654a648c16fa8463d261b8df6844e8472fcc393eab003dd3901dc4b423d8681) removed a build stage from the upsteam Dockerfile. This PR is to align ART configuration for 4.11
> Remove extra build stage

- group.yml
- images/ose-baremetal-installer.yml
- streams.yml
- Migrate content to RHEL 8.6 EUS
- Update base image to rhel-els 8.6 GA equivalent
> Migrate to RHEL 8.6 EUS content and base image

- images/hypershift.yml
- images/ose-installer-artifacts.yml
- streams.yml
Golang 1.18 has been enabled for all images except ose-installer-artifacts, which still have build failures.
> [ART-3892] Use golang-1.18 builders

- streams.yml
work around rebuild gap and address bz 2084234 by triggering a full rebuild.
[context](https://coreos.slack.com/archives/CB95J6R4N/p1652380952857149?thread_ts=1652374760.169169&cid=CB95J6R4N)
> [4.10] bug 2084234: streams.yml: update rhel8-els image

- group.yml
- images/openshift-golang-builder.yml
Service Mesh is asking for a newer 1.17 for [OSSM-1519](https://issues.redhat.com/browse/OSSM-1519).
> [rhel-8-golang-1.17] Bump golang to 1.17.7

- images/ose-csi-driver-shared-resource-webhook.yml
This is needed to unbreak the payloads (see https://github.com/openshift/cluster-storage-operator/pull/285)
This reverts commit 19886920c843c430217b07c6710fc6a03a8ff872.
/cc @thiagoalessio @locriandev
> [ART-4013] Revert "Set WIP mode for Shared Resource CSI Driver Webhook"

- images/ose-csi-driver-shared-resource-webhook.yml
This was a mistake in #1586 that is breaking payload generation.
> [ART-4013] Fix payload name of csi-driver-shared-resource-webhook

- images/ose-csi-driver-shared-resource-webhook.yml
This is necessary as the cluster-storage-operator will reference it: https://github.com/openshift/cluster-storage-operator/pull/278
> [ART-4013] Add csi-driver-shared-resource-webhook to payload

- releases.yml
Test [build-sync](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/24355/console)
> 4.11 - Remove redundant permits from releases.yml

- group.yml
- images/driver-toolkit.yml
...until rhcos is able to switch to 8.6 again
> 4.11: driver-toolkit tracks rhel-8.5

- images/ose-machine-os-images.yml
ose-machine-os-images uses its own shellcheck image and doesn't use golang.
> ose-machine-os-images: Don't reconcile build_root_image

- rpms/openshift-ansible.yml
- rpms/openshift-clients.yml
Follow up on https://github.com/openshift/ocp-build-data/pull/1584
Can stop using rhel7 branches once https://issues.redhat.com/browse/CLOUDBLD-10065 gives us a rhel8 branch.
> [4.11] remove rhel7 rpms

- images/ose-installer-artifacts.yml
- streams.yml
The compile issue with 1.18 for darwin targets should be fixed by https://github.com/openshift/installer/pull/5896
/cc @locriandev
> Build installer-artifacts with golang 1.18

- images/vertical-pod-autoscaler-operator.yml
This fixes this error:
`doozerlib.exceptions.DoozerFatalError: vertical-pod-autoscaler-operator: did not find a *.clusterserviceversion.yaml file @ /mnt/workspace/jenkins/working/aos-cd-builds/build%2Focp4/doozer_working/distgits/containers/vertical-pod-autoscaler-operator/manifests/4.x/`
that was breaking builds after https://github.com/openshift/vertical-pod-autoscaler-operator/pull/126 merged.
Test build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2040170
Jenkins job: https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/28690/consoleFull
> Fix bundle dir for vertical-pod-autoscaler-operator

- releases.yml
The most recent `machine-os-content` introduced a newer version of
`conmon` that catastrophically broke all of the e2e jobs.
We want to pin to the last known good RHCOS 4.11 image in the release
payload while `conmon` is fixed to allow for other changes in OCP to
land.
Last known good payload - https://amd64.ocp.releases.ci.openshift.org/releasestream/4.11.0-0.nightly/release/4.11.0-0.nightly-2022-06-06-025509
> pin to last good x86_64 machine-os-content

- releases.yml
This reverts commit d3096ee7ad655e65d5f8e6051376abaf68e03ff2.
We have a more viable RHCOS ready
> Revert "pin to last good x86_64 machine-os-content"

- releases.yml
4.9.38 assembly with custom RHCOS builds penciled in for later. should be able to prepare the release ASAP while waiting for those builds to complete.
> releases.yml: init 4.9.38 definition

- images/openshift-kubernetes-nmstate-handler.yml
Since we are replacing microdnf with dnf in the Dockerfile in https://github.com/openshift/kubernetes-nmstate/pull/280, this replacement
is not needed anymore.
/hold until https://github.com/openshift/kubernetes-nmstate/pull/280 got merged
> [release-4.8] Bug 2095360: Remove microdnf replacement for handler

- images/cloud-event-proxy.yml
- images/ib-sriov-cni.yml
- images/linuxptp-daemon.yml
- images/ptp-operator-must-gather.yml
- images/ptp-operator.yml
- images/sriov-cni.yml
- images/sriov-dp-admission-controller.yml
- images/sriov-network-config-daemon.yml
- images/sriov-network-device-plugin.yml
- images/sriov-network-operator.yml
- images/sriov-network-webhook.yml
These operators are hardware specific, and nothing relevant is foreseen for IBM Z.
> [openshift-4.11] Drop s390x builds of PTP and SR-IOV operator images

- group.yml
These can be skipped with a parameter in Jenkins or disabling them in assemblies.
> Enable multi-arch release payloads in 4.11

- erratatool.yml
...and stop to look at rhel-7 tags.
```
⫸  elliott -g openshift-4.11 --data-path $(pwd) find-builds -k rpm
2022-06-03 12:05:25,239 INFO Using branch from group.yml: rhaos-4.11-rhel-8
Generating list of rpms: Hold on a moment, fetching Brew builds
2022-06-03 12:05:29,628 INFO Finding builds specific to assembly stream in Brew tag rhaos-4.11-rhel-8-candidate...
2022-06-03 12:05:32,689 INFO Found 83 builds.
2022-06-03 12:05:32,689 INFO Finding builds specific to assembly stream in Brew tag rhaos-4.11-rhel-8-hotfix...
2022-06-03 12:05:32,935 INFO Found 5 builds.
2022-06-03 12:05:32,936 INFO Finding builds specific to assembly stream in Brew tag rhaos-4.11-ironic-rhel-8-candidate...
2022-06-03 12:05:34,220 INFO Found 122 builds.
```
> Add ironic tag to product version mapping

- images/atomic-openshift-descheduler.yml
- images/cluster-nfd-operator.yml
- images/clusterresourceoverride-operator.yml
- images/kube-rbac-proxy.yml
- images/node-feature-discovery.yml
- images/openshift-kubernetes-nmstate-handler.yml
- images/openshift-kubernetes-nmstate-operator.yml
- images/ose-cluster-kube-descheduler-operator.yml
- images/special-resource-operator.yml
- images/vertical-pod-autoscaler-operator.yml
Optional operators that refer to a specific version, say 4.11, need to
be disabled. Also images that declare themselves to be a member of a
disabled operator need to have that reference removed.
The commit was created with the following script (there is
at least one zsh-ism in here)
```sh
operators=( $(
for f in images/*; do
yq -r --arg f $f 'select(has("update-csv")) | select(."update-csv"."bundle-dir" | startswith("stable") | not) | $f' $f
done
) )
for operator in ${operators[@]}; do
echo '# Disabling until upstream updates channels for 4.12' >tmpfile
echo '# ...or updates bundle dir to stable/' >>tmpfile
echo 'mode: disabled' >>tmpfile
cat $operator >>tmpfile
mv tmpfile $operator
done
operands=( $(
for image in images/*; do
yq -er 'select(has("dependents")) | ""' $image && echo $image …
```
> 4.12: Disable operators with versioned bundle directory

- streams.yml
Referenced Build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46133877
> ART-4161 - Bump 4.11 golang to 1.18.2

- group.yml
- images/ironic-agent.yml
- images/ironic-rhcos-downloader.yml
- images/ironic-static-ip-manager.yml
- images/ironic.yml
Ironic tags have been set up to use rhel-9. The base image is not yet
ready. This commit temporarily disables ironic* images, as well as the
ironic repository to get 4.12 moving.
Related: https://github.com/openshift/ocp-build-data/pull/1686
> 4.12: Disable ironic images and repo temporarily

- images/ose-agent-installer-node-agent.yml
...and avoid these build-sync warnings:
```
ose-agent-installer-node-agent:
- code: OUTDATED_RPMS_IN_STREAM_BUILD
msg: Found outdated RPM (conmon-2.1.0-1.module+el8.6.0+14877+f643d2d6) installed
in ose-agent-installer-node-agent-container-v4.11.0-202206230818.p0.gd9f0877.assembly.stream
when conmon-2.1.2-2.rhaos4.11.el8 was available
permitted: true
- code: OUTDATED_RPMS_IN_STREAM_BUILD
msg: Found outdated RPM (fuse-overlayfs-1.8.2-1.module+el8.6.0+14877+f643d2d6)
installed in ose-agent-installer-node-agent-container-v4.11.0-202206230818.p0.gd9f0877.assembly.stream
when fuse-overlayfs-1.9-1.rhaos4.11.el8 was available
permitted: true
- code: OUTDATED_RPMS_IN_STREAM_BUILD
msg: Found outdated RPM (podman-4.0.2-6.module+el8.6.0+14877+f643d2d6) installed
in …
```
> ose-agent-installer-node-agent: container tools from ose repo

- rpms/openshift-ansible.yml
4.11 builds of openshift-ansible were stopped due to a build error.  However, the package is still needed for BYO RHEL (now 8).
The fix for the build error has been filed as https://github.com/openshift/openshift-ansible/pull/12398
This reverts commit 8a976dccad2bfeb73c7b63c422e986cf4146dd08.
> [4.11] Reinstate openshift-ansible RPM, build for RHEL8

- images/ose-cluster-baremetal-operator.yml
As follow-up of https://github.com/openshift/ocp-build-data/pull/1715,
to work around this error:
```
error: unable to create a release: operator "cluster-baremetal-operator" contained an invalid image-references file: no input image tag named "ironic"
```
https://amd64.ocp.releases.ci.openshift.org/releasestream/4.12.0-0.nightly/release/4.12.0-0.nightly-2022-06-24-053902
> Disable baremetal-operator temporarily

- group.yml
ose-ovn-kubernetes is getting the containernetworking-plugins from
appstream, as that module build has an epoch.
This excludes that package to get installed from the appstream repo in
favor of the ose repo.
Resulting test build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46173701
> Exclude containernetworking-plugins from appstream repo

- images/ironic-rhcos-downloader.yml
https://github.com/openshift/ironic-rhcos-downloader/pull/77 introduced
a new build stage. Update config to match
> Fix buildconfig to match upstream

- bug.yml
- bugzilla.yml
With the addition of new images on 4.10 (ART-4052, ART-4074, ART-4075, and ART-4076) we also need to sweep their corresponding bugs into advisories.
> Do not ignore "Telco Edge" BZs

- group.yml
Per [slack](https://coreos.slack.com/archives/CB95J6R4N/p1657130672594489?thread_ts=1657006519.906429&cid=CB95J6R4N) and [Jira](https://issues.redhat.com/browse/RHELDST-6698?focusedCommentId=18475590&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-18475590) rhsm-pulp does not reliably keep minor z-stream repos updated until the next minor RHEL version releases and the z-stream becomes associated with the minor. So use the major release repos until then.
Did not see a reason to change the content sets.
> [4.11] use mainline RHEL repos

- group.yml
> group.yml: use successful 4.12 RHCOS builds

- group.yml
- images/ironic-agent.yml
- images/ironic-rhcos-downloader.yml
- images/ironic-static-ip-manager.yml
- images/ironic.yml
- releases.yml
depends on https://github.com/openshift/aos-cd-jobs/pull/3131 as well as contents of el9 tags.
> reinstate ironic with rhel9 base/repos

- rpms/openshift-ansible.yml
This is essentially a backport of #1718.
OCP 4.9 added RHEL 8 worker nodes, and 4.10 dropped RHEL 7 worker node support.  Since it makes little sense to require a RHEL 7 system in order to configure a RHEL 8 host, openshift-ansible should have been moved to RHEL 8 by 4.10.  We're fixing that by adding a RHEL 8 RPM, but since the RHEL 7 RPM has already shipped in 4.10, it's probably too late to remove it.
This requires a backport of the build fix in https://github.com/openshift/openshift-ansible/pull/12400 as well as adding the package to the tag and creating the dist-git branch ([ticket](https://issues.redhat.com/browse/CLOUDBLD-10416)).
/cc @patrickdillon
> [openshift-4.10] Bug 2100850: Add RHEL8 openshift-ansible RPM

- group.yml
https://releases-rhcos-art.cloud.privileged.psi.redhat.com/?stream=releases/rhcos-4.12-aarch64 exists now
> group.yml: use the arm64 RHCOS builds

- ci_transforms/rhel-8/ci-build-root/Dockerfile
This follows the releases as used by upstream k8s, see the commit where I've linked specific places where this is coming from, so that it's easier to find next time. I'll separately send an announcement, since that protoc change especially will have a broader impact on all devs. 
> Bump etcd to 3.5.4 and protoc to 3.15.5 to match upstream k8s

- images/cluster-version-operator.yml
Currently 4.12 is the dev release, so it [only needs `lgtm` and `approved`][1].  But eventually 4.12 will hit code-freeze, and then it will also [need `bugzilla/valid-bug` and `staff-eng-approved`][2].  And eventually it will be a generally available release, and then it will [need `approved`, `backport-risk-assessed`, `bugzilla/valid-bug`, `cherry-pick-approved`, and `lgtm`][3].  The CVO is very flexible about Go versions and whatnot, so we don't need any of these sign-offs for CI-alignment pull requests.  With this commit, we add all the labels we'll need to merge at any stage of the 4.12 lifecycle.  And hopefully the same configuration will propagate into 4.13 once we get release branches here for that.
[1]: https://github.com/openshift/release/blob/7114512b31971dcfe83454a40ed77f8881cec …
> images/cluster-version-operator: auto_label for merge

- images/jenkins-agent-maven-35-rhel7.yml
- images/jenkins-agent-maven-36-rhel7.yml
- images/jenkins-agent-nodejs-12-rhel7.yml
- images/jenkins-slave-base-rhel7.yml
- images/openshift-jenkins-2.yml
As per
https://drive.google.com/file/d/1z66r7wERKq7hrvlm1KW7muh4ViL0tdZZ/view,
jenkins artifacts are not part of the Extended Life Cycle Support Add-On
offering. This commit stops to build the images.
> [ART-4218] Stop shipping jenkins for 3.11

- rpms/microshift.yml
ART's automation doesn't support excluding a component from a release yet. Temporarily disable microshift for 4.10.24 release preparation.
> Temporarily disable microshift

- rpms/microshift.yml
Reverts openshift/ocp-build-data#1799
/hold until 4.10.24 is promoted.
> Revert "Temporarily disable microshift"

- images/ose-gcp-cloud-controller-manager.yml
- images/ose-gcp-cluster-api-controllers.yml
- images/ose-gcp-pd-csi-driver-operator.yml
- images/ose-gcp-pd-csi-driver.yml
- images/ose-machine-api-provider-gcp.yml
This is just to enable early development for now, depending on how things go, this may be reverted before 4.12 RC.
> Enable GCP images on ARM

- rpms/openshift-clients.yml
- rpms/openshift.yml
This ran fine in test before but I was waiting until the buildroots got synchronized golang versions (was 1.18.0 vs 1.18.2). This should be good now.
> rpms/openshift{,-clients}: enable el9 builds

- group.yml
- releases.yml
depends on https://github.com/openshift/doozer/pull/618
there will also be accompanying changes to assemblies schema
> [ART-3883] group.yml: define RHCOS alternate container conf

- streams.yml
(only el8; el9 is not ready yet)
> [4.12] streams: update golang to 1.18.4

- streams.yml
Update: now also updates etcd golang for CVE fix.
> [4.11] streams: update golang to 1.18.4

- releases.yml
build-sync succeeded: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/26125/console
> Prepare 4.8.47

- releases.yml
This reverts commit 00ee8e9730f667f73d115eb63cb797077d7c634b to mitigate https://issues.redhat.com/browse/TRT-444
Per [TRT policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get ci and/or nightly payloads flowing again.
We believe this is causing 4.12 nightly payload failures as mentioned in [TRT-444](https://issues.redhat.com//browse/TRT-444).
cc: @elfosardo (who has a [fix in mind already](https://github.com/openshift/ironic-agent-image/pull/59))
> [openshift-4.12] Bug 2114968: Revert "releases.yml: remove ironic pins now that they build"

- images/openshift-enterprise-console.yml
Distgit lookaside cache is no longer used. Needs to remove `sources`
file from upstream source.
> ose-console: ensure sources file is removed

- releases.yml
build-sync 
https://saml.buildvm.openshift.eng.bos.redhat.com:8888/view/Build%204.x/job/aos-cd-builds/job/build%252Fbuild-sync/26130/
Running on https://github.com/locriandev/ocp-build-data/commit/4d3650ceff9387d654486dbd338f2d4d823b8457
This branch and daniele's branch are essentially the same, just with advisory and jira values filled in
> rc.7 assembly definition

- releases.yml
re: https://issues.redhat.com/browse/FDN-97
> Defining 4.12-ec.1 for build02 recovery

- bug.yml
There was an error in populating bug.yml with components
that don't belong to 4.6. Restore this list back to what's in
bugzilla.yml
> [4.6] consolidate bug.yml with bugzilla.yml

- group.yml
With assemblies, they are not needed and may cause confusion to our
automation.
> Remove advisories from group.yml

- images/ovn-kubernetes-base.yml
- images/ovn-kubernetes-singlenode.yml
ose-power-machine-controllers is a ppc64 only image. It's not clear if https://issues.redhat.com/browse/ART-3417 has been fixed along the way, 4.12 seems to be the right playground to check this.
> [ART-3911] stop building ose-power-machine-controllers for x86

- releases.yml
Earlier nightlies were chosen previously in order to avoid a regression (a fix in RHEL 8.4.z before 8.6.z). This is waived and the newer nightlies should include that fix.
> releases: update 4.10.31 to newer nightlies for kernel update

- images/openshift-kubernetes-nmstate-operator.yml
In openshift/kubernetes-nmstate/pull/285 we store the bundle manifests in the supposed bundle structure from the operator-sdk. This PR aligns the bundle dir for CSV with these changes.
/hold as it should merge the same tide as openshift/kubernetes-nmstate/pull/285 (which updates the bundle directory path and includes the 4.12 manifests)
> Align kubernetes-nmstate bundle dir with new bundle structure

- images/atomic-openshift-descheduler.yml
- images/ose-cluster-kube-descheduler-operator.yml
Should be fixed up per
https://github.com/openshift/cluster-kube-descheduler-operator/commit/99a002b48361c8b8992d8eb2347358fa530c58dd
> images/ose-cluster-kube-descheduler-operator: re-enable

- images/ose-agent-installer-api-server.yml
An additional build stage has been introduced upstream: https://github.com/openshift/assisted-service/commit/151f68b08d2f0e9111bc5115ba88482e675997a0#diff-b30fb02587208d9c8a793ae835c6fdd8bdc88657b7fe0f7b244e63b42430aad3R2. This configuration change tries to match centos:stream9 with our rhel9 stream
> Add missing build stage

- releases.yml
Component name for ingress-node-firewall changed after brew event. Need to use the old name in ec.3.
> Update ec.3 definition

- releases.yml
The component name for ingress-node-firewall-daemon changed as well. Use the old name in ec.3.
> ec.3 update

- images/ironic-rhcos-downloader.yml
Following https://github.com/openshift/ironic-rhcos-downloader/commit/cc369e6f1051f042b941e69ee7f9d486249189f2, a new build stage needs to be declared.
> Fix rebase of ironic-rhcos-downloader

- images/openshift-kubernetes-nmstate-handler.yml
- images/ose-agent-installer-api-server.yml
- images/ose-image-customization-controller.yml
nmstate got tagged into 4.12 rhel-8 tag. This commit ensures that all nmstate consuming images consume the ose selected build.
As the ose repo is enabled by default in CI, this ensures that CI tests what ART builds.
Context: https://issues.redhat.com/browse/CLOUDBLD-11049
> 4.12: Add ose repo to nmstate consuming images

- images/ironic-agent.yml
- images/ironic-rhcos-downloader.yml
- images/ironic-static-ip-manager.yml
- images/ironic.yml
This will help doozer logic compare against the right RPM candidate tag. Requires https://issues.redhat.com/browse/CLOUDBLD-11118
/hold
until complete
> [ART-4558] move ironic images to rhel9 branch

- images/ptp-operator.yml
move summary field under labels
http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-product-test/ose-ptp-operator-container-v4.12.0-202209231957.p0.g4e588c9.assembly.stream/91325cc3-3d1e-4bc0-87ed-43273fcfc226/sanity-tests-optional-results.json
> ptp-operator: fix CVP optional check failures

- releases.yml
ironic builds no longer need permits.
but we do need to ignore RHCOS failures so we can have nightlies more often without ARTist intervention.
> releases: tweak permits

- images/ibm-vpc-node-label-updater.yml
- images/ose-gcp-filestore-csi-driver-operator.yml
- images/ose-gcp-filestore-csi-driver.yml
- images/ose-ibm-cloud-controller-manager.yml
- images/ose-ibm-vpc-block-csi-driver-operator.yml
- images/ose-ibm-vpc-block-csi-driver.yml
- images/ose-ibmcloud-machine-controllers.yml
- Set arches in new GCP images
- Drop ppc64le from IBM Cloud VPC images
> [4.12] Fix and update arches in cloud-specific images

- images/ose-route-controller-manager.yml
- images/ose-sdn.yml
* [ART-4756] route-controller-manager should be in payload (ref. [conversation](https://coreos.slack.com/archives/CB95J6R4N/p1664552031166729))
* reverting the content_set "fix" for ose-sdn, which does in fact need the repo to avoid [inconsistency](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/27411/artifact/gen-payload-artifacts/assembly-report.yaml/*view*/)
> [4.12] couple minor fixes

- group.yml
- images/openshift-enterprise-hyperkube.yml
- images/openshift-enterprise-pod.yml
- images/ose-aws-ebs-csi-driver.yml
- streams.yml
also includes an updated golang-builder 1.19 with a non-scratch golang in it as well as dos2unix installed.
once we get a 4.12 nightly from in-flight content (update: got it with [4.12.0-0.nightly-2022-09-30-200028](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.12.0-0.nightly/release/4.12.0-0.nightly-2022-09-30-200028)), we can merge this which is going to kick off a mass rebuild (even though most will not be changed) and create all those PRs encouraging moving to go 1.19
> [ART-2617] configure for golang-1.19, but use upstream builder

- rpms/microshift.yml
To prevent this error during promotion:
```
ValueError: /mnt/workspace/jenkins/working/_cd-builds_build_prepare-release@3/artcd_working/elliott-working/ocp-build-data/rpms/microshift.yml contains template key `release_name` but no value was provided
```
> <temp> replace microshift release name template with actual release

- streams.yml
The compiler and most content is the same as previous build; but a few RHEL RPMs are reverted back to released versions (previously included some pending releases which caused problems for later layers).
No rush on this, wait for a time when a mass rebuild won't get in the way.
> streams: bump golang builder

- group.yml
Reverts openshift/ocp-build-data#2034
logging-elasticsearch6 image is failing to build. Upstream ticket: https://issues.redhat.com/browse/CLOUDBLD-11234.
Proposing to move 4.6 back to imagebuilder, as 4.6 can stop building before osbs1 cluster is torn down.
> Revert "Move 4.6 to osbs2"

- releases.yml
successful build-sync run against my fork: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/27578/console
> [FDN-163] Add ec.4 release

- modifications/microshift-rebase
- rpms/microshift.yml
microshift has rebased on 4.12.
This rpm is added with `mode: disabled` so that it won't be built during ordinary ART automation.
> Add microshift rpm

- streams.yml
Following
https://github.com/openshift/etcd/commit/8af13441b6476d15ecc96bdf58b5ff9ed61fb8a9, golang should be bumped to 1.16.
> 4.8: Bump etcd golang

- streams.yml
Ref. https://issues.redhat.com/browse/ART-4564
> 4.12 - Update rhel-9-golang builder to 1.19

- erratatool.yml
[OSDOCS-4289](https://issues.redhat.com//browse/OSDOCS-4289): shortens stock text and moves it from the description to the solution.
[Jira](https://issues.redhat.com/browse/OSDOCS-4289) 
Preview
Additional Info:
> OSDOCS-4289: shortens the stock text for errata 4.11

- streams.yml
This should fix the cli-artifacts build failures.
> [4.10] Update rhel-7 golang-builder for goversioninfo rebuild

- erratatool.yml
Same as https://github.com/openshift/ocp-build-data/pull/2049 but for 4.12
> OSDOCS-4289: shortens the stock text for errata 4.12

- group.yml
- rpms/openshift-clients.yml
We don't want to support this against rhel7 and we no longer need to even for internal purposes; statically-linked builds from cross-arch rhel8 compiles will work fine.
> [4.11] openshift-clients: stop building for rhel7

- streams.yml
nothing uses it yet, but just for completeness
> streams.yml: update rhel9 golang builder

- erratatool.yml
This PR is to update the errata text for OCP's RN docs team. Specifically, we are updating the Image advisories `Description` and `Solution` sections. Our goal is to shorten the `Description` section by moving Quay and sha values into the `Solution` section. 
@thiagoalessio and @vfreex this needs cherry picked to 4.10 and 4.12, please. I'll submit a separate PR for 4.8 to be cherrypicked to 4.9. We cannot cherry pick this to 4.8 and 4.9 because  aarch64 architecture is not in that errata text. Thank you
Relates to:
#2094 
#2049
> RNs-4.11-errata: updates errata text for Images

- images/ose-ibmcloud-cluster-api-controllers.yml
https://coreos.slack.com/archives/CB95J6R4N/p1667208399070669?thread_ts=1666984321.707159&cid=CB95J6R4N
> temporarily use upstream for ibmcloud-cluster-api-controllers

- modifications/microshift-rebase
- To rebase against nightlies, define MICROSHIFT_PAYLOAD_X86_64 and MICROSHIFT_PAYLOAD_AARCH64.
- To rebase against a named release, define RELEASE_NAME.
- To not rebase at all, define MICROSHIFT_NO_REBASE=1
> [ART-4863] [4.12] microshift: Support rebasing against nightlies

- images/ose-gcp-cloud-controller-manager.yml
- images/ose-gcp-cluster-api-controllers.yml
- images/ose-gcp-filestore-csi-driver-operator.yml
- images/ose-gcp-filestore-csi-driver.yml
- images/ose-gcp-pd-csi-driver-operator.yml
- images/ose-gcp-pd-csi-driver.yml
- images/ose-machine-api-provider-gcp.yml
This is ONLY for 4.12; enablement will continue in 4.13.
> [4.12 ONLY] Disable GCP images on ARM

- images/ose-powervs-block-csi-driver-operator.yml
- images/ose-powervs-block-csi-driver.yml
The x86 images need to be enabled because of ART-3417.
> [4.12] Fix arches of PowerVS images

- erratatool.yml
```
yq . <erratatool.yml
yq: Error running jq: ParserError: while parsing a block mapping
in "<stdin>", line 70, column 5
expected <block end>, but found '<scalar>'
in "<stdin>", line 83, column 7.
```
> Fix YAML parsing errors

- images/openshift-enterprise-console.yml
we need to access it securely and I [tested that it works|https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fcustom/2790/console].
> [ART-4858] openshift-enterprise-console: access ocp-artifacts with https

- images/ose-ibmcloud-cluster-api-controllers.yml
Unlike the rest of the IBM Cloud support images, this image is used for both IBM Cloud VPC and PowerVS.
https://coreos.slack.com/archives/CB95J6R4N/p1666984321707159
> Enable ppc64le in ibmcloud-cluster-api-controllers

- images/ibm-vpc-node-label-updater.yml
- images/ose-ibm-cloud-controller-manager.yml
- images/ose-ibm-vpc-block-csi-driver-operator.yml
- images/ose-ibm-vpc-block-csi-driver.yml
- images/ose-ibmcloud-cluster-api-controllers.yml
- images/ose-ibmcloud-machine-controllers.yml
IBM is working on this enablement.  Unlike PowerVS, which sits on top of "classic" IBM Cloud APIs and therefore has its own images, the Z additions are in VPC and therefore should share images with x86.
> [4.13] Add s390x to IBM Cloud images

- erratatool.yml
Updates errata text for 4.8 by moving SHAs and quay to the solutions section. The move leave more room in the description section for bugs.
PTAL @thiagoalessio and @opayne1
> RNs-4.8-errata:updates OCP errata text

- group.yml
- releases.yml
This PR temporarily pins 4.12 rhcos and adds permits to stream assembly to let nightlies production start.
> OCP-4.13 - add permits to let nightlies start flowing

- rpms/openshift-clients.yml
[4.13 build-sync](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/28326/console) is breaking with:
```
OSError: RPM openshift-clients claims to have a rhel-9 build target, but not build was detected
```
> Disable openshift-clients rhel9 targets

- releases.yml
Need this until pinned rpms are updated https://github.com/openshift/ovn-kubernetes/pull/1362
also see: https://coreos.slack.com/archives/C048BG69N8H/p1668031797575059
> 4.13: permit openvswitch outdatedness

- releases.yml
https://coreos.slack.com/archives/CB95J6R4N/p1668002087089749
This should be reverted as soon as the problem is fixed
> [4.12] Permit rhcos because p8 is broken

- releases.yml
This is the default for all stream assemblies so we should keep this
from stopping our nightlies
https://github.com/openshift/doozer/blob/a7fc1984673fdcc9bbf9d0fc12a71cfe270a6649/doozerlib/assembly.py#L298
> [4.13] Permit outdated rpms

- releases.yml
This is the default for all stream assemblies so we should keep this
from stopping our nightlies
https://github.com/openshift/doozer/blob/a7fc1984673fdcc9bbf9d0fc12a71cfe270a6649/doozerlib/assembly.py#L298
> [4.12] Permit outdated rpms

- releases.yml
4.13 builds are back (most recent one [here](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2256388)).
> Unpin console

- group.yml
/hold the PR for creating the repo is not created yet.
> [3.11] Update plashet repo URLs

- group.yml
Requires https://github.com/openshift/aos-cd-jobs/pull/3323
> [4.11] Update plashet repo URLs

- images/ose-nutanix-cloud-controller-manager.yml
Per https://issues.redhat.com/browse/ART-5201 we want this to remain in 4.13
This reverts commit 7e106b621262b35d103131e721ec08a29e2862eb.
> Revert "Remove nutanix-cloud-controller-manager image (#2161)"

- group.yml
/hold don't merge until we start building plashet repos for 4.12.
> [4.12] Update plashet repo URLs

- images/ose-etcd.yml
etcd will keep their build root in go 1.16, no need to create alignment pr for 1.19
> update etcd alignment build root

- group.yml
Requires https://github.com/openshift/aos-cd-jobs/pull/3323
> [4.8] Update plashet repo URLs

- group.yml
Requires https://github.com/openshift/aos-cd-jobs/pull/3323
> [4.9] Update plashet repo URLs

- group.yml
Requires https://github.com/openshift/aos-cd-jobs/pull/3323
> [4.10] Update plashet repo URLs

- images/atomic-openshift-cluster-autoscaler.yml
- images/ose-alibaba-cloud-controller-manager.yml
- images/ose-aws-cluster-api-controllers.yml
- images/ose-azure-cluster-api-controllers.yml
- images/ose-cluster-api.yml
- images/ose-cluster-kube-cluster-api-operator.yml
- images/ose-gcp-cloud-controller-manager.yml
- images/ose-gcp-cluster-api-controllers.yml
- images/ose-ibmcloud-machine-controllers.yml
- images/ose-kubevirt-cloud-controller-manager.yml
- images/ose-machine-api-provider-aws.yml
- images/ose-machine-api-provider-azure.yml
- images/ose-ovirt-machine-controllers.yml
- images/ose-powervs-cloud-controller-manager.yml
- images/ose-vsphere-cloud-controller-manager.yml
- images/ose-vsphere-cluster-api-controllers.yml
- images/vertical-pod-autoscaler.yml
Currently we plan to use [rebasebot](https://github.com/openshift-eng/rebasebot) for all our forks, so we need to update commit prefixes accordingly.
This commit adds the prefix for all cluster team forks and removes unnecessary ones.
> OCPCLOUD-1785: Update commit prefixes for cluster infra team forks

- group.yml
To test if we're ready to merge this in run
```
doozer --group openshift-4.13@art_5258_413 --data-path https://github.com/thegreyd/ocp-build-data inspect:stream INCONSISTENT_RHCOS_RPMS
...
RHCOS builds consistent [RHCOSBuild:x86_64:413.86.202211232309-0, RHCOSBuild:ppc64le:413.86.202211232309-0, RHCOSBuild:s390x:413.86.202211232309-0, RHCOSBuild:aarch64:413.86.202211232309-0]
```
> [4.13] Enable multi rhcos builds

- releases.yml
Similar case to https://github.com/openshift/ocp-build-data/pull/2309
https://bugzilla.redhat.com/show_bug.cgi?id=2114759
Fixed in https://github.com/openshift/jenkins/pull/1481
Build request: https://issues.redhat.com/browse/ART-5202
plugins build ^ was shipped as part of 4.9.52 https://errata.devel.redhat.com/advisory/105543
> 4.9.53 Exclude already shipped tracker - 2

- group.yml
Problems with the current multi pipeline prevent nightlies.
This reverts commit 6fae0cde0d6eed24e2bd87607265e2c6aad5c1de.
> Revert "[4.13] Enable multi rhcos builds (#2288)"

- group.yml
This reverts commit ac1fabd0e7bf429cf32b847c5621a57b2c7d0339.
Problem with quoted label fixed, [test job](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/28847/console) with prior commit succeeded in creating a [multi nightly](https://multi.ocp.releases.ci.openshift.org/releasestream/4.13.0-0.nightly-multi/release/4.13.0-0.nightly-multi-2022-12-02-042401) and [p8 nightly](https://ppc64le.ocp.releases.ci.openshift.org/releasestream/4.13.0-0.nightly-ppc64le/release/4.13.0-0.nightly-ppc64le-2022-12-02-042255).
> Revert "Revert "[4.13] Enable multi rhcos builds (#2288)""

- images/cluster-node-tuning-operator.yml
To match upstream dockerfile after https://github.com/openshift/cluster-node-tuning-operator/pull/519
> cluster-node-tuning: Fix declared base images

- releases.yml
- drop reference releases. Promotion is happening rather late, and the reference releases have been garbage collected already. The brew event encodes the same images, so opting for promotion with `--from-image-stream` rather than `--from-release`.
- Allow bug validation to fail. This is investigated under [ART-5478](https://issues.redhat.com//browse/ART-5478)
- Do not exclude OCPBUGS-638. Looks like permission issues have been resolved.
- Do not exclude 2115450. Set bug to ASSIGNED as we did not receive a build.
> Update rc.3 assembly

- releases.yml
The package is now tagged in our buildroot.
This reverts commit 473f9a96ceefbc4ded72020500e0baa4f3e75f6a.
> Revert "releases: pin python-twisted for ironic"

- images/ose-ovn-kubernetes.yml
- images/ovn-kubernetes-base.yml
Since https://github.com/openshift/ovn-kubernetes/pull/1239 merged:
- rpms get installed in the base image, need to add ose repo
- ovn-kubernetes uses the base image as base for its final layer
> ovn-kubernetes: Inherit from base image

- releases.yml
We missed a cve tracker so this is to bump the version
so we can fix the advisory url
https://saml.buildvm.openshift.eng.bos.redhat.com:8888/view/Build%204.x/job/aos-cd-builds/job/build%252Fbuild-sync/29127/console
> Prepare 4.11.20

- modifications/microshift-rebase
Per USHIFT-675, `_output` directory contains temporary files and needs to be removed for SRPM.
> microshift: remove _output directory

- modifications/microshift-rebase
Partial revert of https://github.com/openshift/ocp-build-data/pull/2364. Removal of `_output` dir will be handled in `rebase.sh` - see https://github.com/openshift/microshift/pull/1191
> USHIFT-677: Remove _output dir removal

- releases.yml
Reverts openshift/ocp-build-data#2387
It does not appear RHCOS wants to do this (4.13 will get the update when it ships)
> Revert "[openshift-4.13] pin advance kernel fixes"

- group.yml
- releases.yml
- streams.yml
- update golang-builder to fix leak
- pin latest kernels
> prep for RC

- rpms/microshift.yml
Now that the release-4.12 branch exists, update the build config to use that instead of main when building the MicroShift RPM.
/cc @sosiouxme
> USHIFT-614: update branch for microshift rpmbuild

- releases.yml
we are not building grafana in 4.12
> exclude grafana bug

- group.yml
ref [slack](https://redhat-internal.slack.com/archives/CB95J6R4N/p1673546271966089?thread_ts=1673543198.918899&cid=CB95J6R4N)
> group.yml: sync rhel-9-fast-datapath-rpms for use in SDN

- erratatool.yml
[OSDOCS-4282](https://issues.redhat.com//browse/OSDOCS-4282) updates the stock errata text for the RNs docs team. Updates include 2022 to 2023 and defining a images solution so that both RHBA and RHSA have the SHA values moved from the `description` to the `solution`.
> OSDOC-4282:updates the 4.12 branch stock errata text

- images/cloud-event-proxy.yml
note that errata config went to the wrong repo for this at 4.11 and 4.12 GAs, which broke not only
the main release but another non-ART component that also depends on it being at the non-`-rhel8` repo.
> [ART-5755] cloud-event-proxy: correct repo

- releases.yml
I can't see any evidence this is used anywhere or justification why we need it, so let's try removing the cruft.
> [ART-5758] 4.11 releases.yml: no apparent need to pin rt-setup

- rpms/openshift.yml
builds are failing only there due to [buildroot problems that have stalled](https://issues.redhat.com/browse/CWFCONF-3271). no point in rebuilding constantly.
ref. [slack thread](https://redhat-internal.slack.com/archives/C048BG69N8H/p1674470895490509?thread_ts=1674461263.464709&cid=C048BG69N8H) and [CWFCONF-3271]( https://issues.redhat.com/browse/CWFCONF-3271) and [CWFCONF-3293](https://issues.redhat.com/browse/CWFCONF-3293)
> rpms/openshift: temp. disable el9

- rpms/openshift-clients.yml
Parallel to https://github.com/openshift/ocp-build-data/pull/2515. Stop building perma-failing el9 of openshift-clients as well to not get enourmous churn in rhcos builds.
> Stop rebuilding el9 openshift-clients

- rpms/openshift-clients.yml
- rpms/openshift.yml
Once [slack thread](https://redhat-internal.slack.com/archives/C048BG69N8H/p1674470895490509?thread_ts=1674461263.464709&cid=C048BG69N8H) and [CWFCONF-3271]( https://issues.redhat.com/browse/CWFCONF-3271) and [CWFCONF-3293](https://issues.redhat.com/browse/CWFCONF-3293) get resolved.
> 4.13: Re-enable rhel-9 build targets openshift{,-clients}

- group.yml
Freeze automation until we can get new golang builders in.
This is important since mass rebuild is being triggered by
rhel update, and we want to wait until we have new golang
> Freeze automation until golang bump

- modifications/microshift-rebase
- rpms/microshift.yml
Since there's no lvms for 4.13 yet and microshift doesn't require a specific version of lvms-operator-bundle, hardcode v4.12 for now.
This has been confirmed with microshift team.
> microshift: Fix build

- images/ose-ibmcloud-cluster-api-controllers.yml
This adds the carry prefix to cluster-api-provider-ibmcloud, so than we can use it with the rebase bot.
> images: ose-ibmcloud-cluster-api-controllers: add carry commit prefix

- modifications/microshift-rebase
- rpms/microshift.yml
Since there's no lvms for 4.14 yet and microshift doesn't require a specific version of lvms-operator-bundle, hardcode v4.12 for now.
This has been confirmed with microshift team.
> [4.14] microshift: Fix build

- product.yml
These updates are already present in our own tooling, and were based on feedback from the respective maintainers.
The following component names do not exist in the OCPBUGS jira project:
- "Cloud Compute"
- "Node" 
- "Node / Cluster Autoscaler"
Once this is merged, on the ProdSec side we can transition to being pure downstream consumers of this data.
> Update jira component owners based on ProdSec data

- erratatool.yml
This update adds the `y` and `z` to MicroShift's rpm advisories.
> Microshift-errata:name change to include .z

- product.yml
Is the image name I've used here (`monitoring-plugin-container`) in the correct format?
The image repository is https://github.com/openshift/monitoring-plugin
> ART-6050 Add monitoring-plugin to component mapping

- group.yml
on https://download.lab.bos.redhat.com/ certificate is invalid
> update rcm url

- images/ose-ovn-kubernetes.yml
- images/ovn-kubernetes-base.yml
- images/ovn-kubernetes-microshift.yml
Ref. https://issues.redhat.com/browse/ART-6050
https://github.com/openshift/monitoring-plugin/pull/15 must merge first.
Test build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2400973
> Add monitoring-plugin

- product.yml
Both "Samples" and "Insights operator" do not exist as valid component names in OCPBUGS.
> Update jira component for samples and insights operator

- group.yml
/hold
until MCO is ready for the change and [ART-6053](https://issues.redhat.com//browse/ART-6053) is complete (https://github.com/openshift/doozer/pull/738).
along with this, revert the pin in https://github.com/openshift/ocp-build-data/pull/2618 (or similar)
if prior to branch-cut, cherry-pick this to 4.14 as well.
> [ART-6233] group.yml: update RHCOS stream and tags

- images/nmstate-console-plugin.yml
The image name needs to match the delivery repo name.
> nmstate-console-plugin: Update image name

- streams.yml
https://issues.redhat.com/browse/ART-6286
```
$ elliott go -n openshift-golang-builder-container-v1.19.6-202303140941.el8.g6a2861c
Following nvrs are built with 1.19.6-1.module+el8.8.0+18289+edd6c8b6:
openshift-golang-builder-container-v1.19.6-202303140941.el8.g6a2861c
```
> [ART-6286] 4.13 - Bump rhel9 golang builder

- streams.yml
```  
$ elliott go -n openshift-golang-builder-container-v1.19.6-202303140941.el8.g6a2861c
Following nvrs are built with 1.19.6-1.module+el8.8.0+18289+edd6c8b6:
openshift-golang-builder-container-v1.19.6-202303140941.el8.g6a2861c
```
Note: This will trigger mass rebuilds - Do not merge before Friday. 
Also Force rebuild all 4.13 rpms when close to merging this
> [ART-6286] 4.13 - Bump rhel8 builder

- releases.yml
I realize this is a 4.14 image, but I don't think it will matter.  This is a temporary image that is only needed until we pivot to RHEL 9.2 beta.
> [ART-6195] Pin DTK with scos kernel so that 9.2 kernels match

- images/monitoring-plugin.yml
- images/nmstate-console-plugin.yml
- streams.yml
Ref. https://issues.redhat.com/browse/ART-6289
Follows:
- https://github.com/openshift/nmstate-console-plugin/pull/9
- https://github.com/openshift/monitoring-plugin/pull/19
> [4.14] Remove nginx stream; use ocp base as last build layer

- group.yml
- images/driver-toolkit.yml
CoreOS for 4.14 has pivoted to using RHEL 9.2 beta bits. Following along.
> Migrate dtk to use rhel 9.2

- group.yml
- images/driver-toolkit.yml
4.13 CoreOS has pivoted to use RHEL 9.2 beta. Change driver-toolkit to use the same compose for the kernel.
> Pivot driver-toolkit to use 9.2

- images/driver-toolkit.yml
EUS repo for kernel and kernel-rt is outdated, include new tagged kernel from our repo
https://redhat-internal.slack.com/archives/C01UQM3PM3L/p1680067397745539
> include new kernel for DTK

- streams.yml
ref [ART-6416](https://issues.redhat.com/browse/ART-6416)
> bump 4.11 golang to 4.18.10

- group.yml
The older compose has expired. We should soon switch to rel-eng RC compose which should persist indefinitely.
> Bump 4.14-9.2 to RHEL-9.2.0-20230409.21

- releases.yml
AWS has rolled out permissions changes to S3 which are preventing installs.
This release minimizes the risk for promoting a release into cincy channels by basing 4.12.12 on 4.12.10.
See #tmp-aws-s3-public-access for details.
> 4.12.12 release

- releases.yml
AWS has rolled out permissions changes to S3 which are preventing installs. This release minimizes the risk for promoting a release into cincy channels by basing 4.11.36 on 4.11.34.
See #tmp-aws-s3-public-access for details.
> 4.11.36 release
