openshift-3.11/group.yml
=> add / to ppc64le repo

openshift-4.0/group.yml, openshift-4.0/images/ose-containernetworking-plugins-supported.yml, openshift-4.0/images/ose-containernetworking-plugins-unsupported.yml, openshift-4.0/images/ose-hadoop.yml, openshift-4.0/images/ose-hive.yml, openshift-4.0/images/ose-metering-helm-operator.yml, openshift-4.0/images/ose-service-serving-cert-signer.yml, openshift-4.0/images/ose-telemeter.yml, openshift-4.0/images/tuned.yml
Right now I'm only doing openshift-4.0 I'll eventually do 3.11 once I'm done with these builds
=> Misc. YAML Additions and Modifications for OpenShift 4.0 build

images/marketplace-operator.yml
-Update ose-operator-marketplace to ose-marketplace-operator
=> Fix operator marketplace name

images/ose-cluster-authentication-operator.yml
@ericavonb  updating, since repository was renamed.
=> rename repo cluster-osin-operator to cluster-authentication-operator

group.yml
Content Set Names derived from: 
https://projects.engineering.redhat.com/browse/RCM-50129
=> attempting to add OpenStack RPMs to group.yml

images/ose-etcd.yml
Updating branch naming per conversation with @smarterclayton. 
ref: https://github.com/openshift/release/pull/2632
=> images: update etcd branch naming

images/ose-kube-client-agent.yml
*  RCM-53342
* https://jira.coreos.com/browse/ART-511
Depends on: https://github.com/openshift/kubecsr/pull/5
=> images: add kube-client-agent

images/ose-kube-etcd-signer-server.yml
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>
* RCM-53344
* https://jira.coreos.com/browse/ART-512
Depends on: https://github.com/openshift/kubecsr/pull/5
=> images: add ose-kube-etcd-signer-server

images/hadoop.yml, images/hive.yml, images/presto.yml
Updates the metering images to output image names with a metering- prefix.
/assign @smarterclayton
=> images: Update image names for metering hive, hadoop, presto

group.yml
Companion PR to https://github.com/openshift/doozer/pull/58
=> group.yaml: use new doozer option to prefer 'fallback' branches

images/atomic-openshift-descheduler.yml
Update email id to point to correct one.
/cc @sosiouxme
=> Update email id

images/atomic-openshift-node-problem-detector.yml
Starting using RHEL docker files instead of using RPMs as they are not being built anymore.
/cc @joelsmith @sosiouxme
=> Update npd dockerfile location

group.yml
Adding fast-data repo for ppc64le.
=> add fast-data repo for ppc64le

README.md
Describe the purpose of the misc-sync branch, and what inputs are required here.
=> README: describe "misc-sync" branch

group.yml
=> Remove ovn-kube from blacklist 4.1

group.yml
=> Remove ovn-kube from blacklist 4.0

rpms/openshift.yml
Take advantage of https://github.com/openshift/doozer/pull/73 (so, pending that PR)
=> rpms/openshift: use custom tito config

group.yml
Related to https://github.com/openshift/elliott/pull/30
=> Add default advisory keys for bug sweep automation

images/ose-cluster-kube-apiserver-operator.yml, images/ose-cluster-kube-controller-manager-operator.yml, images/ose-cluster-openshift-apiserver-operator.yml, images/ose-cluster-openshift-controller-manager-operator.yml
=> Switch kas-o, kcm-o, oas-o and ocm-o to go1.11

images/ose-baremetal-operator.yml
remove mode wip for ose-baremetal-operator.yml
image build successfully 
https://buildvm.openshift.eng.bos.redhat.com:8443/job/aos-cd-builds/job/build%252Fcustom/257/console
https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=21246770
=> remove mode wip

README.md
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
/assign @tbielawa @adammhaile
=> Update README to point to existing branch

jobspec.yaml
Enable the new declarative pipeline.
=> jobspec: update for v3.1 pipeline

Jenkinsfile
=> Jenkinsfile: use SHA for checkout

images/cluster-logging-operator.yml, images/elasticsearch-operator.yml
fixes:
* https://bugzilla.redhat.com/show_bug.cgi?id=1706506
* https://bugzilla.redhat.com/show_bug.cgi?id=1706509
=> CSV substitution for CLO and EO

images/jenkins-slave-base-rhel7.yml
@adammhaile @sosiouxme PTAL
@waveywaves @sthaha fyi
=> enable repos so slave-base can install dumb-init

images/ose-metering-helm-operator.yml
/hold
Waiting for https://github.com/operator-framework/operator-metering/pull/711
=> Update metering-helm-operator base

images/jenkins-slave-base-rhel7.yml
=> add rpm repo to allow dumb-init install on 4.2

images/ose-openshift-state-metrics.yml
@sosiouxme PTAL for the container first image part, since this is very similar to project https://github.com/openshift/ocp-build-data/blob/8ce6c16ba413e1efcb179b7af3b0d461eef574db/images/kube-state-metrics.yml#L13
also @wanghaoran1988 PTAL
=> add ose-openshift-state-metrics

images/openshift-state-metrics.yml
https://buildvm.openshift.eng.bos.redhat.com:8443/job/aos-cd-builds/job/build%252Fcustom/301/console
https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=21859803
=> remove wip for openshift-state-metrics

images/ghostunnel.yml
RCM ticket: https://projects.engineering.redhat.com/browse/RCMAUTO-695
=> Add ghostunnel.yml to image builds

streams.yml
as I rebuild this job: https://localhost:8888/job/aos-cd-builds/job/build%252Fupdate-base-images/2/console we can replace those images
=> Update streams.yml for 3.11

images/ose-metering-ansible-operator.yml
=> adding ose-metering-ansible-operator.yml

images/cluster-monitoring-operator.yml, images/configmap-reload.yml, images/grafana.yml, images/kube-rbac-proxy.yml, images/kube-state-metrics.yml, images/ose-prometheus-adapter.yml, images/prom-label-proxy.yml, images/prometheus-config-reloader.yml, images/prometheus-operator.yml
/cc @paulfantom @brancz @adammhaile @sosiouxme
=> add more monitoring team owners

images/ose-cluster-dns-operator.yml, images/ose-cluster-ingress-operator.yml
* `images/ose-cluster-dns-operator.yml`:
* `images/ose-cluster-ingress-operator.yml`: Use the golang-1.12 builder.
=> Use golang-1.12 for Network Edge operators

group.yml
Could I attach bugs right now @smunilla @sosiouxme  ?
=> [PROD-1276] Release 4.1.3 Update group.yml

images/node-feature-discovery.yml
Same thing as the 4.1 PR but for 4.2
=> un-WIP node-feature-discovery build for 4.2

images/node-feature-discovery.yml
This builds successfully, I think confirmation just came in late enough to get lost in the shuffle.
=> un-WIP node-feature-discovery build for 4.1

images/ose-gcp-machine-controllers.yml, images/sriov-network-config-daemon.yml
=> Update image arch restrictions

README.md
=> Update gitlab URL to Github URL

images/ose-machine-config-operator.yml
Adding myself and Steve for notifications (so that when it breaks we're aware instantly)
cc @ashcrow 
Signed-off-by: Antonio Murdaca <runcom@linux.com>
=> MCO: add runcom and steve to MCO build

images/ironic-hardware-inventory-recorder-image.yml, images/ironic-inspector.yml, images/ironic-ipa-downloader.yml, images/ironic-rhcos-downloader.yml, images/ironic-static-ip-manager.yml, images/ironic.yml
Prevent spam of auto generated emails for builds.
=> Redefine ironic images owners

group.yml
Follow-on to https://github.com/openshift/ocp-build-data/pull/202
=> ovn-kubernetes: add FDP Next RHEL8 repos

images/cluster-monitoring-operator.yml, images/configmap-reload.yml, images/grafana.yml, images/kube-rbac-proxy.yml, images/kube-state-metrics.yml, images/ose-prometheus-adapter.yml, images/prom-label-proxy.yml, images/prometheus-config-reloader.yml, images/prometheus-operator.yml
Let's include more folks :)
/cc @openshift/openshift-team-monitoring
=> images: send notifications regarding monitoring components to monitoring team

images/cluster-version-operator.yml
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>
=> Bumping go version for CVO

images/ose-csi-snapshot-controller.yml, images/ose-oauth-apiserver.yml
=> Sync recent 4.4 additions to 4.5

erratatool.yml
releated to PR https://github.com/openshift/elliott/pull/108
=> Update erratatool.yml to make vars works for erratatool.yaml

group.yml
See https://github.com/openshift/doozer/pull/180.
=> Add 3.11 build profiles

group.yml
See https://github.com/openshift/doozer/pull/180.
=> Add build profiles

images/cluster-logging-operator.yml, images/ptp-operator.yml
https://github.com/openshift/cluster-logging-operator/pull/379
https://github.com/openshift/ptp-operator/pull/37
=> Re-enable two of the updated operators which were disabled

images/cluster-network-operator.yml, images/kube-proxy.yml, images/ose-ovn-kubernetes.yml
Backport of #323 to openshift-4.4; no changes
=> Fix up owners of networking images [4.4]

images/cluster-network-operator.yml, images/kube-proxy.yml, images/ose-ovn-kubernetes.yml
Backport of #323 to openshift-4.3; no changes
=> Fix up owners of networking images [4.3]

group.yml
This reverts commit bd7525e05c292d52f53f9b5ec59cb31b0cc8fba2.
=> Revert "Update advisories on group.yml"

images/cluster-nfd-operator.yml, images/clusterresourceoverride-operator.yml
Re: https://issues.redhat.com/browse/ART-1559 [4.5] - Get OLM operator owners to update their CSV channels
=> Enable operators which fixed their package.yaml thing

images/openshift-enterprise-helm-operator.yml
**Description**
Add image for `openshift-enterprise-helm-operator`
PS.: task ART-1565
=>  add images/openshift-enterprise-helm-operator.yml [openshift-4.5]

images/openshift-enterprise-helm-operator.yml
**Description**
Add image for `openshift-enterprise-helm-operator`
PS.: task ART-1565
=> add images/openshift-enterprise-helm-operator.yml [openshift-4.6]

group.yml
Reapply the contents of https://github.com/openshift/ocp-build-data/commit/9ec34e16249b328bad2a8b143f379bd36e47a6de
=> Re-enable automation 4.1.next

images/clusterresourceoverride-operator.yml, images/clusterresourceoverride.yml
=> [release-4.5] update ownership of clusterresourceoverride operator to Node team

images/clusterresourceoverride-operator.yml, images/clusterresourceoverride.yml
=> [release-4.6] change ownership of clusterresourceoverride components to node team

images/clusterresourceoverride-operator.yml, images/clusterresourceoverride.yml
=> [release-4.4] update ownership of clusterresourceoverride operator to Node team

group.yml
This reverts commit 115aef41f7b9e6041e0fd3f2a2c52d8a2fd3d71a.
=> Update 4.3 advisories

group.yml
This reverts commit ec7cc0eddf8bbaa975091aab59f095e3964945c0.
=> Update advisories and freeze automation

images/ose-multus-route-override-cni.yml, images/ose-multus-whereabouts-ipam-cni.yml
Reference: https://coreos.slack.com/archives/CB95J6R4N/p1585072126374100?thread_ts=1585063840.360200&cid=CB95J6R4N
=> Enable all group arches for multus images

images/logging-elasticsearch6.yml, images/logging-kibana6.yml
=> enable es/kibana 6 publishing

group.yml, images/ose-ovn-kubernetes.yml
=> Fix 4.5 ovn-kubernetes builds

erratatool.yml
Applies to all OCP versions, can be cherrypicked onto all branches.
=> Remove deprecated solution boilerplate text

images/ose-ovn-kubernetes.yml
=> Bug 1835318: ovn-kubernetes: re-enable fast-datapath-beta for ovn2.13-2.13.0-30

images/cluster-logging-operator.yml, images/elasticsearch-operator.yml, images/openshift-enterprise-ansible-service-broker-operator.yml, images/openshift-enterprise-template-service-broker-operator.yml
=> (4.1) [ART-1728] Add bundle-dir setting to OLM operators

images/cluster-logging-operator.yml, images/cluster-nfd-operator.yml, images/elasticsearch-operator.yml, images/local-storage-operator.yml, images/openshift-enterprise-ansible-service-broker-operator.yml, images/openshift-enterprise-template-service-broker-operator.yml, images/ose-metering-ansible-operator.yml, images/sriov-network-operator.yml
=> (4.2) [ART-1728] Add bundle-dir setting to OLM operators

images/cluster-logging-operator.yml, images/cluster-nfd-operator.yml, images/elasticsearch-operator.yml, images/local-storage-operator.yml, images/openshift-enterprise-ansible-service-broker-operator.yml, images/openshift-enterprise-template-service-broker-operator.yml, images/ose-metering-ansible-operator.yml, images/ptp-operator.yml, images/sriov-network-operator.yml
=> (4.3) [ART-1728] Add bundle-dir setting to OLM operators

images/cluster-logging-operator.yml, images/cluster-nfd-operator.yml, images/clusterresourceoverride-operator.yml, images/elasticsearch-operator.yml, images/local-storage-operator.yml, images/openshift-enterprise-template-service-broker-operator.yml, images/ose-cluster-kube-descheduler-operator.yml, images/ose-metering-ansible-operator.yml, images/ptp-operator.yml, images/sriov-network-operator.yml
=> (4.4) [ART-1728] Add bundle-dir setting to OLM operators

images/cluster-logging-operator.yml, images/cluster-nfd-operator.yml, images/clusterresourceoverride-operator.yml, images/elasticsearch-operator.yml, images/local-storage-operator.yml, images/ose-cluster-kube-descheduler-operator.yml, images/ose-metering-ansible-operator.yml, images/ptp-operator.yml, images/sriov-network-operator.yml
=> (4.5) [ART-1728] Add bundle-dir setting to OLM operators

images/cluster-logging-operator.yml, images/cluster-nfd-operator.yml, images/clusterresourceoverride-operator.yml, images/elasticsearch-operator.yml, images/local-storage-operator.yml, images/ose-cluster-kube-descheduler-operator.yml, images/ose-metering-ansible-operator.yml, images/ptp-operator.yml, images/sriov-network-operator.yml
=> (4.6) [ART-1728] Add bundle-dir setting to OLM operators

group.yml, images/aos3-installation.yml, images/openshift-enterprise-apb-base.yml
aos-installation.yml builds the ose-ansible image.
=> Update images to Ansible 2.8

images/cluster-logging-operator.yml, images/elasticsearch-operator.yml, images/elasticsearch-proxy.yml, images/golang-github-openshift-oauth-proxy.yml, images/logging-elasticsearch6.yml, images/logging-kibana6.yml, images/promtail.yml
should be ready once https://github.com/openshift/elasticsearch-operator/pull/359 merges
=> logging: fix dependencies and enable builds

group.yml
Inspired by:
https://github.com/rails/rails/pull/33681
https://github.com/elixir-lang/elixir/pull/10078
=> Replace whitelist/blacklist terminology with allowlist/denylist

erratatool.yml
=> [openshift-4.2] Cluster upgrading doc updates

erratatool.yml
=> [openshift-4.3] Cluster upgrading doc updates

erratatool.yml
=> [openshift-4.4] Cluster upgrading doc updates

erratatool.yml
=> [openshift-4.5] Cluster upgrading doc updates

erratatool.yml
=> [openshift-4.6] Cluster upgrading doc updates

group.yml
=> Really remove fast-datapath-beta repo instead of just not using it

group.yml
=> fast-datapath-beta: remove unused repos

images/prom-label-proxy.yml
=> images: update dockerfile path for prom-label-proxy

group.yml
This reverts commit 7219d8421fc40de4ff9970f3e39f3c107a26645f.
=> Revert "add public_upstreams"

images/hive.yml, images/jenkins-agent-maven-35-rhel7.yml, images/logging-kibana6.yml, images/ose-metering-ansible-operator.yml, images/ose-multus-route-override-cni.yml, images/ose-multus-whereabouts-ipam-cni.yml
Some repository adjustments for 4.5
=> 4.5 Adjust some repositories

erratatool.yml, group.yml, images/cluster-logging-operator.yml, images/openshift-enterprise-ansible-operator.yml, images/ose-aws-ebs-csi-driver-operator.yml, images/ose-aws-ebs-csi-driver.yml, images/ose-machine-api-operator.yml, images/ose-metering-ansible-operator.yml, modifications/update-console-sources, streams.yml
=> More 4.6 RHEL 8 changes

images/logging-curator5.yml, streams.yml
change logging-curator5 from stream to python-36
=> update base image of logging-curator5

group.yml, images/ib-sriov-cni.yml, images/ironic-ipa-downloader.yml, images/operator-registry.yml
=> Next batch of RHEL 8 fixes

group.yml
Requires https://github.com/openshift/aos-cd-jobs/pull/2296.
=> Point to embargoed plashets

group.yml, images/cluster-logging-operator.yml, images/csi-driver-manila-operator.yml, images/csi-driver-manila.yml, images/csi-driver-nfs.yml, images/ose-cluster-ovirt-csi-operator.yml, images/ose-containernetworking-plugins.yml, images/ose-ovirt-csi-driver.yml
=> Sync latest 4.6 mainline changes

images/ghostunnel.yml, images/hadoop.yml, images/hive.yml, images/ose-metering-ansible-operator.yml, images/ose-metering-helm.yml, images/ose-metering-reporting-operator.yml, images/presto.yml
We're using a new mailing list since we've moved out of the SD organization and into OCP.
=> images: Update the metering team mailing list.

images/sriov-network-must-gather.yaml
=> [ART-1938] add sriov-network-must-gather

erratatool.yml
=> Errata tweaks for 3.11

erratatool.yml
=> Errata tweaks for 4.3

erratatool.yml
=> Errata tweaks for 4.4

erratatool.yml
=> Errata tweaks for 4.5

erratatool.yml
=> Errata tweaks for 4.6

group.yml, images/openshift-golang-builder.Dockerfile
=> Make rhel-8-golang-1.12 builder fully functional

group.yml, images/openshift-golang-builder.Dockerfile, images/openshift-golang-builder.yml, images/sources
this allows go programs with CGO_ENABLED to target mac and windows
=> add c cross-compilers for mac and windows

images/ose-multus-route-override-cni.yml, images/ose-multus-whereabouts-ipam-cni.yml
=> Remove distgit branch override from multus images

group.yml, images/openshift-golang-builder.yml
=> Use 1.14 specific branch and buildroot

group.yml, images/aos3-installation.yml
https://bugzilla.redhat.com/show_bug.cgi?id=1855743
Need a maintainer to confirm this repo exists on the server.
=> Update ose-ansible to Ansible 2.9

images/openshift-enterprise-builder.yml, images/ose-cluster-openshift-controller-manager-operator.yml, images/ose-cluster-samples-operator.yml, images/ose-openshift-controller-manager.yml
=> [release-4.3] Update owners for build-api images

images/openshift-enterprise-builder.yml, images/ose-cluster-openshift-controller-manager-operator.yml, images/ose-cluster-samples-operator.yml, images/ose-openshift-controller-manager.yml
=> [release-4.4] Update owners for build-api images

images/openshift-enterprise-builder.yml, images/ose-cluster-openshift-controller-manager-operator.yml, images/ose-cluster-samples-operator.yml, images/ose-openshift-controller-manager.yml
=> [release-4.5] Update owners for build-api images

images/openshift-enterprise-builder.yml, images/ose-cluster-openshift-controller-manager-operator.yml, images/ose-cluster-samples-operator.yml, images/ose-openshift-controller-manager.yml
=> [release-4.6] Update owners for build-api images

images/openshift-enterprise-builder.yml, images/ose-cluster-openshift-controller-manager-operator.yml, images/ose-cluster-samples-operator.yml, images/ose-openshift-controller-manager.yml
=> [release-4.7] Update owners for build-api images

images/ptp-operator-must-gather.yml
Test build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=31831691
=> [ART-1941] Add ptp-operator-must-gather.yml

images/ose-baremetal-operator.yml
Depends on https://github.com/openshift/baremetal-operator/pull/108
=> baremetal-operator: use OCP-specific Dockerfile

group.yml, images/openshift-golang-builder.Dockerfile, images/openshift-golang-builder.yml, streams.yml
=> [rhel-8-golang-1.15] Use RHEL 8.2 EUS yum repos and images

images/openshift-golang-builder.Dockerfile, images/openshift-golang-builder.yml, streams.yml
=> [rhel-8-golang-1.12] Use RHEL 8.2 EUS images

group.yml, streams.yml
=> [openshift-4.5] Use RHEL 8.2 EUS yum repos and images

group.yml, streams.yml
=> [openshift-4.6] Use RHEL 8.2 EUS yum repos and images

group.yml, streams.yml
=> [openshift-4.2] Use RHEL 8.2 EUS yum repos and images

bugzilla.yml
As requested [here](https://coreos.slack.com/archives/CB95J6R4N/p1605718195376900)
=> Exclude windows bugzilla component

images/openshift-enterprise-console.yml, modifications/update-console-sources, streams.yml
Blocked by https://github.com/openshift/aos-cd-jobs/pull/2431
/hold﻿
=> [ART-2456] Move console to nodejs-14

group.yml, images/openshift-enterprise-base.yml, images/ose-haproxy-router-base.yml
part of: https://issues.redhat.com/browse/ART-2292
https://github.com/openshift/ocp-build-data-validator/pull/23
=> remove non_release move to for_release

images/ose-hello-openshift.yml
Set the BZ owning component for hello-openshift
=> hello-openshift: Add BZ component

images/aos3-installation.yml
And fix this error:
```
KeyError: 'rhel-server-optional-rpms-embargoed'
2021-01-06 20:47:13,681 ERROR [containers/aos3-installation] 'rhel-server-optional-rpms-embargoed'
```
=> 3.11: Fix non-existing repo

group.yml
=> ART-2589: Adapt to Pulp hostname change - 3.11

group.yml
=> ART-2589: Adapt to Pulp hostname change - 4.8

group.yml
=> ART-2589: Adapt to Pulp hostname change - 4.7

images/golang-github-openshift-oauth-proxy.yml
=> Remove reference to removed elasticsearch-operator

images/openshift-enterprise-builder.yml
/assign @jupierce 
@adambkaplan fyi
=> enable install of runc for openshift/builder

bugzilla.yml
https://coreos.slack.com/archives/CJARLA942/p1611644767069600
=> Don't sweep bugs for OpenShift Update Service

images/jenkins-agent-maven-36-rhel7.yml
Per https://issues.redhat.com/browse/ART-2646
Trying it out with https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fcustom/1812/console
=> [ART-2646] Add Jenkins Agent Maven36 to ocp3.11

group.yml
/me grumbles about getting everything in master
:)
=> Update ci-deps to use new pulp location

images/ib-sriov-cni.yml, images/local-storage-diskmaker.yml, images/local-storage-operator.yml, images/local-storage-static-provisioner.yml, images/openshift-kubernetes-nmstate-handler.yml, images/openshift-kubernetes-nmstate-operator.yml, images/sriov-cni.yml, images/sriov-dp-admission-controller.yml, images/sriov-network-config-daemon.yml, images/sriov-network-device-plugin.yml, images/sriov-network-must-gather.yml, images/sriov-network-operator.yml, images/sriov-network-webhook.yml
- Re-enable local-storage-operator after https://github.com/openshift/local-storage-operator/pull/203
- Re-enable openshift-kubernetes-nmstate-operator after https://github.com/openshift/kubernetes-nmstate/pull/186
- Re-enable sriov-network-operator after https://github.com/openshift/sriov-network-operator/pull/477
Please double-check everything is in place first though.
=> Re-enable some operators in 4.8

images/ose-cloud-network-config-controller.yml
https://issues.redhat.com/browse/ART-2701
test build - https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1523411
Note for reviewer: do verify from the story that the image belongs in the payload. The slack approval discussion mentions it being part of CNO instead of CVO.
=> ART-2701 Onboard image: Cloud network config controller 

images/vertical-pod-autoscaler-operator.yml, images/vertical-pod-autoscaler.yml
Don't merge until openshift/vertical-pod-autoscaler-operator#56 merges
=> Re-enable VPA operator for 4.8

group.yml, images/openshift-golang-builder.Dockerfile, images/openshift-golang-builder.yml, streams.yml
=> RHEL 8 Golang 1.16

group.yml, images/openshift-golang-builder.Dockerfile, images/openshift-golang-builder.yml, rpms/golang-scl-shim.yml
=> Golang 1.16

group.yml, images/driver-toolkit.yml
Really not sure if that is the way to go ... opening the PR to start a conversation about possible solutions.
=> [ART-2744] Add 'rt' repos for driver-toolkit

images/atomic-openshift-cluster-autoscaler.yml, images/atomic-openshift-descheduler.yml, images/atomic-openshift-node-problem-detector.yml, images/cluster-node-tuning-operator.yml, images/golang-github-openshift-oauth-proxy.yml, images/golang-github-prometheus-alertmanager.yml, images/golang-github-prometheus-node_exporter.yml, images/golang-github-prometheus-prometheus.yml, images/hadoop.yml, images/hive.yml, images/ironic-hardware-inventory-recorder-image.yml, images/ironic-inspector.yml, images/ironic-ipa-downloader.yml, images/ironic-rhcos-downloader.yml, images/ironic-static-ip-manager.yml, images/ironic.yml, images/kuryr-cni.yml, images/kuryr-controller.yml, images/openshift-base-nodejs.yml, images/openshift-base-rhel8.yml, images/openshift-enterprise-base.yml, images/openshift-enterprise-builder.yml, images/openshift-enterprise-console.yml, images/ose-cluster-samples-operator.yml, images/ose-metering-helm.yml, images/ose-multus-route-override-cni.yml, images/ose-multus-whereabouts-ipam-cni.yml, images/presto.yml, images/prom-label-proxy.yml, streams.yml
https://issues.redhat.com/browse/ART-2340
=> [ART-2340] [4.8] inline streams as members

group.yml
Automation freeze done for 4.7.5.
=> Freeze automation: 4.7.5

images/ose-vmware-vsphere-csi-driver.yml
=> Drop rhel8 suffix for vmware csi driver image

images/openshift-base-nodejs.yml, images/openshift-base-rhel8.yml, streams.yml
per [slack convo](https://coreos.slack.com/archives/CHY2E1BL4/p1617703305086100?thread_ts=1617699599.084600&cid=CHY2E1BL4)
=> move base image bases to streams

base-images/ansible-runner/Dockerfile, images/openshift-enterprise-apb-base.yml
..and inline the image definition, emulating the approach in https://github.com/openshift/ocp-build-data/commit/fd33bef0935dd0bff6dc06154d9688832d6a912d
=> wip [art-1887]: Fix ansible-runner

images/atomic-openshift-cluster-autoscaler.yml, images/atomic-openshift-descheduler.yml, images/atomic-openshift-node-problem-detector.yml, images/cluster-node-tuning-operator.yml, images/golang-github-openshift-oauth-proxy.yml, images/golang-github-prometheus-alertmanager.yml, images/golang-github-prometheus-node_exporter.yml, images/golang-github-prometheus-prometheus.yml, images/hadoop.yml, images/hive.yml, images/ironic-hardware-inventory-recorder-image.yml, images/ironic-inspector.yml, images/ironic-ipa-downloader.yml, images/ironic-rhcos-downloader.yml, images/ironic-static-ip-manager.yml, images/ironic.yml, images/kuryr-cni.yml, images/kuryr-controller.yml, images/openshift-base-nodejs.yml, images/openshift-base-rhel8.yml, images/openshift-enterprise-base.yml, images/openshift-enterprise-builder.yml, images/openshift-enterprise-console.yml, images/ose-cluster-samples-operator.yml, images/ose-metering-helm.yml, images/ose-multus-route-override-cni.yml, images/ose-multus-whereabouts-ipam-cni.yml, images/presto.yml, images/prom-label-proxy.yml, streams.yml
https://issues.redhat.com/browse/ART-2340
Should wait on https://github.com/openshift/ocp-build-data-validator/pull/29 and a doozer update.
=> [ART-2340] [4.7] inline streams as members 

images/vmware-vsphere-syncer.yml
This created problems elsewhere.
=> Drop rhel8 suffix

images/ose-leader-elector.yml
Reverts openshift/ocp-build-data#887
=> Revert "[ART-2759] remove leader-elector images"

images/cluster-nfd-operator.yml
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
=> fix manfest dir location for nfd

group.yml, images/egress-router-cni-alt.yml, images/multus-cni-alt.yml, images/openshift-enterprise-cli-alt.yml, images/ose-cli-artifacts-alt.yml, images/ose-containernetworking-plugins-alt.yml, images/ose-multus-route-override-cni-alt.yml, images/ose-multus-whereabouts-ipam-cni-alt.yml
[lmeyer] Do not merge until doozer changes are in place to support it. Then, remember to cherry-pick to 4.9.
=> [ART-2822] Split rhel-7-built images

images/kube-rbac-proxy.yml
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
=> Add NFD to dependents of kube-rbac-proxy

group.yml, streams.yml
once RHEL 8.4 is GA, stop referring to beta repos and go back to mainline.
/hold
=> revert 8.4 beta

group.yml, rpms/openshift-ansible.yml, rpms/openshift-clients.yml, rpms/openshift.yml
cherry-pick https://github.com/openshift/ocp-build-data/pull/928
=> 4.9: Define Brew targets for hotfix builds

images/ose-cluster-kube-descheduler-operator.yml
Depends on <https://github.com/openshift/cluster-kube-descheduler-operator/pull/200>
=> [ART-2868] Enable ose-cluster-kube-descheduler-operator builds

erratatool.yml, group.yml
See Elliott change: https://github.com/openshift/elliott/pull/191
=> ART-2718: When switching to RHSA set the appropriate Impact in the topic

images/ose-installer-artifacts.yml
This is necessary after openshift/installer#4891
=> installer-artifacts: add second builder stage

streams.yml
Request from @hexfusion : https://github.com/openshift/etcd/issues/85
=> Migrate etcd to 1.15 for OCP 4.9

images/vertical-pod-autoscaler-operator.yml
Depends on <https://github.com/openshift/vertical-pod-autoscaler-operator/pull/96>
=> [ART-2868] Enable vertical-pod-autoscaler-operator builds

images/cluster-nfd-operator.yml
Depends on <https://github.com/openshift/cluster-nfd-operator/pull/179>
=> [ART-2868] Enable cluster-nfd-operator builds

releases.yml
=> Update test assembly

images/ib-sriov-cni.yml, images/sriov-cni.yml, images/sriov-dp-admission-controller.yml, images/sriov-network-config-daemon.yml, images/sriov-network-device-plugin.yml, images/sriov-network-must-gather.yml, images/sriov-network-operator.yml, images/sriov-network-webhook.yml
Depends on <https://github.com/openshift/sriov-network-operator/pull/517>
=> [ART-2868] Enable sriov-network-operator builds

images/openshift-base-nodejs.yml
See discussion at https://github.com/openshift/doozer/pull/428.
=> ART-3034: add final_stage_user for images building as non-root

images/openshift-golang-builder.Dockerfile, streams.yml
https://issues.redhat.com/browse/ART-3098
context: https://coreos.slack.com/archives/CB95J6R4N/p1625257053178300
=> ART-3098 Update rhel-8-golang-1.15 base image

erratatool.yml
Elliott uses this mapping to attach builds to Errata.
=> Add Errata product version mapping for -hotfix tags

images/local-storage-operator.yml
Signed off by: Priyanka Jiandani <pjiandan@redhat.com>
=> Changed manifests directory as per latest operator-sdk version

images/kube-rbac-proxy.yml, images/linuxptp-daemon.yml, images/ptp-operator.yml
Depends on <https://github.com/openshift/ptp-operator/pull/115>
=> [ART-2868] Enable ptp-operator builds

images/ose-aws-machine-controllers.yml, images/ose-azure-cloud-controller-manager.yml, images/ose-azure-cloud-node-manager.yml, images/ose-openstack-cloud-controller-manager.yml
To ensure that automated alignment PRs use the correct commit format, add the commit prefix to the CCM forked repos added earlier today in #988 
CC @joepvd @Fedosin
=> Ensure forked CCM repos have correct commit prefixes

images/local-storage-diskmaker.yml, images/local-storage-operator.yml, images/local-storage-static-provisioner.yml
Depends on <https://github.com/openshift/local-storage-operator/pull/246>
=> [ART-2868] Enable local-storage-operator builds

releases.yml
The schema is generated by https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/hack/job/yuxzhu/job/aos-cd-jobs/job/build%252Fgen-assembly/4/console.
=> Add release 4.7.21

images/clusterresourceoverride-operator.yml, images/clusterresourceoverride.yml
Depends on <https://github.com/openshift/cluster-resource-override-admission-operator/pull/64>
=> [ART-2868] Enable clusterresourceoverride-operator builds

releases.yml
https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/hack/job/yuxzhu/job/aos-cd-jobs/job/build%252Fgen-assembly/5/console
=> update releases.yaml with 4.7.21

images/openshift-kubernetes-nmstate-handler.yml, images/openshift-kubernetes-nmstate-operator.yml
Depends on <https://github.com/openshift/kubernetes-nmstate/pull/196>
=> [ART-2868] Enable openshift-kubernetes-nmstate-operator builds

releases.yml
https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fgen-assembly/4/console
=> Update 4.7.22 nightlies

erratatool.yml
See initial comment on #1022 for more information.
=> Removes BZ section from 4.7 template

erratatool.yml
See initial comment on #1022 for more information.
=> Removes BZ section from 4.6 template

images/ose-cli-artifacts.yml
This is related to [ART-3150](https://issues.redhat.com/browse/ART-3150) (#999) for the installers﻿.
=> Add Dockerfile modification to fix ARM pthread issue for cli-artifacts

releases.yml
Because of blocker bug found in cri-o
=> Update 4.8.10 release with latest RHCOS

releases.yml
Because of blocker bug found in cri-o
=> Update 4.7.29 release with latest RHCOS

group.yml
for use with https://github.com/openshift/doozer/pull/510
=> [ART-3318] point to alternate rhcos

erratatool.yml
Needed for https://github.com/openshift/elliott/pull/231
=> ART-2720 Boilerplate update

group.yml
See #1106 and [ART-2720](https://issues.redhat.com/browse/ART-2720)
=> Set vars.CVES

group.yml
This is related to https://github.com/openshift/ocp-build-data/commit/6c980b2767d97e141e95663b9c0da0064647f684 and https://github.com/openshift/ocp-build-data/commit/8c5dfeb41e0f7b21016425e53e53470683c8f6a8
=> [openshift-4.6] Fix RT TUS content set

images/atomic-openshift-descheduler.yml, images/ose-cluster-kube-descheduler-operator.yml
https://github.com/openshift/cluster-kube-descheduler-operator/issues/225
=> Enable cluster-kube-descheduler-operator

images/ose-metallb-operator.yml, images/ose-metallb.yml
This is to be merged to go with the change 
https://github.com/openshift/doozer/pull/532
=> ART 3437 Add custom bundle tag names for metallb

images/openshift-kubernetes-nmstate-handler.yml, images/openshift-kubernetes-nmstate-operator.yml
Reverts openshift/ocp-build-data#1159
=> Revert "Explicitly define name_in_bundle for nmstate-handler and its operator"

images/ose-network-interface-bond-cni.yml
cluster-network-operator requires it as of https://github.com/openshift/cluster-network-operator/pull/1205
=> Add network-interface-bond-cni to payload

releases.yml
4.8.21 rpm advisory detect 3 rpms changes, need to swap them out
=> pin cri-o and coreos-installer

streams.yml
TIL from thread https://coreos.slack.com/archives/CB95J6R4N/p1635355092075100
=> Add comment about registry for golang image

releases.yml
=> Respin 4.6.50 as 4.6.51

images/driver-toolkit.yml
This reverts commit 13e6d17076e3825f52b30aeefa0cb52bc4a4c72a.
=> Revert "driver-toolkit: pin kernel for 4.6"

images/openshift-kubernetes-nmstate-handler.yml, images/openshift-kubernetes-nmstate-operator.yml
I am no longer affiliated with this project.
Signed-off-by: Brad P. Crochet <brad@redhat.com>
=> Remove Brad Crochet from owners

images/ose-image-customization-controller.yml
Test run: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=41851524
=> ART-3540 Onboard image-customization-controller

ci_transforms/rhel-8/ci-build-root/Dockerfile
=> Bump etcd to 3.5.1 for CI release image

images/ose-cloud-network-config-controller.yml
This reverts commit 2d8a833c168ba47bd3b8ac7611e5f8c58f61fd92.
=> [ART-2701] Add ose-cloud-network-config-controller

images/ose-machine-api-provider-aws.yml
test build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=41929500
=> [ART-3524] Change ose-aws-machine-controllers -> ose-machine-api-provider-aws

images/ose-machine-api-provider-gcp.yml
test build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=41929501
=> [ART-3538] Change ose-gcp-machine-controllers -> ose-machine-api-provider-gcp

erratatool.yml
=> Remove . from update url

images/driver-toolkit.yml, images/special-resource-operator.yml
As discussed on Slack in #aos-art, we need to update the email about ART builds for these two components. Thanks!
=> Update email for special-resource-operator and driver-toolkit

group.yml
...until the pipeline is up and running
=> 4.11: Point 4.11 rhcos to 4.10 rhcos

group.yml, images/go-1.16-lib.patch, images/openshift-golang-builder.Dockerfile, images/openshift-golang-builder.yml
planning to revert last two commits so will merge as separate
=> [ART-3664] add a go build option with a patch

releases.yml
will allow me to create a release payload to test out for https://issues.redhat.com/browse/ART-3664
=> releases: define art3664 assembly for testing

images/sriov-network-must-gather.yml
mirroring https://github.com/openshift/sriov-network-operator/pull/621/files
=> sriov-network-must-gather: update base to cli

images/openshift-enterprise-hyperkube.yml
The dockerfile build flag changes were merged upstream.
=> [ART-3664] hyperkube: remove build flag modifications

group.yml
Reverts openshift/ocp-build-data#1322
=> Revert "Freeze 4.10 automation temporarily"

releases.yml
See https://coreos.slack.com/archives/CJARLA942/p1645021351319579?thread_ts=1645005654.641919&cid=CJARLA942
=> [4.8.32] Skip bug verification

releases.yml
[build/build-sync#22297](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/22297/console) successful
=> Add 4.10.0-rc.5 release definition

images/hypershift.yml
This was the initial request in https://issues.redhat.com/browse/ART-3509
=> Hypershift should be included in release payloads

images/operator-lifecycle-manager.yml, images/operator-registry.yml
Signed-off-by: perdasilva <perdasilva@redhat.com>
Adds the bugzilla component to OLM images
=> Add bugzilla component to OLM images

images/hypershift.yml
Reverts openshift/ocp-build-data#1363
=> Revert "Revert "Revert "[openshift-4.10] Hypershift should be included in release payloads"""

erratatool.yml
Should be cherry-picked across all branches.
=> Add newline before Security Fixes in RHSA text

images/hypershift.yml
Reverts openshift/ocp-build-data#1375
Merge after GA.
=> Revert "Revert "Revert "Revert "[openshift-4.10] Hypershift should be included in release payloads""""

images/ose-etcd.yml, images/ose-ovn-kubernetes.yml
Follow up to https://github.com/openshift/ocp-build-data/pull/1393
=> Fix yaml after go modules deletion

images/ose-aws-efs-utils.yml
=> Enable Cachito for aws-efs-utils

images/openshift-kubernetes-nmstate-handler.yml, images/openshift-kubernetes-nmstate-operator.yml
...as https://bugzilla.redhat.com/show_bug.cgi?id=2059107 moved to MODIFIED
=> Enable cachito for nmstate images

images/ose-aws-efs-csi-driver.yml
...as https://github.com/openshift/aws-efs-csi-driver/pull/18 merged.
=> 4.11: Reenable cachito for aws-efs-csi-driver

group.yml, images/driver-toolkit.yml, streams.yml
https://issues.redhat.com/browse/ART-3853
=> ART-3853 Rebase 4.11 on RHEL 8 (mainline)

images/ose-frr.yml, images/ose-metallb-operator.yml, images/ose-metallb.yml
https://github.com/openshift/metallb-operator/issues/72 is done so enable builds
=> Enable metallb operator

group.yml
Reverts openshift/ocp-build-data#1486
=> Revert "Freeze automation for 4.6 for now"

images/openshift-enterprise-ansible-operator.yml, images/openshift-enterprise-helm-operator.yml, images/openshift-enterprise-operator-sdk.yml
PR https://github.com/openshift/ocp-release-operator-sdk/pull/234 is merged.
=> Re-enable Cachito for ocp-release-operator-sdk

images/ose-gcp-cluster-api-controllers.yml
successful test build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=44228089
=> [ART-3890] Add ose-gcp-cluster-api-controllers

images/ose-vsphere-cluster-api-controllers.yml
successful test build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=44228085
=> [ART-3891] Add ose-vsphere-cluster-api-controllers

images/openshift-enterprise-ansible-operator.yml, images/openshift-enterprise-helm-operator.yml, images/openshift-enterprise-operator-sdk.yml
https://bugzilla.redhat.com/show_bug.cgi?id=2064204 got merged
=> Bug 2064204: Enable cachito for operator-sdk images

images/vertical-pod-autoscaler-operator.yml, images/vertical-pod-autoscaler.yml
Reverts openshift/ocp-build-data#1502
=> Revert "Enable vertical-pod-autoscaler-operator"

ci_transforms/rhel-7/ci-build-root/Dockerfile, ci_transforms/rhel-8/ci-build-root/Dockerfile
https://go.dev/doc/go-get-install-deprecation
=> Adjust for deprecation of go get behavior

releases.yml
This reverts commit d58027d10aa6dbc5b1afd5118184af56837269a5.
=> Revert "Add release 4.8.40"

images/ose-image-customization-controller.yml
test build with new name: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=44869438
=> [ART-3987] Rename {,machine-}image-customization-controller

releases.yml
This reverts commit 5243a9da18278588f1b5dad0745ff9f5704db0f4.
=> Bug 2081062: Revert "Revert "Pin rhcos for amd64 until BZ2077052 is fixed""

images/multus-cni.yml, images/multus-networkpolicy.yml, images/ose-containernetworking-plugins.yml, images/ose-multus-admission-controller.yml, images/ose-multus-route-override-cni.yml, images/ose-multus-whereabouts-ipam-cni.yml
> For the low, low price of a single PR
...Going to take up ART on this offer!
=> Adds auto_label for OpenShift Network Plumbing Team components

releases.yml
[build-sync](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/view/Build%204.x/job/aos-cd-builds/job/build%252Fbuild-sync/24083/)
=> Prepare 4.9.32

releases.yml
[build-sync](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/view/Build%204.x/job/aos-cd-builds/job/build%252Fbuild-sync/24084/console)
=> Prepare 4.10.13

releases.yml
dpu-network-operator, ose-metallb-operator, and local-storage-operator
=> 4.10.13: Pin kube-rbac-proxy and related images

images/ose-powervs-cloud-controller-manager.yml
https://github.com/openshift/cloud-provider-powervs/pull/8 dropped a stage from this image.
Closes: https://github.com/openshift/cloud-provider-powervs/pull/9
/cc @Karthik-K-N
=> Sync stages for ose-powervs-cloud-controller-manager

images/vertical-pod-autoscaler-operator.yml
Tested with a custom build, the image was successfully built in Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45090979
=> [ART-4049] Enable vertical-pod-autoscaler-operator

images/ose-aws-efs-csi-driver-operator.yml
Related commits:
https://github.com/openshift/aws-efs-csi-driver-operator/commit/e8b155c629369d20033cc452f2c12362977446a5
https://github.com/openshift/aws-efs-csi-driver-operator/commit/60946a1cbdd224b15509c0983d9d89b3acd9e3e6
/cc @thiagoalessio
=> Reflect manifest dir changes made in EFS

images/ose-image-customization-controller.yml
This reverts commit a6a77e5a5bbfb55b45f40e4456c89c0be0fc45d7.
=> [ART-3987] Rename {,machine-}image-customization-controller (#1540)

releases.yml
ON_QA bug 2083786 is a backport of ON_QA bug 2083785
ON_QA bug 2085180 is a backport of ON_QA bug 2084234
=> permit ON_QA bug 2085180 and 2083786

images/openshift-kubernetes-nmstate-handler.yml
Context [CLOUDBLD-9945](https://issues.redhat.com//browse/CLOUDBLD-9945) https://coreos.slack.com/archives/CB95J6R4N/p1651209423722459
=> Temporarily add ose repo for nmstate-handler

group.yml
Reverts openshift/ocp-build-data#1647
=> Revert "Freeze 4.7 automation in anticipation of 8.4 rhel update"

group.yml
Reverts openshift/ocp-build-data#1646
=> Revert "Freeze 4.8 automation in anticipation of 8.4 rhel update"

group.yml, images/driver-toolkit.yml
RHCOS moved to rhel-8.6, dtk should follow suit.
Obsoletes #1579
=> 4.11: Get dtk to rhel-8.6

releases.yml
successful build-sync https://saml.buildvm.openshift.eng.bos.redhat.com:8888/view/Build%204.x/job/aos-cd-builds/job/build%252Fbuild-sync/24968/console
=> 4.8.44 assembly

releases.yml
Successful [build-sync](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/view/Build%204.x/job/aos-cd-builds/job/build%252Fbuild-sync/25069/console)
=> Prepare 4.8.45

images/ose-agent-installer-csr-approver.yml
=> Add bugzilla component info to support product security

images/openshift-enterprise-console.yml
This reverts commit a7dadd7e2cf29f2061373aaacc9b41347b011cb4.
=> Revert "Revert "ose-console: download build deps from ocp-artifacts""

images/bare-metal-event-relay.yml, images/baremetal-hardware-event-proxy.yml
operator: [bare-metal-event-relay-operator-container-v4.10.0-202206240815.p0.g760b9d8.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2063201)
bundle: [bare-metal-event-relay-operator-bundle-container-v4.10.0.202206240815.p0.g760b9d8.assembly.test-1](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2063204)
=> [ART-4075] add bare-metal-event-relay

images/cluster-nfd-operator.yml, images/clusterresourceoverride-operator.yml, images/dpu-network-operator.yml, images/local-storage-operator.yml, images/openshift-kubernetes-nmstate-operator.yml, images/ose-aws-efs-csi-driver-operator.yml, images/ose-cluster-kube-descheduler-operator.yml, images/ose-metallb-operator.yml, images/ptp-operator.yml, images/special-resource-operator.yml, images/sriov-network-operator.yml, images/vertical-pod-autoscaler-operator.yml
@gallettilance some label values are missing on the doc.
=> [ART-4070] Add `valid-subscription-label` values to OLM operators

images/cluster-nfd-operator.yml, images/clusterresourceoverride-operator.yml, images/local-storage-operator.yml, images/openshift-kubernetes-nmstate-operator.yml, images/ose-cluster-kube-descheduler-operator.yml, images/ptp-operator.yml, images/sriov-network-operator.yml, images/vertical-pod-autoscaler-operator.yml
This is a cherry-pick of https://github.com/openshift/ocp-build-data/pull/1635
=> [openshift-4.7] [ART-4070] Add `valid-subscription-label` values to OLM operators

images/cluster-nfd-operator.yml, images/clusterresourceoverride-operator.yml, images/local-storage-operator.yml, images/openshift-kubernetes-nmstate-operator.yml, images/ose-aws-efs-csi-driver-operator.yml, images/ose-cluster-kube-descheduler-operator.yml, images/ose-metallb-operator.yml, images/ptp-operator.yml, images/special-resource-operator.yml, images/sriov-network-operator.yml, images/vertical-pod-autoscaler-operator.yml
This is a cherry-pick of https://github.com/openshift/ocp-build-data/pull/1635
=> [openshift-4.9] [ART-4070] Add `valid-subscription-label` values to OLM operators

group.yml
ref https://coreos.slack.com/archives/C02TN2SJR0F/p1656327696527359
=> group.yml: allow compiler sheer until we get it fixed

images/baremetal-hardware-event-proxy.yml, images/kube-rbac-proxy.yml, images/topology-aware-lifecycle-manager.yml, images/topology-aware-lifecycle-operator-precache.yml
precache image: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46209519
operator: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46209520
bundle:  https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2067934
baremetal-hardware-event-proxy https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46231398
bare-metal-event-relay-operator https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46231398
bare-metal-event-relay-operator-bundle https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=46231480
job: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fcustom/2590/
=> [ART-4052] add topology-aware-lifecycle-manager

images/clusterresourceoverride.yml, images/openshift-kubernetes-nmstate-handler.yml
Distgit branches have been added, enable
openshift-kubernetes-nmstate-handler and clusterresourceoverride.
=> Enable 2 images

images/openshift-kubernetes-nmstate-handler.yml
Reverts openshift/ocp-build-data#1633
=> Bug 2078573: Revert "Temporarily add ose repo for nmstate-handler"

images/ose-cluster-baremetal-operator.yml
Reverts openshift/ocp-build-data#1724
Reinstate CBO
=> Revert "Disable baremetal-operator temporarily"

releases.yml
Build-sync: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/25581/console
=> Prepare 4.11-rc.2

group.yml
Reverts openshift/ocp-build-data#1786
=> Revert "Freeze automation to eliminate moving parts"

releases.yml
build-sync https://saml.buildvm.openshift.eng.bos.redhat.com:8888/view/Build%204.x/job/aos-cd-builds/job/build%252Fbuild-sync/25943/
=> 4.11 rc.6 assembly definition

images/ose-powervs-block-csi-driver-operator.yml, images/ose-powervs-block-csi-driver.yml
test build job https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fcustom/2640/
=> [ART-4204][ART-4157] Add OCP component powervs-block-csi-driver

bug.yml
This is needed for running functional-tests
for elliott
=> Add bug.yml for 4.5

releases.yml
https://issues.redhat.com/browse/FDN-83
=> ec.0 assembly definition

releases.yml
Containers are building and we have the fix for ironic-agent in
place https://github.com/openshift/ironic-agent-image/pull/59
=> Remove pin from ironic images

releases.yml
build-sync: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/26356/
=> Prepare 4.9.46

images/ose-kubevirt-cloud-controller-manager.yml
test build https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2120449
=> [ART-4353] add ose-kubevirt-cloud-controller-manager

images/ingress-node-firewall.yml
test build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=47034613
=> [ART-4316] Add ingress-node-firewall

releases.yml
build-sync https://saml.buildvm.openshift.eng.bos.redhat.com:8888/view/Build%204.x/job/aos-cd-builds/job/build%252Fbuild-sync/
=> 4.7.57 assembly

group.yml
Reverts openshift/ocp-build-data#1880
=> Revert "Freeze 4.11 for now"

images/ose-cluster-control-plane-machine-set-operator.yml
Ref. https://issues.redhat.com/browse/ART-4357
=> [ART-4357] Add cluster control plane machine set operator in 4.12

images/ose-kubevirt-csi-driver-rhel8.yml
test build https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=47407977
=> ART-2846 add ose-kubevirt-csi-driver-rhel8

images/ovn-kubernetes-base.yml, images/ovn-kubernetes-singlenode.yml
Ref:
https://issues.redhat.com/browse/ART-4508
https://issues.redhat.com/browse/ART-4509
=> Add ovn-kubernetes-base and ovn-kubernetes-singlenode to 4.12

images/ose-olm-rukpak.yml
Ref. https://issues.redhat.com/browse/ART-4525
Test build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2144998
=> [4.12] Add the OLM openshift/operator-framework-rukpak component

images/ose-cluster-platform-operators-manager.yml
Ref. https://issues.redhat.com/browse/ART-4526
Test build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2145021
=> [4.12] Add ose-cluster-platform-operators-manager

group.yml
Reverts openshift/ocp-build-data#1913
=> Revert "Freeze 4.11 to ensure one bug gets included in next build"

releases.yml
manual verification looking good
=> add permit for 4.9.48

images/ovn-kubernetes-base.yml, images/ovn-kubernetes-microshift.yml
Ref. https://issues.redhat.com/browse/ART-4557
Test build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2148758
=> Rename image ovn-kubernetes-singlenode to ovn-kubernetes-microshift

erratatool.yml
https://issues.redhat.com/browse/ART-4723
=> ART-4723 Use silent release type for 4.7 advisory creation

images/openshift-kubernetes-nmstate-handler.yml, images/openshift-kubernetes-nmstate-operator.yml
bundle build https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=47586664
operator build https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=47585665
=> enable openshift-kubernetes-nmstate-operator

releases.yml
Ref. https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fgen-assembly/331/console
=> Prepare release 4.11.4

group.yml
https://issues.redhat.com/browse/ART-4750 - adding another RHCOS container to the mix
Said containers are being created, I'm testing that nothing breaks with build-sync before getting this merged.
=> [ART-4750] group.yml: include rhel-coreos-8-extensions

images/ingress-node-firewall-daemon.yml, images/ingress-node-firewall.yml, images/kube-rbac-proxy.yml
Ref. [ART-4724](https://issues.redhat.com/browse/ART-4724)
Brew builds:
- https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2164129
- https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2152733
- https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2164008
=> Add ingress node daemon and bundle

images/ingress-node-firewall.yml
https://comet.engineering.redhat.com/containers/repositories/62fa405130a80ba5a208c1c9
=> subscription type is OCP and up

streams.yml
/hold
until friday for minimal disruption. unless we get another mass-rebuild anyway, then pile on.
=> [ART-4127] rhel8 stream -> rhel-els-container-8.6-921

images/ose-kubevirt-csi-driver-rhel8.yml
as per https://coreos.slack.com/archives/CB95J6R4N/p1663264886101049?thread_ts=1663257720.012149&cid=CB95J6R4N and https://issues.redhat.com/browse/ART-2846?focusedCommentId=20958499&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20958499
=> add image to payload

releases.yml
build-sync job: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/27242/
=> add 4.10.34

releases.yml
build-sync job: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/27246/console
=> add 4.11.6

releases.yml
build-sync https://saml.buildvm.openshift.eng.bos.redhat.com:8888/view/Build%204.x/job/aos-cd-builds/job/build%252Fbuild-sync/27258/console
=> 4.9.49 assembly

group.yml, images/openshift-enterprise-helm-operator.yml, images/openshift-enterprise-hyperkube.yml, images/openshift-enterprise-tests.yml, images/ose-baremetal-installer.yml, images/ose-cli-artifacts.yml, images/ose-installer-artifacts.yml, images/ose-installer.yml
Requires https://github.com/openshift/doozer/pull/645/files
=> ART-4807: Enable OSBS 2

images/ironic-agent.yml, images/ironic-rhcos-downloader.yml, images/ironic-static-ip-manager.yml, images/ironic.yml
Reverts openshift/ocp-build-data#1982
=> Revert "[ART-4558] move ironic images to rhel9 branch"

images/csi-livenessprobe.yml, images/csi-node-driver-registrar.yml, images/csi-provisioner.yml, images/kube-rbac-proxy.yml, images/ose-csi-external-resizer.yml, images/ose-csi-external-snapshotter.yml, images/ose-gcp-filestore-csi-driver-operator.yml, images/ose-gcp-filestore-csi-driver.yml
Ref. https://issues.redhat.com/browse/ART-4803
Ref. https://issues.redhat.com/browse/ART-4805
=> [ART-4805] Add gcp-filestore-csi-driver and gcp-filestore-csi-driver-operator

images/ironic-agent.yml, images/ironic-rhcos-downloader.yml, images/ironic-static-ip-manager.yml, images/ironic.yml
Reverts openshift/ocp-build-data#1985
/hold until https://issues.redhat.com/browse/CLOUDBLD-11118 is processed.
=> Revert "Revert "[ART-4558] move ironic images to rhel9 branch""

images/ovn-kubernetes-microshift.yml
match ose-ovn-kubernetes img and fix http://download.eng.bos.redhat.com/brewroot/work/tasks/7040/47897040/x86_64.log
=> ovn-kubernetes-microshift: add OSE repo for openvswitch2.17 dep

images/ose-machine-os-images.yml
https://issues.redhat.com/browse/ART-4867
=> ART-4867: Build machine-os-images containers for ppc64le

images/ingress-node-firewall-daemon.yml, images/ingress-node-firewall-operator.yml, images/kube-rbac-proxy.yml
test build: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fcustom/2750/console
=> Rename ingress-node-firewall to ingress-node-firewall-operator

releases.yml
Build-sync: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/27485/console
=> Add 4.10.36

releases.yml
Build-sync: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/27486/console
=> Add 4.11.8

group.yml, images/openshift-enterprise-helm-operator.yml, images/openshift-enterprise-tests.yml, images/ose-baremetal-installer.yml, images/ose-cli-artifacts.yml, images/ose-installer-artifacts.yml, images/ose-installer.yml
...and remove the workaround to limit number of threads while go compiling
=> Move 4.9 to osbs2

rpms/microshift.yml
Reverts openshift/ocp-build-data#2025
=> Revert "<temp> replace microshift release name template with actual release"

group.yml, images/openshift-enterprise-helm-operator.yml, images/openshift-enterprise-hyperkube.yml, images/openshift-enterprise-tests.yml, images/ose-baremetal-installer.yml, images/ose-cli-artifacts.yml, images/ose-installer-artifacts.yml, images/ose-installer.yml
and remove obsolete workaround
=> [4.11] move to osbs2

group.yml
...and remove the workaround to limit number of threads while go compiling
=> Move 4.8 to osbs2

group.yml
...and remove the workaround to limit number of threads while go compiling
=> Move 4.7 to osbs2

group.yml
...and remove the workaround to limit number of threads while go compiling
=> Move 4.6 to osbs2

group.yml
Reverts openshift/ocp-build-data#2035
=> Unfreeze 4.10

group.yml
Reverts openshift/ocp-build-data#2036
=> unfreeze 4.9

group.yml
Reverts openshift/ocp-build-data#2038
=> unfreeze 4.7

group.yml
Reverts openshift/ocp-build-data#2039
=> unfreeze 4.6

images/vertical-pod-autoscaler-operator.yml, images/vertical-pod-autoscaler.yml
I did a test rebase and that much seemed fine at least.
=> re-enable vertical-pod-autoscaler

group.yml, images/openshift-enterprise-helm-operator.yml, images/openshift-enterprise-hyperkube.yml, images/openshift-enterprise-tests.yml, images/ose-baremetal-installer.yml, images/ose-cli-artifacts.yml, images/ose-installer-artifacts.yml, images/ose-installer.yml
osbs1 seems to be in less outage than osbs2. Let's clog those pipes.
=> [openshift-4.12] Move temporarily to osbs1

group.yml, images/openshift-enterprise-helm-operator.yml, images/openshift-enterprise-hyperkube.yml, images/openshift-enterprise-tests.yml, images/ose-baremetal-installer.yml, images/ose-cli-artifacts.yml, images/ose-installer-artifacts.yml, images/ose-installer.yml
Reverts openshift/ocp-build-data#2056
=> Revert "[openshift-4.12] Move temporarily to osbs1"

modifications/microshift-rebase
The script was moved in upstream repo.
=> microshift: change scripts/rebase.sh to scripts/auto-merge/rebase.sh

releases.yml
Request from https://coreos.slack.com/archives/CB95J6R4N/p1665671837089669
=> Pin latest microshift rpm build in ec.4

group.yml, images/openshift-golang-builder.Dockerfile, images/openshift-golang-builder.yml, streams.yml
Ref. https://issues.redhat.com/browse/ART-4564
Test build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2207779
=> Add golang-1.19-el9

images/ose-ibmcloud-cluster-api-controllers.yml
Ref. https://issues.redhat.com/browse/ART-4976
=> [ART-4976] Add ibmcloud-cluster-api-controllers

releases.yml
:white_check_mark:[build-sync job](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/27727/)
=> prepare 4.11.10

releases.yml
according to 
https://coreos.slack.com/archives/G01HDTRUU3T/p1666169618121949?thread_ts=1666169284.340439&cid=G01HDTRUU3T
=> fix manifest references mismatch

images/ose-nutanix-cloud-controller-manager.yml
Ref. https://issues.redhat.com/browse/ART-4804
Test build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2200932
=> [ART-4804] Add cloud-provider-nutanix

group.yml
Reverts openshift/ocp-build-data#2092
=> Revert "Switch canonical builders from upstream to on"

releases.yml
[it works this time](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/27932/console) :roll_eyes:
=> 4.11.12: fix openshift-clients spec

releases.yml
hopefully fix issues from https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fpromote-assembly/492/console
=> 4.11.12: handle some bug oddities

erratatool.yml
@thiagoalessio here are the changes for the RNs zstream update for 4.8. 
This can be cherry picked to 4.9.
@opayne1 can you PTAL for approval.
=> OSDOCS-4286:updates errata text for OCP zstream docs team

images/ose-ibmcloud-cluster-api-controllers.yml
Nightlies started failing on the same day this change was introduced, trying to debug and see if this change is responsible for the nightly failures.
=> (Temporarily) removing arch restriction

releases.yml
This reverts commit b75cc496d5f4246994111680b09ca8ee8bee4890.
=> Revert "Allow rhcos inconsistencies in favor of nightlies"

images/ose-ibmcloud-cluster-api-controllers.yml
This reverts commit eb8886190338b2b1595cadea8035e51ac4007f1e.
=> Revert "(Temporarily) removing arch restriction"

group.yml
https://issues.redhat.com/browse/ART-5141
=> [ART-5141] Update golang to 1.18.7

erratatool.yml
See:
https://issues.redhat.com/browse/CWFCONF-2619 
https://errata.devel.redhat.com/release/show/1768
=> [4.6] Switch to silent release advisory type

erratatool.yml
See:
https://issues.redhat.com/browse/CWFCONF-2619
https://errata.devel.redhat.com/release/show/1768
=> [4.7] Switch to silent release advisory type

images/openshift-enterprise-console.yml
backport of https://github.com/openshift/ocp-build-data/pull/2164
=> openshift-enterprise-console: access ocp-artifacts with https

images/openshift-enterprise-tests.yml
TRT would like to be aware of when origin stops building.
=> [openshift-4.12] Add TRT e-mail alias for origin alerts

images/openshift-enterprise-tests.yml
TRT would like to be aware of when origin stops building.
=> [openshift-4.13] Add TRT e-mail alias for origin alerts

group.yml
/hold
until we have another mass rebuild anyway (probably for RPM signing)
(but by no means past this weekend)
=> [4.12][ART-5151] pin repos to 8.6 EUS

group.yml
/hold
until releases are through - this will likely kick off a mass rebuild with no actual changes to content.
=> [4.11][ART-5151] pin repos to 8.6 EUS

images/ose-ibmcloud-cluster-api-controllers.yml
test-build passed: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=48828699
=> switch ibmcloud upstream to priv repo

erratatool.yml
Cherry-pick of https://github.com/openshift/ocp-build-data/pull/2116
=> (4.10) updates errata text for Images

erratatool.yml
Cherry-pick of https://github.com/openshift/ocp-build-data/pull/2116
=> (4.12) updates errata text for Images

images/ose-installer-artifacts.yml
This is needed after https://github.com/openshift/installer/pull/6514
=> Sync layers of ose-installer-artifacts

rpms/openshift-clients.yml
Reverts openshift/ocp-build-data#2200
=> Revert "Disable openshift-clients rhel9 targets"

erratatool.yml
Updates text in images advisory
=> RNs-4.9-errata:updates stock text in images advisory

group.yml
Reverts openshift/ocp-build-data#2212
=> Revert "[ART-5143] 4.13 - Update plashet repo URLs"

group.yml
Reverts openshift/ocp-build-data#2223
=> Revert "Revert "[ART-5143] 4.13 - Update plashet repo URLs""

releases.yml
Re: https://github.com/openshift/doozer/pull/684
=> [4.6] Put in default permits

releases.yml
Re: https://github.com/openshift/doozer/pull/684
=> [4.7] Put in default permits

images/cloud-event-proxy.yml, images/clusterresourceoverride-operator.yml, images/clusterresourceoverride.yml, images/csi-livenessprobe.yml, images/csi-node-driver-registrar.yml, images/csi-provisioner.yml, images/dpu-network-operator.yml, images/ib-sriov-cni.yml, images/ingress-node-firewall-daemon.yml, images/ingress-node-firewall-operator.yml, images/kube-rbac-proxy.yml, images/linuxptp-daemon.yml, images/local-storage-diskmaker.yml, images/local-storage-operator.yml, images/ose-aws-efs-csi-driver-operator.yml, images/ose-aws-efs-csi-driver.yml, images/ose-csi-external-resizer.yml, images/ose-csi-external-snapshotter.yml, images/ose-frr.yml, images/ose-gcp-filestore-csi-driver-operator.yml, images/ose-gcp-filestore-csi-driver.yml, images/ose-metallb-operator.yml, images/ose-metallb.yml, images/ptp-operator.yml, images/sriov-cni.yml, images/sriov-dp-admission-controller.yml, images/sriov-network-config-daemon.yml, images/sriov-network-device-plugin.yml, images/sriov-network-operator.yml, images/sriov-network-webhook.yml
Ref. https://issues.redhat.com/browse/ART-5087
Custom build: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fcustom/2825/consoleFull
=> Re-enable version agnostic operators for 4.13

releases.yml
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fgen-assembly/413/console FWIW
=> 4.10.42: update to later nightly

erratatool.yml
according to https://coreos.slack.com/archives/CJARLA942/p1668527946132939?thread_ts=1667981155.410839&cid=CJARLA942
the solution in the CVE type should be the same as the image type
=> update solution for cve type

releases.yml
Reverts openshift/ocp-build-data#2221
=> 4.11: Revert "Permit rhcos inconsistencies"

releases.yml
Reverts openshift/ocp-build-data#2228
=> 4.8: Revert "stream: Allow inconsistencies in rhcos"

releases.yml
Reverts openshift/ocp-build-data#2226
=> Revert "stream: Allow inconsistencies in rhcos"

images/vertical-pod-autoscaler-operator.yml
https://issues.redhat.com/browse/CLOUDBLD-12460 completed, 4.13 branch is now ready
=> Re-enable vertical-pod-autoscaler-operator

group.yml
Reverts openshift/ocp-build-data#2267
=> Revert "[3.11] Update plashet repo URLs"

ci_transforms/rhel-8/ci-build-root/Dockerfile
/assign @sosiouxme @jupierce 
/cc @sanchezl
=> Update etcd to 3.5.6 and protoc to 3.19.4 to match k8s 1.26

group.yml
Test if this is ready to merge
```
doozer --group openshift-4.12@art_5258 --data-path https://github.com/thegreyd/ocp-build-data inspect:stream INCONSISTENT_RHCOS_RPMS
```
and https://github.com/openshift/aos-cd-jobs/pull/3340 is merged in
=> [4.12] ART-5258 Enable multi rhcos builds

streams.yml
Ref. https://issues.redhat.com/browse/ART-5459
=> [ART-5459] Update golang builder

releases.yml
Follow up to https://github.com/openshift/doozer/pull/684
=> 4.11 - Put in default stream permits

group.yml
=> [ART-3683] group.yml: add rhcos<->payload consistency spec

images/driver-toolkit.yml, releases.yml
cherry-pick of 4.12 https://github.com/openshift/ocp-build-data/pull/2408
=> [4.11] driver-toolkit: make plashet repo official for kernel-rt

releases.yml
https://redhat-internal.slack.com/archives/GDBRP5YJH/p1673546289119639?thread_ts=1673539445.446649&cid=GDBRP5YJH
=> Skip blocker check for 4.12.0 promotion

releases.yml
[ref slack](https://redhat-internal.slack.com/archives/CJARLA942/p1673884022543839?thread_ts=1673538943.834739&cid=CJARLA942)
=> releases: create 4.11.24 based on .23

releases.yml
GCed nightlies led to [failure](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/29793/console)
=> releases: 4.11.24 nightlies n/a

releases.yml
This reverts commit 5c52f52b799a73e37bbd6609041353eca7c80def.
=> Revert "4.10.49 -> 4.10.48"

images/cloud-event-proxy.yml, images/ingress-node-firewall-daemon.yml, images/ingress-node-firewall-operator.yml, images/ose-gcp-filestore-csi-driver-operator.yml, images/ose-gcp-filestore-csi-driver.yml
ref: https://issues.redhat.com/browse/ART-5755
=> [ART-5755] fix image reference name

images/cloud-event-proxy.yml
see also https://issues.redhat.com/browse/CWFENGINE-1002 (may need to revisit in 4.13)
=> [ART-5755] cloud-event-proxy: correct repo

erratatool.yml
This PR removes text that was incorrect from stock 4.12 RNs text.
=> OSDOCS-4282-4.12RN:updates the 4.12 RNs stock text

erratatool.yml
Updates the stock errata text for docs RN team.
=> OSDOCS-4282-4.11RN:updates stock errata text for docs RN team

erratatool.yml
4.10 updates for the docs RN team to their stock errata text.
=> OSDOCS-4282-410:updates 4.10 RNs stock errata text

erratatool.yml
This is failing to parse as valid yaml
=> erratatool.yml - Fix indent

images/driver-toolkit.yml, releases.yml
also remove the kernel pins that are no longer needed as they've shipped or been tagged appropriately.
=> driver-toolkit: make plashet repo official for kernel-rt

releases.yml
ovn image use specific rpm nvr, need permit for stream
=> permit outdate rpm for ovn

group.yml
Ref. https://issues.redhat.com/browse/ART-5552
=> Run 4.9 automation only on weekends

group.yml
Ref. https://issues.redhat.com/browse/ART-5552
=> Run 4.8 automation only on weekends

releases.yml
new build pass cvp test http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/ose-aws-efs-csi-driver-operator-bundle-container-v4.10.0.202302010855.p0.gdb7e452.assembly.stream-1/198c53fb-03ca-41cc-9d37-6d85ef064a18/cvp-test-report.html
=> pin new build for ose-aws-efs-csi-driver-operator-container

releases.yml
Revert this after [CWFCONF-3374](https://issues.redhat.com//browse/CWFCONF-3374) is processed.
=> stream: pin kernel-rt

releases.yml
Reverts openshift/ocp-build-data#2517
=> Revert "stream: pin kernel-rt"

images/atomic-openshift-descheduler.yml, images/ose-cluster-kube-descheduler-operator.yml
as per: https://redhat-internal.slack.com/archives/CB95J6R4N/p1675408347105419
=> re-enable cluster-kube-descheduler-operator

images/ose-ovn-kubernetes.yml, images/ovn-kubernetes-base.yml
fix failed build https://download.eng.bos.redhat.com/brewroot/work/tasks/623/50560623/x86_64.log
=> enable repos for ovn

group.yml
https://issues.redhat.com/browse/ART-5984
=> ART-5984 Update 1.17 golang build for rhel8

erratatool.yml
PR is to add stock errata text for MicroShift advisories.
=> Add stock errata text for MicroShift

images/ose-sdn.yml
Follow upstream change https://github.com/openshift/sdn/pull/495
=> Fix ose-sdn rebase

images/openshift-enterprise-ansible-operator.yml, images/openshift-enterprise-helm-operator.yml, images/openshift-enterprise-operator-sdk.yml, images/operator-lifecycle-manager.yml
FYI, Evan and Jesus have left company.
=> update OLM image owner

group.yml
Reverts openshift/ocp-build-data#2556
=> Revert "Re-enable automation for 4.9"

rpms/microshift.yml
=> [ART-6101] Enable el9 builds of the microshift rpm

erratatool.yml
Small tweaks to MicroShift rpm synopsis to make sure the .z is added.
=> OSDOCS-5229:Microshift advisory .z in synopsis added

product.yml
=> Add security profiles operator components

erratatool.yml
updates 4.12 to 4.13
closed: #2538 
issue:
https://issues.redhat.com/browse/OSDOCS-5361
=> Microshift errata 4.13

erratatool.yml
updates 4.12 to 4.14 
issue:
https://issues.redhat.com/browse/OSDOCS-5362
Closed #2539 in favor of this.
=> Microshift errata 4.14

releases.yml
build-sync: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/31213/console
=> [4.13] Add ec.4 definition

ci_transforms/rhel-9/ci-build-root/Dockerfile, ci_transforms/rhel-9/ci-build-root/OWNERS, streams.yml
Config copied from `doozerlib/cli/ci_transforms/rhel-9`
=> Add ci-build-root ci-transform

images/nmstate-console-plugin.yml, streams.yml
Reverts openshift/ocp-build-data#2628
Merge only when https://pkgs.devel.redhat.com/cgit/containers/nmstate-console-plugin/ has a 4.14 branch
=> Revert "Revert "[openshift-4.14] Add nmstate-console-plugin""

erratatool.yml
PR updates MicroShift advisory with more inclusive language.
=> Microshift-read-4.12:inclusive language update

erratatool.yml
PR updates MicroShift advisory with more inclusive language.
=> Microshift-read-4.13:inclusive language update

erratatool.yml
PR updates MicroShift advisory with more inclusive language.
=> Microshift-read-4.14:inclusive language update

images/openshift-kubernetes-nmstate-handler.yml, images/openshift-kubernetes-nmstate-operator.yml
Test builds:
- https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2407175
- https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2407176
- https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2407179
=> Re-enable nmstate operator and its dependents

product.yml
This will help bugs like https://issues.redhat.com/browse/OCPBUGS-8543 be automatically triaged.
=> ose-kubevirt-csi-driver-container product mapping

group.yml
ref https://issues.redhat.com/browse/ART-6286
=> bump golang to 1.19.6

releases.yml
Reverts openshift-eng/ocp-build-data#2673
=> Revert "Pin rhcos images to stream assembly"

images/openshift-base-nodejs.yml, images/openshift-base-rhel8.yml, images/openshift-base-rhel9.yml
Should be merged only when https://issues.redhat.com/browse/DPP-12304 is done
=> [4.14] ART-6193 Prepare for openshift-eng move

streams.yml
Reverts openshift-eng/ocp-build-data#2677
=> Revert "[ART-6286] 4.13 - Bump rhel8 builder"

streams.yml
Reverts openshift-eng/ocp-build-data#2680
=> Revert "Revert "[ART-6286] 4.13 - Bump rhel8 builder""

releases.yml
Reverts openshift-eng/ocp-build-data#2684
=> Revert "[ART-6195] Pin DTK with scos kernel so that 9.2 kernels match"

images/nmstate-console-plugin.yml, streams.yml
Ref. https://issues.redhat.com/browse/ART-6289
Depends on https://github.com/openshift/nmstate-console-plugin/pull/10#issuecomment-1476132459
=> [4.13] Remove nginx stream; use ocp base as last build layer

group.yml
cherrypick of https://github.com/openshift-eng/ocp-build-data/pull/2701
=> Disable gpgcheck for scos repos

images/cluster-nfd-operator.yml
Need https://github.com/openshift/cluster-nfd-operator/pull/285 to merge first
Ref. https://issues.redhat.com/browse/ART-5725
=> Use stable channel for cluster-nfd-operator

images/openshift-kubernetes-nmstate-handler.yml, images/openshift-kubernetes-nmstate-operator.yml
test build pass: 
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fcustom/3086
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Folm_bundle/9164/
=> enable nmstate

group.yml
https://redhat-internal.slack.com/archives/C028KQL4LEA/p1679683110401159
=> Pin 9.2 RHEL compose

group.yml
https://redhat-internal.slack.com/archives/C028KQL4LEA/p1679685634708139?thread_ts=1679683110.401159&cid=C028KQL4LEA
=> Pin 9.2 RHEL compose for 4.14

ci_transforms/rhel-8/ci-build-root/Dockerfile, ci_transforms/rhel-9/ci-build-root/Dockerfile
/assign @sosiouxme @jupierce
/cc @bertinatto
=> Update etcd to 3.5.7 to match k8s 1.27

releases.yml
Run details - https://redhat-internal.slack.com/archives/C048BG69N8H/p1680022817142449
- [build-sync (Fail)](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/31768/console)
- [build-sync (Success)](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/31771/console)
=> Assembly definition for rc.1

group.yml
Reverts openshift-eng/ocp-build-data#2732
=> Revert "Freeze 4.10 automation during mass rebuild"

group.yml
Ref. https://issues.redhat.com/browse/ART-5434
=> Update plashets location

images/ose-ovn-kubernetes.yml, images/ovn-kubernetes-base.yml, images/ovn-kubernetes-microshift.yml
https://github.com/openshift/cluster-network-operator/pull/1747
=> Follow upstream naming change

product.yml
New request to add the agent-installer-utils image
=> AGENT-592: Add agent-install-utils image

group.yml
ref [ART-6416](https://issues.redhat.com/browse/ART-6416)
=> bump to golang 1.18.10

streams.yml
ref: [ART-6415](https://issues.redhat.com/browse/ART-6415)
=> bump golang builder to 1.19.6

images/ose-machine-config-operator.yml
https://redhat-internal.slack.com/archives/C04L1FPFHNH/p1681199174940729?thread_ts=1681192753.860489&cid=C04L1FPFHNH
=> enable server-ose repo

images/ose-machine-config-operator.yml
backport https://github.com/openshift-eng/ocp-build-data/pull/2771/files
=> enable ose repo

rpms/openshift-ansible.yml
Test build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2449426
=> Build ansible rpm for rhel9

images/ose-ovn-kubernetes.yml, images/ovn-kubernetes-base.yml, images/ovn-kubernetes-microshift.yml
Following changes in https://github.com/openshift/ovn-kubernetes/pull/1635
=> Fix ovn dockerfiles

group.yml
Reverts openshift-eng/ocp-build-data#2821
=> Revert "Freeze automation"

releases.yml
Based on https://github.com/openshift-eng/ocp-build-data/pull/2837
=> Bump 4.11.38 to newer nightly

images/ose-agent-installer-utils.yml
ref [ART-6592](https://issues.redhat.com/browse/ART-6592)
=> [ART-6592] Add OCP component - containers/ose-agent-installer-utils

images/driver-toolkit.yml
dtk need latest kernel https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/31966/console
=> enable embargoed repo for dtk

group.yml
See https://github.com/openshift-eng/doozer/pull/750
=> Enable weekly kernel release support

product.yml
=> Update jira component for node / autoscaler

images/ingress-node-firewall-daemon.yml, images/ingress-node-firewall-operator.yml
Ref. https://issues.redhat.com/browse/ART-6294
=> Build ingress node firewall images on rhel9

images/openshift-kubernetes-nmstate-handler.yml
ref https://github.com/openshift-eng/ocp-build-data/pull/2924/
=> [ART-5985] remove nmstate-console-plugin

images/linuxptp-daemon.yml
Reverts openshift-eng/ocp-build-data#2927
=> Revert "4.12: Get linuxptp in linuxptp-daemon"

images/oc-mirror-plugin.yml
MULTIARCH-3440: add multiarch support for ppc64le
=> MULTIARCH-3440: add multiarch support for ppc64le

images/monitoring-plugin.yml, images/nmstate-console-plugin.yml, streams.yml
Ref. https://issues.redhat.com/browse/ART-6861
Test build details [here](https://issues.redhat.com/browse/ART-6861?focusedId=22323318&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22323318)
=> Upgrade console base image to node 16

bug.yml
=> [4.13] bug.yml: do not manage LVMS bugs

group.yml, images/driver-toolkit.yml
DTK still needs RT, but not `rhel-8-rt`
=> [4.14] RT rpms

streams.yml
[openshift-golang-builder-container-v1.19.9-202305291556.el9.g3460409](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2527283)
=> [ART-6920] update to golang 1.19.9

images/ptp-operator-must-gather.yml
https://redhat-internal.slack.com/archives/CB95J6R4N/p1685860335603839
=> [OCPBUGS-13834] Update ptp-operator-must-gather member

group.yml
URL has changed, we need to update it to fix build failures.
=> Update URL for OSP multiarch repos

group.yml
=> Define ocp_release_state field in group config

group.yml
=> [4.7] Define ocp_release_state field in group config

group.yml
=> [4.8] Define ocp_release_state field in group config

group.yml
=> [4.9] Define ocp_release_state field in group config

group.yml
=> [4.10] Define ocp_release_state field in group config

group.yml
https://issues.redhat.com/browse/ART-6729
=> [4.12] Define ocp_release_state field in group config

group.yml
=> [4.14] Define ocp_release_state field in group config

images/openshift-base-rhel9.yml
=> [HOLD] [4.14] base-rhel9: update with ose plashet

product.yml
The image repository is https://github.com/openshift/console-dashboards-plugin
=> Add console dashboards component mapping

images/cluster-node-tuning-operator.yml
Ref. https://issues.redhat.com/browse/ART-7138
Successful build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2566328
=> Build NTO on rhel9

images/ose-olm-operator-controller.yml
Ref. https://issues.redhat.com/browse/ART-7135
=> Add operator-framework-operator-controller

images/ose-olm-catalogd.yml
test build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2573435
=> [ART-7136] add ose-olm-catalogd

images/ose-cluster-olm-operator.yml
test build: [ose-cluster-olm-operator-container-v4.14.0-202306290942.p0.gdfc350a.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2575920)
=> [ART-7156] add cluster-olm-operator

images/ose-machine-config-operator.yml
The list is very outdated. Just updating for 4.14 for now
=> Update MCO owner references

group.yml, streams.yml
This reverts commit 368bb3c79e5cb183253ecf76368748829afaca97.
=> Revert "Update streams.yml"

images/openshift-base-rhel9.yml
=> [4.13] base-rhel9: update with ose plashet

images/openshift-base-rhel8.yml
=> [4.12] base-rhel8: update with ose plashet

images/openshift-base-rhel8.yml
=> [4.11] base-rhel8: update with ose plashet

group.yml, images/openshift-base-rhel8.yml
=> [4.10] base-rhel8: update with ose plashet

images/linuxptp-daemon.yml
To follow https://github.com/openshift/linuxptp-daemon/pull/153
=> Add layer to linuxptp

images/ose-multus-whereabouts-ipam-cni.yml
...to go with https://github.com/openshift/whereabouts-cni/pull/139
=> 4.13: Adjust froms whereabouts-cni

images/ose-sdn.yml
...to follow https://github.com/openshift/sdn/pull/557
=> 4.13: Get rhel9 golang build stage for sdn

images/ose-network-interface-bond-cni.yml
...to go with https://github.com/openshift/bond-cni/pull/56
=> 4.13: Adjust froms bond-cni

images/kube-rbac-proxy.yml, images/ose-olm-catalogd.yml, images/ose-olm-operator-controller.yml, images/ose-olm-rukpak.yml
according to https://github.com/openshift/cluster-olm-operator/blob/release-4.14/manifests/image-references
=> add dependents

streams.yml
Reverts changes done in https://github.com/openshift-eng/ocp-build-data/commit/f75a59a27a17ae4cf716901acedeed3363915b67 
slack ref https://redhat-internal.slack.com/archives/C01CQA76KMX/p1689188103606639?thread_ts=1689169944.865979&cid=C01CQA76KMX
=> 4.14 - Revert back to no_fips golang

images/ose-multus-whereabouts-ipam-cni.yml, images/ose-network-interface-bond-cni.yml
according to 
https://github.com/openshift/whereabouts-cni/blob/release-4.14/Dockerfile.openshift
https://github.com/openshift/bond-cni/blob/release-4.14/Dockerfile.openshift
=> fix golang layer

images/ose-network-tools.yml
Ref https://github.com/openshift/network-tools/pull/83
=> 4.13 - Move ose-network-tools to rhel-9-golang

images/ose-sdn.yml
ref: https://github.com/openshift/sdn/pull/559
=> Adjust builder images for https://github.com/openshift/sdn/pull/559

images/openshift-kubernetes-nmstate-handler.yml
ref: https://redhat-internal.slack.com/archives/CP7329Z5Z/p1689692208082079?thread_ts=1689228182.615619&cid=CP7329Z5Z
=> Update openshift-kubernetes-nmstate-handler brew name

images/openshift-kubernetes-nmstate-operator.yml
according to https://github.com/openshift-eng/ocp-build-data/pull/3215
=> Update base image to el9

releases.yml
https://issues.redhat.com/browse/ART-7274
green build-sync https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/34838/console
=> Define art7274 assembly

releases.yml
Green build-sync https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/34850/console
=> ART-7274 - rebuild driver tooklit

images/linuxptp-daemon.yml
cherry-pick of https://github.com/openshift-eng/ocp-build-data/pull/3219
=> revert new from image from linuxptp-daemon.yml

images/ose-sdn.yml
...to match https://github.com/openshift/sdn/pull/560
=> Adjust ose-sdn Dockerfile
