releases.yml

Now that 9.2 rhcos builds have stabilized, we want to make
sure rhcos is in line with assembly selected rpms.
Current nightlies are not failing/blocked on these permits
see assembly_issues in
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/32243/

[4.13] Remove stream permits for rhcos

---

group.yml

https://issues.redhat.com/browse/ART-5546
golang 1.20.3 build has been tagged in build repo and regen'd
http://download-node-02.eng.bos.redhat.com/brewroot/repos/rhaos-4.14-rhel-8-build/latest/x86_64/pkglist
[slack ref](https://redhat-internal.slack.com/archives/CB95J6R4N/p1681752484491239?thread_ts=1678464475.365519&cid=CB95J6R4N)

ART-5546 rhel8 - Pick up golang 1.20.3 - Revert to build repos

---

streams.yml

https://issues.redhat.com/browse/ART-5546
[openshift-golang-builder-container-v1.20.3-202304171838.el9.g169fa12](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2467997)
[openshift-golang-builder-container-v1.20.3-202304171839.el8.g3464689](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2468004)
Verified the right rpms were picked
```
$ elliott go -n  openshift-golang-builder-container-v1.20.3-202304171838.el9.g169fa12
Following nvrs are built with 1.20.3-1.el9:
openshift-golang-builder-container-v1.20.3-202304171838.el9.g169fa12
$ elliott go -n openshift-golang-builder-container-v1.20.3-202304171839.el8.g3464689
Following nvrs are built with 1.20.3-1.el8:
openshift-golang-builder-container-v1.20.3-202304171839.el8.g3464689
```

ART-5546 Bump 4.14 golang to 1.20.3

---

group.yml

[slack ref](https://redhat-internal.slack.com/archives/GDBRP5YJH/p1681827364531299?thread_ts=1681738119.840439&cid=GDBRP5YJH)

[4.14] make canonical_builders_from_upstream "auto"

---

images/thanos.yml

Reverts openshift-eng/ocp-build-data#2818
Taking another approach

Revert "Thanos back to golang-1.19"

---

ci_transforms/rhel-9/ci-build-root/Dockerfile

The command `rpmbuild` disappeared from ci-buildroot image with the move from rhel-8 to rhel-9, as the rpm rpm-build does not get installed. The packages that got removed relative from the rhel8 build-root image is:
```
libvirt-devel
mercurial
tito
```
Tito has a dependency on rpm-build. This brings back the missing package.

Add rpm-build to ci buildroot

---

images/ose-frr.yml

brew isn't configured to allow the build into our rhel9 tag yet; we can still build on the "wrong" tag for now

ose-frr: temporarily keep building on rhel-8 branch

---

images/monitoring-plugin.yml

fixes validation complaining about the upstream location; the private location looks good to me so let's use it

monitoring-plugin: use private org

---

images/cluster-storage-operator.yml
images/ose-cluster-csi-snapshot-controller-operator.yml

All images owned by aos-storage-staff should have enabled auto lgtm + approve on "_Updating %s images to be consistent with ART_" PRs.

4.14: Enable auto-lgtm+approve on storage image PRs

---

images/ose-agent-installer-utils.yml

[slack ref](https://redhat-internal.slack.com/archives/CB95J6R4N/p1682527843540499?thread_ts=1681736898.206669&cid=CB95J6R4N)

ART-6592 Reconcile ose-agent-installer-utils name with upstream

---

rpms/microshift.yml

dhellmann requested stopping building MicroShift 4.14 and later for RHEL 8.

microshift: Disable el8 build

---

releases.yml

```
oc image info -o json quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:29d23fcae3934be056e1e410bf1641373d5bcdce6b8f5d8dfcfdee44af26058f | jq | grep machine-os
"io.openshift.build.version-display-names": "machine-os=Red Hat Enterprise Linux CoreOS",
"io.openshift.build.versions": "machine-os=414.92.202304281310-0",
```

4.14 ec0 - Correct mcos sha for x86

---

images/dpu-network-operator.yml

[This change](https://github.com/openshift/dpu-network-operator/commit/a293f35609ba1a42d828b1b4fb1cba2b1b1085c4) renamed Dockerfile.rhel7 into Dockerfile.rhel9

[4.14] Update dpu-network-operator Dockerfile

---

rpms/microshift.yml

group.yml has default target `rhaos-{MAJOR}.{MINOR}-rhel-8-candidate`. We need to explicitly set the build target to
`rhaos-{MAJOR}.{MINOR}-rhel-9-candidate` for microshift.

microshift: explicitly set target to rhel 9

---

group.yml

rhcos: Add definition for build repos

---

group.yml

rhcos: Add definition for build repos [4.13]

---

group.yml

rhcos: Add definition for build repos [4.12]

---

group.yml

rhcos: Add definition for build repos [4.11]

---

group.yml

rhcos: Add definition for build repos [4.10]

---

group.yml

rhcos: Add definition for build repos [4.9]

---

group.yml

rhcos: Add definition for build repos [4.7]

---

group.yml
images/openshift-golang-builder.yml

there is no longer an "imagebuilder" build type.
and we would update the 4.13 buildroot before backporting to 4.12

update for newer reality

---

streams.yml

Console has trouble building in CI because nodejs16 builder wasn't renamed, so `registry.ci.openshift.org/ocp/builder:rhel-8-base-nodejs-openshift-4.14` still contains node14. 
Follows https://github.com/openshift-eng/ocp-build-data/pull/2947
Ref. https://issues.redhat.com/browse/ART-6294

Rename nodejs ci image

---

streams.yml

[openshift-golang-builder-container-v1.19.9-202305291556.el9.g3460409](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2527283)

[ART-6092] update to golang 1.19.9

---

releases.yml

slack ref - https://redhat-internal.slack.com/archives/GDBRP5YJH/p1685545115620139
Build: https://releases-rhcos-art.apps.ocp-virt.prod.psi.redhat.com/?stream=prod/streams/4.13-9.2&release=413.92.202305302312-0&arch=x86_64
```
x64
RHCOS Base OS	quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fa341312c06ce6d200ab0d24f1851e6bc97b4bf94f4aaf9eeca6a04d8aeaa030
Extensions	quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84f018f1495feb3045d8f6e0e2fbda5a972d8bb15c1f4823fd81c932d90777cb
machine-os-content (legacy)	quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:172102e1326b724fbd84d59308ed6f1f91a22adbadf4193f469d1846958264b6
s390x
RHCOS Base OS	quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1bd525e2136b3f74a3aec4d6de2ea36dbf77c7ddff1c63e0b8faf10cc7bb3282
Extensions …
```

4.13.2 - Pin newer rhcos

---

releases.yml

By default, we allow the code OUTDATED_RPMS_IN_STREAM_BUILD in the stream assembly, yet CONFLICTING_GROUP_RPM_INSTALLED is not allowed.
This leads to the following situation:
```yaml
rhcos:
- code: OUTDATED_RPMS_IN_STREAM_BUILD
msg: Found outdated RPM (openshift-clients-4.14.0-202305311616.p0.g603c3af.assembly.stream.el9)
installed in RHCOSBuild:x86_64:414.92.202305311647-0 (x86_64) when openshift-clients-4.14.0-202306012015.p0.g493ee2b.assembly.stream.el9
is available in repo rhel-9-server-ose-rpms
permitted: true
- code: CONFLICTING_GROUP_RPM_INSTALLED
msg: Expected 414.92.202305311647-0/ppc64le image to contain assembly selected
RPM build openshift-clients-4.14.0-202306012015.p0.g493ee2b.assembly.stream.el9
but found …
```

Allow CONFLICTING_GROUP_RPM_INSTALLED for rhcos in stream

---

images/golang-github-prometheus-alertmanager.yml
images/golang-github-prometheus-node_exporter.yml
images/openshift-enterprise-registry.yml

docker_api was used in some images for working around some bugs in imagebuilder, e.g. https://github.com/openshift/imagebuilder/issues/87.
I believe those issues no longer exist with the current OSBS 2 builder. Let's try it instead.

Move docker_api builder to osbs2

---

group.yml

rhcos: Add definition for build repos - 4.6

---

group.yml

rhcos: Add definition for build repos - 4.8

---

bug.yml
group.yml

Add config for tag-rpms and scan-for-kernel-bugs jobs [4.14]

---

bug.yml
group.yml

Add config for tag-rpms and scan-for-kernel-bugs jobs [4.11]

---

bug.yml
group.yml

Add config for tag-rpms and scan-for-kernel-bugs jobs [4.10]

---

bug.yml
group.yml

Add config for tag-rpms and scan-for-kernel-bugs jobs [4.12]

---

bug.yml
group.yml

Add config for tag-rpms and scan-for-kernel-bugs jobs - 4.9

---

group.yml

This will be reverted in a few hours.

[4.14] freeze scheduled automation to allow ocp4 testing

---

group.yml

Reverts openshift-eng/ocp-build-data#3053

Revert "[4.14] freeze scheduled automation to allow ocp4 testing"

---

product.yml

This adds component mapping for Secrets Store CSI Driver, its operator, and the operator bundle.
/cc @openshift/storage @jupierce

Add secrets-store-csi-driver to product.yml

---

images/multus-cni-alt.yml

Multus needs a RHEL7 binary to run on bring-your-own RHEL7 nodes. However, aarch64 is not supported on RHEL7. To address this, compile an -alt image for non-aarch64 which include RHEL7.

Compile multus on rhel7 on non-aarch64 arches

---

images/monitoring-plugin.yml

the payload name default is based on the image name. but in the payload its name does not have `-rhel8`

monitoring-plugin: needs a matching payload name

---

images/ose-olm-catalogd.yml
images/ose-olm-operator-controller.yml

[ref slack](https://redhat-internal.slack.com/archives/CB95J6R4N/p1687972687910899)
```
OCP and Origin images should match failures:
Found recent tags downstream that are not built upstream (not in ocp/4.14): olm-catalogd-rhel8, olm-operator-controller-rhel8
```
They'll be published with `-rhel8` in the name, but named without it in the payload tags.

olm-catalogd/operator-controller: correct payload names

---

rpms/microshift.yml

Ref. https://issues.redhat.com/browse/ART-6671
We need to configure what arches need to be synced, in order to auto-trigger the `microshift-sync` job

Define what arches should be published for microshift RPM

---

images/ose-multus-whereabouts-ipam-cni.yml
images/ose-network-interface-bond-cni.yml

FIPS compliance has forced binaries which were previously statically linked to compile dynamically linked. This means that binaries that are copied to the host, like these CNI binaries, must be compiled using a builder image that corresponds to the RHCOS RHEL version.

Compile CNI binaries for RHCOS RHEL

---

streams.yml

slack ref https://redhat-internal.slack.com/archives/CJARLA942/p1689264000855209
[openshift-golang-builder-container-v1.19.10-202307131621.el8.gba7a391](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2592841)
[openshift-golang-builder-container-v1.19.10-202307131626.el9.g446ea7c](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2592843)

[4.13] Revert to no-fips-enforcing-wrapper golang

---

images/ose-machine-config-operator.yml

This reverts commit https://github.com/openshift-eng/ocp-build-data/commit/3282312e60f92f87071c5d0dda01aff802af2c92. The MCO
change was reverted in https://github.com/openshift/machine-config-operator/pull/3802
due to a regression, so update the build here accordingly.
Also cherry-pick in the owners change so the emails gets sent out to the correct MCO members

Updates to MCO 4.13

---

images/ptp-operator.yml

ptp operator builds are failing due to known blocker https://issues.redhat.com/browse/OCPBUGS-16041
Which is showing up in various places (images:health, failed ocp4/olm_bundle jobs)
Disable it until blocker is resolved

4.14 - Disable ptp operator builds until blocker is resolved

---

product.yml

Minor update to have bugs like https://issues.redhat.com/browse/OCPBUGS-16361 be automatically routed to the right component.

product mapping for openshift-kubernetes-nmstate-handler

---

images/ose-machine-config-operator.yml

with PR https://github.com/openshift/machine-config-operator/pull/3799 merged, MCO is using rhel-9-golang to build mcd daemon binary for RHEL 9 target

Include rhel-9-golang builder stream in ose-machine-config-operator.yml

---

images/openshift-enterprise-tests.yml

While working on a story, noticed that this image is missing github repo details.
I haven't checked why/how this has continued working? how does doozer get to the repo?
and what alias exactly means (seems harmless?)

4.14 - [ose-tests] Add git repo details

---

modifications/Dockerfile
modifications/microshift-rebase

This commit involves refactoring the `microshift-rebase` script and the Dockerfile to ensure a safer and more robust containerized operations.
- The Dockerfile  incorporates the environment setup for Go, Python, yq, jq, and the OpenShift client. This ensures all dependencies are packaged within the container, reducing potential conflicts with host dependencies.
- The Dockerfile clones the MicroShift repository from a specific branch (defaulted to 'release-4.13'), allowing for flexible version control.
- The Dockerfile initiates the `./scripts/auto-rebase/rebase.sh` operation directly based on set environment variables. This is a significant change as the logic to perform the rebase operation has been shifted from the `microshift-rebase` script into the Dockerfile. This ensures that the …

[ART-7130] Refactor microshift-rebase script for hardened containerization.

---

images/ose-sdn.yml

Fixing this error:
```
OSError: Build metadata for openshift/ose-sdn expected 3 image parent(s), but the upstream Dockerfile contains 4 FROM statements. These counts must match
```
Needed after https://github.com/openshift/sdn/commit/ed6c5da1c2b9feeb5bc5a4d0ac5695d14133d293

[4.6] Add missing build stage to ose-sdn

---

group.yml

This will make doozer ensure this key exists in meta.json
and skip builds that don't have it.
Right now it crashes since it doesn't have this info.

4.9 - Add rhcos primary payload tag

---

group.yml

`release_state` usage is redunt. We only need x86 for 3.11

[3.11] Merge release_state with release arches

---

rpms/microshift.yml

This is making microshift_sync job make "https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp-dev-preview/4.14.0-ec.4/elrhel-9/" dir - and we want `el9`
I looked and rhel_targets looks to be a new key we're introducing, and think it's okay to keep it just an int to simplify parsing

Change microshift rhel target to just integer

---

product.yml

Trying to make sure the following bugs are automatically routed to the correct component:
https://issues.redhat.com/browse/OCPBUGS-17288
ose-cluster-control-plane-machine-set-operator-container 
\* I confirmed with the owner that "Cloud Compute / Other Provider" is the correct component
https://issues.redhat.com/browse/OCPBUGS-17290
ose-gcp-cluster-api-controllers-container
The second one was just missing "-container" on the end.

More mappings for Cloud Compute / Other Provider

---

product.yml

This commit fixes the declared components of images.
Images that get built by ART got a fix for the declared components. Externally built images were dropped.
The following script was used to find jira components that do not exist:
```python
import os
from requests import get
import sys
import ruamel.yaml as yaml
from jira import JIRA
url = 'https://raw.githubusercontent.com/openshift/ocp-build-data/main/product.yml'
product = yaml.safe_load(get(url).text)
images = product['bug_mapping']['components']
jira_components = {images[i]['issue_component'] for i in images}
token_auth = os.environ["JIRA_TOKEN"]
client = JIRA("https://issues.redhat.com", token_auth=token_auth)
existing_components = {c.name for c in client.project_components('OCPBUGS')}
missing = jira_components - …
```

Fix jira components for images

---

group.yml
images/openshift-golang-builder.Dockerfile
images/openshift-golang-builder.yml

add go wrapper during golang build process, the wrapper script will get from [doozer repo](https://github.com/openshift-eng/doozer/pull/811)

[ART-7273] add modifications to support go wrapper

---

group.yml

We started forcing olm operators to have default channel set to `stable` from 4.9+ 
and get operators to switch from 4.Y naming convention to stable. 
Now that all operators (4.14/15) are using the "stable" naming convention,
there are requests to override it (for example: operator in tech preview using preview channel).
So removing this config will let doozer use the `update-csv.channel` as the only channel
in annotations (https://github.com/openshift-eng/doozer/blob/0a73132bc3e97901f0651d99463c47e4e8267b1e/doozerlib/olm/bundle.py#L570)
https://redhat-internal.slack.com/archives/CB95J6R4N/p1692646497373029?thread_ts=1692638515.176259&cid=CB95J6R4N

4.15 - Remove operator channel stable config

---

streams.yml

re: [ART-4761](https://issues.redhat.com/browse/ART-4761)
to support https://github.com/openshift-eng/doozer/pull/817
add upstream_image_mirror in the build's config, they are supposed to be synced to the corresponding private namespace for CI

add upstream_image_priv confg

---

releases.yml

This unblocks failing 4.14 build-sync 
driver-toolkit image has kernel-rt package which is ahead of kernel
We have untagged the kernel-rt but driver-toolkit will need a rebuild,
meanwhile pin an older build containing the current kernel-rt to unblock nightlies
```
$ doozer --debug --group openshift-4.14@pin_older_driver_toolkit --data-path https://github.com/thegreyd/ocp-build-data inspect:stream FAILED_CONSISTENCY_REQUIREMENT
...
Payload contents consistency requirements satisfied
```

4.14 - Pin older consistent driver toolkit image

---

releases.yml

This reverts commit 6fc0676ce86914f42b7e400dc357cf2e26f96849.
Reverting this as latest driver-toolkit is good and will not block nightlies

Revert "4.14 - Pin older consistent driver toolkit image (#3438)"

---

group.yml

This reverts commit dcd47cc3d2f7d362cea83c389c70a4461825025b.
Wait until 4.15 mass rebuild completes

Revert "Disable 4.11 automation (#3422)"

---

ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

This matches:
- https://github.com/kubernetes/kubernetes/blob/release-1.28/hack/lib/etcd.sh#L19
- https://github.com/kubernetes/kubernetes/blob/release-1.28/hack/lib/protoc.sh#L28
/assign @jupierce @bertinatto

Update etcd and protoc to match k8s 1.28

---

ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

This matches:
- https://github.com/kubernetes/kubernetes/blob/release-1.27/hack/lib/etcd.sh#L19
- https://github.com/kubernetes/kubernetes/blob/release-1.27/hack/lib/protoc.sh#L28
/assign @jupierce @bertinatto

Update protoc to match k8s 1.27

---

ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

This matches:
- https://github.com/kubernetes/kubernetes/blob/release-1.26/hack/lib/etcd.sh#L19
- https://github.com/kubernetes/kubernetes/blob/release-1.26/hack/lib/protoc.sh#L43
/assign @jupierce @bertinatto

Update protoc to match k8s 1.26 and etcd in rhel9 builder to match rhel8

---

product.yml

We created a new component "Networking / network-tools" to classify bugs created for the network-tools repository. This commit updates the image to refer to this new component.

Update network-tools container image to refer to new JIRA component

---

group.yml
images/openshift-golang-builder.Dockerfile
images/openshift-golang-builder.yml

add go wrapper during golang build process, the wrapper script will get from https://github.com/openshift-eng/doozer/pull/811
rhel-8-golang-1.17 can built with FoD wrapper and don't update new builder to floating tag for now

[ART-7273] add modifications to support rhel-8-golang-1.17

---

images/sriov-cni.yml

This should resolve to rhel9 repo https://comet.engineering.redhat.com/containers/repositories/650022db8f57a98d4e3ee969
...and keep current image references intact.

sriov-cni: Fix rhel9 image name in operator

---

group.yml

By marking 4.6 as `eol` instead of `release`, we will keep signing artifacts but skip jobs like `check-bugs`, `nag-upstream` and the like that can produce undesired spam in private and public channels

Mark 4.6 as EOL

---

group.yml

By marking 4.7 as `eol` instead of `release`, we will keep signing artifacts but skip jobs like `check-bugs`, `nag-upstream` and the like that can produce undesired spam in private and public channels

Mark 4.7 as EOL

---

group.yml

By marking 4.8 as `eol` instead of `release`, we will keep signing artifacts but skip jobs like `check-bugs`, `nag-upstream` and the like that can produce undesired spam in private and public channels

Mark 4.8 as EOL

---

group.yml

By marking 4.9 as `eol` instead of `release`, we will keep signing artifacts but skip jobs like `check-bugs`, `nag-upstream` and the like that can produce undesired spam in private and public channels

Mark 4.9 as EOL

---

group.yml

By marking 3.11 as `eol` instead of `release`, we will keep signing artifacts but skip jobs like `check-bugs`, `nag-upstream` and the like that can produce undesired spam in private and public channels

Mark 3.11 as EOL

---

group.yml

This will make the standard operators available in OperatorHub for 4.14+ public indexes, although only the latest GA version. This is intended for use cases involving testing operator management mechanisms, without too much concern for the operators themselves.

[ART-5526] publish 4.13 operators in 4.14+ index

---

ci_transforms/rhel-9/ci-build-root/Dockerfile

This is a follow up to https://github.com/openshift-eng/ocp-build-data/pull/3454.
/assing @jupierce
CC @soltysh

Update protoc on RHEL 9 builder to match k8s 1.28

---

releases.yml

Sid and Ashwin paired on creating this assembly definition. There wasn't a consistent set of nightlies (release controller creates x86 nightlies slower than the rest of the arches -- because of blocking tests and it's limit of only 1 pending nightly -- and they get inconsistent sometimes).
We picked the x64 nightly as the authoratative one and ran the command to get the brew event
```
doozer --assembly stream --group openshift-4.14 release:gen-assembly --name rc.1 from-releases --nightly 4.14.0-0.nightly-2023-09-15-055234 --custom
```
and then ashwin manually found the rhcos shasums and had them in

assembly definition for 4.14 rc.1

---

releases.yml

Image was added to ocp-build-data after nightly for RC was created so that we can unblock prepare release which is looking for this build for rc.1

pin ose-secrets-store-csi-mustgather

---

images/ose-olm-catalogd.yml
images/ose-olm-operator-controller.yml
images/ose-olm-rukpak.yml

We need to use `commit_prefix` to comply with `commitchecker` validations.

Updates `ci_alignment` for OLM components

---

images/azure-file-csi-driver.yml
images/csi-attacher.yml
images/csi-livenessprobe.yml
images/csi-node-driver-registrar.yml
images/csi-provisioner.yml
images/csi-snapshot-validation-webhook.yml
images/ibm-vpc-node-label-updater.yml
images/ose-alibaba-cloud-csi-driver.yml
images/ose-aws-ebs-csi-driver.yml
images/ose-aws-efs-csi-driver.yml
images/ose-azure-disk-csi-driver.yml
images/ose-csi-external-resizer.yml
images/ose-csi-external-snapshotter.yml
images/ose-csi-snapshot-controller.yml
images/ose-gcp-filestore-csi-driver.yml
images/ose-gcp-pd-csi-driver.yml
images/ose-ibm-vpc-block-csi-driver.yml
images/ose-secrets-store-csi-driver.yml
images/ose-vmware-vsphere-csi-driver.yml
images/vmware-vsphere-syncer.yml

Add `"UPSTREAM: <carry>:"` to forks of upstream CSI drivers, CSI sidecars and similar storage repos.

Add prefix to automatic PR in storage repos

---

images/azure-file-csi-driver.yml
images/csi-attacher.yml
images/csi-livenessprobe.yml
images/csi-node-driver-registrar.yml
images/csi-provisioner.yml
images/csi-snapshot-validation-webhook.yml
images/ibm-vpc-node-label-updater.yml
images/ose-alibaba-cloud-csi-driver.yml
images/ose-aws-ebs-csi-driver.yml
images/ose-aws-efs-csi-driver.yml
images/ose-azure-disk-csi-driver.yml
images/ose-csi-external-resizer.yml
images/ose-csi-external-snapshotter.yml
images/ose-csi-snapshot-controller.yml
images/ose-gcp-filestore-csi-driver.yml
images/ose-gcp-pd-csi-driver.yml
images/ose-ibm-vpc-block-csi-driver.yml
images/ose-secrets-store-csi-driver.yml
images/ose-vmware-vsphere-csi-driver.yml
images/vmware-vsphere-syncer.yml

Add `"UPSTREAM: <carry>:"` to forks of upstream CSI drivers, CSI sidecars and similar storage repos.

4.14: Add prefix to automatic PR in storage repos 

---

images/ose-secrets-store-csi-driver-operator.yml
images/ose-secrets-store-csi-driver.yml

ose-secrets-store-csi-driver and ose-secrets-store-csi-driver-operator are relatively new storage team repos and we'd like auto-lgtm + auto-approve on base image / go version changes.

Add auto-lgtm to new storage repos

---

images/openshift-kubernetes-nmstate-operator.yml
images/ose-agent-installer-node-agent.yml

when building something for rhel9, should have rhel9 branch; this causes it to build against the rhel9 tag, which when attached to errata is associated with rhel9 CDN repo.
/cherry-pick openshift-4.15

rhel9 builds should happen in rhel9 branches/tags

---

images/ose-agent-installer-node-agent.yml

This change was already made in 4.14, we need it to persist into 4.15.

Compile assisted-installer-agent for RHEL 9

---

releases.yml

Investigate bugs that have pscomponent package that do not have a corresponding build in any of our advisories.
We want to ship some of these, indicate that as well.

4.14 GA - Add reasons for why some ocpbugs have wrong pscomponents

---

erratatool.yml

This PR is from the core OCP docs writers. It updates a URL change for our updating link in the errata. 
@thiagoalessio PTAL
cc: @dfitzmau @cbippley
Issue:
https://issues.redhat.com/browse/OSDOCS-6742

OCP-4.14-linkfix: updates links for 4.14 docs url move

---

releases.yml

follow up from https://github.com/openshift-eng/ocp-build-data/pull/3560 
doozer doesn't like bools as image labels 
This is blocking all 4.14 rebase & builds right now

[4.14] Make image label bool into string

---

images/cluster-version-operator.yml

Having `qe-approved` allows linked OCPBUGS cards to automatically move to `VERIFIED` once the PR merges and is included in a subsequent green nightly.
4.15 PRs were already filed, I assume the `openshift-4.16` branch will be populated from `openshift-4.15`.

cvo: label alignment PRs with `qe-approved`

---

images/openshift-enterprise-pod.yml

re https://issues.redhat.com/browse/ART-7894
openshift-enterprise-pod in 4.14 ci is using rhel9

ART-7894 don't update ci build root for openshift-enterprise-pod in 4.14

---

images/openshift-enterprise-pod.yml

re https://issues.redhat.com/browse/ART-7894
upstream changed to rhel9 https://github.com/openshift/kubernetes/blob/release-4.15/build/pause/Dockerfile.Rhel#L1
test build success https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=56052752

ART-7894 move openshift-enterprise-pod to rhel9 in 4.15

---

images/atomic-openshift-descheduler.yml
images/ose-cluster-kube-descheduler-operator.yml

Following upstream [bump](https://github.com/openshift/cluster-kube-descheduler-operator/pull/304) for 4.15
[Tested](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/47734), build started normally.
_PR ready to merge. Requesting lgtm and approve_

Re-enable ose-cluster-kube-descheduler-operator

---

images/openstack-cluster-api-controllers.yml

Test build: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/47452/console

ART-7892 Add openstack-cluster-api-controllers

---

group.yml

with 4.14 GA imminent, stop publishing 4.13 bundles to 4.14 indexes.

group.yml: end bundle drift from 4.13

---

group.yml

I have a new strategy for pre-releases, which is to just rebuild the bundles that are going to be pre-released. The rest of the time it makes sense to build them as normal. This way we don't have to remember to switch the setting at the right time.

[4.15] group: only do bundle pre-release on demand

---

group.yml

The e4s repositories do not get updated for all arches. Preferring building x86_64 over not building at all.

4.9: Build on x86_64 exclusively

---

group.yml

The e4s repositories do not get updated for all arches. Preferring building x86_64 over not building at all.

4.10: Build on x86_64 exclusively

---

streams.yml

https://issues.redhat.com/browse/ART-7949
Use new builders
- [openshift-golang-builder-container-v1.19.13-202310161903.el9.g0f9bb4c](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726876)
- [openshift-golang-builder-container-v1.19.13-202310161907.el8.g0d095f7](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726878)

ART-7949 - 4.13 - Bump golang builder

---

streams.yml

https://issues.redhat.com/browse/ART-7948
Use new builders
- [openshift-golang-builder-container-v1.19.13-202310161903.el9.g0f9bb4c](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726876)
- [openshift-golang-builder-container-v1.19.13-202310161907.el8.g0d095f7](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726878)

ART-7948 - 4.12 - Bump golang builders

---

streams.yml

https://issues.redhat.com/browse/ART-7947
- [openshift-golang-builder-container-v1.18.10-202310162029.el8.gacd8ae5](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726966)
- [openshift-golang-builder-container-v1.19.13-202310161907.el8.g0d095f7](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726878)

ART-7947 - 4.11 - Bump golang builders

---

streams.yml

https://issues.redhat.com/browse/ART-7950
- [openshift-golang-builder-container-v1.20.10-202310161945.el8.gdc4b478](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726932)
- [openshift-golang-builder-container-v1.20.10-202310161945.el9.gbbb66ea](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726933)
- [openshift-golang-builder-container-v1.19.13-202310161903.el9.g0f9bb4c](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726876)
- [openshift-golang-builder-container-v1.19.13-202310161907.el8.g0d095f7](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726878)

ART-7950 - 4.14 - Bump golang builders

---

streams.yml

https://issues.redhat.com/browse/ART-7951
* [openshift-golang-builder-container-v1.20.10-202310161945.el8.gdc4b478](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726932)
* [openshift-golang-builder-container-v1.20.10-202310161945.el9.gbbb66ea](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726933)
* [openshift-golang-builder-container-v1.19.13-202310161903.el9.g0f9bb4c](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726876)
* [openshift-golang-builder-container-v1.19.13-202310161907.el8.g0d095f7](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2726878)

bump golang to 1.20.10/1.19.13

---

group.yml
images/openshift-golang-builder.Dockerfile
images/openshift-golang-builder.yml

https://issues.redhat.com/browse/ART-7952

ART-7952 rhel-8-golang-1.16 - Update branch with fips support and latest compiler

---

streams.yml

https://issues.redhat.com/browse/ART-7952
nvrs
- [openshift-golang-builder-container-v1.17.12-202310200755.el8.g1ac8da3](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2738798)
- [openshift-golang-builder-container-v1.17.12-202310201412.el7.g53b4bc4](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2739973)
- [openshift-golang-builder-container-v1.16.12-202310201409.el8.g1370b35](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2739965)

ART-7952 Bump golang for 4.10

---

rpms/microshift.yml

To fix `ERROR: No arches configured.` as in https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fmicroshift_sync/38/console

Define arches for mucroshift rpm to be synced

---

streams.yml

Currently, these components build on top of nodejs:
- console
- monitoring-plugin
- nmstate-console-plugin
The console uses `openshift-base-nodejs` member as its last build stage: a test run has been build successfully: [openshift-enterprise-console-container-v4.15.0-202310201407.p0.g2b34cb0.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2740005)
`monitoring-plugin` and `nmstate-console-plugin` build from `nodejs` stream, that is mirrored  to `registry.ci.openshift.org/ocp/builder:rhel-8-openshift-nodejs-base-4.15.art`. Since this does not happen for `test` assemblies, their builds have been tested by replacing `- stream: nodejs` with `- member: openshift-base-nodejs`. This led to:
- [monitoring-plugin-container-v4.15.0-202310230802.p0.gfc4303c.assembly.test]( …

ART-7991 Bump nodejs to 18

---

product.yml

Adding the new cluster-config-api image, following directions here: https://source.redhat.com/groups/public/openshift/openshift_wiki/guidelines_for_requesting_new_content_managed_by_ocp_art

add cluster-config-api component mapping

---

images/atomic-openshift-descheduler.yml
images/ose-cluster-kube-descheduler-operator.yml

In parallel with https://github.com/openshift/cluster-kube-descheduler-operator/pull/311 and https://github.com/openshift/descheduler/pull/97

descheduler[-operator]: bump rhel version to rhel9

---

product.yml

Cluster Resource Override Admission Operator component listing has changed and has dropped the prefix "Node /".

Update clusterresourceoverride component mapping

---

images/ose-frr.yml
images/ose-metallb-operator.yml
images/ose-metallb.yml

test build: [ose-metallb-container-v4.15.0-202310240847.p0.ge3846ec.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2747316)
[ose-metallb-operator-container-v4.15.0-202310240847.p0.g7a0395f.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2747314)
depends on https://github.com/openshift/metallb-operator/pull/190

ART-7727 move ose-metallb to RHEL9

---

releases.yml

We overrode advisories at https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.14/releases.yml#L19

Remove redundant advisories field

---

streams.yml

https://issues.redhat.com/browse/ART-8110
Builder nvrs
- [openshift-golang-builder-container-v1.16.12-202310311649.el7.g5db8891](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2759456)
- [openshift-golang-builder-container-v1.16.12-202310201409.el8.g1370b35](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2739965)

ART-8110 Bump golang for 4.9

---

images/cluster-nfd-operator.yml
images/kube-rbac-proxy.yml
images/node-feature-discovery.yml

OCPBUGS-21904 reports cluster-nfd-operator is disabled in 4.15 awaiting fixes. These changes have now been made and this PR re-enables building

revert #3722 'disable operators until fixed' due to fixing

---

releases.yml

trying out better mechanics for a pre-release :)
the `operator_index_mode: pre-release` will enable [re-building](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Folm_bundle/10262/console) the normal bundles (which we can use for initial stage push) with pre-release tags.

[ART-7994] ec.1 release: adjust to become an operator pre-release

---

group.yml

Reverts openshift-eng/ocp-build-data#3714

Revert "Disable early kernel tagging for 4.14"

---

group.yml

Reverts openshift-eng/ocp-build-data#3715

Revert "Disable early kernel tagging for 4.13"

---

images/clusterresourceoverride-operator.yml
images/clusterresourceoverride.yml

This reverts commit e94ff58c8b908c3f960d92c7ac5d1f4c7a4dfd0c.
CRO's manifests have been updated for 4.15, should be able to be safely re-enabled.

OCPBUGS-21942: Revert "[ART-7960] disable clusterresourceoverride until fixed"

---

images/vertical-pod-autoscaler-operator.yml
images/vertical-pod-autoscaler.yml

This reverts commit ffc98e62c4c89ad58ecbb0b8a606ca49a8b1ac87.
VPA's manifests have been updated for 4.15, should be able to be safely re-enabled.

OCPBUGS-21944: Revert "[ART-7960] disable vertical-pod-autoscaler-operator until fixed"

---

images/ose-aws-ebs-csi-driver-operator.yml

OCP storage team is merging all CSI driver operators into a single repo, github.com/openshift/csi-operator.
AWS EBS CSI driver operator is the first one. All code is already in https://github.com/openshift/csi-operator + there is Dockerfile.aws-ebs there.
The resulting image has the same binary as before, just built from a different source repo. No image is renamed.
Details: https://github.com/openshift/enhancements/blob/master/enhancements/storage/csi-driver-operator-merge.md#building-and-shipping-the-operators
Explicitly, we keep WORKDIR of the new  [Dockerfile.aws-ebs](https://github.com/openshift/csi-operator/blob/5cc6a6b66ff3b773996ee68adc948e14377fff2c/Dockerfile.aws-ebs#L2)  the same as the old  [Dockerfile.rhel7](https://github.com/openshift/aws-ebs-csi-driver-operator/blob/9f6f8a0 …

Move aws-ebs-csi-driver-operator from its own repo to csi-operator

---

group.yml

fulfill https://issues.redhat.com/browse/MCO-392

[ART-4932] group.yml: remove machine-os-content

---

erratatool.yml

along with https://github.com/openshift-eng/art-tools/pull/167 this enables elliott to create these advisories in 4.15
used to create https://errata.devel.redhat.com/advisory/123948

[ART-8113][4.15] enable prerelease/advance/bootimage advisories

---

releases.yml

to be filled with prepare-release (although it doesn't know about `prerelease` advisories yet so I created that manually - https://github.com/openshift-eng/art-tools/pull/167)

[4.15-ec.2] manually include advisories w/ prerelease

---

images/cluster-nfd-operator.yml
images/clusterresourceoverride-operator.yml
images/clusterresourceoverride.yml
images/csi-livenessprobe.yml
images/csi-node-driver-registrar.yml
images/ib-sriov-cni.yml
images/kube-rbac-proxy.yml
images/local-storage-diskmaker.yml
images/local-storage-operator.yml
images/nmstate-console-plugin.yml
images/node-feature-discovery.yml
images/ose-aws-efs-csi-driver-operator.yml
images/ose-aws-efs-csi-driver.yml
images/ptp-operator.yml
images/sriov-dp-admission-controller.yml
images/sriov-network-config-daemon.yml
images/sriov-network-device-plugin.yml
images/sriov-network-operator.yml
images/sriov-network-webhook.yml
images/vertical-pod-autoscaler-operator.yml
images/vertical-pod-autoscaler.yml

Found operators
```
(venv) asdas@asdas-thinkpadp1gen3:~/PycharmProjects/ocp-build-data$ grep -l update-csv images/*
images/cluster-nfd-operator.yml
images/clusterresourceoverride-operator.yml
images/dpu-network-operator.yml
images/ingress-node-firewall-operator.yml
images/local-storage-operator.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-aws-efs-csi-driver-operator.yml
images/ose-cluster-kube-descheduler-operator.yml
images/ose-gcp-filestore-csi-driver-operator.yml
images/ose-metallb-operator.yml
images/ose-secrets-store-csi-driver-operator.yml
images/ptp-operator.yml
images/sriov-network-operator.yml
images/vertical-pod-autoscaler-operator.yml
```
Added `name_in_bundle` to ones that were missing
Opreators: https://github.com/openshift-eng/ocp-build-data/pull/3881/commi …

Explicitly mention name_in_bundle for operators and operands

---

group.yml

This reverts commit 840fb811b101eff09d0be911fc6fe2861b66c45a.
We can attempt again later when upstream dependencies have cleared up.

Revert "[ART-4932] group.yml: remove machine-os-content"

---

group.yml
images/sriov-network-operator.yml

Following https://github.com/openshift-eng/art-tools/pull/141
We have granular control on how this feature is activated.
- [Image metadata level](https://github.com/openshift-eng/art-tools/blob/22dc7ad1f3ee331acaf1bb08f818d97d6ba13a78/doozer/doozerlib/cli/scan_osh.py#L181)
- [group.yaml level](https://github.com/openshift-eng/art-tools/blob/22dc7ad1f3ee331acaf1bb08f818d97d6ba13a78/doozer/doozerlib/cli/scan_osh.py#L521) 
_Requesting /lgtm only_

[ART-7926] Activate sast scanning bugs pipeline for 4.15 sriov

---

images/ose-baremetal-cluster-api-controllers.yml

The image is bumped to rhel9 but the payload name doesn't have the suffix in upstream

Set payload_name baremetal-cluster-api-controllers

---

group.yml
images/openshift-golang-builder.Dockerfile
images/openshift-golang-builder.yml

- [ART-8111](https://issues.redhat.com/browse/ART-8111)
- [golang-1.21.3-5.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2770477)
- https://brew-task-repos.engineering.redhat.com/repos/official/golang/1.21.3/5.el9/

ART-8111 Update rhel-9 golang-1.21 branch

---

group.yml

Reverts openshift-eng/ocp-build-data#3912
Should happen when 4.15-4.13 mass rebuilds are complete https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/

Revert "4.12 - Freeze automation until mass rebuilds are complete"

---

images/ci-openshift-golang-builder-previous.yml
images/ose-ovn-kubernetes.yml
streams.yml

Golang-1.19 should not be used anymore in 4.15. This removes all stanzas to keep the builds updated in CI. We missed to update ovn to 1.20. This is already updated in upstream CI.

4.15: Remove golang-1.19

---

erratatool.yml

Version(s):
4.14
Issue:
[OSDOCS-8825](https://issues.redhat.com/browse/OSDOCS-8825)
Updates broken URL in Product Description and inserts version numbering as applicable.

OSDOCS-8829: fix url in microshift 4.14 errata text

---

images/monitoring-plugin.yml
images/ose-azure-workload-identity-webhook.yml
images/ose-cluster-olm-operator.yml
images/ose-libvirt-machine-controllers.yml

[monitoring-plugin](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=57235742)
```
ENV NGINX_VERSION=1.20
RUN yum -y module enable nginx:$NGINX_VERSION  &&     INSTALL_PKGS="nginx"  &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS
Error: Problems in request:
missing groups or modules: nginx:1.20
```
[azure-workload-identity-webook](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=57235741)
```
BuildError: package (container) ose-azure-workload-identity-webhook-container not in list for tag rhaos-4.15-rhel-9-candidate
```
[ose-cluster-olm-operator](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=57235731)
```
BuildError: package (container) ose-cluster-olm-operator-container not in list for tag rhaos-4.15-rhel-9-candidate
``` …

Revert 4 images to rhel8

---

images/ose-libvirt-machine-controllers.yml

The image build is looking to install genisoimage, which does not seem shipped in rhel9. Reverting to rhel8 for now.

Restore libvirt-machine-controllers to rhel8

---

images/ose-aws-ebs-csi-driver-operator.yml

We update openshift/csi-operator Dockerfile in
https://github.com/openshift/csi-operator/pull/69 to build the aws-ebs-csi-driver-operator directly from `/` and not from `/legacy/*`.
Reflect that change in the image metadata.

Remove cachito from AWS EBS CSI driver operator

---

images/ci-openshift-golang-builder-extra.yml
images/ci-openshift-golang-builder-latest.yml
images/ci-openshift-golang-builder-previous.yml

CI images right now are building whenever any commit lands on the branch,
since their Dockerfile resides on the branch. This leads to unecessary rebuilds 
since the branch is not specific to CI images and gets a lot of churn. 
We still want to build CI images when it's parent `stream:golang` updates.
`mode:disabled` also stops these images from appearing in sync-ci-images job
Good thing is `stream:golang` updates are infrequent, so we will not be out of
sync anytime soon.
https://issues.redhat.com/browse/ART-8364 is for discussing solutions to get 
around this. until then, stop building them

ART-8364 Stop building CI images

---

product.yml

This allows bugs like https://issues.redhat.com/browse/OCPBUGS-24076 to be routed automatically to the correct team.

Fixing typo in ose-gcp-cluster-api-controllers-container mapping

---

releases.yml

rhcos builds are failing, and the consistency requirement that dtk and rhcos have the same kernel build prevents us from creating nightlies.
This commit pins dtk to the build of the most recent nightly.
Note that nightly creation will fail again when rhcos builds succeed. Which is what we want, because then we will not forget to revert this.

Pin dtk until newer rhcos

---

releases.yml

Cherrypick of https://github.com/openshift-eng/ocp-build-data/pull/3967

4.11: Do not rebuild because of redhat-release 

---

rpms/microshift.yml
rpms/openshift-ansible.yml
rpms/openshift-clients.yml
rpms/openshift.yml
rpms/openshift4-aws-iso.yml

SAST pipeline looks at the `web` part to get the URL to display upstream commit.

Add web links to RPMs

---

product.yml

This should help bugs like https://issues.redhat.com/browse/OCPBUGS-24296 automatically be routed to the correct team.

openstack-cluster-api-controllers-container mapping

---

releases.yml

Since its already shipped live, we need to create a new one.

Do not reuse prerelease advisory

---

images/ose-apiserver-network-proxy.yml

This is to fix repeated 4.11 failures for [ose-apiserver-network-proxy-container](https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=81734)
`apiserver-network-proxy` is consuming 4.14 content that needs a newer golang builder than the one currently configured for 4.11. `etcd_golang` stream is already high enough, pointing at `openshift/golang-builder:v1.19.13-202310161907.el8.g0d095f7`. So instead of bumping the `golang` stream, we might just reuse that one only for `apiserver-network-proxy`.
Successful test build: [ose-apiserver-network-proxy-container-v4.11.0-202312041132.p0.g3362d67.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2805058)

Build apiserver-network-proxy on etcd_golang stream

---

streams.yml

Follow up to https://github.com/openshift-eng/ocp-build-data/pull/3937
This image built from the image that was removed in the above PR,
since we removed that, we should remove this too.

4.15 - Remove go-1.19 ci buildroot

---

group.yml

Until target version `4.16.0` is created

disable OCPBUGS pipeline feature for 4.16

---

images/baremetal-machine-controller.yml
images/ironic-agent.yml
images/ose-baremetal-operator.yml

This commit removes kni-devel ML, so we don't spam it with emails about failures. 
Remove shardy@redhat.com, since he left the company

[4.11] Remove some owners in ose-baremetal-operator, baremetal-machine-controller and ironic-agent

---

product.yml

Since ART builds
```
openshift-base-nodejs-container
openshift-base-rhel8-container
ci-openshift-golang-builder-extra-container
ci-openshift-golang-builder-latest-container
ci-openshift-golang-builder-previous-container
openshift-base-rhel9-container
openshift-enterprise-base-rhel9-container
```
adding them to `Release`
And adding `ose-aws-efs-utils-container` to `Storage` along with the other `ose-aws-efs-*`

[SAST] add missing product mappings

---

images/baremetal-machine-controller.yml
images/ose-baremetal-operator.yml

This commit removes kni-devel ML, so we don't spam it with emails. 
Remove shardy@redhat.com, since he left the company

[4.13] Remove some owners in ose-baremetal-operator and baremetal-machine-controller

---

releases.yml

Keeping the `operator_index_mode` as `pre-release` will add the `com.redhat.prerelease` which is needed by the pre-release advisory

ec.3 set operator index mode to pre-release

---

images/baremetal-machine-controller.yml
images/ose-baremetal-operator.yml

This commit removes kni-devel ML, so we don't spam it with emails about failures. Remove shardy@redhat.com, since he left the company

[4.16] Remove some owners in ose-baremetal-operator and baremetal-machine-controller

---

images/baremetal-machine-controller.yml
images/ose-baremetal-operator.yml

This commit removes kni-devel ML, so we don't spam it with emails about failures.
Remove shardy@redhat.com, since he left the company

[4.15] Remove some owners in ose-baremetal-operator and baremetal-machine-controller

---

group.yml

Respective teams have requested ART to exclude them from SAST workflow

[sast] exclude kernel and systemd

---

streams.yml

We currently have `canonical_builders_from_upstream: False` in group.yml. This means that the golang builders defined in ocp-build-data for images are taken, without consideration of what builder images are defined in upstream dockerfiles.
Recently, while adding the 1.21 golang, we made it the default. This means that the production builds made the change immediately.
To set `canonical_builders_from_upstream` to the value we'd expect at this phase of 4.16, is a bit risky. Image builds will potentially break for those images that made the switch to rhel9, but have not had that switch reflected through reconciliation PRs.
The proposal of this PR is:
- to restore the default golang builder to 1.20
- to work to get existing reconciliation prs merged, in order to switch …

4.16: Revert default golang to 1.20

---

group.yml

Disable temporarily so that we can phase out the deployment.

[4.14] [scan-osh] disable OCPBUGS workflow

---

group.yml

rhcos 4.16 pipeline is created now https://releases-rhcos-art.apps.ocp-virt.prod.psi.redhat.com/storage/prod/streams/4.16-9.2/builds/416.92.202312090309-0/x86_64/meta.json

ART-8170: Use 4.16-9.2 for 4.16

---

images/ose-secrets-store-csi-driver-operator.yml

ref https://github.com/openshift/secrets-store-csi-driver-operator/blob/release-4.16/config/manifests/preview/image-references#L6
failed build : https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/50427/

fix ose-secrets-store-csi-driver-operator reference

---

images/kube-rbac-proxy.yml
images/ose-olm-catalogd.yml
images/ose-olm-operator-controller.yml
images/ose-olm-rukpak.yml

`dependents` signifies that the dependent image needs to rebuild when this image changes. (This mechanism exists on top of rebuilding when a base image changes). This is useful for operators, as they need to get rebuilt with the updated image references. As olm is a payload image, and thwe images it depends on as well, there is no need to rebuild the olm image when an image this paylooad operator depends on, changes.

Remove olm image from any dependents

---

images/csi-livenessprobe.yml
images/csi-node-driver-registrar.yml
images/ose-secrets-store-csi-driver-operator.yml
images/ose-secrets-store-csi-driver.yml
images/ose-secrets-store-csi-mustgather.yml

Brew and product configuration is not yet ready for rhel9. Disabling the operator + operands for now, and configuring all to work for after the product bits are set up.

Disable secrets-store-csi-driver-operator

---

releases.yml

Reverts openshift-eng/ocp-build-data#4084
There is a good rhcos now. Unpinning.

Revert "Pin dtk to get nightlies"

---

releases.yml

Somehow, artifacts cannot be copied from terraform base container: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=57676532
Think path is correct, so looks like infra limitation (last layer is 2.7GB).
Pin installer* for now to allow for nightlies.

Pin old installer

---

images/marketplace-operator.yml
images/openshift-enterprise-deployer.yml
images/openshift-enterprise-haproxy-router.yml
images/openshift-enterprise-tests.yml
images/ose-agent-installer-api-server.yml
images/ose-agent-installer-csr-approver.yml
images/ose-aws-efs-csi-driver.yml
images/ose-baremetal-installer.yml
images/ose-cli-artifacts.yml
images/ose-csi-driver-shared-resource-mustgather.yml
images/ose-installer-artifacts.yml
images/ose-installer.yml
images/ose-machine-os-images.yml
images/ose-must-gather.yml
images/ose-network-tools.yml
images/ose-ovn-kubernetes.yml
images/ose-tools.yml
images/ovn-kubernetes-microshift.yml
images/ptp-operator-must-gather.yml

Since https://github.com/openshift-eng/art-tools/pull/246 merged and
config was merged to make use of it:
https://github.com/openshift-eng/ocp-build-data/pull/4080, there is a
circumstance that we did not account for.
Some base images are not synced by ART to their place in CI, but get
promoted there by CI builds themselves. A base image like `cli` does not
override their `"com.redhat.component"` label, so production builds
started to use the base image rather than the cli image with the newly
introduced logic.
This commit disables the "adhere to upstream" logic for images that have
a base image whose construction in CI is beyond ARTs control, pending a
real solution.

Exclude some member froms from upstream initiative

---

group.yml

Excluded ovs and ovn components for SAST scanning until the ticket solved: https://issues.redhat.com/browse/ART-8525

[sast] exclude ovs and ovn

---

group.yml
images/ose-agent-installer-utils.yml

Test build: [ose-agent-installer-utils-container-v4.14.0-202312191513.p0.gad85376.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2827703)

OCPBUGS-19685: Use RHEL 9 builder image for ose-agent-installer-utils

---

group.yml

This PR adds config options for Doozer to check external rpms (rpms tagged into rhaos but not owned by ART).
This config is to support https://github.com/openshift-eng/art-tools/pull/245

[ART-8416] Add check_external_packages config options - 4.16

---

group.yml

Now that `4.16.0` target version exists, activating for 4.16

[scan-osh] activate for 4.16

---

ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

Ref: https://github.com/kubernetes/kubernetes/blob/master/hack/lib/etcd.sh#L19
cc: @soltysh
/hold
Until openshift-4.16 branch is created !

OCPNODE-1887: Bump etcd version in accordance with k8s-v1.29

---

group.yml

Alongside https://github.com/openshift-eng/art-tools/pull/296
Should be cherry-picked to lower versions

[group.yml] remove operator index mode

---

images/ose-libvirt-machine-controllers.yml

Test build: [ose-libvirt-machine-controllers-container-v4.15.0-202401081251.p0.g1e096cd.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2840698)

ART-8476 Move ose-libvirt-machine-controllers to rhel9

---

images/ose-installer-terraform-providers.yml

...as promotion is handled by CI here: https://github.com/openshift/release/blob/2b1755b8cc5f722487506cc2755005c73040559c/ci-operator/config/openshift/installer/openshift-installer-master__terraform.yaml#L21-L26

installer-terraform-providers: Leave promotion in CI to CI

---

images/ose-baremetal-cluster-api-controllers.yml

Found this issue while running gen-assembly:
```
ERROR Unable to find ose-baremetal-cluster-api-controllers in releases despite it being marked as is_payload in ART metadata; this may mean the image does not have the proper labeling for being in the payload. Choosing what was in the estimated basis event sweep
```
Adding name  and description labels should fix it

Add missing labels to baremetalc-luster-api-provider

---

releases.yml

Prepare new prerelease advisory for `ec.1`
Need to rerun prepare release after merge.

prepare prerelease for ec.1

---

streams.yml

[openshift-golang-builder-container-v1.20.12-202401111603.el9.g0bebe58](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2845926)
[openshift-golang-builder-container-v1.20.12-202401111802.el8.g17c0aac](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2846059)

4.14 - Bump golang 1.20 to 1.20.12

---

streams.yml

https://issues.redhat.com/browse/ART-8632
[openshift-golang-builder-container-v1.20.12-202401111603.el9.g0bebe58](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2845926)
[openshift-golang-builder-container-v1.20.12-202401111802.el8.g17c0aac](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2846059)

ART-8632 4.15 - Bump golang 1.20 to 1.20.12

---

streams.yml

https://issues.redhat.com/browse/ART-8633
[openshift-golang-builder-container-v1.20.12-202401111603.el9.g0bebe58](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2845926)
[openshift-golang-builder-container-v1.20.12-202401111802.el8.g17c0aac](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2846059)

ART-8633 4.16 - Bump golang 1.20 to 1.20.12

---

group.yml

Reverts openshift-eng/ocp-build-data#4187
Merge when 4.15 and 4.14 mass rebuilds have completed 
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/

Revert "4.11 - Temporarily freeze automation to delay mass rebuild"

---

group.yml

Reverts openshift-eng/ocp-build-data#4188
Merge when 4.15 and 4.14 mass rebuilds have completed 
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/

Revert "4.12 - Temporarily freeze automation to delay mass rebuild"

---

images/operator-lifecycle-manager.yml

- remove `envs` because this is [set upstream](https://github.com/openshift/operator-framework-olm/blob/master/operator-lifecycle-manager.Dockerfile#L9)
- Remove "Don't listen to upstream" because 4.16 has rhel9 base images
- Use golang-1.21.

olm: base image fixes

---

images/ose-azure-disk-csi-driver-operator.yml

The ART bot is fighting with itself to reconcile .ci-operator.yaml in the csi-operator repo:
https://github.com/openshift/csi-operator/pull/114
https://github.com/openshift/csi-operator/pull/115
This is because aws-ebs-csi-driver-operator uses rhel-9 while azure-disk-csi-driver-operator uses rhel-8. This PR bumps azure-disk-csi-driver-operator to rhel-9 so they'll be consistent.
/cc @openshift/storage

bump ose-azure-disk-csi-driver-operator to rhel-9 images

---

erratatool.yml

We want prerelease advisories to be automatically pushed once they are set to `push_ready` by QEs
Only "advance" operator advisory need to be pushed in 2 stages (1 week before ga and at ga)
in coordination with SP, so keep it to "rhose async"
ref: https://art-docs.engineering.redhat.com/release/4.y-ga/#update-advisory-release-type-and-remove-dependencies

4.15 - Set prerelease advisory release back to rhose async auto

---

bug.yml

Start looking at 4.15.z bugs too. It is available in jira - sometimes devs will use this target version
We don't want to miss these bugs iff they are fixed in GA

Add 4.15 z target release

---

images/openshift-golang-builder.Dockerfile

krb5-devel library required to build oc

Add krb5-devel to RHEL9 golang 1.21 image

---

.github/workflows/validate.yaml

Sample [run](https://github.com/openshift-eng/ocp-build-data/actions/runs/7631535191/job/20789690813?pr=4236)
Need to be cherry picked to all `openshift-4.*` branches

Migrate ocp-build-data-validator to art-tools

---

images/baremetal-runtimecfg.yml

Ref [ART-8476](https://issues.redhat.com/browse/ART-8476)
Define `alternative_upstream` config stanza for `baremetal-runtimecfg`.

[4.16] Define alternative config

---

ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

RHEL released a new version of git (https://access.redhat.com/errata/RHSA-2024:0407)
which disables a feature called safe.directory. CI uses this feature to allow git interactions by non-root users in CI: https://github.com/openshift/ci-tools/blob/acad25edd747d5a21c839c60d480aaf7902961ec/pkg/steps/pod.go#L241 . This caused failures in many CI builds. We need a new workaround in CI before we can unpinned older versions of git that still have the safe.directory feature.

Pin versions of git being used by CI in buildroot images

---

images/egress-router-cni.yml
images/multus-cni.yml
images/ose-containernetworking-plugins.yml
images/ose-machine-config-operator.yml
images/ose-multus-route-override-cni.yml
images/ose-multus-whereabouts-ipam-cni.yml
images/ose-network-interface-bond-cni.yml

for rhel8 builds that build with el8 and el9 golang, migrate them to rhel9 but leave rhel8 config in place to match upstream until they get the PR and make the move. (like https://github.com/openshift-eng/ocp-build-data/pull/4237/)
can merge on lgtm

[ART-8358][4.16] alignment for multi-builder migration to rhel9

---

images/ovn-kubernetes-microshift.yml

`ovn` started using golang-1.21 with https://github.com/openshift/ovn-kubernetes/pull/2027/, and this confuses our bot that wants to downgrade it to 1.20
Test build: [ovn-kubernetes-microshift-container-v4.16.0-202401291455.p0.ge8f87e8.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2875855)

Bump ovn-kubernetes to golang-1.21

---

images/ose-machine-config-operator.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/4276/files#diff-64c70eca940106602f26735a4ad5b1f427ba8b1faa66dbaf06516fabcddccf00

[4.16] Fix alternative config payload name for machine-config-operator

---

images/ose-cli-artifacts.yml

This PR adds `rhel-9-golang` stream in oc 4.15 just like we did it for 4.16 in https://github.com/openshift-eng/ocp-build-data/pull/4046

Add rhel-9-golang stream for oc 4.15

---

images/ose-cli-artifacts.yml

Because of upstream mismatch https://github.com/openshift/oc/blob/release-4.15/images/cli-artifacts/Dockerfile.rhel

Revert "Add rhel-9-golang stream for oc 4.15"

---

images/ose-machine-config-operator.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/4324

[4.16] re-enable canonical builders for machine-config-operator

---

group.yml

due to the last z-stream (for 4.11.z) produced: **4.11.58** 
we don't need anymore the 4.11.z build on weekdays

4.11 stream builds not on weekdays

---

images/ptp-operator.yml

rhel8 stream was defined incorrectly.

Fix ptp-operator stream

---

releases.yml

Since `operator_index_mode: pre-release` was missing in assembly config bundles were rebuilt without the prerelease tag

Fix 4.15 rc.5 prerelease

---

group.yml

Since RHEL 9.3, kernel-rt is merged into the kernel package.

Remove kernel-rt from require_consistency

---

images/marketplace-operator.yml
images/oauth-server.yml
images/openshift-enterprise-keepalived-ipfailover.yml
images/ose-cluster-config-operator.yml
images/ose-cluster-openshift-controller-manager-operator.yml
images/ose-kubevirt-cloud-controller-manager.yml
images/ose-openshift-controller-manager.yml
images/ose-service-ca-operator.yml
images/telemeter.yml

For those images that haven't made the move to rhel9 yet, we are currently disabling canonical_builders unless we define an `alternative_upstream` config stanza that accounts for the el version switch. Adding these stanzas for all images (except one that is disabled) and enabling canonical builders yet

[4.16] Define alternative_upstream configs

---

images/openshift-base-nodejs.yml
images/openshift-base-rhel8.yml
images/openshift-base-rhel9.yml

For these components, ocp4-scan uselessly tries to determine the "upstream" intended rhel version. This means useless operations (running `oc` against non-sense pullspecs) and ugly error messages that go like this: `error: source image must point to an image ID or image tag`, see for example [here](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4_scan/626428/consoleFull)
Let's just disable canonical builders for these images.

Disable canonical builders for ART images

---

images/openshift-enterprise-egress-dns-proxy.yml

Upstream moved to rhel9: https://github.com/openshift/images/commit/3d1e257555d26747af503ebb88b6381a7a8846a8

[4.16] Bump egress-dns-proxy to rhel9

---

images/openshift-enterprise-tests.yml

Needed after https://github.com/openshift/origin/pull/28587
Test build: [openshift-enterprise-tests-container-v4.16.0-202402161704.p0.g7812f3c.assembly.test.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2913929)

[4.16] build enterprise-tests with  golang 1.21

---

images/telemeter.yml

Upstream moved to rhel9, canonical builders can be re-enabled without regressions

[4.16] re-enable canonical builders for telemeter

---

images/azure-file-csi-driver.yml

Reverts #4413 ; tracked by [TRT-1523](https://issues.redhat.com//browse/TRT-1523)
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
All azure jobs broke after this merged
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
Verify azure payload jobs succeed
```
CC: @locriandev
<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>

TRT-1523: Revert #4413 "Switch azure-file to csi-operator"

---

ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

This matches:
* https://github.com/kubernetes/kubernetes/blob/release-1.28/hack/lib/etcd.sh#L19
/assign @soltysh @jupierce

Update etcd to match k8s 1.28

---

images/ose-ibm-cloud-controller-manager.yml

The component is again failing to build using cachito: [logs](https://download.eng.bos.redhat.com/brewroot/work/tasks/7279/59167279/osbs-build.log)

[4.16] disable cachito processing for ibm-cloud-controller-manager

---

images/csi-livenessprobe.yml
images/csi-node-driver-registrar.yml
images/ose-secrets-store-csi-driver-operator.yml
images/ose-secrets-store-csi-driver.yml
images/ose-secrets-store-csi-mustgather.yml

The secrets-store image builds were disabled in https://github.com/openshift-eng/ocp-build-data/pull/4071 and this PR attempts to move all 3 images to rhel9 and re-enable the builds for 4.16.
/hold
Depends on:
https://github.com/openshift/secrets-store-csi-driver/pull/14
https://github.com/openshift/secrets-store-csi-driver-operator/pull/45
/cc @openshift/storage @joepvd

Enable secrets-store-csi-driver and operator and move to rhel9

---

images/csi-livenessprobe.yml
images/csi-node-driver-registrar.yml
images/csi-provisioner.yml
images/ose-csi-external-resizer.yml
images/ose-gcp-filestore-csi-driver.yml

Reverts openshift-eng/ocp-build-data#4449
Looks like it's working: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/42024/consoleFull has `viable: true`

Revert "Revert "Move extra storage images to rhel9""

---

images/csi-livenessprobe.yml

File "/mnt/workspace/jenkins/working/aos-cd-builds/build%2Focp4/art-tools/doozer/doozerlib/image.py", line 494, in <setcomp>
referred_streams = {builder.get("stream") for builder in builders if builder.get("stream")}
AttributeError: 'str' object has no attribute 'get'
2024-02-29 18:18:33,744 ERROR [containers/csi-livenessprobe] 'str' object has no attribute 'get'

Fix stream definition

---

streams.yml

https://issues.redhat.com/browse/ART-8972
- [openshift-golang-builder-container-v1.21.7-202403061535.el8.g1ac3e39.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2943572)
- [openshift-golang-builder-container-v1.21.7-202403061534.el9.gab74a9a.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2943571)

ART-8972 Bump builders to 1.21.7

---

images/nmstate-console-plugin.yml

`nmstate-console-plugin` is using the bare `nodejs` stream; it should use the `openshift-base-nodejs` member base image just like the console does.
Test build: [nmstate-console-plugin-container-v4.16.0-202403111057.p0.gd607541.assembly.test.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2950177)

[4.16] use member base image for nmstate-console-plugin

---

images/monitoring-plugin.yml

Green [build](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2963459)
Similar to https://github.com/openshift-eng/ocp-build-data/pull/4496

[ART-8355] monitoring-plugin use openshift-base-nodejs instead

---

images/openshift-enterprise-cluster-capacity.yml
images/openshift-enterprise-egress-router.yml
images/openshift-enterprise-helm-operator.yml
images/openshift-enterprise-operator-sdk.yml
images/openstack-cluster-api-controllers.yml
images/ose-agent-installer-orchestrator.yml
images/ose-aws-efs-utils.yml
images/ose-azure-workload-identity-webhook.yml
images/ose-cloud-credential-operator.yml
images/ose-cloud-network-config-controller.yml
images/ose-cluster-olm-operator.yml
images/ose-egress-http-proxy.yml
images/ose-kube-metrics-server.yml
images/ose-kubevirt-csi-driver-rhel8.yml
images/ose-olm-catalogd.yml
images/ose-olm-operator-controller.yml
images/ose-olm-rukpak.yml
images/ose-route-controller-manager.yml

Ref ticket: https://issues.redhat.com/browse/ART-9189
All images except ose-olm-operator-controller [succeeded](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/236/)
ose-olm-operator-controller issue fixed by https://github.com/openshift-eng/ocp-build-data/pull/4535, green build [here](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2966003).

[ART-9189] alternative_upstream suggest move to rhel9

---

streams.yml

https://issues.redhat.com/browse/ART-9185
[openshift-golang-builder-container-v1.20.12-202403212137.el9.g144a3f8.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2966777)
[openshift-golang-builder-container-v1.20.12-202403212140.el8.g2983c24.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2966778)

ART-9185 4.15 - Bump builders to latest 1.20.12

---

images/oc-mirror-plugin.yml

After https://github.com/openshift/oc-mirror/pull/804 got in, production
build configuration followed up with https://github.com/openshift-eng/ocp-build-data/pull/4475.
This was incomplete, as the change to the final layer was not reflected
in this configuration update.
This PR sets rhel layers as upstream expects, and ensures ENTRYPOINT
does not run into a linking error.

Fix rhel layers oc-mirror-plugin

---

streams.yml

Same as 4.15 bump: https://github.com/openshift-eng/ocp-build-data/pull/4539

ART-9185 4.14 - Bump builders to latest 1.20.12

---

images/ose-ovn-kubernetes.yml

align with https://github.com/openshift/ovn-kubernetes/commit/2f51c186ff5adcdf4fe4f94486469af6b67b598d

remove rhel8 golang in ose-ovn-kubernetes

---

releases.yml

This is to satisfy assembly issue:
```
rhcos:
- code: CONFLICTING_INHERITED_DEPENDENCY
msg: Expected cri-o-1.28.4-7.rhaos4.15.git14784b2.el9 to be installed in RHCOS
build 415.92.202403191241-0 (x86_64) but found cri-o-1.28.4-5.rhaos4.15.git159b3c8.el9
permitted: false
- code: CONFLICTING_INHERITED_DEPENDENCY
msg: Expected cri-o-1.28.4-7.rhaos4.15.git14784b2.el9 to be installed in RHCOS
build 415.92.202403191241-0 (ppc64le) but found cri-o-1.28.4-5.rhaos4.15.git159b3c8.el9
permitted: false
- code: CONFLICTING_INHERITED_DEPENDENCY
msg: Expected cri-o-1.28.4-7.rhaos4.15.git14784b2.el9 to be installed in RHCOS
build 415.92.202403191241-0 (s390x) but found cri-o-1.28.4-5.rhaos4.15.git159b3c8.el9
permitted: false
- code: CONFLICTING_INHERITED_DEPENDENCY
msg: Expected …
```

4.15.5 pin rpms

---

group.yml

As of Mar 28, 2024, RHEL has a newer version of conmon:
```
- code: CONFLICTING_INHERITED_DEPENDENCY
msg: Expected image to contain assembly override dependencies NVR conmon-2.1.2-5.2.rhaos4.12.el8
but found conmon-2.1.4-1.module+el8.6.0+21266+3e24c7b3 installed
permitted: false
```

check_external_packages: change to greater_equal for conmon

---

releases.yml

backported bugs OCPBUGS-31129 and OCPBUGS-31374 are ready despite and OCPBUGS-30190  not being ready in 4.16

4.15.6: Add ATTACHED_BUGS promotion permit

---

product.yml

This should go to the more specific `Cloud Compute / OpenStack Provider` component rather than `Cloud Compute / Other Provider`.

Fix component for openstack-cluster-api-controllers-container

---

releases.yml

Image didn't exist at nightly time and is breaking prepare-release

[4.16] Pin networking-console-plugin build to ec5

---

images/ose-baremetal-installer.yml

This is the only installer image that is dynamically built, so it needs to build the terraform providers as well since the terraform-providers image contains statically linked binaries.
/hold
for https://github.com/openshift/installer/pull/8215

ose-baremetal-installer does not depend on terraform-providers

---

images/ose-aws-efs-utils.yml

Currently, 4.16 build-sync is complaining because
```
image "registry.ci.openshift.org/ocp/4.16:aws-efs-utils-base-rhel9" not found: manifest unknown: manifest unknown
```
In fact, 
```
$ oc get istag | grep 4.16:aws-efs-utils-base | cut -d " " -f 1 | sort --unique
4.16:aws-efs-utils-base
```
so that imagestream tag never existed. This happened because:
1. [this change](https://github.com/openshift-eng/ocp-build-data/pull/4544/files#diff-5d61cb477dc5f256d5d951c468df930e26ae239fc8be9e17f4eef18120801854R36) added the `alternative_upstream` config, where the image was named `openshift/ose-aws-efs-utils-base` (just like it is in all other branches. In the main config, it started having the `-rhel9` suffix
2. [this change](https://github.com/openshift-eng/ocp-build-data/commit/fcf3db9a94bd157b7 …

Fix aws-efs-utils-base name

---

bug.yml

LCA operator is built in CPaaS, so exclude it from ART operations.
example bug: https://issues.redhat.com/browse/OCPBUGS-31374
ref: https://redhat-internal.slack.com/archives/CB95J6R4N/p1712846278042069?thread_ts=1712844263.382109&cid=CB95J6R4N

4.15 - Exclude LCA operator jira component

---

streams.yml

Builds:
rhel8: [openshift-golang-builder-container-v1.20.12-202404151507.g92d4921.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3004037)
rhel9: [openshift-golang-builder-container-v1.20.12-202404151445.g5488123.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3003949)

[ART-9397] 4.15 golang bump

---

streams.yml

Builds:
rhel8: [openshift-golang-builder-container-v1.20.12-202404151507.g92d4921.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3004037)
rhel9: [openshift-golang-builder-container-v1.20.12-202404151445.g5488123.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3003949)

[ART-9397] 4.14 golang bump

---

streams.yml

Builds:
rhel8: [openshift-golang-builder-container-v1.19.13-202404160928.gfa00de2.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3005887)
rhel9: [openshift-golang-builder-container-v1.19.13-202404160932.g3172d57.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3005938)

[ART-9397] 4.13 golang bump

---

streams.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/4671
rhel8: [openshift-golang-builder-container-v1.19.13-202404160928.gfa00de2.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3005887)
rhel9: [openshift-golang-builder-container-v1.19.13-202404160932.g3172d57.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3005938)

4.16 v1.19.13 golang bump

---

streams.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/4671
rhel8: [openshift-golang-builder-container-v1.19.13-202404160928.gfa00de2.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3005887)
rhel9: [openshift-golang-builder-container-v1.19.13-202404160932.g3172d57.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3005938)

4.14 v1.19.13 golang bump

---

streams.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/4671
rhel8: [openshift-golang-builder-container-v1.19.13-202404160928.gfa00de2.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3005887)
rhel9: [openshift-golang-builder-container-v1.19.13-202404160932.g3172d57.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3005938)

4.15 v1.19.13 golang bump

---

streams.yml

Builds:
rhel8: [openshift-golang-builder-container-v1.21.9-202404181433.g1ac3e39.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3010854)
rhel9: [openshift-golang-builder-container-v1.21.9-202404181431.gab74a9a.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3010856)

[ART-9397] 4.16 golang bump

---

rpms/openshift-clients.yml

There is a weird build error for openshift-clients on golang-1.22. Disabling for now.

no openshift-clients

---

streams.yml

Looks like the earlier one didn't have the correct module build
Builder: [openshift-golang-builder-container-v1.21.9-202404231038.g1ac3e39.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3019534)

4.16 golang bump v1.21.9

---

images/openshift-enterprise-tests.yml

Reverts openshift-eng/ocp-build-data#4717
To be merged when https://github.com/openshift/origin/pull/28733 lands

Revert "Fix tests"

---

images/openshift-enterprise-tests.yml

Reverts openshift-eng/ocp-build-data#4718
To be merged when https://github.com/openshift/origin/pull/28733 lands

Revert "[openshift-4.16] Fix tests"

---

images/ose-installer-altinfra.yml

This is needed to enable capi providers in the release.
Depends on https://github.com/openshift/installer/pull/8309

CORS-3250: installer: add etcd/kas to altinfra image.

---

releases.yml

Tested with:
```
elliott --data-path=/home/dpaolell/develop/github.com/openshift/ocp-build-data --group=openshift-4.16 --assembly ec.6 find-builds --kind=image --payload
```
and
```
elliott --data-path=/home/dpaolell/develop/github.com/openshift/ocp-build-data --group=openshift-4.16 --assembly ec.6 find-builds --kind=image --non-payload
```

[4.16.0-ec.6] pin NVRs for components that did not exist at nightly time

---

images/ose-smb-csi-driver-operator.yml

[operator-valid-subscriptions-bundle-image](http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/ose-smb-csi-driver-operator-bundle-container-v4.16.0.202404231239.p0.g097858b.assembly.stream.el9-8/58bb1ba2-d3dd-48d0-b6a7-06f5ab0dd44d/operator-valid-subscriptions-bundle-image-output.txt) failed with:
```
[INVALID] 'openshift4/ose-smb-csi-driver-operator-bundle' subscription type: OCP and up
-> The annotation must contain: 'OpenShift Container Platform', 'OpenShift Platform Plus', but not contain: 'OpenShift Kubernetes Engine'
```
/cc @ashwindasr @mpatlasov @joepvd
/cherrypick openshift-4.17

smb-csi-driver-operator: fix valid-subscription-label

---

images/ose-baremetal-installer.yml
images/ose-installer-altinfra.yml
images/ose-installer-artifacts.yml
images/ose-installer.yml

This is the last step needed before we can enable capi and capi providers in the release image.

CORS-3191: installer: add kas/etcd deps to images

---

erratatool.yml

`find-builds --attach` fails because it tries to enable non existent cdn repos to advisory
Related: https://github.com/openshift-eng/art-tools/pull/634
Test:
```
curl -sSL --negotiate --user : "https://errata.devel.redhat.com/api/v1/cdn_repos?filter
\[name\]=rhocp-4_DOT_16-for-rhel-8-x86_64-rpms" | jq
```
Request to create https://issues.redhat.com/browse/CLOUDDST-22780

Comment out cdn repos that don't exist

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile

Brew builds of ci-build-root rhel8 images are failing the content set check of brew, as the package less is different between the arches. This is because less gets removed from some of the arches when git gets installed. Reinstalling git pulls in the current less on arches where it was removed, whereas it remains the old one where there was no removal.
This change instructs dnf to not be smart and remove perceived dependencies.

Fix ci-build-root build failures

---

ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-8/golang/Dockerfile

This was already done in https://issues.redhat.com/browse/ART-7963 for RHEL9.

Silence RHEL8 builders in CI

---

releases.yml

Fixes error
```
Bundle ose-smb-csi-driver-operator-bundle-container-v4.16.0.202405110441.p0.ga82a211.assembly.stream.el9-2 reference ose-smb-csi-driver-container-v4.16.0-202405110441.p0.gff97707.assembly.stream.el9:
needs CDN repo 'openshift4/ose-smb-csi-driver-container-rhel9' but advisory only has {'openshift4/ose-smb-csi-driver-rhel9'}
```
Newer build had the correct `name`

[rc.2] fix ose-smb-csi-driver-operator bundle error

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile

go install was creating /go/bin in the build root image. This was directory was only writeable by root. CI builds install tools as well, running as non-root, so it is necessary for them to be able to write to this directory structure.

Make /go writeable in ci-build-root

---

group.yml
images/dpu-network-operator.yml
images/egress-router-cni.yml
images/ib-sriov-cni.yml
images/monitoring-plugin.yml
images/multus-cni.yml
images/networking-console-plugin.yml
images/oc-mirror-plugin.yml
images/openshift-enterprise-ansible-operator.yml
images/ose-cli-artifacts.yml
images/ose-cloud-credential-operator.yml
images/ose-containernetworking-plugins.yml
images/ose-etcd.yml
images/ose-installer-etcd-artifacts.yml
images/ose-machine-config-operator.yml
images/ose-multus-route-override-cni.yml
images/ose-multus-whereabouts-ipam-cni.yml
images/ose-network-interface-bond-cni.yml
images/ose-ovn-kubernetes.yml
images/ose-sdn.yml
images/ptp-operator.yml
images/sriov-cni.yml
streams.yml

This commit proposes to change the default golang to 1.22. The rhel8
golangs have been given a new name to include their rhel version.
Disable cachito because cachito does not do 1.22
Until https://issues.redhat.com/browse/STONEBLD-2206 is resolved,
cachito will not work for repositories with `1.22` in `go.mod`. As part
of the move to 1.22:
- disabling cachito processing globally
- enabling it for images that use REMOTE_SOURCES in their Dockerfile
- do not suggest to move to 1.22 for images that have their golang deps not
vendored

4.17 to golang 1.22

---

images/baremetal-machine-controller.yml
images/ose-olm-operator-controller.yml

Upstream bumped to golang 1.22 and this is breaking cachito

[4.17] disable cachito for images using 1.22

---

streams.yml

Both of these are being sync'd via the 4.17 branch now

Remove temporary 4.17 streams from 4.16

---

product.yml

TALO bugs go here
This is based on the following query:
https://issues.redhat.com/browse/OCPBUGS-7396?jql=project%20%3D%20OCPBUGS%20and%20text%20~%20talo
Most of the ZTP Jiras moved to GitOps ZTP:
https://issues.redhat.com/browse/OCPBUGS-22675?jql=project%20%3D%20OCPBUGS%20and%20text%20~%20ztp-site-generate-container%20and%20labels%20in%20(Security)

Fixing two Telco component mappings

---

images/ose-multus-route-override-cni.yml

For OKD builds, this is necessary to ensure uuidgen is available.

Have route-override image use standard enterprise base

---

images/cluster-version-operator.yml

Reverts openshift-eng/ocp-build-data#4966
This is ineffective. As long as `canonical_builders_from_upstream: True` is set in `group.yml`, we'll listen for the desired golang version of upstream. https://github.com/openshift/cluster-version-operator/pull/1055 made the actual switch back.

Revert "Move cvo to rhel-9-golang-1.21"

---

releases.yml

OCPBUGS-35706
- https://github.com/openshift/installer/pull/8622 , merge commit: 0dc3033
- ose-installer-terraform-providers-container-v4.16.0-202406180107.p0.g0dc3033.assembly.stream.el9
- ose-installer-artifacts-container-v4.16.0-202406180107.p0.g0dc3033.assembly.stream.el9
- ose-installer-container-v4.16.0-202406180107.p0.g0dc3033.assembly.stream.el9
- ose-baremetal-installer-container-v4.16.0-202406180107.p0.g0dc3033.assembly.stream.el9
- ose-installer-altinfra-container-v4.16.0-202406180107.p0.g0dc3033.assembly.stream.el9
- ose-machine-os-images-container-v4.16.0-202406180107.p0.g3cc9709.assembly.stream.el9
OCPBUGS-35291
- https://github.com/openshift/kubernetes/pull/1989, merge commit 29c95f3
- openshift-enterprise-hyperkube-container-v4.16.0-202406170957.p0.g29c95f3.assembly.stream. …

4.16 - Define rc.6 assembly

---

group.yml

Reverts openshift-eng/ocp-build-data#4974
Possibly due to [RHELCOUNCL-91](https://issues.redhat.com/browse/RHELCOUNCL-91) not being fully implemented, this change has broken [openshift-base-rhel8 builds](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=62042563) because
```
Comparison mismatch for component libnghttp2:
aarch64: libnghttp2-1.33.0-4.el8_6.1 (199e2f91fd431d51)
ppc64le: libnghttp2-1.33.0-4.el8_6.2 (199e2f91fd431d51)
s390x: libnghttp2-1.33.0-4.el8_6.1 (199e2f91fd431d51)
x86_64: libnghttp2-1.33.0-4.el8_6.2 (199e2f91fd431d51)
```
Looking at https://pub.devel.redhat.com/pub/task/769592/log/stdout.log, there is no mention to s390x or aarch64 builds being pushed. Reverting for now as `4.12.60` is due to be prepared on June 20.

Revert "ART-9931 Move 4.12 RHEL 8.6 to E4S"

---

images/ose-nutanix-cloud-controller-manager.yml

Our automation on this repository expects commits prefixed by `commit_prefix: "UPSTREAM: <carry>: "` as it is a fork of an upstream repo

Nutanix CCM should use commit prefix

---

group.yml
streams.yml

- use `ubi8` base image instead of `ELS`
- use standard rhel8 repos instead of `EUS`

ART-9391 [4.15] Update to ubi8 repos and base images

---

releases.yml

Same as rc.6 except:
- Added upgrade edges `4.15.19` and `4.16.0-rc.6`
- Attached ovn bug and build

rc.7 assembly

---

releases.yml

Due to a gap in build-sync, the automation did not detect that the new children images should be present. Manually pinning them

rc.8 assembly

---

releases.yml

Pin fix for https://issues.redhat.com/browse/OCPBUGS-35992
https://github.com/openshift/machine-config-operator/pull/4427
[ose-machine-config-operator-container-v4.16.0-202406241749.p0.g9e4a1f5.assembly.stream.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3130897)

Define 4.16 rc.9 assembly

---

releases.yml

Edges `4.15.19`, and `4.16.0-rc.8` excluded

prep 4.16.0 GA assembly

---

streams.yml

Builder: [openshift-golang-builder-container-v1.22.4-202406271838.g4c8b32d.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3138669)

[ART-10029] bump rhel-9 golang to 1.22.4

---

group.yml
images/openshift-enterprise-console.yml

alongside https://github.com/openshift-eng/ocp-build-data/pull/5021

[ART-9503] [4.11] replace repo URLs with the new ocp-artifacts host

---

erratatool.yml

Version(s):
4.16
Issue:
[OSDOCS-11155](https://issues.redhat.com/browse/OSDOCS-11155)
Details: The solution text for the 4.16.z Errata did not update. This PR updates the version to 4.16 in the solution field for MicroShift.

OSDOCS-11155: updates solution text to 4.16 for MicroShift

---

streams.yml

Build: [golang-1.22.4-2.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3138766)
Builder: [openshift-golang-builder-container-v1.22.4-202407012208.g4c8b32d.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3146058)
Fixes issue on CI. See [thread](https://redhat-internal.slack.com/archives/C01CQA76KMX/p1719867853687099)

[4.17] [ART-10029] bump golang to 1.22.4-2

---

images/coredns.yml
images/csi-attacher.yml
images/csi-livenessprobe.yml
images/openshift-enterprise-ansible-operator.yml
images/openshift-enterprise-cluster-capacity.yml
images/openshift-enterprise-console-operator.yml
images/openshift-enterprise-registry.yml
images/ose-aws-pod-identity-webhook.yml
images/ose-cluster-config-api.yml
images/ose-cluster-config-operator.yml
images/ose-cluster-csi-snapshot-controller-operator.yml
images/ose-cluster-kube-apiserver-operator.yml
images/ose-cluster-kube-controller-manager-operator.yml
images/ose-cluster-kube-scheduler-operator.yml
images/ose-must-gather.yml
images/ose-oauth-apiserver.yml
images/ptp-operator-must-gather.yml
images/ptp-operator.yml
images/sriov-dp-admission-controller.yml
images/sriov-network-config-daemon.yml
images/sriov-network-device-plugin.yml
images/sriov-network-operator.yml
images/sriov-network-webhook.yml

In this pass, covering all components that have already migrated to golang 1.22 but still have `.rhel7` or `.rhel8` in their name

[4.17] [ART-9923] Set dockerfile fallbacks for go 1.22 components

---

streams.yml

https://issues.redhat.com/browse/ART-9928
[openshift-golang-builder-container-v1.22.4-202407021644.gd58751c.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3148484)

ART-9928 Update 1.22 rhel8 builders

---

images/ose-aws-efs-csi-driver-operator.yml

Needs to be merged along with: https://github.com/openshift/release/pull/52706

STOR-1856: move AWS EFS operator to csi-operator repo

---

images/local-storage-mustgather.yml
images/ose-secrets-store-csi-mustgather.yml

Upstream wants to use `mustgather` as base image instead of `openshift-enterprise-base`. This change will prevent our bot to open alignment PRs like [this](https://github.com/openshift/local-storage-operator/pull/482/files#diff-1a46cd98e1dd1e1eb02deaa992828147cd6f22d2c5d8b8cf43a4d3be71c32f33R1) and [this](https://github.com/openshift/secrets-store-csi-driver-operator/pull/57/files#diff-1a46cd98e1dd1e1eb02deaa992828147cd6f22d2c5d8b8cf43a4d3be71c32f33R1)
Test builds:
- [ose-secrets-store-csi-mustgather-container-v4.17.0-202407040928.p0.g84bd1d4.assembly.test.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3153514)
- [ose-local-storage-mustgather-container-v4.17.0-202407040928.p0.g7f342da.assembly.test.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=31535 …

[4.17] use must-gather as base for LSO and secrets-store-csi mustgather

---

images/ose-azure-workload-identity-webhook.yml

Reverts openshift-eng/ocp-build-data#5037
Fallback not needed, since we are aiming for 4.17 only for now

Revert "[4.14] dockerfile_fallback for azure-workload"

---

images/ose-azure-workload-identity-webhook.yml

Reverts openshift-eng/ocp-build-data#5036
Fallback not needed, since we are aiming for 4.17 only for now

Revert "[4.15] dockerfile_fallback for azure-workload"

---

images/ose-azure-workload-identity-webhook.yml

Reverts openshift-eng/ocp-build-data#5035
Fallback not needed, since we are aiming only for 4.17 now

Revert "[openshift-4.16] [ART-9923] set dockerfile_fallback"

---

images/cluster-etcd-operator.yml
images/ose-azure-workload-identity-webhook.yml

Remove fallback, since upstream PRs have merged
- https://github.com/openshift/azure-workload-identity/pull/23
- https://github.com/openshift/cluster-etcd-operator/pull/1289

Remove fallbacks

---

ci_images/dnf_wrapper.sh
ci_images/dnf_wrapper_test.Dockerfile

- Don't rely on openshift build specific environment variable as runtime hint (not always set when build loglevel is not specified)
- Disable subscription manager to aovid unnecessary noise.
- Retry CI mirroring service to be a bit more robust.
- Add testing procedure.

Improve DNF wrapper behavior and output

---

images/ose-baremetal-cluster-api-controllers.yml

The image is not labelled for payload:
```
$ oc adm release info registry.ci.openshift.org/ocp/release:4.17.0-0.nightly-2024-07-08-042329  --image-for baremetal-cluster-api-controllers
error: no image tag "baremetal-cluster-api-controllers" exists in the release image registry.ci.openshift.org/ocp/release:4.17.0-0.nightly-2024-07-08-042329
```
PRs had been suggested to add the required label (e.g. [in 4.15](https://github.com/openshift/cluster-api-provider-metal3/pull/14)), but never got attention. Proposing to mark this image as not for payload, and evaluate deprecation.

[4.17] baremetal-cluster-api-controllers not for payload

---

group.yml

Reinstating https://github.com/openshift-eng/ocp-build-data/pull/4711 after https://github.com/openshift-eng/ocp-build-data/pull/5052

Make rteval available to tests image

---

images/ingress-node-firewall-daemon.yml
images/ingress-node-firewall-operator.yml
images/kube-rbac-proxy.yml

ART is currently not able to ship ingress-node-firewall. Upstream has indicated that backports will not be done: https://issues.redhat.com/browse/OCPBUGS-32780

4.12: Stop building ingress-node-firewall-operator

---

images/dpu-network-operator.yml
images/kube-rbac-proxy.yml

ART is not able to ship dpu-operator, as infra labels are not set. https://issues.redhat.com/browse/OCPBUGS-32779 has been unaddressed since quite a while. Proposing to stop to build and ship this operator.

4.12: Disable abandoned dpu-operator

---

group.yml

Reverts openshift-eng/ocp-build-data#5076
[RHELWF-11439](https://issues.redhat.com/browse/RHELWF-11439) claims packages got reshipped.

Revert "Stop 4.12 automation"

---

group.yml

in rhel 8.6 still need kernel-rt

include kernel-rt

---

images/ose-aws-efs-csi-driver-operator.yml

Must merge after https://github.com/openshift/csi-operator/pull/237

STOR-1856: remove cachito legacy manifest dir for aws efs

---

images/ose-baremetal-cluster-api-controllers.yml

This reverts commit 5543e1deda506b033549466993a2426e8922e04a.
Operator label added: https://github.com/openshift/cluster-api-provider-metal3/pull/19

Revert "[4.17] baremetal-cluster-api-controllers not for payload"

---

images/clusterresourceoverride-operator.yml
images/clusterresourceoverride.yml
images/vertical-pod-autoscaler-operator.yml
images/vertical-pod-autoscaler.yml

VPA and CRO are no longer part of the AOS Node team, but are now overseen by the Pod Autoscaling team.

Update CRO & VPA owners to pod autoscaling team

---

product.yml

We created a component for IBM providers. The machine provider is still using the global one.

Update machine-api provider IBM component mapping

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile
ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

[RHEL-22852](https://issues.redhat.com//browse/RHEL-22852) got resolved, CI builds should not fail with errors like these anymore:
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```

Stop pinning git in ci images

---

images/ose-frr.yml

ref https://issues.redhat.com/browse/ART-10306

[ART-10306] [ose-frr] set for_payload as true

---

images/openshift-golang-builder.Dockerfile

https://issues.redhat.com/browse/ART-7860

ART-7860: Use GOAMD64=v2 on rhel9 1.22 golang builder containers

---

images/okd-only-upi-installer.yml

I'm working on getting OKD CI configurations generated using ART metadata. Mostly this has gone seamlessly, but vpshere requires one image, `upi-installer` which does not exist in the product and simply exists to enable CI workflows. It should never ship. 
To accommodate this, we can introduce a disabled image that will be processed by the okd:images verbs to generate its OKD metadata.
Requires: https://github.com/openshift-eng/art-tools/pull/839 .

Add OKD-only image for upi-installer

---

images/ose-aws-efs-csi-driver-operator.yml

disable ose-aws-efs-csi-driver-operator to unblock pipeline until [OCPBUGS-38578](https://issues.redhat.com/browse/OCPBUGS-38578) resolved

disable ose-aws-efs-csi-driver-operator

---

group.yml

add rhel-9-base and rhel-9-appstream repo to support sync rhel9 repos to mirror/enterprise/ci-deps

[ART-10455] add rhel9 base and appstream repo to sync list

---

images/pf-status-relay.yml

Ticket: https://issues.redhat.com/browse/ART-10298
```
asdas@asdas-thinkpadp1gen3:/tmp/crap/check-payload$ sudo ./check-payload -V 4.17 scan image --spec registry-proxy.engineering.redhat.com/rh-osbs/openshift-pf-status-relay-rhel9@sha256:67ac6316a46367d5906d89055f08b1f887c6bc84d4c73940bf014684f0dd0dd9
---- Successful run
```
ref [thread](https://redhat-internal.slack.com/archives/CB95J6R4N/p1721917527586489)

[ART-10298] pf-status-relay image add

---

images/openshift-enterprise-ansible-operator.yml

Update Dockerfile path and repo location for ansible-operator-plugins
Switch the building of the `openshift-enterprise-ansible-operator` from [https://github.com/openshift/ocp-release-operator-sdk](https://github.com/openshift/ocp-release-operator-sdk/blob/d147fd3b63cf4a6bc4c1d9168f5388f2da102505/release/ansible/Dockerfile.ocp#L1) to [https://github.com/openshift/ansible-operator-plugins](https://github.com/openshift/ansible-operator-plugins/blob/f30dff62ceda41de7bfe69ce82cb6fb08c2feefe/openshift/Dockerfile#L1)
https://issues.redhat.com//browse/CFE-1111

CFE-1111: [openshift-4.17] Update Dockerfile and repo location for ansible-operator-plugins

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile
ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

[RHEL-22852](https://issues.redhat.com//browse/RHEL-22852) got resolved, CI builds should not fail with errors like these anymore:
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```

4.17: Stop pinning git in ci images

---

images/ose-tools.yml

With https://github.com/openshift/csi-operator/commit/172f99bcfddd7c356ecf9cbe4b87557dc7d0d31a ose-tools was included as image-reference

[fix] include ose-aws-efs-csi-driver-operator as dependency for ose-tools

---

images/ose-aws-efs-csi-driver-operator.yml

Reverts openshift-eng/ocp-build-data#5264.
[Changed](https://github.com/openshift/csi-operator/pull/261/files) `tools` to `ose-tools`, as requested [here](https://github.com/openshift/csi-operator/pull/252/files#r1719471717).
@Ximinhan is it possible to know if my changes fixed the build issue before merging this?

Revert "disable ose-aws-efs-csi-driver-operator"

---

images/vertical-pod-autoscaler-operator.yml

This is needed as a result of this PR that was merged to migrate the repo to operator-sdk 1.35: https://github.com/openshift/vertical-pod-autoscaler-operator/pull/169
All the ART stuff should be here now: https://github.com/openshift/vertical-pod-autoscaler-operator/tree/master/bundle

PODAUTO-225: Fix bundle and manifest directories for vertical-pod-autoscaler-operator

---

images/openshift-enterprise-helm-operator.yml
images/openshift-enterprise-operator-sdk.yml

Dockerfiles disappeared with https://github.com/openshift/ocp-release-operator-sdk/commit/2e2ec82b15ed43e46804e6b3d21a782c7a26c2c3, disabling while we figure out what there is to do.

Disable helm and operator-sdk images

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile.previous
ci_images/rhel-9/ci-openshift-build-root/Dockerfile.previous
images/ci-openshift-build-root-previous.rhel8.yml
images/ci-openshift-build-root-previous.rhel9.yml

current ci image failed to build because latest go/tools update its deps to go 1.22
add `Dockerfile.previous` to align with `ci-openshift-build-root-previous-container` image usage, also good for cherry pick
the `Dockerfile.previous` changed two parts from Dockerfile
- pin go/tools v0.24.0 vetsion since v0.25.0 requires at least go 1.22 but current previous image is on go 1.21
- remove go/tools/cmd/cover due to its deprecated in go/tools
test build 
https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=64195448
https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=64195449

pin go tools with previous version to match golang version

---

images/ose-openstack-cinder-csi-driver-operator.yml

We have moved the contents of the old `openstack-cinder-csi-driver-operator` repo into the `csi-operator` repo ([1]) and have migrated our jobs accordingly ([2]). We are also in the process of marking the old repo as deprecated ([3]). This is the final step in the process.
By way of prior art, this is what was previously done for the Azure disk operator in #4148.
[1]: https://github.com/openshift/csi-operator/pull/278
[2]: https://github.com/openshift/release/pull/56812
[3]: https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/180

OSASINFRA-3609: Move OpenStack Cinder CSI Driver Operator to csi-operator repo

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-8/ci-openshift-build-root/Dockerfile.previous
ci_images/rhel-9/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile.previous
images/ci-openshift-build-root-previous.rhel8.yml
images/ci-openshift-build-root-previous.rhel9.yml

replace https://github.com/openshift-eng/ocp-build-data/pull/5401

[openshift-4.17] pin go tools with previous version to match golang version

---

images/ose-machine-config-operator.yml

Test build: [ose-machine-config-operator-container-v4.7.0-202408281348.p0.g9bbeff5.assembly.test.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3254191)

[4.7] disable cachito for machine-config-operator

---

images/csi-driver-manila-operator.yml

We have [moved the content of csi-driver-manila-operator repo to csi-operator repo](https://github.com/openshift/csi-operator/pull/280) and are in the progress [of migrating our jobs](https://github.com/openshift/release/pull/56882). This is the final step of the process.
Here is the similar process that was done for cinder csi https://github.com/openshift-eng/ocp-build-data/pull/5402

OSASINFRA-3610: OpenStack: ship manila CSI operator from csi-operator

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-8/ci-openshift-build-root/Dockerfile.previous
ci_images/rhel-9/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile.previous

CI builds were failing on Konflux with:
- cert error ([example](https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-18/pipelineruns/doozer-build-openshift-4-18-ci-openshift-build-root-latest42xkh/detail))
- Condition with repos ([example](https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-18/pipelineruns/doozer-build-openshift-4-18-ci-openshift-build-root-latestjxmmn/logs))
This PR includes fixes proposed by Justin

support CI builds in Konflux

---

images/ose-secrets-store-csi-driver-operator.yml

https://issues.redhat.com/browse/STOR-1873
/hold for https://github.com/openshift/secrets-store-csi-driver-operator/pull/63
/cc @openshift/storage

STOR-1873: update OLM manifests to use stable channel

---

releases.yml

OCPBUGS-42624 is targeting new cri-o after this release
OCPBUGS-42300 has the wrong pscomponet but pr is included in this release

handle bugs for 4.16.17

---

images/cluster-nfd-operator.yml
images/clusterresourceoverride-operator.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-metallb-operator.yml
images/ptp-operator.yml

metadata refers 4.17.0 instead of 4.18.0, temporary disable until upstream fixes it
```
Bundle ose-metallb-operator-bundle-container-v4.18.0.202410071541.p0.g785764e.assembly.stream.el9-2 CSV metadata.name has no datestamp: metallb-operator.v4.17.0
Bundle ose-metallb-operator-bundle-container-v4.18.0.202410071541.p0.g785764e.assembly.stream.el9-2 CSV spec.version has no datestamp: 4.17.0
Bundle cluster-nfd-operator-metadata-container-v4.18.0.202410071842.p0.g58df9de.assembly.stream.el9-2 CSV metadata.name has no datestamp: nfd.v4.17.0
Bundle cluster-nfd-operator-metadata-container-v4.18.0.202410071842.p0.g58df9de.assembly.stream.el9-2 CSV spec.version has no datestamp: 4.17.0
Bundle ose-clusterresourceoverride-operator-metadata-container-v4.18.0.202410022110.p0.ga720b90.assembly.stream.el9 …
```

[chore] disable few operators with wrong metadata.{name,version}

---

images/cloud-event-proxy.yml

To setup commit forwarding for a repo that does not have a fork in openshift-priv yet:
- Created a priv repo ([openshift-priv/cloud-event-proxy](https://github.com/openshift-priv/cloud-event-proxy)): [ticket](https://issues.redhat.com/browse/DPP-15691) (though the name is different from the request)
- Setup a whitelist: https://github.com/openshift/release/pull/57236
After that we see that commits are being forwarded (cloud-event-proxy mentioned in CI deck [logs](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?job=periodic-openshift-release-private-org-sync))
Docs: https://docs.ci.openshift.org/docs/architecture/private-repositories/#openshift-priv-organization
This PR can be backported if needed

use priv repo for cloud-event-proxy

---

group.yml

Removing these entries:
```sh
for r in $(yq -r '.repos | keys[]' group.yml); do
git grep -q "\b$r$" images/* || echo $r
done
openstack-16-for-rhel-8-rpms
rhel-8-codeready-builder-rpms
rhel-8-rt-rpms
rhel-8-server-ansible-2.9-rpms
```

Cleanup unused repos

---

streams.yml

Ref. [ART-9905](https://issues.redhat.com/browse/ART-9905)
Make unembargoed golang builders available to our partners. We can combine mirroring locations in a single (per-builder) stream entry, where:
- `upstream_image` is the mandatory mirroring location for the first partner
- additional partners can be added by populating an optional `upstream_image_info` list in the same entry

ART-9905 [openshift-4.18] Publish golang builders for partner access

---

images/ose-smb-csi-driver-operator.yml

https://issues.redhat.com/browse/STOR-1844
(followup for https://github.com/openshift/csi-operator/pull/300)
/cc @openshift/storage

STOR-1844: update OLM manifests to use stable channel

---

product.yml

This change is required since oc-mirror component field is going to be renamed in the OCPBUGS jira project.

CLID-252: renaming oc-mirror component

---

images/thanos.yml

This was blocking the rpm from being available for konflux. (failed [run](https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-18/pipelineruns/4-18-thanos-j62zq/logs?task=build-images))
Removing this seems to have [fixed](https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-18/pipelineruns/ose-4-18-thanos-5trtt/logs?task=build-images) it

remove non_shipping field for thanos

---

images/openshift-base-nodejs.rhel9.yml

to avoid unnecessary rebuilds.

base-nodejs: Exempt nodejs packages from update check

---

group.yml
streams.yml

Ref. [ART-11107](https://issues.redhat.com/browse/ART-11107)

Bump golang-1.22 builder to RHEL 9.4

---

group.yml

Looking forward to work on [ART-10785](https://issues.redhat.com/browse/ART-10785) a new var in group.yml
is needed: NEW_RELEASE_VERSION
This new var will decide if the coming up format of the release version has to have a certain format or not. 
**4.16.0** or **4.20.0-0**.
This var is needed in gen-assembly jobs to verify that a correct format for the OCP release version was used.

ART-10785: parameter for new release versioning scheme

---

images/ose-etcd.yml

ref [thread](https://redhat-internal.slack.com/archives/GDBRP5YJH/p1730381903233859?thread_ts=1730227468.852159&cid=GDBRP5YJH)

scan-sources:noop [konflux] use Dockerfile.rhel for ose-etcd

---

group.yml
images/ci-openshift-base.rhel9.yml
images/ci-openshift-build-root-latest.rhel8.yml
images/ci-openshift-build-root-latest.rhel9.yml
images/ci-openshift-build-root-previous.rhel8.disabled
images/ci-openshift-build-root-previous.rhel9.disabled
images/ci-openshift-golang-builder-latest.rhel8.yml
images/ci-openshift-golang-builder-latest.rhel9.yml
images/ci-openshift-golang-builder-previous.rhel8.disabled
images/ci-openshift-golang-builder-previous.rhel9.disabled
images/openshift-base-nodejs.rhel9.yml
images/openshift-base-rhel9.yml

Using the new repo in priv https://github.com/openshift-priv/ocp-build-data so that we can keep config uniform across all components and konflux can rebase to priv

scan-sources:noop use priv org for ocp-build-data

---

images/ose-ovn-kubernetes.yml

Following https://github.com/openshift/ovn-kubernetes/pull/2323
For some reason, this is only pinned in 4.14:
```
ose-ovn-kubernetes_4.12_Dockerfile:	libreswan \
ose-ovn-kubernetes_4.13_Dockerfile:	libreswan \
ose-ovn-kubernetes_4.14_Dockerfile:	libreswan-4.5-1.el9 \
ose-ovn-kubernetes_4.15_Dockerfile:	libreswan \
ose-ovn-kubernetes_4.16_Dockerfile:	libreswan \
ose-ovn-kubernetes_4.17_Dockerfile:	libreswan \
ose-ovn-kubernetes_4.18_Dockerfile:	libreswan \
```

4.14: Stop eternal rebuild loop for ovn-kubernets

---

images/csi-driver-manila-operator.yml

Manila was just integrated to csi-operator. Let's update the build.
https://github.com/openshift/csi-operator/pull/288
The legacy folder is being removed in this PR https://github.com/openshift/csi-operator/pull/317

Remove caching of legacy manila CSI dir

---

images/ose-insights-runtime-exporter.yml

[ART-11252] add insights-runtime-exporter

---

streams.yml

Reverts openshift-eng/ocp-build-data#5700

Revert "ART-11389 - Bump 4.18 golang builders to 1.22.9"

---

releases.yml

Reverts openshift-eng/ocp-build-data#5717 per https://redhat-internal.slack.com/archives/CJARLA942/p1732240809175579?thread_ts=1732105733.058509&cid=CJARLA942

Revert "Add assembly 4.17.6"

---

releases.yml

permit CONFLICTING_INHERITED_DEPENDENCY

---

group.yml

The aarch64 and s390x RHOS don't exist, so use the same repo as a dummy for other arches.

Fix openstack-16-for-rhel-8-rpms repo

---

images/vertical-pod-autoscaler-operator.yml

build is failing dues to issues with the CSV for 4.18.
```
2024-11-22 20:30:04,900 artcommonlib INFO Task state: FREE
2024-11-22 20:33:04,945 artcommonlib INFO Fault: <Fault 2001: 'Image
build failed. Error in plugin pin_operator_digest: Both relatedImages
and RELATED_IMAGE_* env vars present in
/workspace/ws-build-dir/x86_64/manifests/vertical-pod-autoscaler.clusterserviceversion.yaml.
Please remove the relatedImages section, it will be reconstructed
automatically.; . OSBS build id:
vertical-pod-autosca-rhaos-418-rhel-9-f331015954-20241122203110'>
```
Removing `RELATED_IMAGES_` seems to fix the issue but the change is not trivial for upstream
https://github.com/openshift/vertical-pod-autoscaler-operator/pull/182

disable vertical-pod-autoscaler-operator build

---

streams.yml

Reverts openshift-eng/ocp-build-data#5711

Revert "Revert "ART-11389 - Bump 4.18 golang builders to 1.22.9""

---

images/vertical-pod-autoscaler-operator.yml

Reverts openshift-eng/ocp-build-data#5741
Now that https://github.com/openshift/vertical-pod-autoscaler-operator/pull/185 and https://github.com/openshift/vertical-pod-autoscaler-operator/pull/183 have merged, could we try ART builds again?

Re-enable vertical-pod-autoscaler-operator build

---

images/kube-proxy.yml

With the deprecation of openshift-sdn, the Dockerfile for the standalone kube-proxy image build has been moved from openshift/sdn to openshift/kubernetes (https://github.com/openshift/kubernetes/pull/2082). CI update is https://github.com/openshift/release/pull/58505.
(See #5712 for the `openshift-4.18` update, and discuss there if there are any problems with this...)

SDN-5457: Move kube-proxy image from openshift/sdn to openshift/kubernetes

---

product.yml

Of the image names defined in the [openshift-4.18 branch images subdir](https://github.com/openshift-eng/ocp-build-data/tree/openshift-4.18/images) that had 'master' as the main branch, I found these that had no mapping:
* [container-networking-plugins-microshift](https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.18/images/container-networking-plugins-microshift.yml)
* [ose-kubevirt-csi-driver-rhel8](https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.18/images/ose-kubevirt-csi-driver-rhel8.yml)
This PR adds those components and has my best guess for the Jira component they should map to.

OCPCRT-339: Update with missing components

---

group.yml

This change:
- removes a duplicate repository entry
- moves one of the pinned packages to the build root repo
- introduces the codeready builder repository for the rest

rhel8 golang: Add codeready builder repo

---

images/openshift-base-rhel9.yml
images/openshift-enterprise-base-rhel9.yml

Before this change, reconciliation PRs were being opened to reference registry.ci.openshift.org/ocp/4.19:openshift-enterprise-base-rhel9 . Confusingly, we have previously opened PRs to use
registry.ci.openshift.org/ocp/4.x:base-rhel9 . This is not the same as the ART base-rhel9, which is just an up-to-date ELS RHEL9 base image.
CI expects this image to be our enterprise-base RHEL9 image.

Force CI to use 4.x:base-rhel?

---

group.yml

If the stop-ship tag is applied to a kernel, that is a signal that OCP
should not be shipping that release. Strictly speaking, this does not
apply to releases that are not shipping yet. CI of pre-GA releases
should be informing such a decision.
This is a minimal change to not let auatomation run havoc on pre-GA
releases, and to make it a human decision to retract the kernel or not.

Ignore stop-ship-tag for non-GA release

---

images/ose-installer-artifacts.yml

Alongside https://github.com/openshift-eng/art-tools/pull/1186

[konflux] use VM with higher disk for ose-installer-artifacts

---

images/ose-installer-artifacts.yml

Until https://issues.redhat.com/browse/ART-11563 is resolved

ART-11563: [konflux] disable ose-installer-artifacts until issue is resolved

---

images/ose-cli-artifacts.yml

Build failing due to insufficient storage ([logs](https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-19/pipelineruns/ose-4-19-ose-cli-artifacts-4pjmw/logs?task=build-images))

[konflux] use linux-d160/arm64 VM for ose-cli-artifacts

---

images/ose-azure-service-operator.yml

This adds the carry prefix to azure-service-operator, so than we can use it with the rebase bot.

OCPCLOUD-2642: ASO should use commit prefix

---

images/monitoring-plugin.yml
images/nmstate-console-plugin.yml
images/oc-mirror-plugin.yml
images/openshift-enterprise-console.yml
images/ose-alibaba-machine-controllers.yml
images/ose-cli-artifacts.yml
images/ose-etcd.yml
images/ose-installer-artifacts.yml
images/vertical-pod-autoscaler-operator.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/5823

[konflux] override params

---

images/openshift-base-nodejs.yml

Since we don't want to retrigger builds continuously

[konflux] disable openshift-base-nodejs

---

product.yml

We originally had:
```
multus-cni-container:
issue_component: Networking / multus
multus-cni-container-microshift-container:
issue_component: MicroShift
```
In [images](https://github.com/openshift-eng/ocp-build-data/tree/openshift-4.18/images), we have multus-cni-container-microshift.yml and multus-cni.yml and both have a content.source.git.web of https://github.com/openshift/multus-cni.
So, we'll make the owner as `Networking / multus`.

Set component for multus-cni to Networking

---

images/ose-installer-etcd-artifacts.yml

Disabling until upstream issue is fixed

scan-sources:noop [konflux] disable ose-installer-etcd-artifacts

---

images/openshift-kubernetes-nmstate-operator.yml

Since parent is disabled and no green build exists

scan-sources:noop [konflux] disable openshift-kubernetes-nmstate-ope

---

images/ose-installer-etcd-artifacts.yml

needed for konflux
```
[build] Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
[build] subprocess exited with status 1
[build] subprocess exited with status 1
[build] Error: building at STEP "RUN yum install --setopt=tsflags=nodocs -y jq && yum clean all && rm -rf /var/cache/yum/*": exit status 1
```
https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-17/pipelineruns/ose-4-17-ose-installer-etcd-artifacts-2cp7b/logs

enable repos for ose-installer-etcd-artifacts

---

images/monitoring-plugin.yml
images/nmstate-console-plugin.yml
images/oc-mirror-plugin.yml
images/openshift-enterprise-console.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-alibaba-cloud-csi-driver.yml
images/ose-alibaba-machine-controllers.yml
images/ose-baremetal-installer.yml
images/ose-cli-artifacts.yml
images/ose-etcd.yml
images/ose-installer-artifacts.yml
images/ose-installer.yml
images/ose-machine-os-images.yml
images/vertical-pod-autoscaler-operator.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/5838

scan-sources:noop [konflux] override params

---

images/ose-baremetal-installer.yml
images/ose-installer.yml
images/ose-machine-os-images.yml

ose-installer-terraform-providers does not exist in 4.14

[konflux] enable images

---

images/clusterresourceoverride-operator.yml

Now that https://github.com/openshift/cluster-resource-override-admission-operator/pull/174 is merged, hopefully we get cluster-resource-override-operator 4.19 builds again.

Re-enable cluster-resource-override-operator build for 4.19

---

modifications/Dockerfile

fix microshift build, 4.19 use go 1.23 but 4.18 golang builder use go 1.22

fix microshift build

---

images/pf-status-relay-operator.yml

To fix failed CVP [test](http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/pf-status-relay-operator-bundle-container-v4.18.0.202412131108.p0.g1c649ad.assembly.stream.el9-1/9693e891-715b-46d9-b59f-fbdd25510456/operator-valid-subscriptions-bundle-image-output.txt)
```
[INVALID] 'openshift4/pf-status-relay-operator-bundle' subscription type: OCP and up
-> The annotation must contain: 'OpenShift Container Platform', 'OpenShift Platform Plus', but not contain: 'OpenShift Kubernetes Engine'
````
ref [thread](https://redhat-internal.slack.com/archives/CB95J6R4N/p1736535516497769?thread_ts=1721917527.586489&cid=CB95J6R4N)

update valid-subscription-label for pf-status-relay-operator

---

ci_images/dnf_wrapper.sh
ci_images/dnf_wrapper_test.Dockerfile
ci_images/install_dnf_wrapper.sh
ci_images/rhel-8/ci-openshift-base/Dockerfile
ci_images/rhel-9/ci-openshift-base/Dockerfile

The previous version of this script removed all files from /etc/yum.repos.d and reinitialized content in that directory based on execution context (e.g. running in CI vs localdev mode).
This prevents child images from installing other repos that might be relevant to CI or local development.
The new approach manages only the DNF "reposdir" option to alter which directories in the image are searched for .repo files.
Child images can store .repo files in /etc/yum.repos.art/ci and they will be used during CI context builds or /etc/yum.repos.art/localdev and they will be used in the localdev context.

Allow child images to add repos

---

images/ironic.yml

Since hermetic builds are not a priority for now, switching back to open, to unblock build sync.

[konflux] ironic reset network mode

---

images/ose-installer-artifacts.yml

Looks like [ART-11563](https://issues.redhat.com/browse/ART-11563) is resolved, test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/3291/parameters/

scan-sources:noop [4.19] re-enable installer-artifacts for Konflux

---

images/driver-toolkit.yml

https://github.com/openshift-eng/ocp-build-data/pull/5999 broke DTK builds for Konflux. By replacing the konflux config stanza for `enabled_repos` with the old values, the builds succeed.
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/3339/console
Needs https://github.com/openshift-eng/art-tools/pull/1314
Ref. https://issues.redhat.com/browse/ART-11911

scan-sources:noop [4.19][konflux] fix enabled repos for DTK

---

releases.yml

RHCOS has a newer kernel now, DTK should probably float to match it

[4.19] unpin dtk

---

releases.yml

Reverts openshift-eng/ocp-build-data#6064
Newer nightly has fixes that corresponding 4.16 release cut today does not,
so revert to older 4.15 nightly we selected.
https://redhat-internal.slack.com/archives/C05FEGT8SH2/p1738858463249309?thread_ts=1738856739.237459&cid=C05FEGT8SH2

Revert "Add assembly 4.15.45"

---

releases.yml

https://amd64.ocp.releases.ci.openshift.org/releasestream/4.18.0-0.nightly/inconsistency/4.18.0-0.nightly-2025-02-05-033447
[Slack Thread](https://redhat-internal.slack.com/archives/GDBRP5YJH/p1738864025290239?thread_ts=1738863970.456419&cid=GDBRP5YJH)

Pin openshift-4.18.0 RPM

---

releases.yml

RHCOS extensions temporarily use inconsistent RPMs between arches. allow this for now.
ref. https://redhat-internal.slack.com/archives/C01CQA76KMX/p1738863088399379
trying it out [here](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/14595/console)

[4.19] temporarily allow RHCOS RPM inconsistencies

---

images/openstack-resource-controller.yml

This image doesn't exist in ec.1

ec.1: temporarily disable openstack-resource-controller

---

releases.yml

Telco only requires the kube-rbac build to be prod, which happens when we push out a pre-release. Advance release is for the bundles themselves, which does not need to be shipped out.

rc.8 pre-release

---

images/ose-installer-artifacts.yml

ose-installer-artifacts requires higher disk space for its builds, for ppc. For s390x, using a bigger VM to shorten build times.

[konflux] ppc VM with bigger disk space, s390x

---

images/openshift-enterprise-console.yml

The console image builds fine with commenting out cachito specific env vars.

Dynamic removal of cachito references to REMOTE_SOURCES

---

images/ose-olm-catalogd.yml

Reverts openshift-eng/ocp-build-data#6027 to prepare ec.1 Errata.
Will get it back once the advisories are prepared.

Revert "OPRUN-3711: OLMv1: Get catalogd image from operator-controller repo"

---

images/monitoring-plugin.yml

Was failing due to 
```
Error: building at STEP "RUN test -d ${REMOTE_SOURCES_DIR}/cachito-gomod-with-deps || exit 1; 
```
Successful run: https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-19/pipelineruns/ose-4-19-monitoring-plugin-r64lc

[konflux] monitoring-plugin cachito comment out

---

images/ose-olm-catalogd.yml

Reverts openshift-eng/ocp-build-data#6084
/hold until ec.1 is prepared.

Revert "Revert "OPRUN-3711: OLMv1: Get catalogd image from operator-controller repo""

---

images/kuryr-cni.yml
images/kuryr-controller.yml

Stuck in infinite rebuild
Ref [thread](https://redhat-internal.slack.com/archives/GDBRP5YJH/p1736264134036469)

[konflux] disable kuryr images in 4.12

---

images/openstack-resource-controller.yml

Fix stream to the one that exists and should be used
Failure first seen at https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/scheduled-builds/job/sync-ci-images/32349/
```
raise IOError(f"Unable to find definition for stream '{stream_name}'")
OSError: Unable to find definition for stream 'rhel-9-golang-ci-build-root'
```

Fix ci build root stream

---

images/linuxptp-daemon.yml

ART Dockerfile was recently moved (https://github.com/openshift/linuxptp-daemon/pull/402/commits/5c0fc1c44ab2dc810ab802b00d6288f6d037edb8) to https://github.com/openshift/linuxptp-daemon/blob/release-4.19/addons/redhat/Dockerfile.ocp
This is causing the rebase to fail https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/14904/consoleFull

linuxptp-daemon: Update dockerfile path

---

erratatool.yml

Issue:
https://issues.redhat.com/browse/OSDOCS-13376
The documentation has moved to docs.redhat.com; this PR updates the link in the Errata.

OSDOCS-11376-414: updates release note link for MicroShift 4.14

---

erratatool.yml

Issue:
https://issues.redhat.com/browse/OSDOCS-13376
The documentation has moved to docs.redhat.com; this PR updates the link in the Errata.

OSDOCS-13376-415: updates release note link for MicroShift 4.15

---

erratatool.yml

Issue:
https://issues.redhat.com/browse/OSDOCS-13376
The documentation has moved to docs.redhat.com; this PR updates the link in the Errata.

OSDOCS-11376-417: updates release note link for MicroShift 4.17

---

group.yml
images/driver-toolkit.yml

this will be required in the context of 2 Nodes OpenShift
See: https://issues.redhat.com/browse/OCPEDGE-1493

add HighAvailability repo

---

images/kuryr-cni.yml
images/kuryr-controller.yml

Reverts openshift-eng/ocp-build-data#6088
scan-sources bug fixed with https://github.com/openshift-eng/art-tools/pull/1359

Revert "[konflux] disable kuryr images in 4.12"

---

releases.yml

Reverts openshift-eng/ocp-build-data#6156
rpm-ostree-2024.3-6.el9_4 has been shipped in RHEL.

Revert "4.18.0: pin rpm-ostree rpm"

---

images/ose-cli-artifacts.yml

Image build was failing with insufficient storage

[konflux] cli-artifacts use d320 VMs

---

images/ose-cli-artifacts.yml

IBM arches doesn't seem to need the increased disk space

[konflux] ose-cli-artifacts IBM flavor update

---

images/ose-secrets-store-csi-driver-operator.yml
images/ose-secrets-store-csi-driver.yml
images/ose-secrets-store-csi-mustgather.yml

We are transferring ownership of the secrets-store csi driver and operator to the OAP team.
This PR updates the alias for the new image owners.
/cc @arkadeepsen

[4.18] secrets-store-csi-driver: update owners alias

---

images/ose-secrets-store-csi-driver-operator.yml
images/ose-secrets-store-csi-driver.yml
images/ose-secrets-store-csi-mustgather.yml

We are transferring ownership of the secrets-store csi driver and operator to the OAP team.
This PR updates the alias for the new image owners.
/cc @arkadeepsen

[4.19] secrets-store-csi-driver: update owners alias

---

images/ose-ovirt-machine-controllers.yml

This reverts commit d55a2b563a568b011cbbd6e82eb08097c15066bf.

Revert "ART-11740: 4.18: remove ovirt-machine-controllers"

---

group.yml

Until IBM arches are reliable again

[konflux] restrict arches to x86,arm

---

images/ose-cluster-autoscaler-operator.yml
images/ose-machine-api-operator.yml
images/ose-machine-api-provider-aws.yml
images/ose-machine-api-provider-azure.yml
images/ose-machine-api-provider-gcp.yml
images/ose-machine-api-provider-openstack.yml

Example: https://github.com/openshift/cluster-autoscaler-operator/blob/227f7537c3b459d4940522809df60b2dfca738ed/Makefile#L5-L6 is checked for semver compliance at runtime.

Enabling rebase tagging for impacted images

---

images/ose-alibaba-cloud-csi-driver.yml

4.12 and 4.13 has a different script name: https://github.com/openshift/alibaba-cloud-csi-driver/blob/release-4.12/Dockerfile.openshift#L5

update ose-alibaba-cloud-csi-driver replace

---

releases.yml

Has correct 4.19 references (older builds had references to 4.18 images)

4.19 ec.3 pin cluster-nfd-operator

---

group.yml

Since multiple builds are failing in 4.12

[konflux] cachi2 disable group

---

streams.yml

https://issues.redhat.com/browse/ART-12284
/hold

ART-12284: Update `nodejs-rhel9` to node 22

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile

With `--nobest`, packages that are explicitly being installed, but where an outdated version is already installed, will not see an upgrade. This causes problems for packages that are available on, say, x86_64, but not on one of the other arches. The OSBS plugin that checks for consistent RPMs across the arches will fail the build.
This PR says: _Do better, dnf!_

ci build root images: No nobest

---

group.yml

[konflux] 4.19 disable cachi2

---

rpms/openshift.yml
rpms/ose-aws-ecr-image-credential-provider.yml
rpms/ose-azure-acr-image-credential-provider.yml
rpms/ose-gcp-gcr-image-credential-provider.yml

4.19 is shipping without support for Bring Your Own RHEL8. This change stops to build non-client rpms into the rhel8 target.

Prune "bring your own RHEL"-rpms for 4.19

---

images/ose-cluster-update-keys.yml

The okd_alignment was missing from this. add it back

cluster-update-keys: use Dockerfile for OKD, not Dockerfile.rhel

---

group.yml

As a follow-up of https://github.com/openshift-eng/ocp-build-data/pull/6169.

[openshift-4.20] Switch to 10.1 repos for CI

---

group.yml

At the request of konflux infra: https://redhat-internal.slack.com/archives/C06Q309QUDV/p1744211584812859?thread_ts=1744211222.760909&cid=C06Q309QUDV

Enable IBM arches

---

images/ose-installer-terraform-providers.yml

Fixes `no space left on device` error
https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/ocp-art-tenant/applications/openshift-4-15/pipelineruns/ose-4-15-ose-installer-terraform-providers-7rtwg/logs

Terraform increase IBM VM disk

---

images/local-storage-mustgather.yml
images/openshift-enterprise-pod.yml
images/openstack-resource-controller.yml
images/ose-installer.yml
images/ose-secrets-store-csi-mustgather.yml
images/ovn-kubernetes-microshift.yml

Reviewed all image definitions using [this script](https://gist.github.com/lgarciaaco/e9517b914ba7bff19382a274d727e474) and identified several enabled_repos blocks that are no longer required. This PR removes those redundant definitions to simplify and clean up the configuration.
The following build job was used to validate the changes:
🔗 [OCP4 Build Job #16784](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/16784/console)
All builds passed successfully with these changes.

Remove Unnecessary enabled_repos Definitions from Image Configs

---

images/openshift-enterprise-ansible-operator.yml

- Add a new requirements-build file for ansible-operator-plugins
- Needed for https://github.com/openshift/ansible-operator-plugins/pull/37
https://issues.redhat.com//browse/OAPE-35

OAPE-35: [openshift-4.19] Add new requirements-build file for ansible-operator-plugins

---

OWNERS

The automated cherry-pick of #6505 failed so this is a manual cherry pick with some re-ordering of the names to keep them consistent across all versions.  I also added the two additional members that needed to be added to avoid spamming PRs.
The intention is to then cherry pick this up to 4.20

Add Sustaining ART members to owners file

---

group.yml

Reverts openshift-eng/ocp-build-data#6597
Cause of [error](https://redhat-internal.slack.com/archives/C06Q309QUDV/p1744986384342639?thread_ts=1744888045.688729&cid=C06Q309QUDV)

Revert "Enable ppc"

---

group.yml

Changes in this PR:
- ppc is stable enough for us to enable them for 4.19
- we have good workarounds for prefetch. enabling to sort out the errors

scan-sources:noop enable ppc, cachi2

---

images/multus-networkpolicy.yml
images/ose-openshift-controller-manager.yml
images/pf-status-relay.yml

scan-sources:noop disable cachi2 image

---

images/ib-sriov-cni.yml
images/node-feature-discovery.yml
images/openshift-enterprise-console.yml
images/openshift-kubernetes-nmstate-handler.yml
images/ose-ibmcloud-cluster-api-controllers.yml
images/ose-network-tools.yml
images/ptp-operator.yml

Changes in this PR:
- Adding `modifications` for `ose-ibmcloud-cluster-api-controllers`, `ib-sriov-cni`
- Disabling images with known issues.
- Enabling `ptp-operator` and `node-feature-discovery` images which are failing on the build step, if prefetch is enabled. Prefetch succeeds. If prefetch is not enabled, build-step succeeds.

cachi2 images update

---

images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-microshift.yml

`gomod` was initially added to the pkg_mangers list as part of [this commit](https://github.com/openshift-eng/ocp-build-data/commit/0364c238ab0aa61a4c1c39720c76802ec747b2b2), but the situation seems to be different right now. There is no go.mod file found in the default (root) dir of upstream, hence package manager is not required here

ovn images remove gomod

---

images/node-feature-discovery.yml
images/ptp-operator.yml

Since IBM arches are working, priority has shifted to getting green builds non-hermetically first

disable ptp, nfd

---

group.yml

Since IBM builds are relatively stable now

disable cachi2 in group

---

images/aws-karpenter-provider-aws.yml

Image was added with wrong ci build root name: https://github.com/openshift-eng/ocp-build-data/pull/6450
`OSError: Unable to find definition for stream 'rhel-9-golang-ci-build-root'`
Seen at: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/scheduled-builds/job/sync-ci-images/37910/consoleFull

4.20 - Fix build root stream name

---

product.yml

Altinfra was a terraform-free version of the installer, which is now terraform-free by default.

Remove altinfra container

---

images/microshift-bootc.yml

For them, vendor modifications are necessary
https://redhat-internal.slack.com/archives/C06Q309QUDV/p1745508906683839

disable cachi2 for bootc

---

bug.yml

ART opted for greedy bug sweep, but that fails because jira throws an error when a Target Version does not exist. Temporarily disabling.

Fix 4.20 bug sweep

---

images/golang-github-prometheus-alertmanager.yml
images/ose-azure-service-operator.yml
images/ose-sriov-rdma-cni.yml

Prefetch succeeded for images/ose-sriov-rdma-cni.yml: https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/ocp-art-tenant/applications/openshift-4-20/pipelineruns/ose-4-20-ose-sriov-rdma-cni-dfphm/logs

disable cachi2 for images

---

images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-base.yml
images/ovn-kubernetes-microshift.yml

openvswitch* RPMs will no longer pinned in ovn-kubernetes images once https://github.com/openshift/ovn-kubernetes/pull/2525 lands in order to facilitate timely CVE and bug fix delivery.  Remove from exemptions.

ovn-kubernetes: Remove exemptions for now unpinned OVS rpms.

---

images/ose-metallb.yml

https://github.com/openshift/metallb/pull/239/files#diff-f20a7cf8ba7e8b20f3bd1963e18191e6ba4474bb0bf92bdd745bb62841e4a6c3 seems to have fixed the problem that called for modification. They did specify a builder that is not present in the production build system:
```
FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.24-nofips-openshift-4.19 AS builder
```
I expect the rebase to continue, but the build to fail, but let's see.

Fix metallb rebase

---

streams.yml

ValueError: Duplicate alias detected: rhel-8-golang-{GO_EXTRA} is already mapped to golang-1.19
https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fgolang-builder/139/console

Remove EXTRA mentions

---

erratatool.yml

For 4.12 and 4.13, the templates are different: https://docs.google.com/spreadsheets/d/1pySmokqVb-zNYmoZ5D43LQJ8GJh50idwC4Ow_Sn15Gg/edit?gid=1797967923#gid=1797967923
Keeping the config here (`erratatool.yml`) will override the default config (https://github.com/openshift-eng/ocp-build-data/blob/main/config/advisory_templates.yml)

[4.13] docs override

---

streams.yml

4.14: reinstate rhel8 go1.19 builder

---

releases.yml

Our automation gets confused if it sees brewevent and search for brew builds when the builds are actually from konflux. Removing the brewevent should work

[4.20 ex.2] remove brewevent since its for konflux

---

releases.yml

As per the slack thread conversation these images are required in 4.19:
https://redhat-internal.slack.com/archives/CB95J6R4N/p1749112753370699
[sriov-network-operator-container-v4.19.0-202506041351.p0.gf66d332.assembly.stream.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3676510)
[sriov-network-webhook-container-v4.19.0-202506041351.p0.gf66d332.assembly.stream.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3676507)
[sriov-network-config-daemon-container-v4.19.0-202506041351.p0.gf66d332.assembly.stream.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3676508)

pinning sriov with correct imagestreams

---

config/advisory_templates.yml

See https://issues.redhat.com/browse/OSDOCS-14853 for details; this PR creates separate advisory text for the **image mode for RHEL MicroShift ready-to-use image** so that it is different than the general advisory text for MicroShift product releases.
Please cherry-pick to 4.18 and 4.19 branches as applicable.

Updates MicroShift bootc image boiler plate advisory text

---

group.yml

Add exempt rpms for node image rpm check because they could be outdated to align with rhel base image

add exempt_rpms for layered rhcos

---

images/monitoring-plugin.yml

Looking at https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=67912372
```
2025-06-11 15:33:32,837 - atomic_reactor.tasks.binary_container_build - INFO - cp: cannot stat '/remote-source/cachito-gomod-with-deps/app/web/.yarnrc': No such file or directory
```

[4.17] monitoring fix

---

images/monitoring-plugin.yml

Looking at https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=67913936
```
2025-06-11 17:30:21,690 - atomic_reactor.tasks.binary_container_build - INFO - touch: cannot touch '/remote-source/cachito-gomod-with-deps/app/web/registry-ca.pem': No such file or directory
2025-06-11 17:30:21,690 - atomic_reactor.tasks.binary_container_build - INFO - touch: cannot touch '/remote-source/cachito-gomod-with-deps/app/web/.npmrc': No such file or directory
```
Since path is default dir

[4.16] monitoring fix

---

releases.yml

Lack of brew event breaks microshift jobs and will break rpm prep as well.
Until we have rpm prep working with basis.time, we need this defined.

[4.20] Reinstate brew event for ec.2

---

images/cluster-nfd-operator.yml
images/clusterresourceoverride-operator.yml
images/dpu-operator.yml
images/ingress-node-firewall-operator.yml
images/local-storage-operator.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-aws-efs-csi-driver-operator.yml
images/ose-gcp-filestore-csi-driver-operator.yml
images/ose-metallb-operator.yml
images/ose-secrets-store-csi-driver-operator.yml
images/ose-smb-csi-driver-operator.yml
images/ptp-operator.yml
images/sriov-network-operator.yml
images/vertical-pod-autoscaler-operator.yml

Add bundle_delivery_repo_name for all OLM bundles - 4.17

---

images/cluster-nfd-operator.yml
images/clusterresourceoverride-operator.yml
images/dpu-operator.yml
images/helloworld-operator.yml
images/ingress-node-firewall-operator.yml
images/local-storage-operator.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-aws-efs-csi-driver-operator.yml
images/ose-gcp-filestore-csi-driver-operator.yml
images/ose-metallb-operator.yml
images/ose-secrets-store-csi-driver-operator.yml
images/ose-smb-csi-driver-operator.yml
images/pf-status-relay-operator.yml
images/ptp-operator.yml
images/sriov-network-operator.yml
images/vertical-pod-autoscaler-operator.yml

This field will be required by building FBC for OLM operators.

Add bundle_delivery_repo_name for all OLM bundles - 4.18

---

images/ib-sriov-cni.yml

The modification was necessary because of upstream inconsistency between vendor and go.mod which has since been fixed (https://github.com/openshift/ib-sriov-cni/pull/94)

Remove add modification for ib-sriov-cni in 4.19

---

releases.yml

cloud-event-proxy and ptp-operator are non-payload images
Bundle build that would be attached: [ose-ptp-operator-metadata-container-v4.18.0.202506260833.p0.g28fb484.assembly.stream.el9-1](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3713516)

4.18.19 ptp-operator fix

---

releases.yml

Pin dpu-operator in stream so that it uses the same upstream commit as the last successful build of dpu-intel-ipu-vsp (which is currently failing to build)
[Pinned dpu-operator](https://art-build-history-art-build-history.apps.artc2023.pc3z.p1.openshiftapps.com/build?nvr=dpu-operator-container-v4.19.0-202507011209.p0.gd7bbf4c.assembly.stream.el9&outcome=success&type=image)
[Last successful dpu-intel-ipu-vsp](https://art-build-history-art-build-history.apps.artc2023.pc3z.p1.openshiftapps.com/build?nvr=dpu-intel-ipu-vsp-container-v4.19.0-202507011209.p0.gd7bbf4c.assembly.stream.el9&outcome=success&type=image)

Pin dpu-operator in stream

---

images/clusterresourceoverride-operator.yml
images/clusterresourceoverride.yml

Opt `clusterresourceoverride` and `clusterresourceoverride-operator` into auto merging for ART PRs.
We are trying this out for some of the autoscaling teams repos for a few releases, and we'll see how if it's something we want for all our repos.

AUTOSCALE-286: opt clusterresourceoverride into auto_label for merge

---

images/openshift-kubernetes-nmstate-operator.yml
images/ose-metallb-operator.yml
images/pf-status-relay-operator.yml

As part of 
Based on Slack conversation : https://redhat-internal.slack.com/archives/CB95J6R4N/p1751978092274309?thread_ts=1751899967.141159&cid=CB95J6R4N
Pf status-relay operator :  https://issues.redhat.com/browse/OCPBUGS-57971
https://github.com/openshift/pf-status-relay-operator/pull/39
Bug https://issues.redhat.com/browse/OCPBUGS-57974 is fixed with : https://github.com/openshift/kubernetes-nmstate/pull/631/files

Re-enable openshift-kubernetes-nmstate-operator, ose-metallb-operator.yml, pf-status-relay-operator.yml

---

images/coredns.yml
images/csi-driver-manila.yml
images/ose-cluster-baremetal-operator.yml
images/ose-metallb.yml
images/ose-openstack-cinder-csi-driver.yml
images/ose-vsphere-cloud-controller-manager.yml
images/ose-vsphere-cluster-api-controllers.yml

Remove modifications fixing vendor inconsistency errors during Konflux builds and instead disable cachi2 for these images. This is so that all such images have an identical way of working arround these issues. Further details are in [ART-13345](https://issues.redhat.com/browse/ART-13345)

ART-13260: Replace add modifications with disabling cachi2 in 4.18

---

images/ptp-operator.yml

Disable cachi2 for ptp-operator to prevent Konflux build failures due to cachi2-related errors.

ART-13260: Disable cachi2 for ptp-operator in 4.15

---

images/ci-openshift-build-root-latest.rhel8.yml
images/ci-openshift-build-root-latest.rhel9.yml

Disabling Konflux builds of ci-build-root images until [ART-13429](https://issues.redhat.com//browse/ART-13429) is solved

ART-13429: ci-openshift-build-root*: Stop building in Konflux

---

images/kube-rbac-proxy.yml
images/ose-frr.yml

```
doozerlib.exceptions.DoozerFatalError: Related image contains ose-frr but this does not have ose-metallb-operator in dependents
```
https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/22743/consoleText

fix ose-metallb-operator build errors

---

images/ose-metallb.yml

same as 4.19: https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.19/images/ose-metallb.yml#L20

add missing delivery repo name

---

images/clusterresourceoverride-operator.yml
images/dpu-operator.yml
images/sriov-network-operator.yml

Since below bugs are fixed we can renable these operators.
https://issues.redhat.com/browse/OCPBUGS-57973
https://issues.redhat.com/browse/OCPBUGS-57962
https://issues.redhat.com/browse/OCPBUGS-57969

Renable dpu-operator, sriov-network-operator, clusterresource override operator

---

releases.yml

Reverts openshift-eng/ocp-build-data#7248

Revert "[temporary]: pin driver-toolkit to match kernel version used by rhcos"

---

images/openshift-base-nodejs.rhel9.yml
images/openshift-enterprise-keepalived-ipfailover.yml
images/ose-egress-http-proxy.yml

Set `network_mode` to `open` to fix lockfile-related Konflux build errors
Error logs:
- https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/ocp-art-tenant/applications/openshift-4-19/pipelineruns/ose-4-19-openshift-enterprise-keepalived-ipfailover-d7x84
- https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/ocp-art-tenant/applications/openshift-4-19/pipelineruns/ose-4-19-ose-egress-http-proxy-ccw66
- https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/ocp-art-tenant/applications/openshift-4-19/pipelineruns/ose-4-19-openshift-base-nodejs-rhel9-8gjx4

scan-sources:noop Set network_mode to open

---

group.yml

9.2 EUS ended July 1, need to move to e4s

openshift-4.14: Move from eus to e4s for 9.2 content

---

images/sriov-cni.yml

`sriov-cni` is failing to build in Konflux due to cachi2 issues
[Failed build](https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/ocp-art-tenant/applications/openshift-4-13/pipelineruns/ose-4-13-sriov-cni-f4ccc/logs?task=prefetch-dependencies)

ART-13260: Disable Konflux cachi2 for sriov-cni in 4.13

---

group.yml

Reverts openshift-eng/ocp-build-data#7385
There are several issues with 4.21
- scan will fail if rhcos tag does not exist in imagestream, there is a workaround https://github.com/openshift-eng/art-tools/pull/1924/files , but without it scan will fail
- rpms cannot be built on 4.21 buildroot
- images need careful manual fixing.
- So we need a successful ocp4-konflux job + build-sync job 
Until then keeping automation on scheduled

Revert "[4.21] unfreeze automation"

---

releases.yml

revert to earlier advisory ids for rpm and rhcos

4.12.80 - revert to earlier advisory ids for rpm and rhcos

---

group.yml
rpms/openshift-clients.yml
rpms/openshift.yml

In order to have signed rpms, we need to have rhel10 set up in errata tool. We're waiting on https://issues.redhat.com/browse/CLOUDDST-29483

4.20: Stop signing

---

releases.yml

```
(asdas) asdas-mac:asdas$ python3 -c "import datetime; print(datetime.datetime.fromtimestamp(1745622717.51316, tz=datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%S+00:00'))"
2025-04-25T23:11:57+00:00
```

add basis.time

---

product.yml

we have an [image](https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.21/images/pf-status-relay-operator.yml) **pf-status-relay-operator** which is not listed in product.yml

added missing component

---

group.yml
images/openshift-enterprise-base-rhel9.yml
images/openshift-enterprise-base.yml
streams.yml

- Build in normal times
- Set network_mode to "open" because hermeto cannot deal with module_hotfixes
- Update golang references to latest available

Get 4.15 to build

---

group.ext.yml
plashet.yml
repos/openstack-17-for-rhel-9-rpms.yml
repos/rhel-10-appstream.yml
repos/rhel-10-baseos.yml
repos/rhel-10-highavailability.yml
repos/rhel-10-nfv.yml
repos/rhel-10-server-ose-rpms-embargoed.yml
repos/rhel-10-server-ose-rpms.yml
repos/rhel-8-appstream-rpms.yml
repos/rhel-8-baseos-rpms.yml
repos/rhel-8-fast-datapath-rpms.yml
repos/rhel-8-server-ose-rpms-embargoed.yml
repos/rhel-8-server-ose-rpms.yml
repos/rhel-9-appstream-rpms.yml
repos/rhel-9-baseos-rpms.yml
repos/rhel-9-codeready-builder-rpms.yml
repos/rhel-9-fast-datapath-rpms.yml
repos/rhel-9-rt-rpms.yml
repos/rhel-9-server-ironic-rpms.yml
repos/rhel-9-server-microshift-rpms.yml
repos/rhel-9-server-ose-rpms-embargoed.yml
repos/rhel-9-server-ose-rpms.yml
repos/rhel-96-appstream.yml
repos/rhel-96-baseos.yml
repos/rhel-96-highavailability.yml
repos/rhel-96-nfv.yml

Those repos will replace current repo definitions in group.yml.
`group.ext.yml` will be used to tell art-tools which additional files to load with group.yml.
Because old-style repo configs are not removed in this PR, merging this won't break things.

Add new-style repo config files

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile

Per [kube update](https://github.com/kubernetes/kubernetes/blob/master/go.mod#L61-L63), a new etcd version is needed.

bump(k8s): bump 4.21 builder image to etcd version 3.6.4

---

images/oadp-operator.yml

This reverts commit 2743d7a251367d1929a340cb2d06e712afe3caf2.
Depends-On: https://github.com/openshift/oadp-operator/pull/1966

Revert "oadp-1.4: operator use dev branch"

---

group.yml

fix: add trailing slash to baseurl entries (4.12)

---

group.yml

fix: add trailing slash to baseurl entries (4.17)

---

group.yml

fix: add trailing slash to baseurl entries (4.14)

---

group.yml

fix: add trailing slash to baseurl entries (4.15)

---

group.yml

fix: add trailing slash to baseurl entries (4.16)

---

images/dpu-intel-ipu-vsp.yml
images/driver-toolkit.yml
images/linuxptp-daemon.yml
images/openshift-enterprise-builder.yml
images/openshift-enterprise-haproxy-router.yml
images/openshift-kubernetes-nmstate-handler.yml
images/ose-agent-installer-api-server.yml
images/ose-agent-installer-csr-approver.yml
images/ose-agent-installer-node-agent.yml
images/ose-image-customization-controller.yml
images/ose-machine-config-operator.yml
images/ose-machine-os-images.yml
images/ovn-kubernetes-base.yml

Converted 11 images to hermetic mode following the GPG check fix in https://github.com/openshift-eng/art-tools/pull/2030. Two images remain in open mode due to specific technical constraints with active tickets tracking resolution.
**Before:** Images blocked from hermetic conversion due to GPG check failures with unsigned RPMs
**After:** 11 images successfully converted to hermetic mode, 2 remain blocked with documented issues
Successfully converted to hermetic mode (removed network_mode: open):
- images/dpu-intel-ipu-vsp.yml
- images/driver-toolkit.yml (+ added konflux cachi2 config)
- images/linuxptp-daemon.yml
- images/openshift-enterprise-builder.yml
- images/openshift-enterprise-haproxy-router.yml
- images/openshift-kubernetes-nmstate-handler.yml
- …

Enable hermetic mode for 11 images after GPG fix resolution

---

images/ose-aws-ebs-csi-driver.yml
images/ose-frr.yml

Convert ose-aws-ebs-csi-driver and ose-frr from network_mode: open to hermetic builds.

build(konflux): convert 2 images to hermetic mode

---

images/ose-aws-ebs-csi-driver.yml
images/ose-frr.yml

Convert ose-aws-ebs-csi-driver, ose-aws-efs-csi-driver, and ose-frr from network_mode: open to hermetic builds.

build(konflux): convert 2 CSI/networking images to hermetic mode

---

images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-base.yml
images/ovn-kubernetes-microshift.yml

openvswitch* RPMs are no longer pinned in ovn-kubernetes images in order to facilitate timely CVE and bug fix delivery.  Remove from exemptions.
Manual cherry-pick of https://github.com/openshift-eng/ocp-build-data/pull/6716.
4.18 ovn-k PR that removed the OVS pin: https://github.com/openshift/ovn-kubernetes/pull/2646 ([relevant diff](https://github.com/openshift/ovn-kubernetes/pull/2646/files#diff-8f5e5cdf9d8c402d512a6f0cc8b414617cd93c533d36b90ea46def15909f28af))

[openshift-4.18] CORENET-5975: ovn-kubernetes: Remove exemptions for now unpinned OVS rpms.

---

images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-base.yml
images/ovn-kubernetes-microshift.yml

openvswitch* RPMs are no longer pinned in ovn-kubernetes images in order to facilitate timely CVE and bug fix delivery.  Remove from exemptions.
Manual cherry-pick of https://github.com/openshift-eng/ocp-build-data/pull/7227 due to conflicts on the `delivery:` section.
4.16 ovn-k PR that removed the OVS pin: https://github.com/openshift/ovn-kubernetes/pull/2648.

[openshift-4.16] CORENET-5975: ovn-kubernetes: Remove exemptions for now unpinned OVS rpms.

---

images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-base.yml
images/ovn-kubernetes-microshift.yml

openvswitch* RPMs are no longer pinned in ovn-kubernetes images in order to facilitate timely CVE and bug fix delivery.  Remove from exemptions.
Manual cherry-pick of https://github.com/openshift-eng/ocp-build-data/pull/7226 due to conflicts with Libreswan still being pinned in 4.17.
4.17 ovn-k PR that removed the OVS pin: https://github.com/openshift/ovn-kubernetes/pull/2647.

[openshift-4.17] CORENET-5975: ovn-kubernetes: Remove exemptions for now unpinned OVS rpms.

---

images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-base.yml
images/ovn-kubernetes-microshift.yml

openvswitch* RPMs are no longer pinned in ovn-kubernetes images in order to facilitate timely CVE and bug fix delivery.  Remove from exemptions.
4.15 ovn-k PR that removed the OVS pin: https://github.com/openshift/ovn-kubernetes/pull/2649

[openshift-4.15] CORENET-5975: ovn-kubernetes: Remove exemptions for now unpinned OVS rpms.

---

group.yml
images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-base.yml
images/ovn-kubernetes-microshift.yml

Cleaning up some mess, as Libreswan was unpinned and the pinned back:
* https://github.com/openshift/ovn-kubernetes/pull/2678
* https://github.com/openshift/os/pull/1849
Not a full revert of https://github.com/openshift-eng/ocp-build-data/pull/7182 as we're keeping the consistency requirement between ovn-k and rhcos.
CC: @joepvd

[openshift-4.18] Re-add exemptions for Libreswan as it was pinned back in 4.18 ovn-k.

---

images/openshift-enterprise-hyperkube.yml
images/openstack-resource-controller.yml
images/ose-insights-runtime-extractor.yml

Convert 3 images from network_mode: open to hermetic mode by removing konflux network_mode configuration, allowing them to use the default hermetic build isolation.
**Before:** Three images (openshift-enterprise-hyperkube, ose-insights-runtime-extractor, and openstack-resource-controller) were configured with network_mode: open in their konflux section, allowing network access during builds.
**After:** Images now use the default hermetic mode, providing build isolation and improved security by preventing network access during container builds.
- images/openshift-enterprise-hyperkube.yml - Removed network_mode: open, added basic cachi2 lockfile config
- images/ose-insights-runtime-extractor.yml - Removed network_mode: open, updated RPM lockfile with proper package list
- …

build(konflux): convert 3 images from network_mode open to hermetic

---

images/openshift-enterprise-builder.yml
images/openshift-enterprise-egress-dns-proxy.yml
images/openshift-enterprise-egress-router.yml
images/openshift-enterprise-haproxy-router.yml
images/openshift-enterprise-keepalived-ipfailover.yml
images/openshift-enterprise-operator-sdk.yml
images/openshift-enterprise-pod.yml
images/openshift-enterprise-registry.yml
images/openshift-enterprise-tests.yml

Proposing to stop the network_mode trick for some images in 4.17. 4.17, because we're not producing a zstream release in the next week. Aim is to either have things work, or to create errors that are fixable.
When fixing an error, please try and see if this fix could/should be applied to other ystreams. As an overview:
| image                                          | 4.12 | 4.13 | 4.14 | 4.15 | 4.16 | 4.17 | 4.18 | 4.19   | 4.20   | 4.21   |
| ---------------------------------------------- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ------ | ------ | ------ |
| openshift-enterprise-builder.yml               | open | open | open | open | open | open | open | closed | closed | closed |
| openshift-enterprise-egress-dns-proxy.yml      | open | open | open | open | open | open | open …

4.17: Set network_mode to hermetic for some
