openshift-eng/ocp-build-data

product.yml

MON-3270: Add kube-metrics-server mapping

---

images/ose-ovn-kubernetes.yml

...to follow https://github.com/openshift/ovn-kubernetes/pull/1759

ovn: Add rhel7 builder layer

---

rpms/microshift.yml

Ref. https://issues.redhat.com/browse/ART-6671

[4.14] Add rhel_targets for microshift configuration

---

images/ose-sdn.yml

Needed after https://github.com/openshift/sdn/commit/b3fd83d5858512ee16a1cb448d7ad0e57c46ccd6

Add missing build stage

---

images/ose-sdn.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/3258

[4.6] Add missing build stage to ose-sdn

---

images/ose-sdn.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/3258

[4.7] Add missing build stage to ose-sdn

---

README.md

_description in JIRA:_ [ART-7275](https://issues.redhat.com/browse/ART-7275)

ART-7275 - Rename Slack channels to match new conventions

---

group.yml

Rename release_state into software_lifecycle

---

images/ose-sdn.yml

..to follow https://github.com/openshift/sdn/pull/564

Add cli base image for sdn

---

images/ose-multus-route-override-cni.yml

Add RHEL9 builder for route-override-cni as #3151

Add RHEL9 builder for route-override-cni

---

.github/workflows/validate.yaml

Use https://github.com/openshift-eng/ocp-build-data-validator/pull/102

Use flag to skip VPN validations

---

images/linuxptp-daemon.yml

update Dockerfile reference for d/s build from Dockerfile.rhel7 to Dockerfile.ocp

Bug OCPBUGS-15370: update Dockerfile reference for downstream build

---

bug.yml

4.14 is not GA, comment out z stream release versions

update target_release versions

---

images/linuxptp-daemon.yml

Rebase succeeded in https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/45597/console

[4.14] Add missing build stage to ptp

---

images/ose-azure-workload-identity-webhook.yml

Ref https://issues.redhat.com/browse/ART-7323

[ART-7323] add ose-azure-workload-identity-webhook image

---

images/local-storage-mustgather.yml

re https://github.com/openshift/local-storage-operator/pull/416

add deps for local storage operator

---

images/local-storage-mustgather.yml

...to follow https://github.com/openshift/local-storage-operator/pull/420

Fix rebase local-storage-mustgather

---

group.yml

Reverts openshift-eng/ocp-build-data#3413

Revert "[openshift-4.10] [ART-7474] Set freeze_automation to weekdays"

---

group.yml

Add configuration to use https://github.com/openshift-eng/art-tools/pull/22

[ART-7318] introduce pre-release operator_index_mode

---

group.yml

Reverts openshift-eng/ocp-build-data#3423

Revert "Freeze 4.15 automation"

---

images/local-storage-mustgather.yml

https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/46362/

[4.14] local-storage-mustgather: actually fix bundle/name

---

images/cloud-event-proxy.yml
images/local-storage-mustgather.yml

to match 4.14 after https://github.com/openshift-eng/ocp-build-data/pull/3462

[4.15] update operand cdn/bundle name to match errata

---

images/ose-etcd.yml
streams.yml

To follow https://github.com/openshift/etcd/pull/212

4.13: etcd to rhel9

---

images/sriov-cni.yml

To follow https://github.com/openshift/sriov-cni/pull/83

sriov-cni to rhel9

---

images/ingress-node-firewall-daemon.yml

ingress-node-firewall to rhel9

---

images/kube-rbac-proxy.yml
images/node-feature-discovery.yml

Follow up to https://github.com/openshift-eng/ocp-build-data/pull/3481

4.14 - Enable nfd operator as dependent

---

images/kube-rbac-proxy.yml
images/node-feature-discovery.yml

Follow up to https://github.com/openshift-eng/ocp-build-data/pull/3482

[4.15] Enable nfd operator as dependent

---

images/sriov-cni.yml

...to be reverted when https://issues.redhat.com/browse/CWFCONF-5362 resolves

Build on rhel8 branch for now

---

images/linuxptp-daemon.yml

update CI build root stream for linuxptp-daemon

---

images/sriov-cni.yml

Reverts openshift-eng/ocp-build-data#3486

Revert "Build on rhel8 branch for now"

---

group.yml
images/openshift-golang-builder.Dockerfile
images/openshift-golang-builder.yml

add go wrapper during golang build process, the wrapper script will get from https://github.com/openshift-eng/doozer/pull/811

[ART-7273] add modifications to support go 1.19 rhel9 wrapper

---

images/openshift-golang-builder.Dockerfile
images/openshift-golang-builder.yml

add go wrapper during golang build process, the wrapper script will get from https://github.com/openshift-eng/doozer/pull/811

[ART-7273] add modifications to support go 1.19 rhel8 wrapper

---

group.yml
images/openshift-golang-builder.Dockerfile
images/openshift-golang-builder.yml

add go wrapper during golang build process, the wrapper script will get from https://github.com/openshift-eng/doozer/pull/811

[ART-7273] add modifications to support go 1.18 rhel8 wrapper

---

images/sriov-cni.yml

Cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/3529 with merge conflict fixes

sriov-cni: update name for rhel9

---

product.yml

Slack [ref](https://redhat-internal.slack.com/archives/CB95J6R4N/p1695061563894649)

Update ose-vertical-pod-autoscaler product mapping

---

product.yml

/cc @openshift/storage
Should go in after https://issues.redhat.com/browse/ART-7545

Add ose-secrets-store-csi-mustgather-container to product.yml

---

images/openshift-kubernetes-nmstate-handler.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-agent-installer-node-agent.yml

cherry-pick of #3541 and related missing commits

[4.15] rhel9 builds should happen in rhel9 branches/tags

---

releases.yml

Cleanup from https://github.com/openshift-eng/ocp-build-data/pull/3555

Remove test assembly

---

releases.yml

[4.14][ART-7318] make everything ship to prerelease tags for now

---

images/ose-kube-metrics-server.yml

Upstream was not matching downstream.
Slack [convo](https://redhat-internal.slack.com/archives/CB95J6R4N/p1695827602955389)
_Ready to merge. Requesting lgtm and approve_

ose-kube-metrics-server.yml Update payload_name to match upstream

---

images/openshift-enterprise-hyperkube.yml

https://issues.redhat.com/browse/ART-7821
Re https://github.com/openshift/kubernetes/pull/1703

ART-7821 4.14 - Migrate hyperkube build to rhel9

---

group.yml

Reverts openshift-eng/ocp-build-data#3605

Revert "Suspend builds for 4.15"

---

group.yml

Reverts openshift-eng/ocp-build-data#3607

Revert "Suspend builds"

---

releases.yml

[Context](https://redhat-internal.slack.com/archives/CJARLA942/p1696533424205099)

Rebuild cri-tools to have new tests running

---

group.yml

Reverts openshift-eng/ocp-build-data#3614

Revert "Suspend automation"

---

images/ose-baremetal-cluster-api-controllers.yml

Test build: [ose-baremetal-cluster-api-controllers-container-v4.15.0-202310041321.p0.gf8ed8db.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2704183)

ART-7859 Add cluster-api-provider-metal3

---

releases.yml

ref slack [thread](https://redhat-internal.slack.com/archives/CB95J6R4N/p1697122268631459)

rc.5 microshift rebuild with a specific commit

---

images/dpu-network-operator.yml
images/kube-rbac-proxy.yml

Ref https://issues.redhat.com/browse/OCPBUGS-18967

Stop building dpu-network-operator

---

group.yml
images/openshift-golang-builder.yml

Picking these fixes
- https://github.com/openshift-eng/ocp-build-data/pull/3694
- https://github.com/openshift-eng/ocp-build-data/pull/3692
requesting /lgtm

[rhel-8-golang-1.19] Tag into hotfix tags; update wrapper script path; update repo path

---

group.yml
images/openshift-golang-builder.yml

Picking these fixes
- https://github.com/openshift-eng/ocp-build-data/pull/3694
- https://github.com/openshift-eng/ocp-build-data/pull/3692
requesting /lgtm

[rhel-9-golang-1.19] Tag into hotfix tags; update wrapper script path; update repo path

---

group.yml
images/openshift-golang-builder.yml

Cherrypick https://github.com/openshift-eng/ocp-build-data/pull/3702

[rhel-8-golang-1.20] Tag into hotfix tags; update wrapper script path; update repo path

---

group.yml
images/openshift-golang-builder.yml

Cherrypick https://github.com/openshift-eng/ocp-build-data/pull/3703

[rhel-9-golang-1.20] Tag into hotfix tags; update wrapper script path; update repo path

---

images/sriov-network-config-daemon.yml
images/sriov-network-device-plugin.yml
images/sriov-network-operator.yml
images/sriov-network-webhook.yml

To follow:
- https://github.com/openshift/sriov-network-operator/pull/831
cc @bn222, @joepvd

sriov-network-operator to rhel9

---

images/openshift-base-nodejs.yml
images/openshift-base-rhel8.yml
images/openshift-base-rhel9.yml

Reverts openshift-eng/ocp-build-data#3641

Revert "ART-7945 4.14 ocp-build-data moved to openshift-eng"

---

images/openshift-base-nodejs.yml
images/openshift-base-rhel8.yml

Reverts openshift-eng/ocp-build-data#3638

Revert "ART-7945 4.10 ocp-build-data moved to openshift-eng"

---

images/openshift-base-nodejs.yml
images/openshift-base-rhel8.yml
images/openshift-base-rhel9.yml

Reverts openshift-eng/ocp-build-data#3718

ART-7945 4.12 ocp-build-data moved to openshift-eng

---

images/openshift-base-nodejs.yml
images/openshift-base-rhel8.yml
images/openshift-base-rhel9.yml

Reverts openshift-eng/ocp-build-data#3721

ART-7945 4.15 ocp-build-data moved to openshift-eng

---

images/openshift-base-nodejs.yml
images/openshift-base-rhel8.yml
images/openshift-base-rhel9.yml

Reverts openshift-eng/ocp-build-data#3720

ART-7945 4.14 ocp-build-data moved to openshift-eng

---

images/openshift-base-nodejs.yml
images/openshift-base-rhel8.yml
images/openshift-base-rhel9.yml

Reverts openshift-eng/ocp-build-data#3719

ART-7945 4.13 ocp-build-data moved to openshift-eng

---

images/openshift-base-nodejs.yml
images/openshift-base-rhel8.yml
images/openshift-base-rhel9.yml

Reverts openshift-eng/ocp-build-data#3717

ART-7945 4.11 ocp-build-data moved to openshift-eng

---

images/openshift-base-nodejs.yml
images/openshift-base-rhel8.yml

Reverts openshift-eng/ocp-build-data#3716

ART-7945 4.10 ocp-build-data moved to openshift-eng

---

group.yml
images/openshift-golang-builder.yml

fix config for golang builder job

ART-7952 Tag into hotfix tags; update wrapper script path; update repo path

---

images/ose-apiserver-network-proxy.yml

ref [thread](https://redhat-internal.slack.com/archives/CB95J6R4N/p1697816973514759)

Fix ose-apiserver-network-proxy branch

---

rpms/microshift.yml

fix microshift_sync job https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fmicroshift_sync/36/

Update microshift target config

---

images/atomic-openshift-descheduler.yml
images/ose-cluster-kube-descheduler-operator.yml

As per honeybadger [config](https://gitlab.cee.redhat.com/pipeline/products/-/merge_requests/2101/diffs#8a9ee5d2f11a8c2805d7ba7484cddcc8e2fb5ad2)
Follow up for https://github.com/openshift-eng/ocp-build-data/pull/3777
_Requesting lgtm and approve_

fix deschedular comet repo names

---

images/multus-cni.yml

align with https://github.com/openshift/multus-cni/blob/release-4.10/Dockerfile.openshift#L12

disable alignment pr

---

images/ose-cluster-kube-descheduler-operator.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/3777

4.15 ose-cluster-kube-descheduler-operator: use rhel9 distgit branch

---

product.yml

Adding this so bugs like https://issues.redhat.com/browse/OCPBUGS-22376 will make it to the right team.

ose-baremetal-operator-container mapping

---

releases.yml

Context: https://redhat-internal.slack.com/archives/C04L1FPFHNH/p1698402382297929?thread_ts=1698401774.546859&cid=C04L1FPFHNH

Exclude bugs

---

images/ose-cluster-config-api.yml

test build: [ose-cluster-config-api-container-v4.15.0-202310250440.p0.gd294dff.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2749469)

ART-7999 add ose-cluster-config-api

---

group.yml
images/openshift-golang-builder.yml

- fix repo path
- add fips wrapper

Fix 1.16 rhel7 golang-builder

---

images/ose-cluster-config-api.yml

To match [upstream](https://github.com/openshift/release/blob/5432a823855a87a6c5347cd0ba0a83d6066f14c0/ci-operator/config/openshift/api/openshift-api-master.yaml#L20)

[cluster-config-api] remove -rhel9 suffix

---

releases.yml

ref [slack](https://redhat-internal.slack.com/archives/CB95J6R4N/p1699543711615689?thread_ts=1699520432.946729&cid=CB95J6R4N)

Promotion permit for 4.14.2

---

images/openshift-kubernetes-nmstate-operator.yml

Reverts openshift-eng/ocp-build-data#3867

Revert "Enable kubernetes-nmstate-operator"

---

product.yml

Request to add the installer-altinfra image to the release payload.

ART-8233: Add installer-altinfra to product build.

---

images/ose-installer-altinfra.yml

test build [ose-installer-altinfra-container-v4.15.0-202311100549.p0.gf60ebb0.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2774417)

ART-8233 add ose-installer-altinfra

---

images/cluster-node-tuning-operator.yml
images/driver-toolkit.yml
images/ose-baremetal-cluster-api-controllers.yml
images/ose-cluster-config-api.yml
images/ose-etcd.yml
images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-microshift.yml

Shipped to the rhel9 suffixed cdn repos in 4.15

append -rhel9

---

group.yml
images/openshift-golang-builder.Dockerfile
images/openshift-golang-builder.yml

- [ART-8111](https://issues.redhat.com/browse/ART-8111)
- [golang-1.21.3-4.el8_9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2770478)
- https://brew-task-repos.engineering.redhat.com/repos/official/golang/1.21.3/4.el8_9/

ART-8111 Update rhel-8-golang-1.21 branch

---

streams.yml

[ART-8111](https://issues.redhat.com/browse/ART-8111)

4.15 - ART-8111 Define golang-1.21 streams

---

group.yml
images/openshift-golang-builder.Dockerfile
images/openshift-golang-builder.yml

https://issues.redhat.com/browse/ART-8370

ART-8370 Update golang-1.18 with fips wrapper

---

images/ose-cli-artifacts.yml

Requires https://github.com/openshift/oc/pull/1609

[ART-8372] Build el7 oc in 4.11

---

images/ose-machine-os-images.yml

Build machine-os -images for s390x. Don't specify which architectures to build, thereby building all of them.

MULTIARCH-4040: Add all arches for Agent Install

---

releases.yml

Reverts openshift-eng/ocp-build-data#3964

Revert "Pin dtk until newer rhcos"

---

rpms/microshift.yml
rpms/openshift-ansible.yml
rpms/openshift-clients.yml
rpms/openshift.yml
rpms/openshift4-aws-iso.yml

Reverts openshift-eng/ocp-build-data#3982

Revert "[openshift-4.16] [sast-scan] Enable OCPBUGS workflow for RPMs"

---

releases.yml

Reverts openshift-eng/ocp-build-data#3988

Revert "Allow conflicting rpms in rhcos for stream assembly"

---

group.yml

[4.12] enable SAST OCPBUGS workflow

---

images/openshift-enterprise-tests.yml
images/ose-machine-config-operator.yml
images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-base.yml
images/ovn-kubernetes-microshift.yml
releases.yml

Start using pattern matching and new config key https://github.com/openshift-eng/art-tools/pull/237

4.16 - Pattern match exempt rpms

---

streams.yml

https://issues.redhat.com/browse/ART-8307
Following up from https://github.com/openshift-eng/ocp-build-data/pull/3935

ART-8307 4.16 - Bump to go1.21

---

images/kuryr-cni.yml
images/kuryr-controller.yml
images/openshift-base-nodejs.yml
images/openshift-enterprise-tests.yml
images/ose-machine-config-operator.yml
images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-base.yml
images/ovn-kubernetes-microshift.yml
releases.yml

Cherrypick https://github.com/openshift-eng/ocp-build-data/pull/4024

4.13 - Pattern match exempt rpms

---

images/kuryr-cni.yml
images/kuryr-controller.yml
images/openshift-base-nodejs.yml
images/openshift-enterprise-tests.yml
images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-base.yml
images/ovn-kubernetes-microshift.yml
releases.yml

Cherrypick https://github.com/openshift-eng/ocp-build-data/pull/4024

4.12 - Pattern match exempt rpms

---

images/kuryr-cni.yml
images/kuryr-controller.yml
images/openshift-base-nodejs.yml
images/openshift-enterprise-tests.yml
images/ose-ovn-kubernetes.yml
releases.yml

Cherrypick https://github.com/openshift-eng/ocp-build-data/pull/4024

4.11 - Pattern match exempt rpms

---

images/ose-cli-artifacts.yml

To build RHEL9 oc https://github.com/openshift/oc/pull/1632

OCPBUGS-23386: add rhel-9-golang in cli artifacts stream

---

product.yml

correctly direct bugs like https://issues.redhat.com/browse/OCPBUGS-25288 and https://issues.redhat.com/browse/OCPBUGS-25289

product.yml: add catch and fmt

---

erratatool.yml

Follow up to https://github.com/openshift-eng/art-tools/pull/239

4.11 - Cleanup erratatool.yml

---

images/ose-baremetal-installer.yml
images/ose-installer-artifacts.yml
images/ose-installer-terraform-providers.yml
images/ose-installer.yml

Cherrypick https://github.com/openshift-eng/ocp-build-data/pull/3996/ 
context: https://github.com/openshift-eng/ocp-build-data/pull/4089

ART-8419 4.16 - Introduce installer-terraform-providers base image

---

images/ose-sdn.yml

https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2810803
For use with https://github.com/openshift/sdn/pull/593

OCPBUGS-25036:  Use openshift-clients rpm

---

releases.yml

Reverts openshift-eng/ocp-build-data#4091

Revert "Pin old installer"

---

images/openshift-enterprise-haproxy-router.yml
images/ose-haproxy-router-base.yml

Should merge after https://github.com/openshift/router/pull/548

4.16 - Move router base image to rhel9

---

images/ironic-agent.yml
images/ironic.yml

Reverts openshift-eng/ocp-build-data#4093

Revert "Stop ironic rebuilds"

---

erratatool.yml

Supports https://github.com/openshift-eng/art-tools/pull/263

4.16 - Set preGA advisory release

---

group.yml

[scan-osh] activate for 4.14

---

group.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/4152

[group.yml] remove operator index mode

---

group.yml

4.14-4.16 have been enabled so far.

[scan-osh] enable for 4.13

---

releases.yml

Add missing upgrade edges for promote

Add upgrade edges

---

group.yml

[scan-osh] activate for 4.12

---

rpms/ose-aws-ecr-image-credential-provider.yml

RPM add ose-aws-ecr-image-credential-provider

---

group.yml

Cherrypick https://github.com/openshift-eng/ocp-build-data/pull/4174

Temporarily freeze automation to batch mass rebuild

---

releases.yml

exclude OCPBUGS-14708 from 4.12.47

---

images/ose-azure-disk-csi-driver-operator.yml

https://issues.redhat.com/browse/STOR-1713

STOR-1713: Move azure disk operator to csi-operator repo

---

group.yml

Reverts openshift-eng/ocp-build-data#4176

4.14 - Revert "Temporarily freeze automation to batch mass rebuild"

---

group.yml

Reverts openshift-eng/ocp-build-data#4174

4.15 - Revert "Temporarily freeze automation to batch mass rebuild"

---

rpms/ose-aws-ecr-image-credential-provider.yml

Update ose-aws-ecr-image-credential-provider path to priv

---

images/oc-mirror-plugin.yml

...to accompany https://github.com/openshift/oc-mirror/pull/767

oc-mirror both rhel8 and rhel9

---

releases.yml

[ose-baremetal-installer-container-v4.12.0-202401171701.p0.g3f1b29d.assembly.art8712](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2854666)
green [build-sync](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync/40952/console)

Add assembly for ART-8712

---

erratatool.yml

cherrypick https://github.com/openshift-eng/ocp-build-data/pull/4214

4.16 - Set prerelease advisory to auto

---

images/ose-frr.yml

Add builder to match upstream change https://github.com/openshift/frr/commit/3c2f9cf65219a53fc0b7d3ca10d47afcfc45e26c

4.16 - ose-frr Add builder to match upstream

---

releases.yml

4.11 - Fix release schema

---

erratatool.yml

To support https://github.com/openshift-eng/art-tools/pull/343

Enable advisory type comment

---

erratatool.yml

To support https://github.com/openshift-eng/art-tools/pull/343

4.13 - Enable advisory type comment (#4247)

---

ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

context: https://github.com/openshift-eng/ocp-build-data/pull/4268

Pin git for CI

---

group.yml

Freeze automation temporarily 

---

group.yml

Reverts openshift-eng/ocp-build-data#4313

Revert "Freeze automation temporarily "

---

group.yml

Reverts openshift-eng/ocp-build-data#4314

Revert "[openshift-4.13] Freeze automation temporarily "

---

group.yml

Reverts openshift-eng/ocp-build-data#4315

Revert "[openshift-4.12] Freeze automation temporarily "

---

group.yml

Reverts openshift-eng/ocp-build-data#4316

Revert "[openshift-4.11] Freeze automation temporarily "

---

images/azure-file-csi-driver-operator.yml
images/csi-driver-manila-operator.yml
images/ose-alibaba-disk-csi-driver-operator.yml
images/ose-aws-efs-csi-driver-operator.yml
images/ose-cluster-ovirt-csi-operator.yml
images/ose-csi-driver-shared-resource-operator.yml
images/ose-gcp-filestore-csi-driver-operator.yml
images/ose-gcp-pd-csi-driver-operator.yml
images/ose-ibm-vpc-block-csi-driver-operator.yml
images/ose-openstack-cinder-csi-driver-operator.yml
images/ose-powervs-block-csi-driver-operator.yml
images/ose-vmware-vsphere-csi-driver-operator.yml

with alternative config for rhel8 to drive the change upstream first

[ART-8354] migrate csi drivers to rhel9

---

images/ose-cli-artifacts.yml

[Upstream](https://github.com/openshift/oc/blob/release-4.15/images/cli-artifacts/Dockerfile.rhel) has only 2 from statements
Fix following https://github.com/openshift-eng/ocp-build-data/pull/4303

Fix cli-artifacts from statements

---

releases.yml

ref: https://redhat-internal.slack.com/archives/GDBRP5YJH/p1707106407422309?thread_ts=1706885322.210349&cid=GDBRP5YJH

exclude bugs for 4.15 rc

---

releases.yml

Will drop advance after preparing pre-release advisory

Add prerelease

---

product.yml

This should catch Jiras like this one: https://issues.redhat.com/browse/OCPBUGS-25960

Another component for the security profiles operator maintainers

---

images/ci-openshift-base.rhel8.yml
images/ci-openshift-base.rhel9.yml
images/ci-openshift-build-root-extra.rhel9.disabled
images/ci-openshift-build-root-latest.rhel8.yml
images/ci-openshift-build-root-latest.rhel9.yml
images/ci-openshift-build-root-previous.rhel8.yml
images/ci-openshift-build-root-previous.rhel9.yml
images/ci-openshift-golang-builder-extra.rhel9.disabled
images/ci-openshift-golang-builder-latest.rhel8.yml
images/ci-openshift-golang-builder-latest.rhel9.yml
images/ci-openshift-golang-builder-previous.rhel8.yml
images/ci-openshift-golang-builder-previous.rhel9.yml

Fixes error`doozerlib.exceptions.DoozerFatalError: Requested target branch openshift-4-16 does not exist and no fallback provided`

Fix target branch path

---

ci_images/dnf_wrapper.sh
images/ci-openshift-base.rhel8.yml
images/ci-openshift-base.rhel9.yml

KUBERNETES_SERVICE_HOST was either racey or not set in build pods.

Use a different method to detect running in pod

---

images/ose-openshift-controller-manager.yml

Follows upstream change https://github.com/openshift/openshift-controller-manager/pull/283

Bump openshift-controller-manager to go1.21

---

images/ci-openshift-golang-builder-extra.yml
images/ci-openshift-golang-builder-latest.yml
images/ci-openshift-golang-builder-previous.yml
images/egress-router-cni.yml
images/multus-cni.yml
images/ose-containernetworking-plugins.yml
images/ose-multus-route-override-cni.yml
images/ose-multus-whereabouts-ipam-cni.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/4383 in 4.15

[4.15] Fix misplaced ci_alignment PR disabling

---

images/azure-file-csi-driver.yml

Supersedes https://github.com/openshift-eng/ocp-build-data/pull/4398

Switch azure-file to csi-operator

---

images/ose-nutanix-machine-controllers.yml

Reverts openshift-eng/ocp-build-data#4347

Revert "Temporarily disable cachito gomod handling for nutanix-machine-controllers"

---

images/azure-file-csi-driver-operator.yml
images/cluster-etcd-operator.yml
images/cluster-storage-operator.yml
images/cluster-version-operator.yml
images/csi-driver-manila-operator.yml
images/local-storage-diskmaker.yml
images/local-storage-mustgather.yml
images/local-storage-operator.yml
images/ose-aws-efs-csi-driver-operator.yml
images/ose-cluster-autoscaler-operator.yml
images/ose-cluster-cloud-controller-manager-operator.yml
images/ose-cluster-control-plane-machine-set-operator.yml
images/ose-cluster-csi-snapshot-controller-operator.yml
images/ose-csi-driver-shared-resource-operator.yml
images/ose-gcp-filestore-csi-driver-operator.yml
images/ose-gcp-pd-csi-driver-operator.yml
images/ose-ibm-cloud-controller-manager.yml
images/ose-ibm-vpc-block-csi-driver-operator.yml
images/ose-libvirt-machine-controllers.yml
images/ose-machine-api-operator.yml
images/ose-machine-api-provider-aws.yml
images/ose-machine-api-provider-azure.yml
images/ose-machine-api-provider-gcp.yml
images/ose-openstack-cinder-csi-driver-operator.yml
images/ose-powervs-block-csi-driver-operator.yml
images/ose-vmware-vsphere-csi-driver-operator.yml
images/vsphere-problem-detector.yml

Reverts PRs after [STONEBLD-1973](https://issues.redhat.com/browse/STONEBLD-1973) resolved:
- https://github.com/openshift-eng/ocp-build-data/pull/4295
- https://github.com/openshift-eng/ocp-build-data/pull/4379
- https://github.com/openshift-eng/ocp-build-data/pull/4362
- https://github.com/openshift-eng/ocp-build-data/pull/4327
- https://github.com/openshift-eng/ocp-build-data/pull/4305

[4.16] re-enable cachito processing

---

bug.yml

https://issues.redhat.com/browse/ART-9017

ART-9017 - Ignore lvms bugs

---

bug.yml

https://issues.redhat.com/browse/ART-9017

4.14 - Ignore lvms bugs

---

images/openshift-enterprise-deployer.yml
images/openshift-enterprise-haproxy-router.yml
images/openshift-enterprise-tests.yml
images/ose-agent-installer-api-server.yml
images/ose-agent-installer-csr-approver.yml
images/ose-aws-efs-csi-driver.yml
images/ose-baremetal-installer.yml
images/ose-cli-artifacts.yml
images/ose-csi-driver-shared-resource-mustgather.yml
images/ose-installer-artifacts.yml
images/ose-installer.yml
images/ose-machine-os-images.yml
images/ose-must-gather.yml
images/ose-network-tools.yml
images/ose-ovn-kubernetes.yml
images/ose-tools.yml
images/ovn-kubernetes-microshift.yml
images/ptp-operator-must-gather.yml

Reverts openshift-eng/ocp-build-data#4440

Revert "[4.16] Re-enable canonical builders for unresolved member images"

---

images/csi-livenessprobe.yml
images/csi-node-driver-registrar.yml
images/csi-provisioner.yml
images/ose-csi-external-resizer.yml
images/ose-gcp-filestore-csi-driver.yml

Reverts openshift-eng/ocp-build-data#4443

Revert "Move extra storage images to rhel9"

---

images/csi-livenessprobe.yml
images/csi-node-driver-registrar.yml
images/csi-provisioner.yml
images/ose-csi-external-resizer.yml
images/ose-gcp-filestore-csi-driver.yml

Reverts openshift-eng/ocp-build-data#4455

Revert "Revert "Revert "Move extra storage images to rhel9"""

---

images/csi-livenessprobe.yml
images/csi-node-driver-registrar.yml
images/csi-provisioner.yml
images/ose-csi-external-resizer.yml
images/ose-gcp-filestore-csi-driver.yml

Reverts openshift-eng/ocp-build-data#4456

Revert "Revert "Revert "Revert "Move extra storage images to rhel9""""

---

group.yml

Reverts openshift-eng/ocp-build-data#4467

Revert "Postpone mass rebuild until weekend"

---

images/linuxptp-daemon.yml

ref https://issues.redhat.com/browse/CWFCONF-8884

[CNF-11522] linuxptp: use pre-release content from candidate

---

group.yml

Explicitly define global canonical_builders_from_upstream and update comment

Explicitly define global canonical_builders_from_upstream

---

releases.yml

See https://issues.redhat.com/browse/CWFCONF-8917
does not block promotion

Permit invalid errata status

---

group.yml

Reverts openshift-eng/ocp-build-data#4468

Revert "[openshift-4.11] Postpone mass rebuild until weekend"

---

images/sriov-cni.yml

Needed after https://github.com/openshift/sriov-cni/pull/97

[4.16] Fix sriov-cni-rebase

---

images/ib-sriov-cni.yml

Needed after https://github.com/openshift/ib-sriov-cni/pull/46

[4.16] add missing build stage to ib-sriov-cni

---

group.yml

ref https://github.com/openshift-eng/ocp-build-data/pull/4493

remove machine-os-content

---

modifications/microshift-rebase

test job: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift/13/console

fix microshift-rebase

---

images/ose-aws-efs-csi-driver.yml
images/ose-aws-efs-utils.yml

Green [run](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/ashwin-aos-cd-jobs/job/build%252Focp4/9/console)

[ART-9189] rhel9 move ose-aws-efs images

---

streams.yml

https://issues.redhat.com/browse/ART-9185

Bump builders to latest 1.19.13 builds

---

streams.yml

https://issues.redhat.com/browse/ART-9185

4.16 - Bump builders to latest 1.20.12 and 1.19.13

---

images/monitoring-plugin.yml
images/nmstate-console-plugin.yml
images/openshift-base-nodejs.rhel9.yml
images/openshift-enterprise-console.yml

Green [run](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/ashwin-aos-cd-jobs/job/build%252Focp4/10/)

[ART-8355] nodesjs images inherit from rhel9

---

group.yml

Cherrypick https://github.com/openshift-eng/ocp-build-data/pull/4557

4.14 - Enable rpm check between candidate tag and rhcos

---

images/ose-cli-artifacts.yml

fix ose-cli-artifacts

---

images/openshift-enterprise-hyperkube.yml
images/openshift-enterprise-pod.yml
rpms/openshift.yml

Alongside https://github.com/openshift-eng/art-tools/pull/515

Configuration tweak

---

images/networking-console-plugin.yml

Test build: [networking-console-plugin-container-v4.16.0-202403271304.p0.g0719a22.assembly.test.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2976182)

ART-9115  Add networking-console-plugin

---

images/openshift-enterprise-hyperkube.yml
images/openshift-enterprise-pod.yml
rpms/openshift.yml

Reverts openshift-eng/ocp-build-data#4576

Revert "Configuration tweak"

---

images/ose-azure-storage-azcopy-base.yml

ref https://issues.redhat.com/browse/ART-8909

[ART-8909] base image add azcopy

---

images/ose-machine-config-operator.yml

Follows https://github.com/openshift/machine-config-operator/pull/4241

MCO match upstream

---

ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

This matches:
* https://github.com/kubernetes/kubernetes/blob/release-1.28/hack/lib/etcd.sh#L19
/assign @soltysh @jupierce

Update etcd to match k8s 1.28.8

---

product.yml

(I confirmed this with the apiserver team)

ose-installer-kube-apiserver-artifacts-container mapping

---

images/ose-azure-storage-azcopy-base.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/4651

Fix azure-storage-azcopy-base name

---

images/ose-cloud-credential-operator.yml

To follow https://github.com/openshift/cloud-credential-operator/pull/692

cloud-credential-operator: to rhel9

---

images/openshift-enterprise-tests.yml

align with https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.16/streams.yml#L114

fix ci stream name

---

images/ib-sriov-cni.yml

To follow https://github.com/openshift/ib-sriov-cni/pull/48

Fix ib-sriov-cni build

---

images/sriov-cni.yml

Follows https://github.com/openshift/sriov-cni/pull/97

[4.15] fix sriov-cni rebase

---

images/ose-agent-installer-csr-approver.yml

Follows https://github.com/openshift/assisted-installer/pull/760/files

[4.16] fix agent-installer-csr-approver

---

releases.yml

permit ATTACHED_BUGS

---

rpms/ose-azure-acr-image-credential-provider.yml
rpms/ose-gcp-gcr-image-credential-provider.yml

Adds build config for azure-acr-image-credential-provider and gcp-gcr-image-credential-provider

Adds {gcr,acr}-image-credential-provider

---

streams.yml

remove golang-1.21 stream from 4.15

---

images/dpu-cni.yml
images/dpu-daemon.yml
images/dpu-operator.yml
images/kube-rbac-proxy.yml

ref https://issues.redhat.com/browse/ART-9295
Test builds:
dpu-cni: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3017837
dpu-daemon: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3017838
dpu-operator: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3018014
HB MR: https://gitlab.cee.redhat.com/pipeline/products/-/merge_requests/2541

[ART-9295] dpu image adds

---

images/csi-livenessprobe.yml
images/csi-provisioner.yml
images/kube-rbac-proxy.yml
images/ose-smb-csi-driver-operator.yml
images/ose-smb-csi-driver.yml

Cherry picking https://github.com/openshift-eng/ocp-build-data/pull/4704

[ART-9294] [ART-9444] smb image add

---

product.yml

Add new operator: https://github.com/openshift/dpu-operator to product config.

Add dpu-operator to product config

---

images/dpu-cni.yml

To match https://github.com/openshift/dpu-operator/pull/57
Streams defined here: https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.16/streams.yml

dpu-cni bump builder to rhel9

---

images/ose-baremetal-installer.yml
images/ose-installer.yml

..and follow along with https://github.com/openshift/installer/pull/8242

Fix installer builds

---

images/ose-baremetal-installer.yml
images/ose-installer.yml

...to accompany https://github.com/openshift/installer/pull/8326

installer: oc from rpm

---

images/ose-must-gather.yml

To go with https://github.com/openshift/must-gather/pull/418

must-gather inherits from cli-artifacts

---

images/ose-agent-installer-api-server.yml
images/ose-agent-installer-csr-approver.yml

To go with:
- https://github.com/openshift/assisted-service/pull/5792
- https://github.com/openshift/assisted-installer/pull/760

agent-installer-api-server to rhel9

---

product.yml

[ose-smb-csi-driver-container](https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=86047)
[ose-smb-csi-driver-operator-container](https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=86049)

[ART-9294] [ART-9444] onboard ose-smb-csi-driver

---

images/openshift-enterprise-cli.yml
images/openshift-enterprise-deployer.yml
images/ose-cli-artifacts.yml
images/ose-tools.yml

..to follow https://github.com/openshift/oc/pull/1752

WRKLDS-1251: cli to rhel9

---

images/ose-installer-etcd-artifacts.yml

To follow https://github.com/openshift/etcd/pull/269

Fix installer etcd build

---

images/container-networking-plugins-microshift.yml
images/multus-cni-container-microshift.yml

This should now match https://gitlab.cee.redhat.com/pipeline/products/-/blob/master/products/rhose/rhel-9-rhose-4.16.yaml?ref_type=heads

Tweak microshift container names

---

group.yml
images/driver-toolkit.yml

Correct content sets declaration for dtk

---

images/aws-kms-encryption-provider.yml
images/azure-kms-encryption-provider.yml

added images for azure-kms-encryption-provider and aws-kms-encryption-provider
test job: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/1810/console
HB MRs:
aws: https://gitlab.cee.redhat.com/pipeline/products/-/merge_requests/2581 (merged)
azure: https://gitlab.cee.redhat.com/pipeline/products/-/merge_requests/2589 (pending)

added new images

---

images/ose-smb-csi-driver.yml

Fix `name` and `name_in_bundle`

[smb-csi-driver] fix name name_in_bundle

---

images/ose-alibaba-cloud-controller-manager.yml

[thread](https://redhat-internal.slack.com/archives/CB95J6R4N/p1715701719438189)

4.14: Stop alignment PRs alibaba-cloud-provider

---

releases.yml

Ref slack [thread](https://redhat-internal.slack.com/archives/C05FEGT8SH2/p1715868704973069?thread_ts=1715842880.388979&cid=C05FEGT8SH2)

pin openshift-kubernetes-nmstate-operator, ose-metallb-operator

---

releases.yml

Reverts openshift-eng/ocp-build-data#4870

Revert "[rc.2] fix ose-smb-csi-driver-operator bundle error"

---

streams.yml

[openshift-golang-builder-container-v1.22.2-202405221448.gd58751c.el8](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3070824) builder add

[ART-9118] add rhel-8-golang-1.22 builder

---

rpms/openshift-clients.yml

Requires https://github.com/openshift-eng/art-tools/pull/647

Enable openshift-clients rpm

---

images/kube-rbac-proxy.yml

Fix owners for images/kube-rbac-proxy.yml

---

images/ib-sriov-cni.yml

Following https://github.com/openshift/ib-sriov-cni/pull/51

Fix sriov-cni rebase

---

group.yml

To go along with https://github.com/openshift-eng/art-tools/pull/662

ART-9793 Introduce 'signing' release phase

---

images/ose-installer-altinfra.yml

To follow https://github.com/openshift/installer/pull/8471/files#diff-97154c9b6fb7ab7c0dc3aef2e57c49178cb60fa3944e9e0fa8b62d1a412b9246

Remove altinfra modification

---

images/cluster-version-operator.yml

slack [thread](https://redhat-internal.slack.com/archives/CB95J6R4N/p1718300336579269)

Move cvo to rhel-9-golang-1.21

---

product.yml

This component was recently created as part of https://issues.redhat.com/browse/DPP-14834

Mapping for networking-console-plugin-container

---

releases.yml

operator added after reference nightly picked for assembly

pin ose-sriov-network-metrics-exporter

---

releases.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/5004
Override doesn't work

override permits with {}

---

releases.yml

build-sync https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/4071/console

add permits for ec.1

---

images/ose-installer-altinfra.yml

to follow https://github.com/openshift/installer/pull/8470

Fix installer-altinfra rebase

---

images/ose-operator-framework-tools.yml

test build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3144660

ART-9441 add ose-operator-framework-tools.yml

---

images/openshift-base-nodejs.yml

Add ose rpms to the list of available ones for nodejs

add rhel-8-server-ose-rpms to openshift-base-nodejs

---

images/cluster-etcd-operator.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/5002
Add fallback for etcd

add dockerfile_fallback for etcd

---

images/ose-azure-workload-identity-webhook.yml

follows https://github.com/openshift-eng/ocp-build-data/pull/5035

[4.15] dockerfile_fallback for azure-workload

---

images/ose-azure-workload-identity-webhook.yml

follows https://github.com/openshift-eng/ocp-build-data/pull/5036

[4.14] dockerfile_fallback for azure-workload

---

ci_images/dnf_wrapper.sh

Suggested enhancement to replace https://github.com/openshift-eng/ocp-build-data/pull/5068

Allow default behavior overrides from dnf wrapper callers

---

group.yml

While it is figured out if we can go ahead with https://github.com/openshift-eng/ocp-build-data/pull/4975

Stop 4.12 automation

---

images/sriov-network-operator.yml

Reverts openshift-eng/ocp-build-data#5016

Revert "Stop building and shipping sriov-operator until backport of OCPBUGS-3…"

---

releases.yml

releases.yml: Change off to false

---

images/dpu-network-operator.yml
images/ingress-node-firewall-daemon.yml
images/ingress-node-firewall-operator.yml
images/kube-rbac-proxy.yml

Cherrypick these for 4.13
https://github.com/openshift-eng/ocp-build-data/pull/4938/files
https://github.com/openshift-eng/ocp-build-data/pull/4937/files

Disable operators that fail cvp tests

---

releases.yml

update 4.16.4 excludes

---

ci_images/rhel-9/ci-openshift-build-root/Dockerfile

ci-build-root: Add more packages

---

images/openshift-enterprise-registry.yml

To follow https://github.com/openshift/image-registry/pull/407

image-registry update dockerfile name

---

images/cluster-node-tuning-operator.yml
images/monitoring-plugin.yml
images/networking-console-plugin.yml
images/openshift-base-nodejs.rhel9.yml
images/openshift-base-nodejs.yml
images/openshift-base-rhel8.yml
images/openshift-base-rhel9.yml
images/openshift-enterprise-base-rhel9.yml
images/openshift-enterprise-base.yml
images/openshift-enterprise-keepalived-ipfailover.yml
images/openshift-enterprise-pod.yml
images/ose-etcd.yml
images/ose-installer-etcd-artifacts.yml
images/ose-machine-os-images.yml
streams.yml

Requires https://github.com/openshift-eng/art-tools/pull/491

OKD metadata additions

---

group.yml

signing advisory created: https://errata.devel.redhat.com/errata/details/136879

ART-10082: Create an own signing_advisory for 4.18

---

streams.yml

Reverts openshift-eng/ocp-build-data#5200

Revert "Update golang 1.19 for 4.16"

---

images/monitoring-plugin.yml

align with recent upstream change https://github.com/openshift/monitoring-plugin/commit/bf2a0bd0f730bdf767526bdaf3edb8be6c33da72

Update monitoring-plugin builder

---

OWNERS

add owners to rhel-9-golang-1.22

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile

allow nobest install
test job: https://download-01.beak-001.prod.iad2.dc.redhat.com/brewroot/work/tasks/4465/63304465/x86_64.log

fix ci image build

---

group.yml
streams.yml

Ref. https://issues.redhat.com/browse/ART-9391

ART-9391 [4.18] Update to ubi8 repos and base images

---

images/dpu-operator.yml

disable dpu-operator until upstream issue fix https://redhat-internal.slack.com/archives/GDBRP5YJH/p1723610445179879?thread_ts=1723600834.117959&cid=GDBRP5YJH

disable dpu-operator.yml

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile

test build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=63370494

upgrade pkgs to fix mismatch issue

---

images/coredns.yml

For https://github.com/openshift/coredns/pull/128

rename coredns dockerfile

---

images/openshift-enterprise-haproxy-router.yml
images/ose-haproxy-router-base.yml

Follow:
- https://github.com/openshift/router/pull/616

rename haproxy dockerfile

---

images/dpu-operator.yml

/hold
to be merged after https://github.com/openshift/dpu-operator/pull/130

[4.18] re-enable dpu-operator

---

images/monitoring-plugin.yml

this PR should only be merged after https://github.com/openshift/monitoring-plugin/pull/161 was merged

fetch right go version for cachito

---

group.yml

this PR should be merged after the RHCOS 4.18 exists
This ticket has to be closed before: https://issues.redhat.com/browse/COS-2881

ART-10051: update RHCOS to 4.18

---

images/pf-status-relay.yml

[pf-status-relay] add HB mapping

---

images/dpu-operator.yml

/hold
to be merged after https://github.com/openshift/dpu-operator/pull/132

[4.17] re-enable dpu-operator

---

ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

Matches https://github.com/kubernetes/kubernetes/blob/release-1.31/hack/lib/etcd.sh#L19
@bertinatto @soltysh

Update etcd to match k8s 1.31

---

images/ose-aws-efs-csi-driver-operator.yml
images/ose-tools.yml

require https://github.com/openshift/csi-operator/pull/264
test image build https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=63530942
test bundle build https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=63531377

enable ose-aws-efs-csi-driver-operator

---

group.yml

Reverts openshift-eng/ocp-build-data#5331

Revert "<temp> freeze 4.18 automation"

---

images/kube-compare-artifacts.yml

Reverts openshift-eng/ocp-build-data#5336

Revert "Revert "[chore] add initial work for new image kube-compare-artifacts-container""

---

product.yml

I think this minor problem was introduced as part of https://issues.redhat.com/browse/ART-9329

Fixing SR-IOV component mapping

---

images/ose-azure-storage-azcopy-base.yml

Add lgmt + approve + the right commit message prefix

4.17: Update PRs against openshift/azure-storage-azcopy

---

images/ose-azure-storage-azcopy-base.yml

Add lgmt + approve + the right commit message prefix to all automated PRs against openshift/azure-storage-azcopy repo.

4.18: Update PRs against openshift/azure-storage-azcopy

---

releases.yml

[4.12.66] repromote --force

---

releases.yml

ref [thread](https://redhat-internal.slack.com/archives/GDBRP5YJH/p1726561978771989)

4.17-rc.3 pre-release

---

group.yml

Reverts openshift-eng/ocp-build-data#5370

Revert "Freeze 4.12 automation"

---

product.yml

* Cloud Compute / Cloud Controller Manager
* Etcd
* Installer / openshift-installer
* LCA operator
* MicroShift
More info on this comment:
<https://issues.redhat.com/browse/OCPBUGS-18035?focusedId=25509941&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25509941>

Add component mappings

---

group.yml
images/marketplace-operator.yml

This will be required to build with Konflux.

marketplace-operator: Move to openshift-priv

---

releases.yml

pin cri-o version of rhcos

---

images/cloud-event-proxy.yml

This reverts commit d9377bde3e8b5cfb6fe1d4a588e57563e41d125b.
to unblock promote

Revert "use priv repo for cloud-event-proxy (#5480)"

---

images/cloud-event-proxy.yml

Reverts openshift-eng/ocp-build-data#5483

Revert "Revert "use priv repo for cloud-event-proxy (#5480)""

---

ci_transforms/rhel-8/ci-build-root/Dockerfile
ci_transforms/rhel-9/ci-build-root/Dockerfile

This matches https://github.com/kubernetes/kubernetes/blob/v1.30.5/hack/lib/etcd.sh#L19
/assign @joepvd @jerpeter1 @jupierce

Update etcd to match Kubernetes 1.30.5

---

images/gcp-workload-identity-federation-webhook.yml

test build https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3329442

ART-10787: add gcp-workload-identity-federation-webhook

---

group.yml

Reverts openshift-eng/ocp-build-data#5529

Revert "freeze 4.16 automation"

---

images/cluster-nfd-operator.yml
images/clusterresourceoverride-operator.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-metallb-operator.yml
images/ptp-operator.yml

Reverts openshift-eng/ocp-build-data#5481

Revert "[chore] disable few operators with wrong metadata.{name,version}"

---

product.yml

@JoelSpeed PTAL  not sure if below need to be updated to Cloud Compute / Cloud Controller Manager
```
ose-openstack-cloud-controller-manager-container:
issue_component: Installer / OpenShift on OpenStack
```

Update Cloud Compute components

---

images/gcp-workload-identity-federation-webhook.yml

waiting for staff engineer approval
https://issues.redhat.com/browse/ART-10787?focusedId=25961351&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25961351

ART-10787 disable gcp-workload-identity-federation-webhook.yml

---

images/ose-installer-etcd-artifacts.yml

Alongside https://github.com/openshift-eng/art-tools/pull/1095

[konflux] different dockerfile for konflux

---

images/ose-installer-etcd-artifacts.yml

cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/5587
scan-sources:noop [konflux] ose-installer-etcd-artifacts different dockerfile for konflux

[4.17] [konflux] different dockerfile for konflux

---

images/ose-installer-etcd-artifacts.yml

cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/5587
scan-sources:noop [konflux] ose-installer-etcd-artifacts different dockerfile for konflux

[4.16] [konflux] different dockerfile for konflux

---

images/ose-baremetal-installer.yml
images/ose-installer-altinfra.yml
images/ose-installer-artifacts.yml
images/ose-installer.yml
images/ose-machine-os-images.yml

Upstream PRs raised with etcd, the following images are now buildable. Tested and green build exists.

[konflux] Enable fixed images

---

group.yml

Freeze scheduled builds until ready

freeze 4.19 for now

---

group.yml

Reverts openshift-eng/ocp-build-data#5625

Revert "freeze 4.19 for now"

---

group.yml

Reverts openshift-eng/ocp-build-data#5634

Revert "Revert "freeze 4.19 for now""

---

streams.yml

...and leave that to the master tracking branch 4.19

Do not mirror centos_rhel{8,9}

---

group.yml

Reverts openshift-eng/ocp-build-data#5695

Revert "Freeze 4.19 automation for now"

---

group.yml

Reverts openshift-eng/ocp-build-data#5697

Revert "[openshift-4.13] Freeze automation"

---

group.yml
streams.yml

https://issues.redhat.com/browse/ART-11311
https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/ximhan/job/build%252Fgolang-builder/11/console

ART-11311 Update builders to 1.23

---

group.yml

Reverts openshift-eng/ocp-build-data#5698

Revert "[openshift-4.12] Freeze automation"

---

OWNERS

Add my user to OWNERS in 4.12 branch

Add germanparente git user to 4.12 branch

---

images/ose-azure-service-operator.yml

ART-11334: added ose-azure-service-operator image

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile

This matches:
* https://github.com/kubernetes/kubernetes/blob/release-1.32/hack/lib/etcd.sh#L19
/assign @joepvd

CNTRLPLANE-1: Update etcd to match k8s 1.32

---

erratatool.yml

- https://errata.devel.redhat.com/advisory/release/show/2445
- https://redhat-internal.slack.com/archives/CJARLA942/p1733235809303259

Move 4.13 advisories to silent release

---

streams.yml

Disable golang 1.22 for 4.19

---

streams.yml

Disable golang 1.21 for 4.18

---

streams.yml

Disable golang 1.21 for 4.17

---

streams.yml

Disable golang 1.20 for 4.16

---

OWNERS

add germanparente git user to owners for 4.13

add germanparente git user to owners for 4.13

---

images/pf-status-relay-operator.yml

ci build root should use member now

update ci build root to member

---

images/monitoring-plugin.yml
images/networking-console-plugin.yml
images/nmstate-console-plugin.yml
images/oc-mirror-plugin.yml
images/openshift-enterprise-console.yml
images/ose-cli-artifacts.yml
images/ose-etcd.yml
images/ose-installer-artifacts.yml

[4.17] [konflux] override params

---

group.yml
images/ci-openshift-base.rhel8.yml
images/ci-openshift-base.rhel9.yml
images/ci-openshift-build-root-extra.rhel9.disabled
images/ci-openshift-build-root-latest.rhel8.yml
images/ci-openshift-build-root-latest.rhel9.yml
images/ci-openshift-golang-builder-extra.rhel9.disabled
images/ci-openshift-golang-builder-latest.rhel8.yml
images/ci-openshift-golang-builder-latest.rhel9.yml
images/openshift-base-nodejs.rhel9.yml
images/openshift-base-rhel8.yml
images/openshift-base-rhel9.yml

Similar to https://github.com/openshift-eng/ocp-build-data/pull/5607

[konflux] use openshift-priv for openshift-eng

---

images/vertical-pod-autoscaler-operator.yml

ART-11578: [konflux] disable VPA cause of git tag issue

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-8/ci-openshift-build-root/Dockerfile.previous
ci_images/rhel-9/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile.previous

Backport of https://github.com/openshift-eng/ocp-build-data/pull/5447

[konflux] ci images fix

---

releases.yml

permit-conflicting-group-rpm-4.19.ec0

---

group.yml
images/cloud-event-proxy.yml

Backport of https://github.com/openshift-eng/ocp-build-data/pull/5480

scan-sources:noop [konflux] Override public upstream for cne

---

images/openshift-base-nodejs.yml

Reverts openshift-eng/ocp-build-data#5841
issue resolved

Revert "[konflux] disable openshift-base-nodejs"

---

group.yml

Reverts openshift-eng/ocp-build-data#5835

Revert "use 4.19 rhocs"

---

images/ose-installer-etcd-artifacts.yml

Reverts openshift-eng/ocp-build-data#5856
PR has merged

Revert "scan-sources:noop [konflux] disable ose-installer-etcd-artifacts"

---

images/ose-installer-terraform-providers.yml

Sometimes the build flakes out

[konflux] use bigger VM for ose-installer-terraform-providers

---

images/ose-baremetal-installer.yml
images/ose-installer.yml
images/ose-machine-os-images.yml

follows https://github.com/openshift-eng/ocp-build-data/pull/5874

scan-sources:noop [konflux] disable installer-terraform child images

---

images/ose-installer-altinfra.yml
images/ose-installer.yml
images/ose-machine-os-images.yml

Disable images with known issues, so that pipeline doesn't fail

[konflux] disable images with known issues

---

images/ose-alibaba-cloud-csi-driver.yml

[konflux] disable ose-alibaba-cloud-csi-driver

---

images/pf-status-relay-operator.yml

Reverts openshift-eng/ocp-build-data#5855

Revert "[4.18] disabe pf-status-relay-operator"

---

images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-base.yml
images/ovn-kubernetes-microshift.yml

Libreswan is pinned in Dockerfile. Do not start builds because there is a newer version.

libreswan: No reason for rebuild

---

group.yml
images/cloud-event-proxy.yml

Backport of https://github.com/openshift-eng/ocp-build-data/pull/5845

[konflux] Override public upstream for CNE

---

images/ose-installer-terraform-providers.yml

Successful run: https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-16/pipelineruns/ose-4-16-ose-installer-terraform-providers-mht9t/logs?task=build-images

scan-sources:noop [konflux] override VM for terraform

---

images/ose-installer.yml
images/ose-machine-os-images.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/5893

[konflux] enable terraform children

---

images/ose-baremetal-installer.yml
images/ose-installer.yml

Since signal: killed error seemed to be popping up

[konflux] use bigger vms

---

images/oc-mirror-plugin.yml
images/openshift-enterprise-console.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-alibaba-cloud-csi-driver.yml
images/ose-alibaba-machine-controllers.yml
images/ose-cli-artifacts.yml
images/ose-etcd.yml
images/ose-installer-artifacts.yml
images/vertical-pod-autoscaler-operator.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/5888

[konflux] override params

---

images/ose-installer-altinfra.yml
images/ose-installer-etcd-artifacts.yml

Upstream PR has merged: https://github.com/openshift/etcd/pull/298

[konflux] enabling etcd-artifacts

---

images/ose-baremetal-installer.yml
images/ose-installer-altinfra.yml

https://konflux.pages.redhat.com/docs/users/getting-started/multi-platform-builds.html#_cpu_optimised
Use CPU optimized VMs to reduce build times

[konflux] Use CPU optimized VMs to reduce build times

---

releases.yml

ref [thread](https://redhat-internal.slack.com/archives/C06625LHXQS/p1735846458731819?thread_ts=1735844115.938129&cid=C06625LHXQS)

4.17.11 pin builds

---

images/openshift-enterprise-console.yml

Test build [worked](https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-19/pipelineruns/ose-4-19-openshift-enterprise-console-pzwgl/logs)

[konflux] enable console

---

releases.yml

https://redhat-internal.slack.com/archives/CB95J6R4N/p1735808228021709

pin ptp-operator to include fix

---

images/monitoring-plugin.yml
images/oc-mirror-plugin.yml

Fixed with https://github.com/openshift-eng/art-tools/pull/1244

[konflux] enable mirror, monitoring

---

images/networking-console-plugin.yml
images/nmstate-console-plugin.yml

Fixed with https://github.com/openshift-eng/art-tools/pull/1250

[konflux] enable networking-console, nmstate-console

---

images/nmstate-console-plugin.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/5944

[konflux] enable nmstate-console-plugin

---

images/openshift-kubernetes-nmstate-operator.yml

[konflux] enable kubernetes-nmstate

---

group.yml

test [build-sync](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/13218/console) : SUCCESS
(with EMERGENCY_IGNOR_ISSUES enabled)

enabled RHCOS for 4.19

---

images/ironic.yml

Do not comment out cachito lines for ironic

[konflux] ironic cachito fix

---

releases.yml

ref [thread](https://redhat-internal.slack.com/archives/CB95J6R4N/p1736421738607289?thread_ts=1736244421.952959&amp;cid=CB95J6R4N)

4.16.30 pin sriov builds

---

ci_images/install_dnf_wrapper.sh
ci_images/rhel-8/ci-openshift-golang-builder/Dockerfile
ci_images/rhel-9/ci-openshift-golang-builder/Dockerfile

Follow-up of https://github.com/openshift-eng/ocp-build-data/pull/5974

Give golang image necessary env vars

---

releases.yml

in order to bypass OCPBUGS-48766

add BLOCKER_BUGS flag to permits

---

images/ironic.yml

Only allow internal network access for this build
Needs: https://github.com/openshift-eng/art-tools/pull/1280

internal-only mode for ironic

---

images/ose-olm-catalogd.yml

We are merging the catalogd repo into operator-controller

OPRUN-3711: OLMv1: Get catalogd image from operator-controller repo

---

OWNERS

Adding germanparente git user in owners file

Add germanparente in OWNERS file for 4.14

---

product.yml

Add openstack-resource-controller into product.

ART-11973: add ORC to product.yml

---

images/ironic-agent.yml
images/ironic.yml

Requires https://github.com/openshift-eng/art-tools/pull/1332

Cachi2 mode changes

---

images/openshift-enterprise-ansible-operator.yml

[Run](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/4797/console)

[ART-11911][konflux] enable ansible-operator

---

images/openstack-resource-controller.yml

Reverts openshift-eng/ocp-build-data#6076

Revert "ec.1: temporarily disable openstack-resource-controller"

---

images/driver-toolkit.yml
images/monitoring-plugin.yml
images/networking-console-plugin.yml
images/nmstate-console-plugin.yml
images/oc-mirror-plugin.yml
images/openshift-enterprise-console.yml
images/ose-baremetal-installer.yml
images/ose-installer-altinfra.yml
images/ose-installer-artifacts.yml

Syncing overrides from 4.19 branch to 4.18

[konflux] sync overrides from 4.19

---

images/microshift-bootc.yml

https://issues.redhat.com/browse/ART-12057

ART-12057 Use EUS base RHEL image

---

images/ose-installer-artifacts.yml

Follows https://github.com/redhat-appstudio/infra-deployments/pull/5530

[konflux] rename VM flavor to linux-d200-large/ppc64le

---

group.yml

Reverts openshift-eng/ocp-build-data#6093

Revert "Freeze 4.19 automation for mass rebuild management"

---

images/monitoring-plugin.yml
images/networking-console-plugin.yml
images/nmstate-console-plugin.yml
images/openshift-enterprise-console.yml

From https://github.com/openshift-eng/ocp-build-data/pull/6087

[konflux] sync cachito overrides

---

group.yml

Reverts openshift-eng/ocp-build-data#6095

Revert "Freeze 4.18 automation for mass rebuild management"

---

images/openshift-enterprise-console.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/6113

[4.13][konflux] sync cachito overrides

---

images/openshift-enterprise-console.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/6114

[4.12][konflux] sync cachito overrides

---

group.yml

Reverts openshift-eng/ocp-build-data#6094

Revert "Freeze 4.15 automation for mass rebuild management"

---

images/vertical-pod-autoscaler-operator.yml

Since https://github.com/openshift-eng/art-tools/pull/1342 was merged

[konflux] enable vpa

---

images/ose-alibaba-machine-controllers.yml

Since https://github.com/openshift-eng/art-tools/pull/1342 was merged

[konflux] enable alibaba

---

images/ose-baremetal-installer.yml
images/ose-cli-artifacts.yml
images/ose-installer-altinfra.yml
images/ose-installer-artifacts.yml
images/ose-installer-terraform-providers.yml

Cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/6096

[konflux] Use consistent powerful instances across heavyweight builds

---

releases.yml

Reverts openshift-eng/ocp-build-data#6157

Revert "Revert "4.18.0: pin rpm-ostree rpm""

---

releases.yml

Reverts openshift-eng/ocp-build-data#6150

Revert "exempt bind*"

---

images/ose-cli-artifacts.yml

Cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/6168

[konflux] cli-artifacts use d320 VMs

---

images/dpu-intel-ipu-vsp.yml

Test build succeeded: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/5200/

[konflux] enable dpu-intel-ipu-vsp

---

images/ose-alibaba-machine-controllers.yml

Follows https://github.com/openshift-eng/art-tools/pull/1376

[konflux] alibaba tagging mode

---

images/vertical-pod-autoscaler-operator.yml

Follows https://github.com/openshift-eng/art-tools/pull/1376

[konflux] vpa tagging mode

---

images/ose-cli-artifacts.yml

Manual cherrypick of https://github.com/openshift-eng/ocp-build-data/pull/6201

[konflux] ose-cli-artifacts IBM flavor update

---

images/ose-installer-artifacts.yml

Syncing changes from higher versions

[konflux] ose-installer-artifacts update vm_override

---

images/ose-installer-terraform-providers.yml

[konflux] ose-installer-terraform-providers vm_override

---

images/ose-installer-terraform-providers.yml

[konflux] terraform-providers vm_override

---

images/ose-baremetal-installer.yml

[konflux] ose-baremetal-installer vmoverride

---

images/ose-installer-artifacts.yml

Build time > 1.5 hours right now. Swapping in a bigger VM to bring it under an hour.

[konflux] ose-installer-artifacts d250 ppc64le

---

images/ose-installer-artifacts.yml

Reverts openshift-eng/ocp-build-data#6223

Revert "[konflux] ose-installer-artifacts d250 ppc64le"

---

images/ose-installer-altinfra.yml

syncing overrides from higher versions

[konflux] syncing overrides altrinfra

---

images/driver-toolkit.yml
images/ironic.yml
images/oc-mirror-plugin.yml
images/openshift-enterprise-console.yml

[konflux] syncing overrides

---

images/ose-alibaba-cloud-csi-driver.yml

Same as https://github.com/openshift-eng/ocp-build-data/pull/6268 but with `rhaos-{MAJOR}.{MINOR}-rhel8`

[4.14][konflux] add modifications alibaba-cloud-csi-driver

---

images/ose-alibaba-cloud-csi-driver.yml

Fixes build issue on Konflux
Test [Konflux build](https://console-openshift-console.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/k8s/ns/ocp-art-tenant/tekton.dev~v1~PipelineRun/ose-4-15-ose-alibaba-cloud-csi-driver-nmsjh/) ✅ 
Test [Brew build](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=66859884) ✅

[4.15][konflux] add modifications alibaba-cloud-csi-driver

---

images/openshift-kubernetes-nmstate-operator.yml
images/ose-metallb-operator.yml

Reverts openshift-eng/ocp-build-data#6144
upstream pr https://github.com/openshift/kubernetes-nmstate/pull/564 merged

Revert "disabled offending operators"

---

images/ose-ovirt-machine-controllers.yml

Reverts openshift-eng/ocp-build-data#6267

Revert "ART-11740: 4.15: remove ovirt-machine-controllers"

---

group.yml

For https://github.com/openshift-eng/art-tools/pull/1410

[konflux] add konflux_arches param in group.yaml

---

images/vertical-pod-autoscaler-operator.yml

Konflux build [succeeded](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/5363)

[konflux] vpa legacy tagging mode

---

images/ose-alibaba-machine-controllers.yml

Manual cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/6284

[konflux] ose-alibaba-machine-controllers

---

images/ose-installer-terraform-providers.yml

Running out of space with existing VM

[konflux] terraform-providers use bigger VM

---

images/ose-baremetal-installer.yml

Fixes `no space left on device` error

[konflux] ose-baremetal-installer larger VMs

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile

Manual cherry-pick of https://github.com/openshift-eng/ocp-build-data/pull/6327

Fix goimport installation on go1.22

---

images/ose-alibaba-cloud-csi-driver.yml

Cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/6337 and https://github.com/openshift-eng/ocp-build-data/pull/6338

update ose-alibaba-cloud-csi-driver replace

---

images/driver-toolkit.yml

[konflux] update driver-toolkit

---

images/microshift-bootc.yml

See if microshift-bootc can build hermetically

[konflux] set microshift-bootc as hermetic

---

images/microshift-bootc.yml

Reverts openshift-eng/ocp-build-data#6344

Revert "[konflux] set microshift-bootc as hermetic"

---

images/microshift-bootc.yml

Test build [succeeded](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/ashwin-aos-cd-jobs/job/bootc-test/4/console)

internal-only

---

images/microshift-bootc.yml

Manual cherry-pick of https://github.com/openshift-eng/ocp-build-data/pull/6346

bootc internal only

---

group.yml

update rhcos enabled repos to 9.6

update rhcos enabled repos

---

images/ose-ovn-kubernetes.yml

Cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/6378

[konflux] cachi2 disable ovn

---

group.yml

[build-sync](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/16276/console) with EMERGENCY_IGNORE_ISSUES ticked/enabled was successful. So we can start the automation.

automation for 4.20

---

images/dpu-intel-ipu-p4sdk.yml

Tested with 4.20, succeeded: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/6311/

[konflux] set hermetic

---

group.yml

[konflux] enable cachi2

---

images/ose-machine-os-images.yml

Test build worked: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/6429/console
ref thread: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1743022042311039

scan-sources:noop [konflux] x86_64 override machine-os

---

images/ose-machine-os-images.yml

Cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/6426

[konflux] x86_64 override machine-os

---

images/baremetal-runtimecfg.yml
images/cloud-event-proxy.yml
images/cluster-nfd-operator.yml
images/coredns.yml
images/csi-driver-manila.yml
images/golang-github-prometheus-node_exporter.yml
images/ironic-rhcos-downloader.yml
images/linuxptp-daemon.yml
images/multus-networkpolicy.yml
images/openshift-kubernetes-nmstate-handler.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-apiserver-network-proxy.yml
images/ose-cluster-baremetal-operator.yml
images/ose-ibm-vpc-block-csi-driver.yml
images/ose-insights-operator.yml
images/ose-kube-storage-version-migrator.yml
images/ose-metallb.yml
images/ose-network-tools.yml
images/ose-openstack-cinder-csi-driver.yml
images/ose-vsphere-cloud-controller-manager.yml
images/ose-vsphere-cluster-api-controllers.yml
images/pf-status-relay.yml
images/ptp-operator.yml
images/telemeter.yml

Disabling images that are failing for now.

[konflux] disable cachi2

---

group.yml

ref thread: https://redhat-internal.slack.com/archives/C06Q309QUDV/p1743183670944419

[konflux] disable cachi2/prefetch

---

images/kube-proxy.yml
images/openshift-enterprise-hyperkube.yml
images/ose-installer-kube-apiserver-artifacts.yml

Until https://issues.redhat.com/browse/KFLUXSPRT-2639 is resolved

[konflux] disable sast

---

releases.yml

Reverts openshift-eng/ocp-build-data#6472

Revert "Ignore openssl updates for 4.18"

---

releases.yml

Reverts openshift-eng/ocp-build-data#6473

Revert "Ignore openssl updates for 4.17"

---

images/ose-installer-terraform-providers.yml

Cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/6515

terraform increase IBM VM disk

---

images/ose-ovirt-machine-controllers.yml

Reverts openshift-eng/ocp-build-data#6329

Revert "Reapply "ART-11740: 4.16: remove ovirt-machine-controllers""

---

images/ose-installer-artifacts.yml

Fixes `no storage left on device error`

artifacts increase IBM VM disk

---

releases.yml

Reverts openshift-eng/ocp-build-data#6474

Revert "Ignore openssl updates for 4.16"

---

group.yml

Reverts openshift-eng/ocp-build-data#6488

Revert "Enable IBM arches"

---

group.yml

Reverts openshift-eng/ocp-build-data#6489

Revert "[openshift-4.15] Enable IBM arches"

---

group.yml

Reverts openshift-eng/ocp-build-data#6516

Revert "[openshift-4.16] Enable IBM arches"

---

group.yml

Reverts openshift-eng/ocp-build-data#6538

Revert "[openshift-4.17] Enable IBM arches"

---

group.yml

Ref [Slack thread](https://redhat-internal.slack.com/archives/GUSEXGPJP/p1744738564762739)

Freeze automation for the week of Apr 14th

---

group.yml

Cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/6582

gomod_version_patch

---

group.yml

Cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/6582

 gomod_version_patch

---

group.yml

ref [thread](https://redhat-internal.slack.com/archives/C06Q309QUDV/p1744888045688729)

Enable ppc

---

images/openshift-enterprise-console.yml
images/ose-baremetal-installer.yml
images/ose-cli-artifacts.yml
images/ose-installer-altinfra.yml
images/ose-installer-artifacts.yml
images/ose-installer-terraform-providers.yml

Follows https://github.com/openshift-eng/art-tools/pull/1535

s390x static VMs

---

images/coredns.yml
images/ose-aws-ebs-csi-driver.yml
images/ose-cluster-baremetal-operator.yml
images/ose-libvirt-machine-controllers.yml
images/ose-machine-api-provider-openstack.yml
images/ose-metallb.yml
images/ose-vsphere-cloud-controller-manager.yml

Test runs succeeded:
- https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/7895/
- https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/7896

add modification fix gomod vendor

---

images/node-feature-discovery.yml
images/ptp-operator.yml

disable cachi2 image

---

group.yml

Reverts openshift-eng/ocp-build-data#6565

Revert "Freeze automation for the week of Apr 14th"

---

group.yml

Reverts openshift-eng/ocp-build-data#6567

Revert "[openshift-4.13] Freeze automation for the week of Apr 14th"

---

images/openshift-enterprise-console.yml

Disable console until upstream issue is fixed

cachi2 disable console

---

images/coredns.yml
images/csi-driver-manila.yml
images/openshift-kubernetes-nmstate-handler.yml
images/ose-cluster-baremetal-operator.yml
images/ose-ibm-vpc-block-csi-driver.yml
images/ose-insights-operator.yml
images/ose-machine-config-operator.yml
images/ose-metallb.yml
images/ose-openstack-cinder-csi-driver.yml
images/ose-vsphere-cloud-controller-manager.yml
images/ose-vsphere-cluster-api-controllers.yml

Changes in this PR:
- Disable images that need upstream fixes
- Add modifications for missing vendor files

cachi2 updates

---

images/ose-baremetal-installer.yml
images/ose-cli-artifacts.yml
images/ose-installer-altinfra.yml
images/ose-installer-artifacts.yml
images/ose-installer-terraform-providers.yml

To follow https://github.com/redhat-appstudio/infra-deployments/pull/6181

Remove ppc VM override

---

images/openshift-enterprise-console.yml
images/ose-baremetal-installer.yml
images/ose-cli-artifacts.yml
images/ose-installer-altinfra.yml
images/ose-installer-artifacts.yml
images/ose-installer-terraform-providers.yml

Similar to https://github.com/openshift-eng/ocp-build-data/pull/6630

remove IBM vm overrides

---

group.yml

Konflux infra has setup static VMs

enable s390x

---

images/ose-ibmcloud-cluster-api-controllers.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/6626
Updated gomod versions

cachi2 ibmcloud fix

---

streams.yml

See commit message for more details.
This is required for https://github.com/openshift/release/pull/64007 
cc @Prashanth684

OKD-240: streams: add stream10 ocp builder in app.ci

---

group.yml

Reverts openshift-eng/ocp-build-data#6689

Revert "ART-12600: Enable layered rhcos 4.20"

---

group.yml

Reverts openshift-eng/ocp-build-data#6569

Revert "ART-12600: Enable layered rhcos"

---

group.yml

Since we are done with the last EC, start signing RPMs to get ready for RCs.

[openshift-4.19] start singing RPMs

---

releases.yml

https://issues.redhat.com/browse/OCPBUGS-50566?focusedId=26675284&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26675284

4.17.28 exclude OCPBUGS-50566

---

group.yml

need to be built in cachi2 mode for all applicable images

reorder arches to trigger mass rebuild

---

config/advisory_templates.yml

For https://github.com/openshift-eng/ocp-build-data/pull/6751

ART-12761: Move templates from version specific ones

---

config/advisory_templates.yml

Microshift uses a different template
RHBA template: https://docs.google.com/document/d/1Oot2Jl-Xz55swswfhy-Rr5bbJcwA1exYX5P9fhQoTa0/edit?tab=t.0
RHSA, https://docs.google.com/document/d/14GOMaVaTmVjmzxYi9eDsin7T_PAa3xtX1vhOUrHOFEU/edit?tab=t.0 (

ART-12761: Update microshift release notes template

---

config/advisory_templates.yml

Convert the impact field to a template
art-tools is supporting this already: https://github.com/openshift-eng/art-tools/blob/main/elliott/elliottlib/cli/attach_cve_flaws_cli.py#L246

ART-12761: template impact

---

images/kube-rbac-proxy.yml
images/ose-frr.yml
images/ose-ibmcloud-cluster-api-controllers.yml
images/ose-metallb-operator.yml
images/ose-metallb.yml

https://github.com/openshift/cluster-api-provider-ibmcloud/pull/112/files

Fix ibmcloud rebase

---

bundle/art.yaml
bundle/helloworld-operator.package.yaml
bundle/manifests/helloworld-operator.clusterserviceversion.yaml
bundle/manifests/image-references

Add art.yaml and image-references.

[helloworld-operator] Add ART-specific files

---

config/advisory_templates.yml

List the CVEs if there are any

CVES param for microshift

---

releases.yml

exclude OCPBUGS-52548 since hidden

---

releases.yml

Assembly definition taken from https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fgen-assembly/573/console
Added permits for ECs

[4.20] Add EC.1

---

releases.yml

Reverts openshift-eng/ocp-build-data#6830

Revert "Pin NTO for bad tuned"

---

releases.yml

```
import koji
from datetime import datetime
timestamp_str = "2025-05-26T07:41:37+00:00"
datetime_obj = datetime.fromisoformat(timestamp_str)
koji_api = koji.ClientSession("https://brewhub.engineering.redhat.com/brewhub")
print(koji_api.getLastEvent(datetime_obj.timestamp()))
```
which resulted in 
```
{'id': 63905880, 'ts': 1748245224.6323}
```

custom pre-release

---

images/openshift-enterprise-console.yml

Test build succeeded: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=67812861

console modification for hermeto

---

images/openshift-enterprise-console.yml

Manual cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/6874

qhermeto add modification for console

---

images/openshift-enterprise-console.yml

Manual cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/6874

hermeto add modification for console

---

images/openshift-golang-builder.Dockerfile

https://redhat-internal.slack.com/archives/C039LFF79K6/p1749054886352419?thread_ts=1749048669.828619&cid=C039LFF79K6

Pin llvm-toolset to 17

---

releases.yml

Pinning correct nfd operator reference :  https://github.com/openshift/cluster-nfd-operator/pull/437#issuecomment-2932240723

4.19 rc.5 pin cluster-nfd-operator

---

group.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/6871

Switch to Hermeto for 4.18 osbs

---

group.yml

Follows https://github.com/openshift-eng/ocp-build-data/pull/6871

Switch to Hermeto for osbs

---

Dockerfile

Conforma run: https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/ocp-art-tenant/applications/openshift-4-18/pipelineruns/ose-4-18-ec-registry-ocp-art-tmp-onboard-policy-stage-xbv5g/logs

helloworld operator add labels

---

images/cluster-nfd-operator.yml
images/clusterresourceoverride-operator.yml
images/dpu-operator.yml
images/ingress-node-firewall-operator.yml
images/local-storage-operator.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-aws-efs-csi-driver-operator.yml
images/ose-gcp-filestore-csi-driver-operator.yml
images/ose-metallb-operator.yml
images/ose-secrets-store-csi-driver-operator.yml
images/ose-smb-csi-driver-operator.yml
images/ptp-operator.yml
images/sriov-network-operator.yml
images/vertical-pod-autoscaler-operator.yml

Add bundle_delivery_repo_name for all OLM bundles - 4.16

---

images/cluster-nfd-operator.yml
images/clusterresourceoverride-operator.yml
images/ingress-node-firewall-operator.yml
images/local-storage-operator.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-aws-efs-csi-driver-operator.yml
images/ose-gcp-filestore-csi-driver-operator.yml
images/ose-metallb-operator.yml
images/ose-secrets-store-csi-driver-operator.yml
images/ptp-operator.yml
images/sriov-network-operator.yml
images/vertical-pod-autoscaler-operator.yml

Add bundle_delivery_repo_name for all OLM bundles - 4.15

---

releases.yml

Discussed in https://redhat-internal.slack.com/archives/CJARLA942/p1750338013817389

Allow NEW_FILES advisory for 4.18.18

---

images/cluster-nfd-operator.yml
images/clusterresourceoverride-operator.yml
images/ingress-node-firewall-operator.yml
images/local-storage-operator.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-aws-efs-csi-driver-operator.yml
images/ose-gcp-filestore-csi-driver-operator.yml
images/ose-metallb-operator.yml
images/ose-secrets-store-csi-driver-operator.yml
images/ptp-operator.yml
images/sriov-network-operator.yml
images/vertical-pod-autoscaler-operator.yml

Add bundle_delivery_repo_name for all OLM bundles - 4.14

---

images/cluster-nfd-operator.yml
images/clusterresourceoverride-operator.yml
images/ingress-node-firewall-operator.yml
images/local-storage-operator.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-aws-efs-csi-driver-operator.yml
images/ose-gcp-filestore-csi-driver-operator.yml
images/ose-metallb-operator.yml
images/ptp-operator.yml
images/sriov-network-operator.yml
images/vertical-pod-autoscaler-operator.yml

Add bundle_delivery_repo_name for all OLM bundles - 4.13

---

releases.yml

Reverts openshift-eng/ocp-build-data#7013

Revert "Produce 4.20 nightlies by pinning a build"

---

config/advisory_templates.yml

ref [thread](https://redhat-internal.slack.com/archives/CJARLA942/p1750849162472859)
Add comment for image advisory

fix image advisory comment

---

images/coredns.yml
images/csi-driver-manila.yml
images/dpu-cni.yml
images/dpu-daemon.yml
images/dpu-operator.yml
images/golang-github-prometheus-alertmanager.yml
images/ib-sriov-cni.yml
images/kube-proxy.yml
images/node-feature-discovery.yml
images/oauth-server.yml
images/openshift-enterprise-console-operator.yml
images/openshift-kubernetes-nmstate-handler.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-aws-cluster-api-controllers.yml
images/ose-azure-cluster-api-controllers.yml
images/ose-cluster-baremetal-operator.yml
images/ose-gcp-cluster-api-controllers.yml
images/ose-ibm-vpc-block-csi-driver.yml
images/ose-ibmcloud-cluster-api-controllers.yml
images/ose-libvirt-machine-controllers.yml
images/ose-machine-api-provider-openstack.yml
images/ose-machine-config-operator.yml
images/ose-metallb.yml
images/ose-openstack-cinder-csi-driver.yml
images/ose-openstack-cloud-controller-manager.yml
images/ose-sriov-rdma-cni.yml
images/ose-vsphere-cloud-controller-manager.yml
images/ose-vsphere-cluster-api-controllers.yml
images/ptp-operator.yml

Disable cachi2 for images which are failing to build because of cachi2-related issues

[ART-13260] Disable cachi2 for several images in 4.17

---

images/baremetal-machine-controller.yml
images/coredns.yml
images/csi-driver-manila.yml
images/golang-github-prometheus-alertmanager.yml
images/ib-sriov-cni.yml
images/node-feature-discovery.yml
images/openshift-enterprise-console-operator.yml
images/openshift-enterprise-hyperkube.yml
images/openshift-kubernetes-nmstate-handler.yml
images/openshift-kubernetes-nmstate-operator.yml
images/ose-aws-cluster-api-controllers.yml
images/ose-azure-cluster-api-controllers.yml
images/ose-cluster-baremetal-operator.yml
images/ose-gcp-cluster-api-controllers.yml
images/ose-ibm-vpc-block-csi-driver.yml
images/ose-ibmcloud-cluster-api-controllers.yml
images/ose-installer-kube-apiserver-artifacts.yml
images/ose-libvirt-machine-controllers.yml
images/ose-machine-api-provider-openstack.yml
images/ose-metallb.yml
images/ose-openstack-cinder-csi-driver.yml
images/ose-openstack-cloud-controller-manager.yml
images/ose-vsphere-cloud-controller-manager.yml
images/ose-vsphere-cluster-api-controllers.yml
images/ptp-operator.yml

Disable cachi2 for images which are failing to build because of cachi2-related issues

[ART-13260] Disable cachi2 for several images in 4.16

---

images/ose-metallb-operator.yml

verified against https://errata.devel.redhat.com/products/79/product_versions/1960

ART-13269: [4.15] fix bundle namesfix bundle name

---

images/golang-github-prometheus-alertmanager.yml

Since builds are failing on prefetch

promethus disable cachi2

---

releases.yml

Below is the slack thread to exclude the bug : https://redhat-internal.slack.com/archives/C06625LHXQS/p1752168449825449?thread_ts=1752163367.427339&cid=C06625LHXQS

Exclude bug from releases.yml

---

images/ose-aws-efs-utils.yml

To follow https://github.com/openshift/aws-efs-utils/pull/32
Test build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3702853

Add botocore as python dep to aws-efs-utils

---

releases.yml

The blocker bug was not within the cutoff time

include blcoker bug

---

group.yml

Reverts openshift-eng/ocp-build-data#7125

Revert "Freeze automation to prevent mass rebuild"

---

images/dpu-intel-ipu-vsp.yml
images/driver-toolkit.yml
images/golang-github-prometheus-node_exporter.yml
images/golang-github-prometheus-prometheus.yml
images/ironic-rhcos-downloader.yml
images/ironic.yml
images/linuxptp-daemon.yml
images/okd-only-upi-installer.yml
images/openshift-base-rhel9.yml
images/openshift-enterprise-builder.yml
images/openshift-enterprise-egress-dns-proxy.yml
images/openshift-enterprise-haproxy-router.yml
images/ose-agent-installer-api-server.yml
images/ose-agent-installer-csr-approver.yml
images/ose-agent-installer-node-agent.yml
images/ose-agent-installer-utils.yml
images/ose-frr.yml
images/ose-image-customization-controller.yml
images/ose-insights-runtime-extractor.yml
images/ose-machine-config-operator.yml
images/ose-ovn-kubernetes.yml
images/ovn-kubernetes-base.yml
images/prom-label-proxy.yml
images/thanos.yml

For images that is pulling from embargoed repos, set it to open.
ref thread for details: https://redhat-internal.slack.com/archives/C06Q309QUDV/p1752587242773659

ART-13407: 4.19 hermetic #3

---

images/openshift-kubernetes-nmstate-operator.yml
images/ose-metallb-operator.yml
images/pf-status-relay-operator.yml

These images were disabled until recently

[4.20] add delivery_repo_names

---

releases.yml

Reverts openshift-eng/ocp-build-data#7249

Revert "pin dtk"

---

erratatool.yml

Add security_reviewer to boilerplates [4.13]

---

images/ose-network-interface-bond-cni.yml

https://issues.redhat.com/browse/ART-14015
previous work: https://github.com/openshift-eng/ocp-build-data/pull/6970/files, https://github.com/openshift-eng/ocp-build-data/pull/7000/files
needs https://github.com/openshift-eng/ocp-build-data/pull/7390

ART-14015 Point bond-cni image to 1.23 builders and buildroot

---

releases.yml

ref thread: https://redhat-internal.slack.com/archives/CJARLA942/p1756400204999219

4.19.10 exclude bug

---

images/openshift-enterprise-ansible-operator.yml

conforma failed: https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/rhtap-releng-tenant/applications/openshift-4-19/pipelineruns/managed-m8ctt/logs?task=verify-conforma
we need to verify if conforma passes before merging updates to prod ocp-build-data

ansible operator remove artifact lockfile

---

images/nmstate-console-plugin.yml

align with https://github.com/openshift-eng/ocp-build-data/pull/7454

fix nmstate-console-plugin

---

images/ose-network-interface-bond-cni.yml

https://issues.redhat.com/browse/ART-14016
Follow up to https://github.com/openshift-eng/ocp-build-data/pull/7443
Cherry pick of https://github.com/openshift-eng/ocp-build-data/pull/7391/files

ART-14016 Point bond-cni image to 1.23 builders and buildroot

---

group.yml

ref slack thread: https://redhat-internal.slack.com/archives/C04SCM5AYE4/p1756997613397439

stop ship for 4.19

---

ci_images/rhel-8/ci-openshift-build-root/Dockerfile
ci_images/rhel-9/ci-openshift-build-root/Dockerfile

This matches:
* https://github.com/kubernetes/kubernetes/blob/release-1.33/hack/lib/etcd.sh#L19
CC @kevinrizza

Update etcd to match k8s 1.33.4

---

group.yml

This reverts commit 4a2282294a0c0fb0d6206fb0759a3536ecd9d5d8.

Revert "Update group.yml"

---

config/advisory_templates.yml

Needs https://github.com/openshift-eng/art-tools/pull/1953

ART-14033: template payload shas automatically

---

group.yml
images/openshift-base-rhel9.yml

Also for base images
..and enable automation for 4.20 and 4.21

Set network_mode to hermetic

---

images/ose-support-log-gather-operator.yml

Disable ose-support-log-gather-operator

---

releases.yml

This is blocking prep https://redhat-internal.slack.com/archives/GDBRP5YJH/p1758031627890129

[4.21] Remove regular errata advisories for ec.0

---

releases.yml

Since https://github.com/openshift-eng/art-tools/pull/1864/files is not merged

Remove prerelease from ec.0

---

images/ose-support-log-gather-operator.yml

Reverts openshift-eng/ocp-build-data#7618
/hold until ec.0 is created

Revert "Disable ose-support-log-gather-operator"

---

images/oadp-operator.yml

This reverts commit 43fae7204ded5080e6aa7205dc0b443b90f0ba2d.

Revert "oadp-1.5: operator use release-branch"

---

images/oadp-operator.yml

This reverts commit a6edc759a9a55573c7880bfddeb46fc6e49566d3.

Reapply "oadp-1.5: operator use release-branch"

---

images/openshift-enterprise-base.yml

cherry pick https://github.com/openshift-eng/ocp-build-data/pull/7693

set openshift-enterprise-base network mode to open
